### ISSUE TITLE
header in subrequest

### ISSUE THREAD

**Issue by c0de9en** [nginx/njs#100]
Is it possible to add "headers" key in subrequest options?
For example:
{
  args: "arg1=txt",
  body: "request body",
  method: "POST",
  headers: {content_type: "application/json", authorization: "token", ...}
}

**Comment by xeioex** [comment]
Hi @an0ma1ia,

Unfortunately, it is hard to correctly replace incoming headers in nginx. The main and a sub requests share ` incoming headers` structure.

If you want to control the incoming headers you can use the following directives in subrequest location
1) [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) to set or override headers.
2) [proxy_pass_request_headers](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass_request_headers) **off** to drop all the headers of the main request.

In the future, we plan to introduce 'native' http client in njs, which will not rely upon nginx subrequests.

**Comment by an0ma1ia** [comment]
I use GET parameter to pass header value to the subrequest location where I set header by proxy_set_header. Exactly what you recommend. Works well but looks a bit strange.

Thank you for the clarification.

**Comment by hongzhidao** [comment]
@xeioex 
> In the future, we plan to introduce 'native' http client in njs, which will not rely upon nginx subrequests.

Sounds great, but does it still rely upon current request, or is individual in process?

**Comment by xeioex** [comment]
@hongzhidao 

> Sounds great, but does it still rely upon current request, or is individual in process?

It still will be linked to the current request, because njs context is linked to it. But, it will not depend heavily on nginx internal structures.

**Comment by brekt** [comment]
> In the future, we plan to introduce 'native' http client in njs, which will not rely upon nginx subrequests.

Any update on when this might land? My use case is I would like to be able to fetch some JSON from S3 and load it into memory for use in validating requests based on query params. Right now I'm hard coding the data into an njs module which means I have to redeploy my nginx application when I want to update it.

**Comment by xeioex** [comment]
Hi @brekt,

Take a look at [ngx.fetch()](http://nginx.org/en/docs/njs/reference.html#ngx).

```
function handler(r) {
    let reply = await ngx.fetch('http://nginx.org/', {headers: {foo:"bar"}});
    let body = await reply.text();
    r.return(200, body);
}
```

for DNS names resolution the [resolver](https://nginx.org/ru/docs/http/ngx_http_core_module.html#resolver) is also required.

**Comment by brekt** [comment]
@xeioex Thank you for this. It looks like it might work, but when I try to use it with the `js_set` directive I get an error about using async calls. Is it possible to return something from `ngx.fetch` and `js_set` it to a variable in an `http` block?

If I use it outside of a $set block it feels like I'm running into a race condition that I always lose, where it fires off the fetch and then continues on before setting a variable inside my js module equal to what it needs to be.

**Comment by xeioex** [comment]
> @xeioex Thank you for this. It looks like it might work, but when I try to use it with the `js_set` directive I get an error about using async calls. Is it possible to return something from `ngx.fetch` and `js_set` it to a variable in an `http` block?
> 
> If I use it outside of a $set block it feels like I'm running into a race condition that I always lose, where it fires off the fetch and then continues on before setting a variable inside my js module equal to what it needs to be.

@brekt Take a look at https://github.com/xeioex/njs-examples#id14

**Comment by brekt** [comment]
@xeioex Thank you. This has gotten me very close. I have a problem right now where when I make my `auth_request` to my `/auth` route and my ngx.fetch code runs, I lose the original uri that was requested (the request uri is now set to `/auth`.) I need that uri so I can parse it and extract an `accessKey` query param. Is there a way to preserve and pass in that uri to the `/auth` request?

I tried to set a header with `proxy_set_header` like I saw in some examples, but it doesn't make it in. My code currently looks like this for the location block

```
location /auth {
    internal;
    js_content myModule.fetchFroms3;
}
```
This should either return a 200 or 403 if the accessKey that the original uri includes is allowed.

**Comment by xeioex** [comment]
Hi @brekt,

Take a look at [$request_uri](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_uri).

In njs, you can access it as `r.variables.request_uri`.

**Comment by brekt** [comment]
@xeioex This worked for me thank you! Interestingly when I tried to log `r.variables` before, it appeared to be an empty object.

**Comment by xeioex** [comment]
> @xeioex This worked for me thank you! Interestingly when I tried to log `r.variables` before, it appeared to be an empty object.

r.variables is a special object, it can query any variable, but Object.keys()
