### ISSUE TITLE
proposal: r.subrequest() changes

### ISSUE THREAD

**Issue by drsm** [nginx/njs#102]
0.3.0
also, while there, require callback argument to be a function.
the main reason is that it is easier to support a typesafe API.

**Comment by xeioex** [comment]
> also, while there, require callback argument to be a function.

BTW, https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L1775

**Comment by drsm** [comment]
@xeioex
oh ), I mean, that if one wants to run subrequest and forget (which is unusual usage pattern), he have to specify a dummy function:
```r.subrequest('/uri', {}, function() {});```

**Comment by drsm** [comment]
@xeioex it would be nice to add [this](https://github.com/nginx/njs/issues/100#issuecomment-464826905) to the [docs](http://nginx.org/en/docs/njs/reference.html#http)

**Comment by drsm** [comment]
@xeioex  if we fail [there](https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L1867) and below shouldn't we trigger ```njs_vm_error(vm, "internal error")``` ?

**Comment by xeioex** [comment]
@drsm 
> @xeioex it would be nice to add [this](https://github.com/nginx/njs/issues/100#issuecomment-464826905) to the [docs](http://nginx.org/en/docs/njs/reference.html#http)

agree.

**Comment by xeioex** [comment]
@drsm 

Please, try the patch below

https://gist.github.com/xeioex/f170ee865fe2bb89212b416670194d91

Working with arguments is unified (the same way as in #7). No direct checks against the number of arguments.

**Comment by xeioex** [comment]
@drsm 

Documentation is updated: http://nginx.org/en/docs/njs/reference.html#subrequest

**Comment by drsm** [comment]
@xeioex the patch looks good.
so, now we have (in typescript format):
```typescript
interface Request {
// ...
}
interface SubrequestOptions {
  method?: string,
  args?: string,
  body?: string 
}
subrequest(uri: string, options?: string | SubrequestOptions, callback?: (Request) => void): void
subrequest(uri: string, callback: (Request) => void): void
```
i think, there some unclear parts (in the docs):
- the default value of options.method if not specified
- what happens with the options.body if GET or HEAD method is used.

**Comment by xeioex** [comment]
@drsm 

Could you please share a good intro about  typescript format? (why it is useful, and how it can be used).

callback can also be omitted
```typescript
subrequest(uri: string, callback?: (Request) => void): void
```

**Comment by drsm** [comment]
@xeioex 
Typescript definition files is the common way to document an API, [here](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts), for example, the complete ES5 reference. They can be loaded into IDE to provide typechecks, parameter hints, etc...
You can start [here](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html), also this [huge](https://github.com/DefinitelyTyped/DefinitelyTyped) repo may be found useful.

> callback can also be omitted
> 
> ```ts
> subrequest(uri: string, callback?: (Request) => void): void
> ```

AFAIK, they are declarative, so the case of missing callback is handled by the first override.

**Comment by xeioex** [comment]
@drsm 

Looks promising. I wander, if I have a type definition file for njs objects and method. How I can use annotations for existing code?

Example [here](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) shows how to write annotated js code. I need something different, I have js extensions written in C. Now, I have to somehow use the annotation file without writing js code.

**Comment by xeioex** [comment]
@drsm 

I found [an article](https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2). But it is still not clear, whether it is possible to annotate built-in code (not imported as a module).

**Comment by drsm** [comment]
@xeioex 
I'm also just started exploring the direction ), but according to [that](https://peter.grman.at/how-to-write-typescript-definition-files/) article, is is simple (not tested):
```ts
/// <reference path="../path/njs.d.ts" />
```

**Comment by drsm** [comment]
> Example [here](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) shows how to write annotated js code.

It's about the typescript language itself, not about typescript definitions, which can be used with anything accesible from the language runtime.

**Comment by xeioex** [comment]
@drsm 

https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-i-write-definitions-for-packages-that-can-be-used-globally-and-as-a-module

https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html

**Comment by xeioex** [comment]
@drsm 
```
i think, there some unclear parts (in the docs):

* the default value of options.method if not specified
* what happens with the options.body if GET or HEAD method is used.
```

See the [updated](http://nginx.org/en/docs/njs/reference.html#subrequest) docs.

**Comment by drsm** [comment]
@xeioex  looks good
and what if callback is ommited?
i see, that subrequest goes header only, so response body is discarded, and no buffers are allocated for it, so we can GET something huge safely.
am i right?
maybe add an option like 'discardResponseBody', so this will available also when a callback is provided?

**Comment by xeioex** [comment]
@drsm 
> maybe add an option like 'discardResponseBody', so this will available also when a callback is provided?

You can use HEAD method for this.
