### ISSUE TITLE
Object.DefineProperty() do not work for getters and setters

### ISSUE THREAD

**Issue by USSX-Hares** [nginx/njs#103]
Hi!

### Problem
I've found out that NJS' method Object.defineProprerty() is not working properly for getters and setters, but its support is stated at the Compatibility page (https://nginx.org/en/docs/njs/compatibility.html#supported).
This method ignores get or set attributes.

### ES5 Object.defineProperty():
[Mozilla MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Specifications) (with links to the standard)
[X-Team](https://x-team.com/blog/es5-object-defineproperty-method/)
[Join.Me](http://joji.me/en-us/blog/javascript-es5-the-object-defineproperty-method)
[ECMA Standard 5.1](https://www.ecma-international.org/ecma-262/5.1/#sec-8.10.5)

### Technical information
Sending you test script in the code snippet under this link: https://gitlab.com/snippets/1795330
I've tested this snippet in NJS, NodeJS (v4 & v10), and browser console; see details in the snippet's description.
I'm using the latest release of NJS - v0.2.7

##### NodeJS v10.15.0
```
peter@peterpc:~$ nodejs -v
v4.2.6
peter@peterpc:~$ nodejs /home/peter/git/rin/src/njs/local-debug/test-object-define-property-3.js
Testing Object.DefineProperty() method #3...
Define property works: true
Done.
```

##### NodeJS v10.15.0
```
peter@peterpc:~$ node -v
v10.15.0
peter@peterpc:~$ node /home/peter/git/rin/src/njs/local-debug/test-object-define-property-3.js
Testing Object.DefineProperty() method #3...
Define property works: true
Done.
```

##### Chrome v70.0.3538.77
(Browser console)
```
VM56:1  Testing Object.DefineProperty() method #3...
VM56:58 Define property works: true
VM56:61 Done.
VM56:62
```

##### NJS 0.2.7
```
peter@peterpc:~$ njs -v
0.2.7
peter@peterpc:~$ njs /home/peter/git/rin/src/njs/local-debug/test-object-define-property-3.js
'Testing Object.DefineProperty() method #3...'
'Define property works: %s' false
Assertion failed: Object.DefineProperty() does not work properly
    at anonymous (:8)
    at main (native)

```

##### System Information
 - **OS:** Ubuntu 16.04 (Linux peterpc 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
 - **Arch:** x86_64
 - **NJS Version:** v0.2.7

Best regards,
Peter Zaitcev

**Comment by xeioex** [comment]
@USSX-Hares 

Thank you for the report. 

Unfortunately, getters and setters are not supported yet. I will update the compatibility page.

**Comment by xeioex** [comment]
The work for adding accessor descriptions is in #118.
