### ISSUE TITLE
WIP: support async usage.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#104]
@xeioex 

I try to implement async operation by sync way, here's an example.

```
function hello(r) {
    var status = r.sleep();
    r.return(200, "I'm " + status);
}
```

Patch:
https://gist.github.com/hongzhidao/7bb63859965bac1904b63dfd5ca0828a

Please consider it. I talked to developers used to Lua, this way should be welcome.
And we can implement async `subrequest` like `sleep` method, including multiple subrequests.

Though there is a convenient way in js using await/async keywords we discussed, there are still inconvenient places.
```
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

async function something() {
    console.log("this might take some time....");
    await delay(5000);
    console.log("done!")
}

something(); // Actually, it's better to block here.
console.log("this will runs before 'done!'");
```

My suggestion is we can keep convenient non-standard APIs, such as `require`, `async_xxx`, etc.

#85

**Comment by xeioex** [comment]
@hongzhidao 

Hi,

Here is the [JavaScript language model](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop) in particular: 

```
Run-to-completion
Each message is processed completely before any other message is processed. This offers some nice properties when reasoning about your program, including the fact that whenever a function runs, it cannot be pre-empted and will run entirely before any other code runs (and can modify data the function manipulates). This differs from C, for instance, where if a function runs in a thread, it may be stopped at any point by the runtime system to run some other code in another thread.

Never blocking
A very interesting property of the event loop model is that JavaScript, unlike a lot of other languages, never blocks. Handling I/O is typically performed via events and callbacks, so when the application is waiting for an IndexedDB query to return or an XHR request to return, it can still process other things like user input. 
```

I still think it is important to stick to the basics of the language model. Otherwise nobody would understand the way njs works. Non-JavaScript programmers because they do not know JavaScript, and JavaScript programmers because njs would behave quite different from other implementations (standard js idioms would not work). 

> something(); // Actually, it's better to block here.

To me, it seems like a minor issue, you can simply put all your linear code inside async functions.

**Comment by hongzhidao** [comment]
By the standard way, developers need to know `subrequest` is asynchronous, and carefully use callback functions.

**Comment by drsm** [comment]
@hongzhidao 
```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

async function something() {
    console.log("this might take some time....");
    await delay(5000);
    console.log("done!")
}

// something(); // Actually, it's better to block here.
// No, an async function call without await indicates that we want to run it in the background.
// but the code above has error, as any thrown exceptions are go to nowhere.
// at least something like this should be used:
something().catch(function(e) {
// ignore all exceptions
});
console.log("this will runs before 'done!'");
```
