### ISSUE TITLE
Template literal support.

### ISSUE THREAD

**Issue by xeioex** [nginx/njs#107]
[Link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

to convert ugly code like:
```js
r.error(": " + errorset.error + ", " + errorset.error_description); 
```
into
```js
req.error(`: ${errorset.error}, ${errorset.error_description}`); 
```

Scope:
1) Multi-line strings
2) Simple variables references `${errorset.error}`

Optionally:
3) expression interpolation `${a + b}` (not sure)

Not included:
everything else.

Implementation details:
I suggest to see this as a syntax sugar for string concatenations.
`${errorset.error}, ${errorset.error_description}` =>
 `String.prototype.concat("",errorset.error, ", ", errorset.error_description)`

**Comment by hongzhidao** [comment]
@xeioex 

I plan to implement it next week.

**Comment by xeioex** [comment]
@hongzhidao 

Regarding the scope of work. See the updated initial message.

**Comment by drsm** [comment]
@xeioex @hongzhidao 
> expression interpolation ```${a + b}``` (not sure)

I'm using this in node very often.

maybe something like this:
```js
var logmsg = `[${(new Date()).toISOString()}] the message contents ${something} ${one + two}`;
```
can be transformed to:
```js
var __tmp = Array(6);
__tmp[0] = '[';
__tmp[1] = (new Date()).toISOString();
__tmp[2] = '] the message contents ';
__tmp[3] = something;
__tmp[4] = ' ';
__tmp[5] = one + two;
var logmsg = String.prototype.concat.apply('', __tmp);
```
or generate an array literal instead of a variable

**Comment by hongzhidao** [comment]
@xeioex @drsm 

Take a look, the patch is just for discussion.
https://gist.github.com/hongzhidao/1bed25550834947a40e79ac6c35cb467

```
var something = "test something";
var one = 1;
var two = 2;

var logmsg = `[${(new Date()).toISOString()}] the message contents ${something} ${one + two}`;
console.log(logmsg);
```
```
'[2019-03-26T04:09:57.288Z] the message contents test something 3'
```

**Comment by drsm** [comment]
@hongzhidao 
```js
>> var s = `1${ s }`
undefined
>> s
'11'
```
vs.

```js
> var s = `1${ s }`
undefined
> s
'1undefined'
```

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> ```js
> >> var s = `1${ s }`
> undefined
> >> s
> '11'
> ```
> 
> vs.
> 
> ```js
> > var s = `1${ s }`
> undefined
> > s
> '1undefined'
> ```
> 
> also:
> 
> ```js
> var s = 0;
> s = `x${s += '1'}`;
> ```

Get it, thanks.

**Comment by drsm** [comment]
@hongzhidao 
here is another one:
```js
>> var o = 1; `o = \`${o}\``
SyntaxError: Unexpected token "$" in shell:1
// expected: 'o = `1`'
```

**Comment by hongzhidao** [comment]
@drsm 

I haven't considered `\`, I want to confirm the way of `parser and generator` first with you and @xeioex .
But your test is really useful.

**Comment by xeioex** [comment]
@hongzhidao 
>  I want to confirm the way of parser and generator

regarding generator, I like more [drsm's way](https://github.com/nginx/njs/issues/107#issuecomment-475884762). 
Because, using simple addition would produce too much temporary values.

`${a} ${b} ${c} +${d}`
=> 'a ', 'a b', 'a b ', 'a b c', 'a b c ', 'a b c d'

**Comment by drsm** [comment]
@hongzhidao 
the functionality looks promising, thanks!
some tests that pass:
```js
`x${`y${'z'}`}`
`${{ toString: function() { throw new Error('err'); } }}`
```
todo:
```js
> var s = `${s='a'}${s}`; s
'aa'
> var s = `${s}${s='a'}`; s
'undefineda'
```

**Comment by hongzhidao** [comment]
@drsm 

> var __tmp = Array(6);
__tmp[0] = '[';
__tmp[1] = (new Date()).toISOString();
__tmp[2] = '] the message contents ';
__tmp[3] = something;
__tmp[4] = ' ';
__tmp[5] = one + two;
var logmsg = String.prototype.concat.apply('', __tmp);
or generate an array literal instead of a variable

`generate an array literal instead of a variable`
What does it mean? Show example please.

**Comment by drsm** [comment]
@hongzhidao 
```js
console.log(
    String.prototype.concat.apply('', [
        '[',
        (new Date()).toISOString(),
        '] the message contents ',
        'something',
        ' ',
        1 + 2
    ])
);
```

**Comment by xeioex** [comment]
@hongzhidao 

> What does it mean? Show example please.

Igor suggest to add a new VM instructions for invoking  String.prototype.concat.apply().

So genetated code can look like:
```
ARRAY
PROPERTY SET
PROPERTY SET
...
TEMPLATE LITERAL // to be added
```

**Comment by hongzhidao** [comment]
> Igor suggest to add a new VM instructions for invoking String.prototype.concat.apply().

Totally argee.

**Comment by hongzhidao** [comment]
@xeioex @drsm 

This feature supports two formats: 

1. template literal
```
var logmsg = `${start}[${(new Date()).toISOString()}] the message contents ${something} ${one + two}`;
// can be transformed to:
var __tmp = Array(9);
__tmp[0] = '';
__tmp[1] = start;
__tmp[2] = '[';
__tmp[3] = (new Date()).toISOString();
__tmp[4] = '] the message contents ';
__tmp[5] = something;
__tmp[6] = ' ';
__tmp[7] = one + two;
__tmp[8] = '';
```
```
ARRAY
PROPERTY SET
PROPERTY SET
...
TEMPLATE LITERAL // to be added
```

2. tagged template
```
function foo() { console.log(arguments); }

foo`${start}[${(new Date()).toISOString()}] the message contents ${something} ${one + two}`;
// can be transformed to:
var __tmp = Array(5);
__tmp[0] = Array(5);
__tmp[0][0] = '';
__tmp[0][1] = '[';
__tmp[0][2] = '] the message contents ';
__tmp[0][3] = ' ';
__tmp[0][4] = ''
__tmp[1] = start;
__tmp[2] = (new Date()).toISOString();
__tmp[3] = something;
__tmp[4] = one + two;
foo(__tmp);
```

Plans:
1. Implement the second format `tagged template` first, since it needn't add new instructions.
    And njs_parser_array and njs_parser_call_expression will be refactored.
2. Implement the format of `template literal`.

Patch for discussion.
Here's the draft patch which only support format 2.
https://gist.github.com/hongzhidao/d9bc57eb1f9ea1fccac8ac1b3b65a470

Demo:
```
function foo() {console.log(arguments)}

var start = 'NJS:';
var something = 'test';
var one = 1;
var two = 2;

foo`${start}[${(new Date()).toISOString()}] the message contents ${something} ${one + two
}`;
```
```
{0:['','[','] the message contents ',' ',''],1:'NJS:',2:'2019-03-31T07:17:17.844Z',3:'test',4:3}
```

**Comment by xeioex** [comment]
@hongzhidao 

> BTW, do you think it's time to introduce njs_parser_terminator.c?

Agree.

> Plans:
> Implement the second format tagged template first, since it needn't add new instructions.
> And njs_parser_array and njs_parser_call_expression will be refactored.
> Implement the format of template literal.

Agree. Looks promising.

**Comment by drsm** [comment]
@hongzhidao 
the layout of arguments is different there:
```js
> var test = function(...args) { console.log(args); }
undefined
> test`test test test`
[ [ 'test test test' ] ]
undefined
> var a = 1, b = 2, c = 3;
undefined
> test`test ${a} test ${b} test ${c}`
[ [ 'test ', ' test ', ' test ', '' ], 1, 2, 3 ]
undefined
> test`${a} test ${b} test ${c} test`
[ [ '', ' test ', ' test ', ' test' ], 1, 2, 3 ]
undefined
```

**Comment by hongzhidao** [comment]
@xeioex 

Refactored out njs_parser_terminator.c
https://gist.github.com/hongzhidao/4c02ddf28ae77ec4bca2f75bc35e8ba3

**Comment by xeioex** [comment]
@hongzhidao 
> Refactored out njs_parser_terminator.c.
>https://gist.github.com/hongzhidao/4c02ddf28ae77ec4bca2f75bc35e8ba3

I like the change, except, I think njs_parser_terminal.c should be a bit better. Will do.

**Comment by hongzhidao** [comment]
@xeioex 

Improved njs_parser_object() and njs_parser_array().
https://gist.github.com/hongzhidao/38c5208ba0dcbcf92b08ae267841bb8a

There is one place I still want to improve, but I can't find a better way.

1. According to njs_parser_object(), the `object` is created outside for loop. Is this right?
```
diff -r 03be823cd95b njs/njs_parser.c
--- a/njs/njs_parser.c	Tue Feb 12 18:56:04 2019 +0300
+++ b/njs/njs_parser.c	Mon Apr 01 11:18:31 2019 +0800
@@ -2352,6 +2352,13 @@ njs_parser_array(njs_vm_t *vm, njs_parse
     index = 0;
     left = NULL;

+    object = njs_parser_node_new(vm, parser, NJS_TOKEN_OBJECT_VALUE);
+    if (nxt_slow_path(object == NULL)) {
+        return NJS_TOKEN_ERROR;
+    }
+
+    object->u.object = obj;
+
     for ( ;; ) {
         token = njs_parser_token(parser);
         if (nxt_slow_path(token <= NJS_TOKEN_ILLEGAL)) {
@@ -2378,13 +2385,6 @@ njs_parser_array(njs_vm_t *vm, njs_parse
         node->u.value.data.truth = (index != 0);
         index++;

-        object = njs_parser_node_new(vm, parser, NJS_TOKEN_OBJECT_VALUE);
-        if (nxt_slow_path(object == NULL)) {
-            return NJS_TOKEN_ERROR;
-        }
-
-        object->u.object = obj;
-
         propref = njs_parser_node_new(vm, parser, NJS_TOKEN_PROPERTY);
         if (nxt_slow_path(propref == NULL)) {
             return NJS_TOKEN_ERROR;
```

2. simplify njs_parser_array_item.
The function will be used in `template literal`. I still want to eliminate the parameter `object`, but are not able to archieve it.
```
njs_parser_array_item(njs_vm_t *vm, njs_parser_t *parser,
    njs_parser_node_t *array, njs_parser_node_t *object,
    njs_parser_node_t *value)
```

**Comment by xeioex** [comment]
@hongzhidao 

> Introduced njs_variable_copy().
> https://gist.github.com/hongzhidao/f5174774af6c8d2256888ffb650c5429

BTW, do you have plans to reuse it somewhere else? If not, I am not sure it is worth it.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > Introduced njs_variable_copy().
> > https://gist.github.com/hongzhidao/f5174774af6c8d2256888ffb650c5429
> 
> BTW, do you have plans to reuse it somewhere else? If not, I am not sure it is worth it.

No plan, I only want to make njs_parser.c clean, now it's too large :)

**Comment by hongzhidao** [comment]
@xeioex 

Here's the patch of supporting initial tagged template.
https://gist.github.com/hongzhidao/b5ca18e7ab87dc5dd1199867ae057981

But the goal is to refactor njs_parser_object/array and njs_parser_call_expression.
I plan to split this into two patches.
1. Refactored njs_parser_object() and njs_parser_object().
2. Refactored njs_parser_call_expression().

> simplify njs_parser_array_item.

https://gist.github.com/hongzhidao/b5ca18e7ab87dc5dd1199867ae057981#file-njs-04-01-patch-L459
I try it in this way.

**Comment by xeioex** [comment]
@hongzhidao 

> Refactored njs_parser_object() and njs_parser_object().
> Refactored njs_parser_call_expression().

Looks good. Waiting for separate patches.

**Comment by hongzhidao** [comment]
@xeioex 

1. Refactored njs_parser_object() and njs_parser_object().
2. Refactored njs_parser_call_expression().
https://gist.github.com/hongzhidao/2deb9265753f3b8738d3dee5ace277fb

One detail. Is it right?
```
diff -r 03be823cd95b njs/njs_parser_expression.c
--- a/njs/njs_parser_expression.c	Tue Feb 12 18:56:04 2019 +0300
+++ b/njs/njs_parser_expression.c	Mon Apr 01 21:50:49 2019 +0800
@@ -815,7 +815,6 @@ njs_parser_call_expression(njs_vm_t *vm,
         case NJS_TOKEN_NAME:
             func = node;
             func->token = NJS_TOKEN_FUNCTION_CALL;
-            func->scope = parser->scope;  // I removed it.

             break;
```

**Comment by hongzhidao** [comment]
@xeioex @drsm 

I try to implement `njs_vmcode_template_literal` like below, welcome to suggest.
```
var logmsg = `[${(new Date()).toISOString()}] the message contents ${something} ${one + two}`;
//can be transformed to:

var __tmp = Array(6);
__tmp[0] = '[';
__tmp[1] = (new Date()).toISOString();
__tmp[2] = '] the message contents ';
__tmp[3] = something;
__tmp[4] = ' ';
__tmp[5] = one + two;
var logmsg = __tmp.join('');
```
```
njs_ret_t
njs_vmcode_template_literal(njs_vm_t *vm, njs_value_t *invld1,
    njs_value_t *retval)
{
    nxt_int_t           ret;
    njs_value_t         *value, arguments[2];
    njs_function_t      *function;
    njs_object_prop_t   *prop;
    nxt_lvlhsh_query_t  lhq;

    value = njs_vmcode_operand(vm, retval);

    if (!njs_is_primitive(value)) {

        lhq.key = nxt_string_value("join");
        lhq.key_hash = nxt_djb_hash(lhq.key.start, lhq.key.length);

        prop = njs_object_property(vm, value->data.u.object, &lhq);

        if (nxt_fast_path(prop != NULL)) {
            function = prop->value.data.u.function;

            arguments[0] = *value;
            arguments[1] = njs_string_empty;

            ret = njs_function_apply(vm, function, arguments, 2,
                                     (njs_index_t) retval);
            if (ret == NJS_APPLIED) {
                return 0;
            }

            return NXT_ERROR;
        }
    }

    return sizeof(njs_vmcode_template_literal_t);
}
```

BTW, I don't know how to write in string prototype?
```
var logmsg = String.prototype.concat.apply('', __tmp);
''.concat(what parameters); // ideal calling.
```

**Comment by hongzhidao** [comment]
@xeioex 

Here's the patch.
https://gist.github.com/hongzhidao/f72f9023dfebc8f751b4745b3965d0d9

Help check the design. I'll continue to perfect details.

**Comment by xeioex** [comment]
@hongzhidao 

> https://gist.github.com/hongzhidao/f72f9023dfebc8f751b4745b3965d0d9

The last (4th) revision looks good to me.

> String.raw()

looks interesting.

**Comment by drsm** [comment]
@xeioex @hongzhidao 
there also a ```raw``` array for tagged literals:
```js
$ node
> `\unicode`
`\unicode`
 ^^^^^^

SyntaxError: Invalid Unicode escape sequence

> String.raw`\unicode`
'\\unicode'
> function test(str, ...rest) { console.log(str); }
undefined
> test`\unicode`
[ undefined ]
undefined
> function test(str, ...rest) { console.log(str, str.raw); }
undefined
> test`\unicode`
[ undefined ] [ '\\unicode' ]
undefined
```

**Comment by hongzhidao** [comment]
@xeioex @drsm 

Take a look. (including escape string now)
https://gist.github.com/hongzhidao/f72f9023dfebc8f751b4745b3965d0d9

BTW, String.raw has not been supported, I'm not sure how to implement it yet.
Is it used often?

**Comment by drsm** [comment]
@hongzhidao 

> @drsm welcome to test, I think this feature is ready now :)

works fine for me, thanks!

> BTW, String.raw has not been supported, I'm not sure how to implement it yet.
> Is it used often?

it's just a syntax sugar, and it will complicate [things](https://tc39.github.io/proposal-template-literal-revision/) (included in ES2018).

**Comment by hongzhidao** [comment]
> it's just a syntax sugar, and it will complicate [things](https://tc39.github.io/proposal-template-literal-revision/) (included in ES2018).

Agree, do you think it's worth to implement `String.raw()` now?

**Comment by drsm** [comment]
@hongzhidao 
I'm OK if there will be a separate issue for that.

**Comment by xeioex** [comment]
@hongzhidao  @drsm 
Great job guys! Many thanks to both of you. Template literals are really useful for njs in nginx. Without your contribution would still be on the todo list.
