### ISSUE TITLE
WIP: Improved auto configure.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#110]
@xeioex 

Take a look. (draft)
https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

Generated Makefile.
https://gist.github.com/hongzhidao/671e48e01504debeae2e4c9babbd8092

Some thoughts, welcome to suggest.
1. Move nxt/auto to outside since njs also need auto configure. (I thought add njs/auto, but it looks bad)
2. Move all the generated file into build directory. (nxt/nxt_auto_config.h, nxt/Makefile.conf).
3. Add '-MMD -MF -MT'
4. Add auto/sources, auto/make inspired from UNIT.
5. rename build/njs as build/js, I can't find an ideal way to create build/njs directory.
    (or build/njs, build/src/nxt, build/src/njs?)
6. What about replace $NXT_LIB, $NXT_AUTO as nxt, auto? (hardcode the same in UNIT)
7. Rename NXT_BUILDDIR as NXT_BUILD_DIR?
8. Do you think njs is a library? (NJS_LIB_OBJS vs NJS_OBJS?). It seems yes.

Updated again.
https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

**Comment by hongzhidao** [comment]
@xeioex 

1. Improved Makefile.
```
# HG changeset patch
# User hongzhidao <hongzhidao@gmail.com>
# Date 1552401371 -28800
# Node ID 6211dd64d7935221764406781c73dae5e85b2b93
# Parent  49f4eb5afc9bd6528d08d2e07b4f1a3232c8a296
Improved Makefile.

diff -r 49f4eb5afc9b -r 6211dd64d793 Makefile
--- a/Makefile	Mon Mar 11 18:31:40 2019 +0300
+++ b/Makefile	Tue Mar 12 22:36:11 2019 +0800
@@ -7,7 +7,7 @@ NXT_BUILDDIR =	build

 $(NXT_BUILDDIR)/libnjs.a: \
 	$(NXT_LIB)/nxt_auto_config.h \
-	$(NXT_BUILDDIR)/njs_shell.o \
+	$(NXT_BUILDDIR)/njs.o \
 	$(NXT_BUILDDIR)/njs_vm.o \
 	$(NXT_BUILDDIR)/njs_boolean.o \
 	$(NXT_BUILDDIR)/njs_number.o \
@@ -55,7 +55,7 @@ NXT_BUILDDIR =	build
 	$(NXT_BUILDDIR)/nxt_sprintf.o \

 	ar -r -c $(NXT_BUILDDIR)/libnjs.a \
-		$(NXT_BUILDDIR)/njs_shell.o \
+		$(NXT_BUILDDIR)/njs.o \
 		$(NXT_BUILDDIR)/njs_vm.o \
 		$(NXT_BUILDDIR)/njs_boolean.o \
 		$(NXT_BUILDDIR)/njs_number.o \
@@ -104,6 +104,7 @@ NXT_BUILDDIR =	build

 all:	test lib_test

+.PHONY: njs
 njs:	$(NXT_BUILDDIR)/njs

 libnjs:	$(NXT_BUILDDIR)/libnjs.a
@@ -136,7 +137,7 @@ dist:
 	@echo
 	@exit 1

-$(NXT_BUILDDIR)/njs_shell.o: \
+$(NXT_BUILDDIR)/njs.o: \
 	$(NXT_BUILDDIR)/libnxt.a \
 	njs/njs.h \
 	njs/njs_core.h \
@@ -149,7 +150,7 @@ dist:
 	njs/njs.h \
 	njs/njs.c \

-	$(NXT_CC) -c -o $(NXT_BUILDDIR)/njs_shell.o $(NXT_CFLAGS) \
+	$(NXT_CC) -c -o $(NXT_BUILDDIR)/njs.o $(NXT_CFLAGS) \
 		-I$(NXT_LIB) -Injs \
 		njs/njs.c
```

2. Do you think target dist is still used?
Report error while running `make dist`
```
NJS_VER=`grep NJS_VERSION njs/njs.h | sed -e 's/.*"\(.*\)".*/\1/'`; \
	rm -rf njs-${NJS_VER} \
	&& hg archive njs-${NJS_VER}.tar.gz \
		      -p njs-${NJS_VER} \
		      -X ".hg*" \
	&& echo njs-${NJS_VER}.tar.gz done
abort: cannot give prefix when archiving to files
```

**Comment by xeioex** [comment]
@hongzhidao 

> Do you think target dist is still used?
> Report error while running make dist

yes. It it used.

```sh
make dist
NJS_VER=`grep NJS_VERSION njs/njs.h | sed -e 's/.*"\(.*\)".*/\1/'`; \
rm -rf njs-${NJS_VER} \
&& hg archive njs-${NJS_VER}.tar.gz \
              -p njs-${NJS_VER} \
              -X ".hg*" \
&& echo njs-${NJS_VER}.tar.gz done
njs-0.3.0.tar.gz done
```

**Comment by xeioex** [comment]
@hongzhidao 

> https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90#file-njs-auto-patch-L641

`nxt/auto/sources` `nxt/auto/make` are not available.

**Comment by hongzhidao** [comment]
OK, I plan to archive it by refactor. On it.

**Comment by xeioex** [comment]
@hongzhidao 

> Improved Makefile.

BTW, I am not sure, whether we need this. If it will be completely replaced with new code.

**Comment by hongzhidao** [comment]
@xeioex 

Take a look again.
https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

As far, auto/sources and auto/make have been successfully introduced.

**Comment by xeioex** [comment]
@hongzhidao 

> https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

I think, it is better to squash changes into one commit, while stating in commit log what was done.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > Improved Makefile.
> 
> BTW, I am not sure, whether we need this. If it will be completely replaced with new code.

Which patch?

**Comment by xeioex** [comment]
@hongzhidao 

From https://github.com/nginx/njs/issues/110#issuecomment-472028553

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90
> 
> I think, it is better to squash changes into one commit, while stating in commit log what was done.

OK.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> From [#110 (comment)](https://github.com/nginx/njs/issues/110#issuecomment-472028553)

The key is https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90#file-njs-auto-patch-L33

**Comment by xeioex** [comment]
> The key is https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90#file-njs-auto-patch-L33

BTW, regarding .PHONY

Why only njs target and not other non-file targets?

**Comment by xeioex** [comment]
@hongzhidao 

> And I think it's clear that we add njs.o.

it is true. But, is not it will be overwritten by nxt/make script in later commits?

**Comment by hongzhidao** [comment]
> > The key is https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90#file-njs-auto-patch-L33
> 
> BTW, regarding .PHONY
> 
> Why only njs target and not other non-file targets?

Actually, other targets are also needed.
Sorry that I mislead you. We can ignore it.
1. Previously I add build/njs/src.o, we need to distinguish build/njs and build/njs/.
2. build/njs.o is auto generated by auto/make.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > And I think it's clear that we add njs.o.
> 
> it is true. But, is not it will be overwritten by nxt/make script in later commits?

I'll commit these by a complete patch.

**Comment by xeioex** [comment]
@hongzhidao 

My concern is: if we have a huge changeset, I would rather have one such changeset instead of several of them. Logically, it is a single change (Introducing UNIT makefile dependency scripts.)

**Comment by hongzhidao** [comment]
@xeioex 

Take a look.
https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

**Comment by xeioex** [comment]
@hongzhidao 

>https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90

Looks great.  Except for `nxt/Makefile` do we really need it as independent makefile?

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > https://gist.github.com/hongzhidao/2c1ae0639771c366fa86093ecdac3e90
> 
> Looks great. Except for `nxt/Makefile` do we really need it as independent makefile?

I noticed it, it'll be deleted.

**Comment by hongzhidao** [comment]
@xeioex 

Do you think njs is a library? (NJS_LIB_OBJS vs NJS_OBJS?). It seems yes.
Yes, also we need a share library target.

Do you mean we need libnjs.so?

**Comment by xeioex** [comment]
@hongzhidao 

> Do you mean we need libnjs.so? (what about libnxt.so?)

yes (but only libnjs.so). It will be a separate topic, not for now.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > Do you mean we need libnjs.so? (what about libnxt.so?)
> 
> yes (but only libnjs.so). It will be a separate topic, not for now.

It's easy to add in. I'll add it in the same commit.

**Comment by xeioex** [comment]
@hongzhidao 

> It's easy to add in. I'll add it in the same commit.

yes, it is easy. No doubt. The main question is how we going to use it (link with nginx during configuration phase, we also have to install that library into system lib dirs (?? not sure)).

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > It's easy to add in. I'll add it in the same commit.
> 
> yes, it is easy. No doubt. The main question is how we going to use it (link with nginx during configuration phase, we also have to install that library into system lib dirs (?? not sure)).

In real case, I prefer to use static library, it's easier to maintain.

**Comment by xeioex** [comment]
@hongzhidao 

> In real case, I prefer to use static library, it's easier to maintain.

yes, therefore I would leave it as is for now (no .so targets).

**Comment by xeioex** [comment]
@hongzhidao 

You forgot to delete files in nxt/auto.

you did a new copy of the files in auto dir.
```
--- /dev/null	Thu Jan 01 00:00:00 1970 +0000
+++ b/auto/clang	Wed Mar 13 15:04:58 2019 +0800
```

The correct way is `hg mv` existing files to preserve history.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> You forgot to delete files in nxt/auto.
> 
> you did a new copy of the files in auto dir.
> 
> ```
> --- /dev/null	Thu Jan 01 00:00:00 1970 +0000
> +++ b/auto/clang	Wed Mar 13 15:04:58 2019 +0800
> ```
> The correct way is `hg mv` existing files to preserve history.

OK, I need commit again.

**Comment by xeioex** [comment]
@hongzhidao 

```diff
diff --git a/nginx/config b/nginx/config
--- a/nginx/config
+++ b/nginx/config
@@ -3,7 +3,7 @@ ngx_addon_name="ngx_js_module"
 if [ $HTTP != NO ]; then
     ngx_module_type=HTTP
     ngx_module_name=ngx_http_js_module
-    ngx_module_incs="$ngx_addon_dir/../nxt $ngx_addon_dir/../njs"
+    ngx_module_incs="$ngx_addon_dir/../nxt $ngx_addon_dir/../njs $ngx_addon_dir/../build"
     ngx_module_deps="$ngx_addon_dir/../build/libnjs.a"
     ngx_module_srcs="$ngx_addon_dir/ngx_http_js_module.c"
     ngx_module_libs="PCRE $ngx_addon_dir/../build/libnjs.a -lm"
@@ -14,7 +14,7 @@ fi
 if [ $STREAM != NO ]; then
     ngx_module_type=STREAM
     ngx_module_name=ngx_stream_js_module
-    ngx_module_incs="$ngx_addon_dir/../nxt $ngx_addon_dir/../njs"
+    ngx_module_incs="$ngx_addon_dir/../nxt $ngx_addon_dir/../njs $ngx_addon_dir/../build"
     ngx_module_deps="$ngx_addon_dir/../build/libnjs.a"
     ngx_module_srcs="$ngx_addon_dir/ngx_stream_js_module.c"
     ngx_module_libs="PCRE $ngx_addon_dir/../build/libnjs.a -lm"
```

**Comment by hongzhidao** [comment]
@xeioex 

I have an idea. Can you recommit it and I review it? It's easier for me to find a problem.
I'm not sure it's reasonable :)

**Comment by xeioex** [comment]
@hongzhidao 

OK, but I am a bit busy now, will do later today.

**Comment by xeioex** [comment]
@hongzhidao 

https://gist.github.com/xeioex/4fc3879de40a83085c4ff06cd9383a76

Still in progress. Many changes.

for example
```
clean:
	rm -rf $NXT_BUILD_DIR Makefile
```
removes main makefile.

Makefile is redesigned a bit:
it consist of 
1) static part (make clean, make dist, ..)
 2) generated parts:
```
-include build/Makefile.conf
...
-include build/Makefile
```

2. make njs (without configure is fixed), not it warns: `Please run ./configure before make`

**Comment by hongzhidao** [comment]
@xeioex  I'll see it tomorrow.

**Comment by xeioex** [comment]
@hongzhidao 

https://gist.github.com/xeioex/c2e5f72d08874573c200e1d63d719fcb

1. generating in auto/make njs and nxt tests.

2. test targets are refactored.

What is left to do:

1. `hg mv` is not ready yet for all `nxt/auto` files.

2. NXT_BUILD_DIR is not used in main Makefile (return it back).

**Comment by hongzhidao** [comment]
>It seems, Makefile.conf can be also removed.

Agree, I do it base on your commit tomorrow.

**Comment by xeioex** [comment]
@hongzhidao 

>In nginx config.make, build is hard-code, now in main Makefile it's also hard-code.
So, what about replace NXT_BUILD_DIR as build?

`build` was (I think it should be returned back) a default value for NXT_BUILD_DIR
https://gist.github.com/xeioex/c2e5f72d08874573c200e1d63d719fcb#file-deps-03-13-patch-L1855

So, is config.make simply does `./configure && make` it gets what is wants.

on the other hand, if you do it manually you can change it through env variables.

> If it's hard to deal, we can separate it as a patch. It can make the task easier.

IMHO, it is not that hard, see https://gist.github.com/xeioex/c2e5f72d08874573c200e1d63d719fcb#file-deps-03-13-patch-L998 (nxt/auto/editline -> auto/editline)

1. `hg mv -f nxt/auto/editline auto/editline`
2. It can be do in semiautomatic way,  replace:
`$nxt_echo -> $echo`
`${NXT_AUTO}feature -> auto/feature`

I can do it myself.

**Comment by hongzhidao** [comment]
@xeioex 

> It seems, Makefile.conf can be also removed.

Based on the release (not your commit).
https://gist.github.com/hongzhidao/e31175b2fa9fe041aff54320625c13a9

1. Separate $NXT_LIBRT from $NXT_LIB_AUX_LIBS
2. Add $NXT_EDITLINE_LIB into $NXT_LIB_AUX_LIBS
3. Move these code into auto/make. (https://gist.github.com/hongzhidao/e31175b2fa9fe041aff54320625c13a9#file-makefile-conf-patch-L45)
4. Add $NXT_EDITLINE_LIB default value.
https://gist.github.com/xeioex/c2e5f72d08874573c200e1d63d719fcb#file-deps-03-13-patch-L1005
https://gist.github.com/hongzhidao/e31175b2fa9fe041aff54320625c13a9#file-makefile-conf-patch-L84

**Comment by xeioex** [comment]
@hongzhidao 

> Separate $NXT_LIBRT from $NXT_LIB_AUX_LIBS. Reference to Unit.

Done

> Add $NXT_EDITLINE_LIB into $NXT_LIB_AUX_LIBS.

NXT_EDITLINE_LIB is only needed for njs_shell.c, left as is.

> Add $NXT_EDITLINE_LIB default value.

Done

> hg mv is not ready yet for all nxt/auto files.

Done

> NXT_BUILD_DIR is not used in main Makefile (return it back).

Done

> It seems, Makefile.conf can be also removed.

Done

Final version: https://gist.github.com/xeioex/4153e421c7034a445b64962199e52177

Please, check various targets combination.

**Comment by hongzhidao** [comment]
> https://gist.github.com/xeioex/4153e421c7034a445b64962199e52177

Great work.

1. `//`
https://gist.github.com/xeioex/4153e421c7034a445b64962199e52177#file-deps-03-14-patch-L1205

**Comment by xeioex** [comment]
> https://gist.github.com/xeioex/4153e421c7034a445b64962199e52177#file-deps-03-14-patch-L1205

fixed

> https://gist.github.com/xeioex/4153e421c7034a445b64962199e52177#file-deps-03-14-patch-L1232

BTW, https://github.com/nginx/unit/blob/master/auto/make#L124

**Comment by hongzhidao** [comment]
> BTW, https://github.com/nginx/unit/blob/master/auto/make#L124

I think UNIT missed it.

**Comment by xeioex** [comment]
I plan to commit it tomorrow.

**Comment by xeioex** [comment]
@hongzhidao 

FYI, absence of `\\` before $njs_dep_post is not a bug. $njs_dep_post is a separate command. On all platforms except solaris it is empty.
On solaris 11:
```
cc -o build/njs_unit_test -fPIC -O -fast -errwarn=%all -g -m64 \
	-I/usr/include/pcre -I nxt -I build \
	-xMMD -xMF build/test/njs_unit_test.dep.tmp \
	-Injs njs/test/njs_unit_test.c build/libnjs.a \
	-lm  -lpcre \
	@sed -e 's#^.*:#build/njs_unit_test.c:#' build/test/njs_unit_test.dep.tmp > build/test/njs_unit_test.dep && rm -f build/test/njs_unit_test.dep.tmp
ld: fatal: file @sed: open failed: No such file or directory
ld: fatal: file build/test/njs_unit_test.dep.tmp: not an ELF object
gmake: *** [build/Makefile:635: build/njs_unit_test] Error 2
```
