### ISSUE TITLE
MQTT TLS client certificates

### ISSUE THREAD

**Issue by dusanb94** [nginx/njs#111]
Hi,

I'm working on mutual authentication feature between MQTT client and broker, and I follow these tutorials: https://www.nginx.com/blog/nginx-plus-iot-load-balancing-mqtt and https://www.nginx.com/blog/nginx-plus-iot-security-encrypt-authenticate-mqtt/#mqtt-client-certs. However, the code examples are extremely out of date and this JavaScript code does not work with recent versions of njs, so I've tried to write my own code following your example from here: https://gist.github.com/nginx-gists/0e93fe7813ec131fed8329d10ead70ea#file-mqtt-js. However, I can't figure out what is the possible replacement for the following snippet:
``` javaScript
if ( s.buffer.toString().length == 0 ) { // Initial calls may
    s.log("No buffer yet");              // contain no data, so
    return s.AGAIN;                      // ask that we get called again 
} else if ( client_messages == 1 ) {     // CONNECT is first packet from the client...
``` 
From version 0.2.4, s.(OK, ABORT, AGAIN, DECLINED, ERROR) are replace with s.(allow(), done(), decline()). In my case, the initial call does not contain any data. In logs, I can see that I do not read all of the data received from the client. So, when I send, let's say, 50 bytes of data, an event is triggered, but data passed to `upload` callback is empty. Is this a bug? Can I somehow trigger this event again?

**Comment by xeioex** [comment]
Hi @dusanb94 

Sorry for delay.

```js
if ( s.buffer.toString().length == 0 ) { // Initial calls may
    s.log("No buffer yet");              // contain no data, so
    return s.AGAIN;                      // ask that we get called again 
}
```

this code is not needed anymore. Since 0.2.4 js_filter function is not invoked with empty data chunk.
Instead js_filter function is invoked only once and is expected to register a callback if it wants to receive data. See [this](http://nginx.org/en/docs/stream/ngx_stream_js_module.html#example) example.

**Comment by xeioex** [comment]
@dusanb94 

Please, close the issue if your problem is resolved.

**Comment by sandman-cs** [comment]
Would it be possible to get an example of what the new mqtt.js should be?
