### ISSUE TITLE
Second slash is removed from http:// or https:// scheme inside url

### ISSUE THREAD

**Issue by korneevm** [nginx/njs#123]
When passing url with schema inside url, one of the slashes is removed in r.url. 

Let's say I have a function that process url in some way:

`function img_path(r) {
    r.log(r.uri);
    ....
}`

If I'll try to access something like localhost/unsafe/300x200/smart/https://www.davishighnews.com/wp-content/uploads/2018/10/TEST-900x534.jpg

inside r.url I'll get /unsafe/300x200/smart/https:/www.davishighnews.com/wp-content/uploads/2018/10/TEST-900x534.jpg - one slash (https:/www) instead of two (https://www).

I've managed to reproduce this behavior on nginx 1.4.1, 1.4.2 and 1.5.10

**Comment by drsm** [comment]
Hi @korneevm !
1. https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax
> Of the ASCII character set, the characters ```: / ? # [ ] @``` are reserved for use as delimiters of the generic URI components and must be percent-encoded – for example, %3F for a question mark.

2. http://nginx.org/en/docs/http/ngx_http_core_module.html#merge_slashes

**Comment by korneevm** [comment]
@drsm thanks, didn't knew this
