### ISSUE TITLE
import module and nginx

### ISSUE THREAD

**Issue by dongwanjun123** [nginx/njs#128]
Hi @xeioex
There is a question, I don't know how to solve it.
```javascript
[root@NetEnc-centos7-dev-vm path-to-njs]# ./build/njs -p /home/work/dwj/es/ /home/work/dwj/bb.js
{bf:2}
[root@NetEnc-centos7-dev-vm path-to-njs]# more /home/work/dwj/bb.js
import b from "./es/b.js"
console.log(b);
[root@NetEnc-centos7-dev-vm path-to-njs]# 
```
As you can see, I currently compiled  "/home/work/dwj/bb.js" via /build/njs in the njs path, Now I want to compile "/home/work/dwj/bb.js"  through the nginx, So I wrote the “/home/work/dwj/bb.js” in the nginx configuration file. like this:
```javascript
js_include wcone/hello.js;
 location = /hello {
        js_content hello;
    }
[root@NetEnc-centos7-dev-vm bin]# more /infosec/webenc/conf/wcone/hello.js
import b from "/home/work/dwj/es/b.js"
function hello(r) {
  r.return(200,b);
}
[root@NetEnc-centos7-dev-vm bin]# curl http://127.0.0.1:8989/hello
[object Object][root@NetEnc-centos7-dev-vm bin]# 
```
Js_include also parses the script through njs, but  this way the output is [object Object].How to solve this，is the configuration file for nginx written incorrectly?
Thank you !

**Comment by xeioex** [comment]
@dongwanjun123 

> Js_include also parses the script through njs, but this way the output is [object Object].How to solve this，is the configuration file for nginx written incorrectly?

No, r.return() and r.log() uses object.toString() method to stringify an object. Where as console.log() uses njs.dump() which uses an advanced method to stringify values.

```js
>> var o = {a:1}
undefined
>> o.toString()
'[object Object]'
>> njs.dump(o)
'{a:1}'
```

njs.dump() is available inside nginx.
