### ISSUE TITLE
req.subrequest() there is no way to specify/override HTTP headers

### ISSUE THREAD

**Issue by drsm** [nginx/njs#13]
```
    location = /check {
        internal;
        proxy_set_header Accept-Encoding '';
        proxy_set_header Content-Type 'application/x-www-form-urlencoded';
        proxy_pass https://www.google.com/recaptcha/api/siteverify;
    }
```
while proxying i can solve this, but if a subrequest hits a js_content location there is no way.

**Comment by xeioex** [comment]
do you mean to specify/override HTTP headers of req.subrequest()?

You are expected to configure the desired request headers in a sub location.

This is pretty similar to what lua module does:
https://github.com/openresty/lua-nginx-module#ngxlocationcapture
 `Note that subrequests issued by ngx.location.capture inherit all the request headers of the current request by default and that this may have unexpected side effects on the subrequest responses. For example, when using the standard ngx_proxy module to serve subrequests, an "Accept-Encoding: gzip" header in the main request may result in gzipped responses that cannot be handled properly in Lua code. Original request headers should be ignored by setting proxy_pass_request_headers to off in subrequest locations.`

You can find a more elaborate example of req.subrequest() here: https://github.com/nginxinc/nginx-openid-connect/blob/master/openid_connect.server_conf#L35

**Comment by drsm** [comment]
@xeioex thank you! now it is clear how it works. 

yes i mean the subrequest's headers.
the intent was to keep a subrequest  creation logic in one place, actually.
