### ISSUE TITLE
njs and  nginx

### ISSUE THREAD

**Issue by dongwanjun123** [nginx/njs#137]
Hi @xeioex 
There is a problem, how to pass parameters between nginx and njs.  For example：
The  configuration file of nginx is as follows:
```javascript
js_include wcone/hello.js;
location = /hello {
        js_content hello;
    }
```
The content of "hello.js" as follows:
```javascript
import main from "main.js"
import replace from "replace_ast.js"
import Map from "Map.js"
import jscode from "escodegen.js"

function hello(r,org_js)
{
    var ast = main.parse(org_js);
    var myMap = new Map.Map();
    myMap.put("iduser","gergreih");
    myMap.put("idpasswd","gergergerhr");

    replace.replace_ast(ast,myMap);
    var js = jscode.generate(ast);
    r.return(200,njs.dump(js));
}
```
so, how can I  pass the parameter "org_js" to the function hello via "js_content" or "js_set"?
Thank you!

**Comment by xeioex** [comment]
@dongwanjun123 

js_content always invokes its function with one argument.

you can simply use another wrapper function

```js

function hello(r)
{
     hello_orig(r, org_js);
}

function hello_orig(r, org_js) {
...
}


```

**Comment by dongwanjun123** [comment]
Hi@xeioex 
Your method is not what I want. I want to pass arguments when I invoke function “hello”.
So, you mean that nginx can only pass the parameter "r" to njs?

**Comment by dongwanjun123** [comment]
@xeioex  
one more question, how to properly use the 'fs' file modules  in njs？
```javascript
[root@NetEnc-centos7-dev-vm bin]# curl http://127.0.0.1:80/hello
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
[root@NetEnc-centos7-dev-vm bin]# more /infosec/webenc/conf/wcone/hello.js 
import main from "main.js"
import replace from "replace_ast.js"
import Map from "Map.js"
import jscode from "escodegen.js"

function hello(r)
{
    var fs =  require('fs');
     
    var data = fs.readFileSync('main.c', 'utf-8');
    
    r.return(200,njs.dump(data));
}
[root@NetEnc-centos7-dev-vm bin]# 
```

**Comment by drsm** [comment]
@dongwanjun123
```js
 build/njs
interactive njs 0.3.2

v.<Tab> -> the properties and prototype methods of v.
type console.help() for more information

>> var fs = require('fs');
undefined
>> fs.readFileSync('main.c', 'utf-8');
TypeError: Unknown encoding: "utf-8"
    at fs.readFileSync (native)
    at main (native)

>> fs.readFileSync('main.c', 'utf8');
Error: No such file or directory
    at fs.readFileSync (native)
    at main (native)
```
better use `try/catch` there and ```r.return(500,error_info)```

**Comment by dongwanjun123** [comment]
@xeioex 
How should I specify the file path？
```javascript
>> var fs = require('fs')
undefined
>> fs.readFileSync('/root/main.c', 'utf8');
Error: Non-UTF8 file, convertion is not implemented
    at fs.readFileSync (native)
    at main (native)
```

**Comment by xeioex** [comment]
@dongwanjun123 

> So, you mean that nginx can only pass the parameter "r" to njs?

yes.

> How should I specify the file path？

Only absolute path is supported.

**Comment by dongwanjun123** [comment]
Hi @xeioex 
I have a question.
Is the "ctx" of the "r" the same as  "r->parent" ?
```javascript
 ctx = ngx_http_get_module_ctx(r, ngx_http_js_module);
    if (ctx && ctx->done) {
        return NGX_OK;
    }
    if (ctx == NULL) {
        ctx = ngx_pcalloc(r->pool, sizeof(ngx_http_js_ctx_t));
        if (ctx == NULL) {
            return NGX_ERROR;
        }
        ngx_http_set_ctx(r, ctx, ngx_http_js_module);
    }
    ctx->done = 1;
    jmcf = ngx_http_get_module_main_conf(r, ngx_http_js_module);
    ctx = ngx_http_get_module_ctx(r->parent, ngx_http_js_module);
```
This code is in function "ngx_http_js_subrequest_done", there is no place to set "ctx" for r->parent, I don't quite understand it here. Can you tell me about the process?

**Comment by xeioex** [comment]
> Is the "ctx" of the "r" the same as "r->parent" ?

no, it is not.

ngx_http_js_subrequest_done(r - is a subrequest here)

...
// but we call the original request callback inside original request vm
ngx_http_js_handle_event(r->parent, vm_event, njs_value_arg(&reply), 1);


> This code is in function "ngx_http_js_subrequest_done", there is no place to set "ctx" for r->parent, I don't quite understand it here. Can you tell me about the process?

`ctx->done` is a way to handle the fact that ngx_http_js_subrequest_done() can be invoked more than  once in some cases by nginx.  So we need to store somewhere that callback was already called.

"ctx" for r->parent was already created at the moment js_content handler was invoked.

**Comment by fishioon** [comment]
> Hi @xeioex
> There is a problem, how to pass parameters between nginx and njs. For example：
> The configuration file of nginx is as follows:
> 
> ```js
> js_include wcone/hello.js;
> location = /hello {
>         js_content hello;
>     }
> ```
> 
> The content of "hello.js" as follows:
> 
> ```js
> import main from "main.js"
> import replace from "replace_ast.js"
> import Map from "Map.js"
> import jscode from "escodegen.js"
> 
> function hello(r,org_js)
> {
>     var ast = main.parse(org_js);
>     var myMap = new Map.Map();
>     myMap.put("iduser","gergreih");
>     myMap.put("idpasswd","gergergerhr");
> 
>     replace.replace_ast(ast,myMap);
>     var js = jscode.generate(ast);
>     r.return(200,njs.dump(js));
> }
> ```
> 
> so, how can I pass the parameter "org_js" to the function hello via "js_content" or "js_set"?
> Thank you!

You also can pass variable with  r.variables
In nginx.conf set variable, and read from r.variables

**Comment by dongwanjun123** [comment]
Hi @fishioon
Can you give me an example ?
```javascript
include wcone/upteam.conf;
js_path "/home/work/ast/es/";
js_include wcone/hello.js;   
js_set $var "gergoerigjoehjoerhworhgrwohrho";
[root@NetEnc-centos7-dev-vm ~]# more /infosec/webenc/conf/wcone/hello.js 
import main from "main.js"
import Map from "Map.js"
import replace from "replace_ast.js"
import jscode from "escodegen.js"
function hello(r)
{
   var org_js="function cassecheck(o){c1=o.user.value;spm=o.passwd.value;c1=document.getElementById(\"\iduser\"\).value;}";
   var ast = main.parse(org_js);
   var myMap = new Map.Map();
   myMap.put("iduser","gergerhgetr");
   replace.replace_ast(ast,myMap);
   var js = jscode.generate(ast);
   var m = r.variables;
   r.return(200,njs.dump(m));
}
[root@NetEnc-centos7-dev-vm bin]# curl http://127.0.0.1:80/hello
{type:"object",props:["getter","setter"]}
```
So, How to get the variable $var .
Thanks!

**Comment by fishioon** [comment]
nginx.conf:
set $token '123456';

hello.js:
function hello(r) {
  r.return(200, r.variables.token);
}

**Comment by dongwanjun123** [comment]
@fishioon 
No, it doesn't work.
```javascript
js_include wcone/hello.js;
set $tm 'gergoerigjoehjoerhworhgrwohrho';
[root@NetEnc-centos7-dev-vm bin]# ./webenc 
nginx: [emerg] "set" directive is not allowed here in /infosec/webenc/conf/wcone/server.conf:5
```

**Comment by fishioon** [comment]
> @fishioon
> No, it doesn't work.
> 
> ```js
> js_include wcone/hello.js;
> set $tm 'gergoerigjoehjoerhworhgrwohrho';
> [root@NetEnc-centos7-dev-vm bin]# ./webenc 
> nginx: [emerg] "set" directive is not allowed here in /infosec/webenc/conf/wcone/server.conf:5
> ```

http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#set

set Context: server, location, if

**Comment by fishioon** [comment]
More examples: https://github.com/xeioex/njs-examples
Also you can reference the project https://github.com/fishioon/nginx-oidc

**Comment by juliyvchirkov** [comment]
> No, it doesn't work.
> 
> ```js
> js_include wcone/hello.js;
> set $tm 'gergoerigjoehjoerhworhgrwohrho';
> [root@NetEnc-centos7-dev-vm bin]# ./webenc 
> nginx: [emerg] "set" directive is not allowed here in /infosec/webenc/conf/wcone/server.conf:5
> ```

@dongwanjun123, you can use **map** in **http** context, where **set** is not available

```
    js_include wcone/hello.js;

    map var $tm {
        volatile;
        default 'gergoerigjoehjoerhworhgrwohrho';
    }
```
