### ISSUE TITLE
req.subrequest() reply.body does not decoded to plain text

### ISSUE THREAD

**Issue by drsm** [nginx/njs#14]
when server's answer received with Content-Encoding: gzip .

is it ok?

**Comment by xeioex** [comment]
Here you have two options:
1) proxy njs subrequest through location with 'gunzip on' http://nginx.org/en/docs/http/ngx_http_gunzip_module.html module (by default it is off).
2) provide appropriate Accept-Encoding header to enforce backend to respond in plain text.

**Comment by drsm** [comment]
thanks!
