### ISSUE TITLE
Stack-overflow with some invalid inputs

### ISSUE THREAD

**Issue by HongxuChen** [nginx/njs#156]
njs may crash due to stack-overflow with some invalid inputs. These inputs can be files starting with large numbers of repeated `(` or `[`. On my machine, a regularly built njs may segfault with such a file of 8k size.

**update**: Files with only `{` is also affected.

**Comment by xeioex** [comment]
@HongxuChen 

Thanks for your report, the issue seems to be a duplicate of #146
