### ISSUE TITLE
Error compiling 0.3.2 on Ubuntu

### ISSUE THREAD

**Issue by Delagen** [nginx/njs#169]
```
njs/njs_shell.c: In function ‘njs_interactive_shell’:
njs/njs_shell.c:498:9: error: implicit declaration of function ‘add_history’; did you mean ‘rl_clear_history’? [-Werror=implicit-function-declaration]
         add_history((char *) line.start);
         ^~~~~~~~~~~
         rl_clear_history
cc1: all warnings being treated as errors
```

**Comment by xeioex** [comment]
Hi @Delagen 

Try to install ` libreadline-dev` first.

**Comment by Delagen** [comment]
![image](https://user-images.githubusercontent.com/783335/58165011-8e3c6100-7c8f-11e9-9f8c-ed4a675e5111.png)

**Comment by xeioex** [comment]
@Delagen please, show the exact commands you are typing, and what you are getting.

`make clean &&  ./configure` - outputs dependencies status.

**Comment by Delagen** [comment]
The same commands compiled successfully with 0.3.1

**Comment by xeioex** [comment]
@Delagen 

> The same commands compiled successfully with 0.3.1

in 0.3.2 libreadline was made the first choice library and libedit the second.

If you want meaningful response, please provide the output of:
1) `lsb_release -a`
2) `make clean && ./configure`

You can upload text output here: https://gist.github.com/ and paste the link.

**Comment by Delagen** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

configuring for Linux 5.0.0-15-generic x86_64
checking for C compiler: cc
 + using GNU C compiler
 + gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)
checking for GCC unsigned __int128 ... found
checking for GCC __builtin_expect() ... found
checking for GCC __builtin_unreachable() ... found
checking for GCC __builtin_prefetch() ... found
checking for GCC __builtin_clz() ... found
checking for GCC __builtin_clzll() ... found
checking for GCC __attribute__ visibility ... found
checking for GCC __attribute__ malloc ... found
checking for GCC __attribute__ aligned ... found
checking for NAN to uint conversion ... 0
checking for clock_gettime(CLOCK_MONOTONIC) ... found
checking for struct tm.tm_gmtoff ... found
checking for altzone ... not found
checking for posix_memalign() ... found
checking for getrandom() ... found
checking for explicit_bzero() ... found
checking for PCRE library ... found
 + PCRE version: 8.39
checking for GNU readline library ... found
creating build/Makefile
checking for expect ... found
 + Expect version: expect version 5.45.4

**Comment by xeioex** [comment]
@Delagen 

I guess the issue is that some build files from previous builds are still in your working repository.
I suggest to make a clean new copy of the repo.

```
hg clone http://hg.nginx.org/njs
cd njs
hg checkout 0.3.2
./configure && make 
```

**Comment by Delagen** [comment]
@xeioex Yes... this is fixed this error
