### ISSUE TITLE
subRequest to a named location

### ISSUE THREAD

**Issue by vigie** [nginx/njs#17]
Hi

I'd like my njs function to manipulate the req body and then send it along to a private location that is not exposed in the conf file as a public location. I tried

   req.subrequest('@myNamedLocation', ...

and
  
  req.subrequest('http://my.private.url', ...

but in both cases nginx looked in the html folder for a file with these names.

Please advise on how I can best achieve this use case.

Thanks,
Matt

**Comment by xeioex** [comment]
Hi @vigie,

You can make a subrequest to an internal location. Please, take a look: http://nginx.org/en/docs/http/ngx_http_core_module.html#internal

for example:
```javascript

req.subrequest('/internal', {body:my_body}, 
                           function(reply) {res.return(reply.status == 200 ? 200 : 500)})
```

**Comment by vigie** [comment]
This is exactly what I was looking for, `internal` had escaped me somehow.

Thanks very much for the quick help @xeioex
