### ISSUE TITLE
Any plan to support 'child_process' module?

### ISSUE THREAD

**Issue by fishioon** [nginx/njs#171]

**Comment by xeioex** [comment]
Hi @fishioon,

No, there are no plans for it. njs creates a new VM (because they are cheap to create) per each incoming request. Spawning a process per request is a heavy task, especially under heavy load, imagine 10k reqs/sec or more.

**Comment by fishioon** [comment]
Thanks.
Like the 'https://stackoverflow.com/questions/22891148/nginx-how-to-run-a-shell-script-on-every-request'.
Sometimes it's very useful.
