### ISSUE TITLE
Segmentation fault during malloc_consolidate

### ISSUE THREAD

**Issue by jzebor** [nginx/njs#175]
Malformed input file will cause a segmentation fault of njs version 0.3.3 during the call to "malloc_consolidate". The issue appears to be a memory alignment problem which manifests shortly after “nxt_memalign” makes a call to the “posix_memalign” function. This bug was found with AFL. The input file to reproduce this issue is attached. [big_empty.js.txt](https://github.com/nginx/njs/files/3252995/big_empty.js.txt)

Here's the core stack trace with memory addresses removed.
```
0  malloc_consolidate (av=av@entry=<main_arena>) at malloc.c:4183
1  _int_malloc (av=av@entry=<main_arena>, bytes=bytes@entry=44328) at malloc.c:3450
2  __GI___libc_malloc (bytes=44328) at malloc.c:2913
3  _mid_memalign (address=<optimized out>, bytes=44328, alignment=140737488340928) at malloc.c:3087
4  __posix_memalign (memptr=memptr@entry=, alignment=<optimized out>, size=44328) at malloc.c:5028
5  nxt_memalign (alignment=<optimized out>, size=<optimized out>) at nxt/nxt_malloc.c:26
6  nxt_mp_alloc_large (size=44281, alignment=16, mp=) at nxt/nxt_mp.c:605
7  nxt_mp_alloc (mp=, size=size@entry=44281) at nxt/nxt_mp.c:310
8  njs_json_buf_pullup (stringify=, stringify=, str=<synthetic pointer>) at njs/njs_json.c:2055
9  njs_vm_value_dump (vm=vm@entry=, retval=, value=value@entry=, console=console@entry=0, indent=indent@entry=1) at njs/njs_json.c:2535
10 njs_vm_retval_dump (vm=vm@entry=, dst=dst@entry=, indent=indent@entry=1) at njs/njs.c:709
11 njs_output (opts=, ret=0, vm=) at njs/njs_shell.c:707
12 njs_process_script (console=<njs_console>, opts=opts@entry=, script=script@entry=) at njs/njs_shell.c:773
13 njs_process_file (vm_options=, opts=) at njs/njs_shell.c:619
14 main (argc=<optimized out>, argv=<optimized out>) at njs/njs_shell.c:281
```

**Comment by jzebor** [comment]
There is a similar condition which can result in a sig bus fault instead of a seg fault. I believe the root cause for both of these faults is likely the same so I'm attaching a sample file which can result in sigbus instead of seg fault to this issue. The stack trace is the same in both cases, only the fault code differs.

[sigbus.js.txt](https://github.com/nginx/njs/files/3253566/sigbus.js.txt)

**Comment by xeioex** [comment]
Memory sanitizer report in sigbus.js.txt
https://gist.github.com/fe715e978d36378d7f4377246c52c4b5

**Comment by xeioex** [comment]
Cannot reproduce after https://github.com/nginx/njs/commit/c3a334e53b39a171c28235ef7cdfb6552579bf5f
