### ISSUE TITLE
Compiling with `--with-pcre=PCRE_DIR` causes `failed to create JS VM`

### ISSUE THREAD

**Issue by CarterLi** [nginx/njs#18]
See https://travis-ci.org/CarterLi/njs/jobs/392058509#L468

Maybe relate to https://github.com/nginx/njs/blob/master/nxt/auto/pcre#L11. The script always uses system PCRE whose version may not match the PCRE version used to build nginx.

**Comment by xeioex** [comment]
Hi,

Thank you for the report.

There are two issues related to the problem.
1) njs uses global pcre-config (it is not hard to fix it)
2) nginx, while building modules, does not pass any info about extra libs to the njs configure.  The issue is going to be a little bit tricky to fix, because, as of now,  there is not simple way to pass the info about the proper pcre dir to njs configure.

**Comment by CarterLi** [comment]
> The issue is going to be a little bit tricky to fix, because, as of now, there is not simple way to pass the info about the proper pcre dir to njs configure.

What about let user specify the pcre dir?

**Comment by xeioex** [comment]
>What about let user specify the pcre dir?

It will not fix the issue. Because, nginx itself calls njs configure script (https://github.com/nginx/njs/blob/master/nginx/config.make, https://github.com/nginx/njs/blob/master/nginx/config) while building the module.

**Comment by micheljung** [comment]
So is there any workaround? Does it mean we can't build NJS into an nginx with PCRE?

**Comment by xeioex** [comment]
@micheljung 

Yes, there are many of ways.

>Does it mean we can't build NJS into an nginx with PCRE?

We can. njs [infers](https://github.com/nginx/njs/blob/master/auto/pcre#L13) pcre info from 'pcre-config' binary. pcre-config is a shell script.

```sh
$ which pcre-config
/usr/bin/pcre-config

$ head /usr/bin/pcre-config
#!/bin/sh

prefix=/usr
exec_prefix=${prefix}
exec_prefix_set=no

cflags="[--cflags]"

if test yes = yes ; then
  libs="[--libs-cpp]"

$ TMP=`mktemp -d`
$ cp /usr/bin/pcre-config $TMP
$ # change `--libs` and `--cflags` cases
$ diff -u /usr/bin/pcre-config /tmp/tmp.wKBi7nANJi/pcre-config
--- /usr/bin/pcre-config        2016-03-25 04:12:12.000000000 +0000
+++ /tmp/tmp.wKBi7nANJi/pcre-config     2020-06-19 14:32:15.290983783 +0000
@@ -98,7 +98,7 @@
       ;;
     --libs)
       if test yes = yes ; then
-        echo $libS$libR -lpcre
+        echo $libS$libR -lpcre1
       else
         echo "${usage}" 1>&2
       fi
# saving as a patch to automate
$ diff -u /usr/bin/pcre-config /tmp/tmp.wKBi7nANJi/pcre-config > pcre.patch
# checking that patch works, making pure copy 
$ cp /usr/bin/pcre-config $TMP
$ patch -p1 $TMP/pcre-config < pcre.patch
patching file /tmp/tmp.wKBi7nANJi/pcre-config
$ PATH=$TMP:$PATH
$ which pcre-config
/tmp/tmp.wKBi7nANJi/pcre-config
# checking that new pcre-config works as expected
$ pcre-config --libs
-lpcre1
```

**Comment by angrocode** [comment]
Local install pcre in nginx

0. Setting --prefix all build and PATH

1.pcre
./configure \
--prefix=/usr/nginx/pcre \
--enable-unicode-properties \
--enable-pcre16 \
--enable-pcre32 \
--enable-pcregrep-libz \
--disable-static

2. exit build and install pcre
make clean

3.
export PATH="/usr/nginx/pcre/bin/:$PATH"

4.
./configure \
--prefix=/usr/nginx \
--with-pcre=../pcre-8.44 \
--add-module=../njs/nginx
