### ISSUE TITLE
Parsed JSON numbers are not 'truethy'

### ISSUE THREAD

**Issue by ivorbosloper** [nginx/njs#180]
Parsed JSON numbers seem false. This makes numbers from parsed JSON different from native numbers. Compare the following code (njs command line) 

```
>> var obj
undefined
>> obj = {key: 10}
{
 key: 10
}
>> obj.key
10
>> !!(obj.key)
true
>> obj.key || 100
10
>> obj["key"] || 100
10
```

The above is what I expect. Now see the following:

```
>> obj = JSON.parse('{"key": 10}')
{
 key: 10
}
>> obj.key
10
>> !!(obj.key)
false
>> obj.key || 100
100
>> obj["key"] || 100
100
```

This is not what I expected. `obj.key` is false?

An even smaller testcase is:

```
>> obj = JSON.parse('10')
10
>> typeof obj
'number'
>> obj == 10
true
>> obj || 10
40
```

So it's probably a bug in the JSON parser, which constructs different  'number' objects

**Comment by xeioex** [comment]
Hi @ivorbosloper,

Thanks for reporting, will be fixed in the next release.

You may try the following patch: https://gist.github.com/bd6be9fbdb5dd7f2309f03e5d0f6f28f
