### ISSUE TITLE
How to proxy to a subrequest result

### ISSUE THREAD

**Issue by gabrielshawandpartners** [nginx/njs#213]
Hi, I'm trying to do a subrequest and the result of this subrequest will give me url to proxy, but when I return it from the subrequest callback it doesn't set the nginx variable to `proxy_pass`

Here is my example:

**nginx.conf**

```
load_module ngx_http_js_module.so;

http {
  js_include redirector.js;
  js_set $redirect_to redirect;

  server {
   .......
   .......
    location /js {
        proxy_pass $redirect_to;
      }
  }
}
```

**redirector.js**

```
function redirect(r) { 
  function done(res) {
    return res.responseBody;
  }

  r.subrequest("/validate", r.variables.args, done);
}
```

It gives this error message `invalid URL prefix in "", client: 127.0.0.1, server: localhost,....`, which I believe it's Nginx complaining about the `$redirect_to` variable being empty `proxy_pass =  ""`.

**Comment by xeioex** [comment]
Hi @gabrielshawandpartners 

`r.subrequest()` (or any async functions like setTimeout()) is not supported inside js_set variables handler.

you need to use `auth_request` directive. See a related [example](https://github.com/xeioex/njs-examples#complex-redirects-using-njs-file-map).

**Comment by abyken** [comment]
@gabrielshawandpartners Hi,

Could you share how do you resolve the issue?

**Comment by cadavre** [comment]
That's actually... sad. I especially invested my time into `njs` to make use of `r.subrequest()` I need to parse (from JSON) before forwarding to proxy_pass. How do I suppose do that with `auth_request `, which by the way only handles 200 and 401|403 responses, while I need to handle also 402 or 404s?

**Comment by xeioex** [comment]
@cadavre 

You may implement [njs location handler inside auth_request location](https://github.com/xeioex/njs-examples/blob/master/conf/http/complex_redirects.conf#L32).

**Comment by sagitsofan** [comment]
I have a NJS scripts that return me a url, and in the `nginx.conf` i would like to proxy_pass to this url.
Any suggestion on how to do that?

**Comment by xeioex** [comment]
@sagitsofan 

Take a look at: https://github.com/xeioex/njs-examples/blob/master/conf/http/complex_redirects.conf#L22

Here, because proxy_pass and js_content cannot be mixed in a single location, you have to use auth_request.

In a `auth_request location` you may implement arbitrary js_content logic. Your js_content handler have to return a new url in a header (`Route` in the example above). Later auth_request_set extracts this header into `$route` variable, which may be used in proxy_pass directive.

**Comment by xeioex** [comment]
@sagitsofan 

If you do not need any async operations for deriving proxy_pass url (like subrequest), you may use js_set. 

```
js_import http from "my_file.js";
js_set $my_url http.handleRequest;
...

location /test {
        proxy_pass $my_url;
    }
```

my_file.js
```
function handleRequest(r) {
   return "http://example-site.com";
}

export default { handleRequest }
```

**Comment by sagitsofan** [comment]
Thank you @xeioex for the quick replay.

And if I would like to return an object from the _my_file.js_:
`return { statusCode: 200, url: 'http://www.mysite.com' };`

How can i read that in the conf file, this one doesn't work: 
```
        if ($my_url.statusCode = 401) {
            return 401;
        }
```

**Comment by xeioex** [comment]
@sagitsofan 

> And if I would like to return an object from the my_file.js:

no, js_set operates only on strings. You have to return a string.

`$res.url` - it is invalid syntax for nginx.

only js_set and js_content understand dot syntax (`http.handleRequest`).

**Comment by sagitsofan** [comment]
Got it.

And is it possible to inject 3'd party package to my js script, for example _jsonwebtoken_?
https://www.npmjs.com/package/jsonwebtoken 

My goal is to **verify** a token before proxy the request.
I only parsed the JWT, but its not enough for me, I need to verify it against the secret.

**Comment by xeioex** [comment]
@sagitsofan 

You may try [this](http://nginx.org/en/docs/njs/node_modules.html). Not sure it will work with jsonwebtoken. Especially if it depends on node.js internal modules (which are not implemented in njs).

For JWT we have [ngx_http_auth_jwt_module](http://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html) which is available as part of our commercial subscription.

For HS256 algo, an efficient njs implementation is possible (See [this](https://github.com/hongzhidao/nginx-unit-dashboard/blob/master/conf/js/jwt.js)). Others algos require support from njs [crypto module](http://nginx.org/en/docs/njs/reference.html#crypto). We plan to add this in the middle-term future.
