### ISSUE TITLE
Is it possible njs support wasm code ?

### ISSUE THREAD

**Issue by netroby** [nginx/njs#222]
Hello, do you hear some thing about wasm?
```
WebAssembly (abbreviated Wasm) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable target for compilation of high-level languages like C/C++/Rust, enabling deployment on the web for client and server applications.
```
May you please support in njs with wasm?

So we can write any language, golang, rust, then compile it into wasm
Load wasm into nginx, got better performance.

How could it possible...

**Comment by xeioex** [comment]
Hi @netroby,

Sorry but, we do not have plans to implement WASM in the near or middle term future.
