### ISSUE TITLE
Accessing headers of a subrequest's response

### ISSUE THREAD

**Issue by tokumeo** [nginx/njs#240]
Is there a way to access all headers of a subrequest's response? I have a use case for which I need to make two subrequests and merge their response headers in the final response without prior knowledge of what those headers are (meaning I can't use `request.variables.upstream_http_*`)

**Comment by xeioex** [comment]
Hi @tokumeo,

try something like this:

```
var headers = {};

function done(reply) {
for (var h in reply.headersOut) {
  headers[h] = reply.headersOut[h];
}
}

r.subrequest('/dest_uri', done);
```

Please note though, some special headers (like `Set-Cookie`) will be missing from this list (because there can be multiple such headers). We are working on  adding JS API to iterate over cookies.

**Comment by tokumeo** [comment]
Hi @xeioex!

Thanks for quick response. I've tried `headersOut` and got some of the headers, but not all of them. You mentioned that `Set-Cookie` might be missing. In my case, `Content-Type` is also missing (that's one of the headers that my use case requires). Is it also a special header?

Also, I don't quite understand how response headers are constructed when using `js_content` with subrequests. I make two of them, and I noticed that some response headers from subrequests get implicitly copied to final response's headers (specifically `Content-Type`). Could you please shed some light on this process?

**Comment by xeioex** [comment]
@tokumeo 

> Is it also a special header?

yes. nginx itself, for performance reasons, treats some headers specially. Most of the headers are stored in `r->headers_out.headers` list. Whereas for example `Content-Type` and `Content-Length` are stored in theirs own field. 

https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L918

As of now `for (var h in reply.headersOut)` iterates only over `r->headers_out.headers` list.

njs partly fixes this issue for get (`Content-Type` and `Content-Type`) and set operations (`Content-Type`, `Content-Encoding`, `Content-Length`), but not for iteration.

 > I make two of them, and I noticed that some response headers from subrequests get implicitly copied to final response's headers (specifically `Content-Type`). 

I guess, it is not a copy from a subrequest (subrequest's headers are ignored), but a [default content_type](https://nginx.org/en/docs/http/ngx_http_core_module.html#default_type).

**Comment by tokumeo** [comment]
@xeioex 

Thanks for clarifications! And you were right about `default_type`, my bad.
