### ISSUE TITLE
Can't install nginx-module-njs in Raspberry PI

### ISSUE THREAD

**Issue by wmd1942** [nginx/njs#243]
I can't install nginx-module-njs in Raspberry PI. I'd appreciate it if someone can help me. Thanks.

$ sudo apt-get update
$ sudo apt-get install nginx-module-njs nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nginx-module-njs

Here is the background information:

pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux

pi@raspberrypi:~ $ cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://nginx.org/packages/debian/ buster nginx
deb-src http://nginx.org/packages/debian/ buster nginx

**Comment by VBart** [comment]
See "[Supported distributions and versions](http://nginx.org/en/linux_packages.html#distributions)". Currently there are no official packages for "buster" on armv6l. You can build your own module package.

**Comment by wmd1942** [comment]
Really? njs or nginx? It seems nginx can be installed (and it runs) on Raspberry PI.

**Comment by VBart** [comment]
Both. You have nginx installed from Raspbian repository, not from the official nginx.org repository.
If you look to http://nginx.org/packages/debian/dists/buster/nginx/ - there are no directory for your architecture. So, these lines currently add nothing:
```
deb http://nginx.org/packages/debian/ buster nginx
deb-src http://nginx.org/packages/debian/ buster nginx
```

**Comment by VBart** [comment]
To check the source of your nginx package, you can use `apt policy` command:
```
$ apt policy nginx
```

**Comment by wmd1942** [comment]
I see. Thanks.

What's the proper way to build njs module myself? I downloaded the njs source package per direction from "https://nginx.org/en/docs/njs/install.html" but failed to build it as dynamic module. It seems my system missed some components but don't know which libraries I need to install.

pi@raspberrypi:~/njs $ ./configure --add-dynamic-module=~/njs/nginx
configuring for Linux 4.19.66+ armv6l
checking for C compiler: cc
 + using GNU C compiler
 + gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
checking for GCC unsigned __int128 ... not found
checking for GCC __builtin_expect() ... found
checking for GCC __builtin_unreachable() ... found
checking for GCC __builtin_prefetch() ... found
checking for GCC __builtin_clz() ... found
checking for GCC __builtin_clzll() ... found
checking for GCC __attribute__ visibility ... found
checking for GCC __attribute__ malloc ... found
checking for GCC __attribute__ aligned ... found
checking for Address sanitizer ... not found
checking for Memory sanitizer ... not found
checking for NAN to uint conversion ... ffffffff
checking for clock_gettime(CLOCK_MONOTONIC) ... found
checking for struct tm.tm_gmtoff ... found
checking for altzone ... not found
checking for posix_memalign() ... found
checking for getrandom() ... found
checking for explicit_bzero() ... found
checking for PCRE library ... found
 + PCRE version: 8.43
checking for GNU readline library ... not found
checking for editline library in editline/readline.h ... not found
checking for editline in edit/readline/readline.h ... not found
checking for editline in readline/readline.h ... not found
 - building interactive shell is not possible
creating build/Makefile
checking for expect ... not found
 - expect tests are disabled

**Comment by VBart** [comment]
@wmd1942 The `./configure --add-dynamic-module=~/njs/nginx` command is for nginx sources. You have to download nginx sources and run this command pointing to njs sources. The nginx version used to build njs module must match the version of your nginx. Also, you have to use the same configure arguments. You can check the configure arguments of your nginx by running `nginx -V`.
