### ISSUE TITLE
Stream module - send response to client

### ISSUE THREAD

**Issue by mmslex** [nginx/njs#247]
Is it possible to send data to client in 'js_filter -> upload' event handler?

For example, to speed up a custom text protocol it would be good to send a cached response right after receiving some command from a client. 
But I cannot find a way to do this directly in the 'upload' callback. I can only change the data that goes to the backend

**Comment by xeioex** [comment]
@mmslex 

> Is it possible to send data to client in 'js_filter -> upload' event handler?

No, currently it is not possible. But there is a workaround for this case. You just need to force your backend to close the connection.

```js
function js_filter_cached(s) {                                                                                              
        s.on('download', function(data, flags) { 
                /* this callback will be called when connection is closed. */                                                                                
                s.send('wakawaka', {last:1});                                                                           
                s.off('download');                                                                                               
        });                                                                                                                      
                                                                                                                                 
        s.on('upload', function(data, flags) {      
             /* forcing backend to close connection. */                                                                             
            s.send('x' /* any non-empty string */, {last:1});                                                                                      
        });                                                                                                                      
    }  
```

**Comment by mmslex** [comment]
@xeioex,  thanks for the answer.
But in my case this approach doesn't work, the protocol uses long-lived connection. And part of text commands can be easily responded directly from njs script.

Is it an architectural limitation or this feature can be implemented in njs?

**Comment by xeioex** [comment]
Currently `js_filter` is in fact an nginx stream filter (not a standalone content handler as `js_content` for example). It can only filter data chunk at hand.

**Comment by mmslex** [comment]
Well, it looks like I need to find other ways for 'smart-proxying' text protocols.
