### ISSUE TITLE
readDirSync support (directory list)

### ISSUE THREAD

**Issue by axipo** [nginx/njs#254]
It would be very useful to have an ability to list directory content.

**Comment by drsm** [comment]
Here is the patch:
https://gist.github.com/drsm/55b97ce9dbb3106b72ed7c970988c4c8

**Comment by xeioex** [comment]
@drsm 

Thanks, will take a look as time permits.

**Comment by xeioex** [comment]
@drsm 

Thanks, committed with some changes:
1. style
2. portability issues with Sun OS.
