### ISSUE TITLE
setting multiple outgoing headers with the same name (for example 'Set-Cookie')

### ISSUE THREAD

**Issue by ramhar** [nginx/njs#266]
it would be nice to be able to set several identical http headers, something like this:

```JavaScript
r.headersOut['Set-Cookie'] = [
   'foo=111; Max-Age=3600; path=/',
   'bar=qqq; Max-Age=86400; path=/'
];
```

**Comment by xeioex** [comment]
Hi @ramhar,

We plan to add a special `r.cookiesOut` property to work with cookies (like `r.headersOut`).

**Comment by ramhar** [comment]
... this feature is sometimes (albeit extremely rare) not only necessary for the 'set-cookie' header, which is why it seemed to me more appropriate to implement it as in [openresty](https://github.com/openresty/lua-nginx-module#ngxheaderheader)

**Comment by xeioex** [comment]
>... this feature is sometimes (albeit extremely rare) not only necessary for the 'set-cookie' header, which is why it seemed to me more appropriate to implement it as in openresty

Yes, this is a variant. What bugs me the most is that the return value type is different whether it is a ordinary or muti-valued header. So when you access cookie header you have to check the return type (because you do not know in advance), looks ugly to me. It is true?

> Reading ngx.header.HEADER will return the value of the response header named HEADER.
> ..
> For multi-value headers, all of the values of header will be collected in order and returned as a Lua table. For example, response headers

**Comment by xeioex** [comment]
@ramhar 

njs 0.4.0 is released: http://nginx.org/en/docs/njs/changes.html#njs0.4.0
