### ISSUE TITLE
The map and js_set variables aren't writtable in js module.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#272]
Hi. @xeioex 

See the following config example. This usage is common in the real world.
But now, the variables generated by the `map` module can't be set again in js module.
The reason is the flag of these variables is not `NGX_HTTP_VAR_INDEXED`.

ngx_http_js_module.c
```
1738
1739     if (!(v->flags & NGX_HTTP_VAR_INDEXED)) {
1740         njs_vm_error(vm, "variable is not writable");
1741         return NJS_ERROR;
1742     }
1743
```

nginx.conf
```
http {
    include       mime.types;
    default_type  application/octet-stream;

    js_include  http.js;

    map $host $test {
        default  "test";
    }

    server {
        listen  80;

        location / {
            js_content hello;
        }
    }
}
```
http.js
```
function hello(r) {
    r.variables['test'] = 'testing';
    r.return(200, "ok");
}
```

Can nginx official fix it by rework the `map` module? Or is there another way to do?
```
diff --git a/src/http/modules/ngx_http_map_module.c b/src/http/modules/ngx_http
index 2fc9be9..76baf6b 100644
--- a/src/http/modules/ngx_http_map_module.c
+++ b/src/http/modules/ngx_http_map_module.c
@@ -232,6 +232,10 @@ ngx_http_map_block(ngx_conf_t *cf, ngx_command_t *cmd, voi
         return NGX_CONF_ERROR;
     }

+    if (ngx_http_get_variable_index(cf, &name) == NGX_ERROR) {
+        return NGX_CONF_ERROR;
+    }
+
     var->get_handler = ngx_http_map_variable;
     var->data = (uintptr_t) map;
```

Thanks.

**Comment by xeioex** [comment]
@hongzhidao 

> But now, the variables generated by the map module can't be set again in js module.

In fact they can be used if they were referenced in nginx.conf somewhere. 

A variable becomes indexed when it is referenced in nginx.conf, this is a design choice (optimization). So, you can create many thousands of map directives with minimal runtime costs. 

If you need a variables which can be set from njs, `js_set` is a way to go.

**Comment by hongzhidao** [comment]
> A variable becomes indexed when it is referenced in nginx.conf.

Yes, but it does not happen in the `map` directive.

> If you need a variables which can be set from njs, js_set is a way to go.

This way works, but it may cost more (run js function and set many variables again).

Is this patch OK? I want to merge it by myself. 
It's more convenient, and the `map` is lightweight.
```
diff --git a/src/http/modules/ngx_http_map_module.c b/src/http/modules/ngx_http
index 2fc9be9..76baf6b 100644
--- a/src/http/modules/ngx_http_map_module.c
+++ b/src/http/modules/ngx_http_map_module.c
@@ -232,6 +232,10 @@ ngx_http_map_block(ngx_conf_t *cf, ngx_command_t *cmd, voi
         return NGX_CONF_ERROR;
     }

+    if (ngx_http_get_variable_index(cf, &name) == NGX_ERROR) {
+        return NGX_CONF_ERROR;
+    }
+
     var->get_handler = ngx_http_map_variable;
     var->data = (uintptr_t) map;
```

I found this problem while I wrote a module for dynamically update variables without change any config.
```
{
    "variables": {
         "var1": "val1",
         "var2": "val2",
         ...
    }
}
```
Every work process has the same memory space stored the json config.
This module reads the config in the `post_read` phase, then does things like `set` variables.

**Comment by xeioex** [comment]
@hongzhidao 

> Yes, but it does not happen in the map directive.

Because it is a declaration of a variable not referencing.

**Comment by hongzhidao** [comment]
@xeioex , see it again, please.

```
http {
    include       mime.types;
    default_type  application/octet-stream;

    js_include  http.js;

    js_set  $test test;

    server {
        listen  80;

        location / {
            js_content  hello;
        }
    }
}
```
```
function test() {
    return 'test';
}

function hello(r) {
    r.variables['test'] = 'test again';
    r.return(200, "hello njs.");
}
```

```
js exception: Error: variable is not writable
    at hello (http.js:5)
    at main (native)
```

> Because it is a declaration of a variable not referencing.

Yes, it's the root cause of the problem.

> If you need a variables which can be set from njs, js_set is a way to go.

It does not work.  Both map and js_set directives do not set referencing.

In the real world, we don't like to set variables by `set` directive related to every server/location.
It's better to put int the http main block, such as map and js_set.
