### ISSUE TITLE
ngx_http_js_module.so is missing while starting the self-build nginx

### ISSUE THREAD

**Issue by idavollen** [nginx/njs#277]
I have tried to build nginx with the additional module _ngx-js-module_ as following (first change directory to the root for nginx source directory:)

`
./configure --prefix=/Users/itsme/bin/nginx --add-module=/Users/itsme/tmp/njs/nginx
make
sudo make install
`

after finishing building nginx, I always got error when I tried to start nginx from _/Users/itsme/bin/nginx/_ due to import ngx_http_js_module.so in my nginx.conf (_load_module modules/ngx_http_js_module.so;_)

`
./sbin/nginx -c ./conf/nginx.conf
`

Here it is the error message:
_(dlopen(/Users/itsme/bin/nginx/modules/ngx_http_js_module.so, 10): image not found) in /Users/itsme/bin/nginx/conf/nginx.conf:1_

I'm wondering if I should directly build nginx/njs to generate this _ngx_http_js_module.so_ or _ngx_http_js_module.so_ should be automatically built by build-process for building nginx from its source?

**Comment by xeioex** [comment]
Hi @idavollen 

>   or ngx_http_js_module.so should be automatically built by build-process for building nginx from its source?

Yes. See this http://nginx.org/en/docs/njs/install.html (Building from the sources).

**Comment by idavollen** [comment]
Hi @xeioex 

thanks for your reply!

I did follow that _install.html_ page mentioned by you as following:
_./configure --prefix=/Users/itsme/bin/nginx --add-module=/Users/itsme/tmp/njs/nginx_ 

However it does not work as expected with the self built nginx

**Comment by xeioex** [comment]
@idavollen 

Please note that `load_module` directive is only applicable for dynamic modules.
Nginx modules can be dynamic and static.  ` --add-module` option compiles njs as static module (`load_module` is not needed).
