### ISSUE TITLE
Add ability for fs.existsSync

### ISSUE THREAD

**Issue by swood** [nginx/njs#278]
Hello. I tried to write a function which read the backup for a current date from the disk. However, it might be a situation when the file for the current time is not yet ready. 
I thought it might be a great idea to check the file exists before an attempt to read it.
But the function like 'fileExists' or 'stat' does not exist. Why?

**Comment by xeioex** [comment]
Hi @swood,

Please note that checking for file existence before reading it [is not recommended](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) (as other processes may change the file's state between the two calls),  it may introduce hard to debug race conditions. The recommended way is to read a file and handle possible exceptions using `try {} catch (e) {}`.

**Comment by xeioex** [comment]
Since 0.3.9 [fs.access()](http://nginx.org/en/docs/njs/reference.html#fs_accesssync) can be used instead.
