### ISSUE TITLE
Sending datagrams?

### ISSUE THREAD

**Issue by axos88** [nginx/njs#280]
Hi,

I'm reverse proxying TLS traffic without decrypting it. To figure out where I need to proxy the traffic to, I need to check wether a CNAME record exists for the incoming SNI domain.

I tried following the npm module guide, the dns-packet example is almost what I need, but I need to send it to a resolver/DNS server to actually resolve it. The "dgram" npm package was pulled from npm (it seems it was integrated into node), and I have no idea how to get that functionality.

How can I get a DGRAM socket that I can use to send and receive data?
Accessing the resolver would be best, but I guess that's not possible.

nginx config:
```
stream {
log_format basic '$remote_addr [$time_local] '
                 '$protocol $ssl_preread_server_name $selected_upstream $status $bytes_sent $bytes_received '
                 '$session_time';

  access_log /var/log/nginx/access_stream.log basic;
  error_log /var/log/nginx/error_stream.log;

  resolver 8.8.8.8;
  js_include test.js;

  js_set $selected_upstream select_upstream;

  server {
    listen 0.0.0.0:8443;
    proxy_pass $selected_upstream:443;
    ssl_preread on;
  }
}
```

JS Code:
```
RegExp.escape= function(s) {
    return s.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
}

function query_cname(d) {
  ????
 // if a CNAME record exists for d, return the data of the record, otherwise return null
  
}

function match_vpn(d) {
  var m = d.match(new RegExp(`(.*)\.${RegExp.escape(gateway)}$`));

  if (m !== null) {
    return m[1] + "." + vpn;
  } else {
    return null;
  }
}

function select_upstream(s) {
  var sni = s.variables.ssl_preread_server_name;
  var v;
  var d;

  if ((v = match_vpn(sni)) !== null) {
    s.error("SNI match: " + sni + " ==> " + v);
    return v;
  } else if (((d = query_cname(s)) !== null) && ((v = match_vpn(d)) !== null)) {
    s.error("CNAME match: " + s + " -> " + d + " ==> " + v);
    return v;
  } else {
    s.error("No match for " + sni);
    return "127.0.0.1";
  }
}
```

**Comment by xeioex** [comment]
Hi @axos88,

Unfortunately, nginx does not support asynchronous operations inside variable handlers (`$selected_upstream`). Nginx expects a variable handler to return its result right away. While sending and expecting a dns packet is async operation.

Your problem can be solved though in the future by implementing JS interfaces to nginx resolver. We plan to do this in the mid-term future. Will be something like this:

nginx.conf:
```

js_set $selected_upstream selected_upstream;
js_preread preread;
```

```
function selected_upstream(s) {
    return global.selected_upstream;
}

function prepead(s) {
    nginx.resolver.query({domain:<my_domain>})
    .then(dns=> { ... global.selected_upstream = <my_upstream>; s.done();})
}
```

**Comment by axos88** [comment]
This is an extremely low traffic site, so blocking for the time of a DNS query would be tolerable I guess, is there any way to do it in a synchronous way?

Also what about subqueries? Those seem to work in an async manner...
https://nginx.org/en/docs/njs/examples.html#subrequest
```
function set_keyval(r) {
    r.subrequest('/api/5/http/keyvals/foo',
        { method: 'POST',
          body: JSON.stringify({ foo: 789, bar: "ss dd 00" })},

        function(res) {
            if (res.status >= 300) {
                r.return(res.status, res.responseBody);
                return;
            }
            r.return(500);
        });
}
```

**Comment by xeioex** [comment]
@axos88 

> Also what about subqueries? Those seem to work in an async manner...

r.subrequest is only available in http module. We plan to add a http client to the stream module in the future.
