### ISSUE TITLE
Fixed non-native module finding.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#282]
@xeioex @drsm 

Fixed module finding.
https://gist.github.com/hongzhidao/21bb5ad1b41e3f8b5a7b7ae9e5905c52

The key point is we use `from module` as module name previously.
It's OK if the module is native.
If it's a non-native module, I think we need to use the full path as a module name (key).

BTW, it's a good way to use modules that are used in nodejs projects from GitHub.
They can check whether njs runs as well as other js engines.

**Comment by xeioex** [comment]
> BTW, it's a good way to use modules that are used in nodejs projects from GitHub.

Yes, see this: http://nginx.org/en/docs/njs/node_modules.html

**Comment by xeioex** [comment]
Thanks, will be merged after parser refactoring is done by @lexborisov.
