### ISSUE TITLE
Some req.logs are randomly not written 

### ISSUE THREAD

**Issue by nishant-dani** [nginx/njs#284]
function logSummary(req) {
    var a, s, h;

    req.log("Request Log Summary")

    req.log(`Method: ${req.method}`)
    req.log(`HTTP version: ${req.httpVersion}`)
    req.log(`Host: ${req.headersIn.host}`)
    req.log(`Remote Address: ${req.remoteAddress}`)
    req.log(`URI: ${req.uri}`)

    req.log("Headers:")
    for (h in req.headersIn) {
        req.log(`  header ${h} is ${req.headersIn[h]}`)
    }

    req.log("Args")
    for (a in req.args) {
        req.log(`  arg ${a} is ${req.args[a]}`)
    }
}

When I use logSummary(req) only a few of the logs get written.  The others are skipped entirely.  Is there some buffer setting that I might be missing?

These are the ones that show up;
sudoproxy                   | nginx.1    | 2020/02/05 03:44:00 [info] 54#54: *1 js: Host: core.konfettidev.com
sudoproxy                   | nginx.1    | 2020/02/05 03:44:00 [info] 54#54: *1 js:   header authorization is Bearer ***
sudoproxy                   | nginx.1    | 2020/02/05 03:44:00 [info] 54#54: *1 js:   header referer is https://***/***

For instance both the req.log("Headers") and req.log("Args") don't show up.  Neither do the req.  If I do it a second time around; I get more of the logs;

sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: Request Log Summary
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: Method: POST
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: HTTP version: 1.1
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: Host: core.konfettidev.com
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: Remote Address: 172.21.0.1
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: URI: /graph/mutation/campaign
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js: Headers:
sudoproxy                   | nginx.1    | 2020/02/05 03:51:24 [info] 55#55: *1 js:   header host is core.konfettidev.com
sudoproxy                   | nginx.1    | ****
sudoproxy                   | nginx.1    | sec-fetch-mode is cors

Notice that for the "header authorization is Bearer ****"  only the *** show up without the prefix.  Leads me to believe that the logs are being thrown away either by njs or by nginx.  It would be good if the logs show up predictably so that we might not be tracking down errors which are not really there.

I don't mind a slower system in debug so long as I have all the logs to check for correctness.

**Comment by xeioex** [comment]
Hi @nishant-dani 

req.log()  calls ngx_log_error_core() from nginx. [The function ](https://github.com/nginx/nginx/blob/master/src/core/ngx_log.c#L113) uses a stack buffer of 2048 bytes. The reason for doing it is that malloc() may fail when ngx_log_error_core() is used to log memory related issues. So it is not configurable.

For debugging purposes you can send the desired info to the client-side (for example, using `r.return(200, JSON.stringify(r))`);

**Comment by nishant-dani** [comment]
Hi @xeioex - thanks for the explanation!

In case this is useful for others, I have added in my notes.
I am using the debug version of nginx to track down some issues related to njs subrequests.  So the debug strings were flooding the stderr.  I resolved this by pushing the error_log to both stderr and to file.  Somehow the write to file seems to bypass the issue and no prints are dropped.  The prints come through either the nginx code or from my njs content functions.

```
error_log  /var/log/nginx/error.log debug;
error_log  stderr info;
```

Now the error_log file has everything without missing any ndx_log_debugs.  While the stderr is important for me as it helps me to see how the logs are interleaved between logs from other containers.  

As a side note, I am using the nginxproxy written by jwilder/nginxproxy to automatically create a default.conf in response to containers being stopped or restarted.  

The nginx logs get a prefix because they are being pushed through docker-compose, and the prefix identifies the container name.

-- This is my nginx.conf file.  This is my nginx.conf which does not have the full information because it references other files from the vhost.d folder.
user  nginx;
worker_processes  auto;

# Uncomment these for release versions of the njs modules
# load_module /etc/nginx/modules/ngx_http_js_module.so;
# load_module /etc/nginx/modules/ngx_stream_js_module.so;

# Uncomment these for the debug versions of the njs modules
# load_module /etc/nginx/modules/ngx_http_js_module-debug.so;
# load_module /etc/nginx/modules/ngx_stream_js_module-debug.so;

error_log  /var/log/nginx/error.log debug;
error_log  stderr info;

# Uncomment this line to turn error log off;
# error_log /dev/null crit;

pid        /var/run/nginx.pid;

daemon off;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    js_include /etc/nginx/vhost.d/coreMutations.js;

    include /etc/nginx/conf.d/*.conf;
}
