### ISSUE TITLE
njs subrequest not being sent out

### ISSUE THREAD

**Issue by nishant-dani** [nginx/njs#286]
Hi, I am trying to send a subrequest to an upstream http server.  However , it does not get sent out.  I am using the debug version of nginx.   (njs 0.3.8) and (nginx 1.17.8).  If I cat at the error log from nginx; I have the following:

```
2020/02/09 01:52:36 [info] 55#0: *1 js: coreCampaignMutation now doing subrequest
2020/02/09 01:52:36 [debug] 55#0: *1 posix_memalign: 000055F36ED71860:4096 @16
2020/02/09 01:52:36 [debug] 55#0: *1 http subrequest "/coreCampaignMutation?"
2020/02/09 01:52:36 [debug] 55#0: *1 ngx_http_post_request
2020/02/09 01:52:36 [debug] 55#0: *1 ngx_http_v2_state_complete pos:00007F57497CF168 end:00007F57497CF168
2020/02/09 01:52:36 [debug] 55#0: *1 ngx_http_v2_send_output_queue
2020/02/09 01:52:36 [debug] 55#0: *1 http2 frame out: 000055F36EDD6258 sid:0 bl:0 len:4
2020/02/09 01:52:36 [debug] 55#0: *1 ngx_ssl_send_chain
2020/02/09 01:52:36 [debug] 55#0: *1 malloc: 000055F36EF528A0:16384
2020/02/09 01:52:36 [debug] 55#0: *1 SSL buf copy: 13
2020/02/09 01:52:36 [debug] 55#0: *1 SSL to write: 13
2020/02/09 01:52:36 [debug] 55#0: *1 SSL_write: 13
2020/02/09 01:52:36 [debug] 55#0: *1 http2 frame sent: 000055F36EDD6258 sid:0 bl:0 len:4
2020/02/09 01:52:36 [debug] 55#0: *1 event timer del: 8: 153408635
2020/02/09 01:52:36 [debug] 55#0: timer delta: 4758
2020/02/09 01:52:36 [debug] 55#0: worker cycle
2020/02/09 01:52:36 [debug] 55#0: epoll timer: 172496
```
====

So it is reaching all the way to ngx_http_post_request, so the requested apparently is added to the posted requests queue, but ngx_http_run_posted_requests never gets called.  So no further processing on initing the nginx phases for this request starts.  

It appears that nginx is missing a call to ngx_http_run_posted_requests; which only gets called on event handlers.  But as we are initiating the subrequest there are no events yet.  I might be wrong on this but it appears that the subrequest posting should initiate the ngx_http_run_posted_requests if required.  Otherwise everything will stall like it does.

====

Almost 15 minutes later still nothing happens.

====

On a hunch I decided to terminate the connection from the client so I shut the browser tab.  The browser closes the connection and FINALLY this generates the event which starts the upstream processing.  I can confirm now that the upstream server gets the subrequest.   

But it is too late now.

2020/02/09 02:09:19 [info] 55#0: *1 client canceled stream 27, client: 172.21.0.1, server: core.***.com, request: "POST /graph/mutation/campaign HTTP/2.0", host: "core.***.com", referrer: "https://core.***.com/campaigns/createupdate"
2020/02/09 02:09:19 [debug] 55#0: *1 ngx_http_request_handler: http run request: "/graph/mutation/campaign?"
2020/02/09 02:09:19 [debug] 55#0: *1 http reading blocked
2020/02/09 02:09:19 [debug] 55#0: *1 ngx_http_run_posted_requests for connection c: 243.85.0.0

2020/02/09 02:09:19 [debug] 55#0: *1 http posted request: "/coreCampaignMutation?"
2020/02/09 02:09:19 [debug] 55#0: *1 ngx_http_handler
2020/02/09 02:09:19 [debug] 55#0: *1 ngx_http_core_run_phases
2020/02/09 02:09:19 [debug] 55#0: *1 rewrite phase: 0
2020/02/09 02:09:19 [debug] 55#0: *1 test location: "/"
2020/02/09 02:09:19 [debug] 55#0: *1 test location: "graph/mutation/campaign"
2020/02/09 02:09:19 [debug] 55#0: *1 test location: "feedCampaignMutation"
2020/02/09 02:09:19 [debug] 55#0: *1 test location: "coreCloneMutation"
2020/02/09 02:09:19 [debug] 55#0: *1 test location: "coreCampaignMutation"
2020/02/09 02:09:19 [debug] 55#0: *1 using configuration "/coreCampaignMutation"
2020/02/09 02:09:19 [debug] 55#0: *1 http cl:259 max:31457280
2020/02/09 02:09:19 [debug] 55#0: *1 rewrite phase: 2
2020/02/09 02:09:19 [debug] 55#0: *1 post rewrite phase: 3
2020/02/09 02:09:19 [debug] 55#0: *1 generic phase: 4
2020/02/09 02:09:19 [debug] 55#0: *1 generic phase: 5
2020/02/09 02:09:19 [debug] 55#0: *1 generic phase: 9
2020/02/09 02:09:19 [debug] 55#0: *1 generic phase: 10
...
the rest of it goes as expected.

====

My conjecture is that the subrequest in nginx should actually call ngx_http_run_posted_requests to begin processing right away because if no further events get generated on the channel processing will stall indefinitely until there is an event.  This is likely to be exaggerated in a dev environment where we are doing only single requests, and nothing new will be generated until that gets done.

=====

Are there any tips on debugging this further.  I am able to set ndx_log_debug? prints in the ngx code to track the progress.  Thanks for any help and suggestions.

**Comment by nishant-dani** [comment]
I changed the nginx code as follows.  

FILE: src/http/ngx_http_core_module.js

FROM:
ngx_int_t
ngx_http_subrequest(ngx_http_request_t *r,
    ngx_str_t *uri, ngx_str_t *args, ngx_http_request_t **psr,
    ngx_http_post_subrequest_t *ps, ngx_uint_t flags)
{
    ....
    return  ngx_http_post_request(sr, NULL);
}

TO:
ngx_int_t
ngx_http_subrequest(ngx_http_request_t *r,
    ngx_str_t *uri, ngx_str_t *args, ngx_http_request_t **psr,
    ngx_http_post_subrequest_t *ps, ngx_uint_t flags)
{
    ......
    ngx_int_t result =  ngx_http_post_request(sr, NULL);
    ngx_http_run_posted_requests(sr->connection);
    return result;
}

And it no longer stalls.  Possibly this might not be the correct or even the most optimal change or if there are side effect this will cause.  Possibly someone with familiarity with the code could comment?

**Comment by xeioex** [comment]
@nishant-dani 

Please share your nginx.conf and js file.

**Comment by nishant-dani** [comment]
Hi @xeioex I am uploading a zip of all the related files.  I hope it will be useful to you. Its a complex configuration, because the default.conf in conf.d is autogenerated from the current status of the docker containers.  The logic is from jwilder/nginxproxy.
Meanwhile I have been using the changed njs code and it has since been working perfectly for me. I will keep observing for side effects.
[ProxyShare.zip](https://github.com/nginx/njs/files/4183357/ProxyShare.zip)

**Comment by xeioex** [comment]
@nishant-dani 

Can you please share your full debug log?  Before it, please also remove any changes to vanilla nginx source code.

Your configuration is too complicated to debug (You also intruduced your own changes to nginx source code), please minimize it as much as possible.
Trying to reproduce it, without success so far.
My first suspect is `proxy_buffering off` in `conf.d/default.conf`. 

Let's start simple:
[nginx.conf](https://gist.github.com/xeioex/d9fa476df66c97a5c9c15b4329d8c0ec)

github286.js:
```js
function github286(r) {                                                                                                          
    r.subrequest("/proxy/backend")                                                                                               
    .then(reply=>r.return(200, reply.responseBody));                                                                             
}
```

```sh
$ curl --http2-prior-knowledge http://127.0.0.1:8000/github286
BACKEND
```

**Comment by nishant-dani** [comment]
It will take me a few weeks to get back on this as I got pulled into some launch work.  My changes to the nginx are mostly cosmetic (print debugs for more logging), but I will remove my process_requests fix before I debug with the simple nginx.conf.  I will let you know soon as I have something.  Another alternative is to directly debug my configuration directly and I could put in printfs and debug for you if you need more data.  I am quite conversant with the nginx flow now, so I can help track down directly (if you wish).  But for now I will do the simple first and see how that goes.

**Comment by xeioex** [comment]
@nishant-dani 
You may try https://github.com/nginx/njs/issues/215#issuecomment-592601186 patch, probably it solves your issue too.
