### ISSUE TITLE
Subrequest in variable handler not working

### ISSUE THREAD

**Issue by pmraiders** [nginx/njs#296]
Hello!

It would seem that my need for njs coincides with the 0.3.9 release of njs, where subrequests work in variable handlers.

I'm literally using the example from the "Introduction to the NGINX Javascript Module" blog post, with one line added in the .js file.

```
function kvHeaders(headers, parent) {
    var kvpairs = "";
    for (var h in headers) {
        kvpairs += " " + parent + "." + h + "=";
        if ( headers[h].indexOf(" ") == -1 ) {
                kvpairs += headers[h];
        } else {
            kvpairs += "'" + headers[h] + "'";
        }
    }
    return kvpairs;
}


function kvAccessLog(r) {
    var log = r.variables.time_iso8601;    // NGINX JavaScript can access all variables
    log += " client=" + r.remoteAddress;   // Property of request object
    log += " method=" + r.method;          // "
    log += " uri=" + r.uri;                // "
    log += " status=" + r.status;          // Property of response object
    log += kvHeaders(r.headersIn, "in");  // Send request headers object to function
    log += kvHeaders(r.headersOut, "out"); // Send response headers object to function

    //MY ADDED LINE
    r.subrequest('/log', { method: 'POST', body: '$log', detached: true });

    return log;
}
```

My goal here is to be able to capture the http(s) requests coming into the nginx proxy and direct them at another server to be logged for later playback for the purposes of testing with live, logged website traffic. From my somewhat limited knowledge of nginx and njs what I have here should work.

I'm choosing to do the subrequest in the log action because I should have access to all necessary fields to log the request, I just need to send it to another address to be handled. Additionally, since this is happening at the logging stage, the end user should already have their response while the server handles my code.

I understand that my direction of logs toward the subrequest might be incorrect, but I'm not even getting any access logs on the backend webserver.

Here is the .conf file:
```
js_include      conf.d/header_logging.js;
js_set          $access_log_with_headers kvAccessLog;
log_format      kvpairs $access_log_with_headers;


server {
    listen       80;
    server_name  localhost;
    
    access_log /var/log/nginx/access_headers.log kvpairs;
    
    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;
    
    location / {
        proxy_buffering off;
        proxy_pass http://127.0.0.1:8080/;
    }
    
    location /log {
        proxy_buffering off;
        proxy_pass http://127.0.0.1:8080/;
    }
}
```

**Comment by pmraiders** [comment]
If you have any other suggestions of how I can efficiently do this I'd be very happy to hear them. My basic requirements are to log the http fields so that I can replay the requests collected over time for the sake of testing a beta platform with live data.

**Comment by xeioex** [comment]
> If you have any other suggestions of how I can efficiently do this I'd be very happy to hear them. 

Take a look a the [mirror](http://nginx.org/en/docs/http/ngx_http_mirror_module.html) module.

**Comment by xeioex** [comment]
@pmraiders

> If you have any other suggestions of how I can efficiently do this I'd be very happy to hear them. 

Take a look a the [mirror](http://nginx.org/en/docs/http/ngx_http_mirror_module.html) module.

**Comment by xeioex** [comment]
@pmraiders 

> I'm choosing to do the subrequest in the log action because I should have access to all necessary fields to log the request, I just need to send it to another address to be handled. Additionally, since this is happening at the logging stage, the end user should already have their response while the server handles my code.

I have to confirm that running subrequest() in log phase takes no effect. The log example from njs-0.3.9 is incorrect and the result of misunderstanding. Log phase actually happens [AFTER](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.c#L3613) the current request is closed. Creating new subrequest after this stage is too late.

> I'm choosing to do the subrequest in the log action because I should have access to all necessary fields to log the request, I just need to send it to another address to be handled. Additionally, since this is happening at the logging stage, the end user should already have their response while the server handles my code.

Traditionally you collect your access logs from different machines using [syslog](http://nginx.org/en/docs/syslog.html).

**Comment by pmraiders** [comment]
> @pmraiders
> 
> > If you have any other suggestions of how I can efficiently do this I'd be very happy to hear them.
> 
> Take a look a the [mirror](http://nginx.org/en/docs/http/ngx_http_mirror_module.html) module.

Thank you, I had no idea this module existed and its exactly what I need. Keep up the good work on njs though, I'm very impressed by this project and while I don't need it for *this* project it has given me a lot of ideas of how to optimize my existing services.
