### ISSUE TITLE
Set-Cookie headers in headersOut are not accessible

### ISSUE THREAD

**Issue by kepuss** [nginx/njs#298]
Hi,
I have a problem to access Set-Cookie headers (I got 5 of them in response) from reply.headersOut.
I can only read the first one.
When I use the loop to display all headers:
```
for (var h in reply.headersOut) {
  headers[h] = reply.headersOut[h];
}
```
I get 5 times first header.
I saw the same question a few months ago  https://github.com/nginx/njs/issues/240
I'm using nginx-plus-module-njs 0.3.7
Have you introduced any method to access those headers?

**Comment by xeioex** [comment]
@kepuss 

> Have you introduced any method to access those headers?

not yet. We plan to introduced a special interface for cookies  after #16 is done in 0.4.0.

**Comment by xeioex** [comment]
@kepuss 

As a workaround, you can access upstream cookies using `r.variables['upstream_cookie_" + <cookie name>]` (l[ink](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_cookie_)).

**Comment by xeioex** [comment]
Will be done as a part of #266.

**Comment by kepuss** [comment]
Thanks @xeioex 
Any rough estimate when it will be released?

**Comment by xeioex** [comment]
@kepuss I plan to release it as a part of 0.4.0 (the beginning of April) or 0.4.1 (May).

**Comment by joshgibs** [comment]
Hello @xeioex do you have any concrete timelines for the release of the set-cookie fix?

**Comment by xeioex** [comment]
@joshgibs the patch is currently in queue for review.
BTW, you can test it: https://gist.github.com/xeioex/8c287bfc1353f5e30decff8920ea0cb4.

We plan to release 0.4.0 on 21.04.2020.

**Comment by xeioex** [comment]
@joshgibs 
@kepuss 

njs 0.4.0 is released: http://nginx.org/en/docs/njs/changes.html#njs0.4.0
