### ISSUE TITLE
Object.values() / Object.entries()

### ISSUE THREAD

**Issue by drsm** [nginx/njs#3]
ES2017 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values
```javascript
Object.entries = (object) => Object.keys(object).map(
        (key) => [ key, object[key] ]
    );
Object.values = (object) => Object.keys(object).map(
        (key) => object[key]
    );
```

**Comment by xeioex** [comment]
Committed in https://github.com/nginx/njs/commit/634fd42da715280d189207b81817495e4e0a19a4 and  https://github.com/nginx/njs/commit/486c98f21e1c2b5e77c38ed7e673785c521ccfd1
