### ISSUE TITLE
Segmentation violation while importing

### ISSUE THREAD

**Issue by johnpantini** [nginx/njs#300]
The following code causes njs to crash with a segfault:

`handler.js`

```javascript
import Blob from 'blob.js';

export default function () {
  new Blob();
}

```

`blob.js`
```javascript
var blobSupported = false;

try {
  blobSupported = new Blob(['ä']).size === 2;
} catch (e) {
}

export default {};
```

**Comment by xeioex** [comment]
@vryabinin 

Take a look at compatibility [page](http://nginx.org/en/docs/njs/compatibility.html).

Currently only "default export and default import statements" are supported.

`export default function ...` expression is not supported yet. See https://github.com/nginx/njs/issues/121

**Comment by vryabinin** [comment]
@xeioex 

It shouldn't cause a segv anyway. It compiles OK and doesn't produce a warning ("Illegal export statement"). The segv disappears when I remove these lines:

```javascript
var blobSupported = false;

try {
  blobSupported = new Blob(['ä']).size === 2;
} catch (e) {
}
```

**Comment by xeioex** [comment]
@vryabinin 

> It shouldn't cause a segv anyway

agree. Will be fixed.

**Comment by hongzhidao** [comment]
@xeioex 

I simplified it again.
```
# blob.js
new Blob();
export default 1;

# handler.js
import Blob from 'blob.js';
export default 1;

#segv.js
import handler from 'handler.js';
```
The question is the imported file referenced the outside variables. Here is `Blob`.
As expected, they are not able to access these outside variables because of `hoist`.
But, the name of import is processed as a variable.

I suggest fixing it after `parser` refactoring.

**Comment by drsm** [comment]
@hongzhidao 

> Help confirm that only global (I mean those are predefined in language, such as Object, Array, etc) and local(declared in modules) variables are allowed to access in modules. @drsm

Yes. Module scopes are independent.

In our case `let` will help to detect collisions:
```js
/*
$ cat a.js
console.log(name_from_b);
export default 1;
$ cat b.js
import name_from_b from 'a.js';
export default 1;
$ cat c.js
import name from 'b.js'
*/

var name = (function b() {
    var name_from_b = (function a() {
        console.log(name_from_b);
        return 1;
    })();
    return 1;
})();

// vs.

let x_name = (function b() {
    let x_name_from_b = (function a() {
        console.log(x_name_from_b);
        return 1;
    })();
    return 1;
})();
```

**Comment by xeioex** [comment]
@hongzhidao 

> I suggest fixing it after parser refactoring.

Agree.

**Comment by hongzhidao** [comment]
@xeioex 

> In our case let will help to detect collisions

BTW, this seems a good idea though `let` is hard to implement.
If we fixed this issue based on the current `parser`, it may be not a good idea.

**Comment by hongzhidao** [comment]
@drsm 
Help to take a look at the example.
```
import * as os from 'os';
var a = 1;
console.log(globalThis.a);
```
In `babel`, it shows `1`.
In `QuickJS`, it shows `undefined`.

Which is correct?

**Comment by drsm** [comment]
@hongzhidao 

The latter is [correct](https://javascript.info/modules-intro#module-level-scope/).

**Comment by hongzhidao** [comment]
@drsm 
I get it, now. Thanks.
But what's the way of getting global variables?

**Comment by drsm** [comment]
@hongzhidao 

global variables work same way in both scripts or modules:
```shell
$ cat x.mjs 
import * as y from './y.mjs';

console.log(test, y.test, globalThis.test);
$ cat y.mjs 
var test;

globalThis.test = 'xxx';

export { test };
$ node --experimental-modules x.mjs 
(node:8744) ExperimentalWarning: The ESM module loader is experimental.
xxx undefined xxx
```
So, `globalThis` is a hacky thing.

**Comment by xeioex** [comment]
A related issue: https://github.com/nginx/njs/issues/371

**Comment by xeioex** [comment]
Will be fixed as a part of https://github.com/nginx/njs/issues/443.
