### ISSUE TITLE
ngx_http_js_module.so is failng

### ISSUE THREAD

**Issue by laith-leo** [nginx/njs#302]
I'm testing compiling nginx 1.16.1 from source with njs using the nginx official [docs](http://nginx.org/en/docs/njs/)
But when I'm trying to test the [static](http://nginx.org/en/docs/njs/install.html#install_sources) module as of the [examples](http://nginx.org/en/docs/njs/examples.html#helloword), it fails with not creating the modules directory and then missing of ngx_http_js_module.so :

`nginx: [emerg] dlopen() "/Local/ThirdParty/nginx/modules/ngx_http_js_module.so" failed (/Local/ThirdParty/nginx/modules/ngx_http_js_module.so: cannot open shared object file: No such file or directory) in /Local/ThirdParty/nginx/conf/LEO-nginx.conf:1`

Here is my configs:

`[root@8c40580ebac3 ~]# ls /tmp/nginx-1.16.1/
CHANGES  CHANGES.ru  LICENSE  Makefile  README  auto  conf  configure  contrib  html  man  njs  objs  src`

Command used for compiling: 

`cd /tmp/nginx-1.16.1 && ./configure --prefix=$DEST/nginx --sbin-path=$DEST/nginx/nginx --conf-path=$DEST/nginx/conf/LEO-nginx.conf --error-log-path=$DEST/nginx/logs/LEO-error.log --pid-path=$DEST/nginx/runtime/nginx.pid --lock-path=$DEST/nginx/runtime/nginx.lock --without-http_gzip_module --with-debug --with-http_auth_request_module --with-http_realip_module --with-http_stub_status_module --add-module=/tmp/nginx-1.16.1/njs/nginx && make && make install`

But the **modules** directory is not created:

`[root@8c40580ebac3 nginx-1.16.1]# ls /Local/ThirdParty/nginx/
conf  html  logs  nginx  runtime`

I'm under Oracle Linux 7.7, here is the info:

`[root@8c40580ebac3 nginx-1.16.1]# /Local/ThirdParty/nginx/nginx -V
nginx version: nginx/1.16.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC)
configure arguments: --prefix=/Local/ThirdParty/nginx --sbin-path=/Local/ThirdParty/nginx/nginx --conf-path=/Local/ThirdParty/nginx/conf/LEO-nginx.conf --error-log-path=/Local/ThirdParty/nginx/logs/LEO-error.log --pid-path=/Local/ThirdParty/nginx/runtime/nginx.pid --lock-path=/Local/ThirdParty/nginx/runtime/nginx.lock --without-http_gzip_module --with-debug --with-http_auth_request_module --with-http_realip_module --with-http_stub_status_module --add-module=/tmp/nginx-1.16.1/njs/nginx`

`[root@8c40580ebac3 nginx-1.16.1]# uname -a
Linux 8c40580ebac3 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Also, here is the related part of the completion that is related to this module

`...
objs/src/http/modules/ngx_http_stub_status_module.o \
objs/addon/nginx/ngx_http_js_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lcrypt /tmp/nginx-1.16.1/njs/nginx/../build/libnjs.a -lm -lpcre \
-Wl,-E
sed -e "s|%%PREFIX%%|/Local/ThirdParty/nginx|" \
	-e "s|%%PID_PATH%%|/Local/ThirdParty/nginx/runtime/nginx.pid|" \
	-e "s|%%CONF_PATH%%|/Local/ThirdParty/nginx/conf/LEO-nginx.conf|" \
	-e "s|%%ERROR_LOG_PATH%%|/Local/ThirdParty/nginx/logs/LEO-error.log|" \
	< man/nginx.8 > objs/nginx.8
make[1]: Leaving directory `/tmp/nginx-1.16.1'
make -f objs/Makefile install
make[1]: Entering directory `/tmp/nginx-1.16.1'
test -d '/Local/ThirdParty/nginx' || mkdir -p '/Local/ThirdParty/nginx'
test -d '/Local/ThirdParty/nginx' \
	|| mkdir -p '/Local/ThirdParty/nginx'
test ! -f '/Local/ThirdParty/nginx/nginx' \
	|| mv '/Local/ThirdParty/nginx/nginx' \
		'/Local/ThirdParty/nginx/nginx.old'
cp objs/nginx '/Local/ThirdParty/nginx/nginx'
test -d '/Local/ThirdParty/nginx/conf' \
load_module modules/ngx_http_js_module.so;
	|| mkdir -p '/Local/ThirdParty/nginx/conf'
...`

Knowing that when I use the _--add-dynamic-module_ instead of _--add-module_ it works just fine.

**Comment by xeioex** [comment]
@laith-leo 

[load_module](http://nginx.org/en/docs/ngx_core_module.html#load_module) is a directive to load a *dynamic* module. So, you do not need it when you statically compile the module using `--add-module`.
Modules added with `--add-module` are always enabled.

**Comment by xeioex** [comment]
@laith-leo 

You can also look at the following examples: https://github.com/xeioex/njs-examples

**Comment by laith-leo** [comment]
Yes, it works now:

`[root@8c40580ebac3 nginx]# curl localhost:8000
Hello world![root@8c40580ebac3 nginx]#`

However, the [examples](http://nginx.org/en/docs/njs/examples.html#helloword) should be more clear for which Dynamic and Static usage.

Thanks.
