### ISSUE TITLE
Content-type header lost when making a subrequest 

### ISSUE THREAD

**Issue by igabesz** [nginx/njs#306]
I have the following workflow in an nginx.conf file and NJS files:

- [conf] Receive a request (`server`, `location`)
- [conf] Pass execution to the NJS code (`js_content`)
- [JS] Make a subrequest to an internal route
- [conf] The internal route is a proxy_pass to an external server
- [JS] Get the response from the internal route
- [JS] Send back the status code, headers and body to the original request

I found that the returning Content-type header is lost. The external server returns `application/json` while the nginx returns `text/plain`. I don't see the Content-type field in the NJS code when processing the response of the subrequest (`reply.headersOut`). But if I call the proxy_pass directly (without NJS subrequest) then the response contains the proper Content-type header. 

**Edit**: I do see the X-Powered-By header in `reply.headersOut` and others as well. So it's not that all of the headers are lost. But Content-Type and Content-Length are missing indeed. 

Maybe I missed something or something avoided my attention in the docs, dunno... but it might as well be a bug. 

**=== CONFIGS ===** 

nginx.conf entry:

```
location /endpoint {
    js_content execRequest;
}
```

In the `execRequest` implementation. (I tried with and without the commented part.)

```
    r.subrequest('/proxy/endpoint', { 
        method: method,
        body: r.requestBody,
    }).then(reply => {
        r.status = reply.status;
        // No Content-type in the reply.headersOut
        // for (var header in reply.headersOut) { // This might or might not required
            // r.headersOut[header] = reply.headersOut[header];
        // }
        r.sendHeader();
        r.send(reply.responseBody);
        r.finish();
    });
```

And the proxy:
```
  location /proxy {
            # internal; // Turned off to check it manually
            proxy_pass_request_headers on;

            location /proxy/endpoint {
                proxy_pass http://$external_service/endpoint;
            }
    }
```

**Comment by xeioex** [comment]
Hi, @igabesz  

what version of njs are you using?

**Comment by igabesz** [comment]
Thanks, it works with 4.0! Now it copies all of the headers from the reply of the subrequest to the main response. 

I was using nginx:latest (1.17.10 with NJS 3.9), now I moved to nginx:stable (1.18.0 with NJS 4.0) and it works smoothly.
