### ISSUE TITLE
mirror /_NULL directive causing json_validator.js to be called twice

### ISSUE THREAD

**Issue by Narragansett** [nginx/njs#307]
Following this example - Validating Request Bodies - 
https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-2-protecting-backend-services/#request-bodies
I load the json_validator once in api_gateway.conf
js_include json_validator.js;
js_set $validated json_validator;

Once I add the directive in a conf file - 
mirror /_NULL;                    # Create a copy of the request to capture request body

The json_validator.js is invoked twice on each  call. Everything is working except each request results in two calls being sent to the json_validator.js, why? How to stop this doubling?
[nginx_njs_json_validator.zip](https://github.com/nginx/njs/files/4552281/nginx_njs_json_validator.zip)

**Comment by xeioex** [comment]
@Narragansett 

Can you please share the debug log and the version of nginx?

BTW, using the simple conf below, I see no double evaluations:
```
         location = /proxy_validate {                                                                                      
            proxy_pass "http://$validated/proxy_dest";                                                                     
                                                                                                                           
            mirror /_NULL;                                         
            client_body_in_single_buffer on;                             
            client_body_buffer_size      16k;                     
            client_max_body_size         16k;                                                                              
        }                                                                                                                  
                                                                                                                           
         location = /proxy_dest {                                                                                          
             return 200 "PROXY_DEST";                                                                                      
        }                                                                                                                  
                                                                                                                           
         location = /_NULL {                                                                                               
             internal;                                                                                                     
             return 204;                                                                                                   
         }
```

```
2020/04/29 15:22:40 [notice] 2512#2512: using the "epoll" event method
2020/04/29 15:22:40 [notice] 2512#2512: nginx/1.17.9 (/tmp/build/nginx//nginx)
2020/04/29 15:22:40 [notice] 2512#2512: built by clang 10.0.0-++20200323044127+d32170dbd5b-1~exp1~20200323154723.129 
2020/04/29 15:22:40 [notice] 2512#2512: OS: Linux 4.4.0-1105-aws
2020/04/29 15:22:40 [notice] 2512#2512: getrlimit(RLIMIT_NOFILE): 1024:1048576
2020/04/29 15:22:42 [error] 2512#2512: *1 js: validate
127.0.0.1 - - [29/Apr/2020:15:22:42 +0000] "GET /proxy_dest HTTP/1.0" 200 10 "-" "curl/7.47.0"
127.0.0.1 - - [29/Apr/2020:15:22:42 +0000] "GET /proxy_validate HTTP/1.1" 200 10 "-" "curl/7.47.0"
2020/04/29 15:22:42 [info] 2512#2512: *1 client 127.0.0.1 closed keepalive connection
```

```
function validate(r) {                                                                                                     
    r.error("validate");                                                                                                   
    return '127.0.0.1:8000'                                                                                                
} 
```

**Comment by Narragansett** [comment]
Thank you for the reply I have this
root@ubuntu-VirtualBox:/etc/nginx# nginx -v
nginx version: nginx/1.16.1

[access.log](https://github.com/nginx/njs/files/4553197/access.log)
[error.log](https://github.com/nginx/njs/files/4553201/error.log)

BTW, how to get more verbose logging? For one request I see two calls sent to the handlers (nodeJS apps redirected by the plugin) where I have console.log statements.


I'm using this conf from the example, which seems fine ...
server {
    listen 80;
    server_name localhost;

    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
	proxy_pass http://$validated$request_uri;

    mirror /_NULL;                    # Create a copy of the request to capture request body
    client_body_in_single_buffer on;  # Minimize memory copy operations on request body
    client_body_buffer_size      16k; # Largest body to keep in memory (before writing to file)
    client_max_body_size         16k;

    }
}

And this json_validator.js (from the Nginx example)
// Attempt to validate requests as JSON
function json_validator(req) {
    try {
        req.log('json_validator entered ...');
        if ( req.variables.request_body.length > 0 ) {
            JSON.parse(req.variables.request_body);
        }
        //return req.variables.upstream;
        return '127.0.0.1:5000'; // Address for success response
    } catch (e) {
        req.log('JSON.parse exception');
        return '127.0.0.1:10415'; // Address for error response
    }
}

**Comment by xeioex** [comment]
@Narragansett 

> BTW, how to get more verbose logging? 

See https://nginx.org/en/docs/ngx_core_module.html#error_log
and https://nginx.org/en/docs/debugging_log.html

**Comment by Narragansett** [comment]
So you're right but ...
error.log shows json_validator being called once but ...
2020/05/01 10:44:58 [info] 2684#2684: *4 js: json_validator entered ...
2020/05/01 10:44:58 [info] 2684#2684: *4 js: JSON.parse exception
2020/05/01 10:44:58 [info] 2684#2684: *4 js: Forward failed request ...
2020/05/01 10:44:58 [info] 2684#2684: *4 client 127.0.0.1 closed keepalive connection

.... but my error handling server gets called twice ...
Request blocked due to invalid JSON - object, [object Object]
Request blocked due to invalid JSON - object, [object Object]

with json_validator.js being this ... both success and failed URLs get invoked 2x, which is crazy but why?

// Attempt to validate requests as JSON
function json_validator(req) {
    try {
        req.log('');
        req.log('json_validator entered ...');
        if ( req.variables.request_body.length > 0 ) {
            JSON.parse(req.variables.request_body);
        }
        req.log('Forward successful request ...');
        //return req.variables.upstream;
        return '127.0.0.1:5000'; // Address for success response
    } catch (e) {
        req.log('JSON.parse exception');
        req.log('Forward failed request ...');
        return '127.0.0.1:10415'; // Address for error response
    }
}

**Comment by xeioex** [comment]
@Narragansett 

> with json_validator.js being this ... both success and failed URLs get invoked 2x, which is crazy but why?

I may only suggest to look into your handling server access log closely.

**Comment by Narragansett** [comment]
Solved!
I needed to add this directive. But what does it do? Why is it necessary with the mirror directive?
	location = /_NULL {
		internal;
		return 204;  
	}
Thank you,
Jerry

**Comment by Narragansett** [comment]
Needed to consume the mirror's duplicate copy of the request object.

**Comment by xeioex** [comment]
@Narragansett 

Please elaborate which directive are you talking?

**Comment by Narragansett** [comment]
This stanza was needed -
         location = /_NULL {                                                                                               
             internal;                                                                                                     
             return 204;                                                                                                   
         }

What's not intuitive is the need to add a mirror, which creates a copy of the request, and then need to add the above to consume the extra copy of the request created by the mirror. Why not just let all requests flow through the plugin once it has been configured? Adding a mirror and then having to consume it seems redundant (and not intuitive). Else my client code was receiving 2x requests.

**Comment by xeioex** [comment]
@Narragansett 

> What's not intuitive is the need to add a mirror, 

yes, this is not intuitive, but that was explained in the article and your nginx.conf contained these line uncommented.

The reason is complicated. In short when the variable for `proxy_pass http://$validated$request_uri;` is evaluated the request body may be not read yet by nginx (It may be very large for example). When njs handler is executed as a variable handler it is executed in synchronous context by nginx (he wants the variable content right away, so it cannot wait for example until request body is full read).
