### ISSUE TITLE
Segmentation fault when string replace capture

### ISSUE THREAD

**Issue by crasyangel** [nginx/njs#308]
```
./build/njs
interactive njs 0.4.1

v.<Tab> -> the properties and prototype methods of v.

>> var a='/universal/v1/69e38/MDtUGuPFPsEAT4k-rkMDFO8WKUE/eyJkbCI6MTU4OTM2NDAwMiwiZXMiOjg2NDAwLCJpZCI6IjE5MTM0NDU0MyIsInYiOiIxLjAifQ/?type=m3u8&mt=0'
undefined
>> console.log(a.replace(/^\/universal\/v1\/69e38\/[^/]*\/[^/]*\/([^\?]*)\?.*(mt=[^&]*).*$/, "/universal/v1/69e38/$1?$2"))
Segmentation fault: 11
```

njs_string_replace_substitute njs_arr_add_multiple last+1 item, but not all items would be assigned, maybe continue directly.
The items of r->parts need to re-calc, and it should increase only when part++

**Comment by crasyangel** [comment]
@xeioex patch updated. The last part assigned at first, and should re-assigned to the real last, or set internal part size to be zero

**Comment by crasyangel** [comment]
patch deleted. The problem is not the wrong items, actually the capture is not right

**Comment by crasyangel** [comment]
```
interactive njs 0.4.1

v.<Tab> -> the properties and prototype methods of v.

>> var b = 'xxxxx'
undefined
>> console.log(b.replace(/([a]*)([b]*)(xxx)([c]*)([d]*)(xx)/, '$3$6'))
xxxxx
undefined
>> console.log(b.replace(/([a]*)([b]*)(xxx)([c]*)([d]*)(xx)/, '$1$2$3$6'))
xxx
undefined
>> console.log(b.replace(/([a]*)([b]*)(xxx)([c]*)([d]*)(xx)/, '$1'))
x
undefined
```

@xeioex $1,$2,$4,$5 should be empty, and $3 should be 'xxx', $6 should be 'xx'
but the result show $1$2$3$6 as 'xxx', and $1 as 'x'

**Comment by xeioex** [comment]
@crasyangel  Thanks for reporting, will take a look at the end of the week.

**Comment by xeioex** [comment]
@crasyangel 
As a side not, regexps is not the best possible way to do this kind of tasks. It gets complicated too quickly.

More structured alternative:
```js
var uri='/universal/v1/69e38/MDtUGuPFPsEAT4k-rkMDFO8WKUE/eyJkbCI6MTU4OTM2NDAwMiwiZXMiOjg2NDAwLCJpZCI6IjE5MTM0NDU0MyIsInYiOiIxLjAifQ/?type=m3u8&mt=0';
var parts = uri.split('?'); 
var location = parts[0]; var args = parts[1].split('&');
var p = location.split('/');
var mt = args.filter(v=>v.startsWith('mt='))[0];
var result = `/${p[1]}/${p[2]}/${p[3]}/${p[5]}/?${mt}`; 

console.log(result) 
// /universal/v1/69e38/eyJkbCI6MTU4OTM2NDAwMiwiZXMiOjg2NDAwLCJpZCI6IjE5MTM0NDU0MyIsInYiOiIxLjAifQ/?mt=0
```

BTW, we also plan to simplify this parsing implementing https://github.com/nginx/njs/issues/143

**Comment by crasyangel** [comment]
> @crasyangel Thanks for reporting, will take a look at the end of the week.

Good idea. looking forward to the URL native object

**Comment by xeioex** [comment]
@crasyangel I also forgot that njs already does arguments and uri parsing for you.

So the code above is simplified to:
```js
var p = r.uri.split('/');
var result = `/${p[1]}/${p[2]}/${p[3]}/${p[5]}/?$mt=${r.args.mt}`; 
```

**Comment by crasyangel** [comment]
@xeioex How to fix segfault? any idea?

**Comment by xeioex** [comment]
@crasyangel 

> How to fix segfault? any idea?

I am on it. It is in progress. Trying to rewrite it using new more straightforward primitives from njs_chb.c.

The current code in njs_string_prototype_replace() became too complicated.
