### ISSUE TITLE
sub_filter on njs

### ISSUE THREAD

**Issue by benone** [nginx/njs#309]
Could you please make example of sub_filter with njs?

I have location:

```
location / {
    try_files $uri 
      /cache/$host/$uri/index.html
      /cache/$host/$uri.html
      /cache/$host/$uri
      @puma_special_equipment_production;  
}
```

and njs file:

```
function replaceText(r) {
  r.headersOut['Content-Type'] = "text/html; charset=utf-8";

  r.subrequest(r.uri, r.variables.args)
    .then(function(reply){
      var body = reply.responseBody;
      body = body.replace(/\<div\>/g, "<span>")
      r.return(reply.status, body)
    })
}
```

But I don't understand where to place
`js_content replaceText;`

It should be new location?

Thanks!

**Comment by xeioex** [comment]
@benone 

Did you consider [sub_filter](https://nginx.org/ru/docs/http/ngx_http_sub_module.html) module?
I suggest to start from that place.

It supports multiple replacement strings as well as nginx variable.

The njs variant requires intermediate location and therefore less efficient.
Something like this (did not verify, do not recommend):

```
js_set $orig_uri  orig_uri;

location / {
    js_content replace;
}

location /p/ {
    internal;
    try_files $orig_uri 
      /cache/$host/$orig_uri/index.html
      /cache/$host/$orig_uri.html
      /cache/$host/$orig_uri
      @puma_special_equipment_production;  
}
```

```
function orig_uri(r) {
    return r.uri.substr(2);
}

function replaceText(r) {
  r.headersOut['Content-Type'] = "text/html; charset=utf-8";

  r.subrequest(`/p${r.uri}`, r.variables.args)
    .then(function(reply){
      var body = reply.responseBody;
      body = body.replace(/\<div\>/g, "<span>")
      r.return(reply.status, body)
    })
}
```

We have plans to implement native body filters with njs (similar to sub_filter).

**Comment by benone** [comment]
> @benone
> 
> Did you consider [sub_filter](https://nginx.org/ru/docs/http/ngx_http_sub_module.html) module?
> I suggest to start from that place.
> 
> It supports multiple replacement strings as well as nginx variable.
> 
> The njs variant requires intermediate location and therefore less efficient.
> Something like this (did not verify, do not recommend):
> 
> ```
> js_set $orig_uri  orig_uri;
> 
> location / {
>     js_content replace;
> }
> 
> location /p/ {
>     internal;
>     try_files $orig_uri 
>       /cache/$host/$orig_uri/index.html
>       /cache/$host/$orig_uri.html
>       /cache/$host/$orig_uri
>       @puma_special_equipment_production;  
> }
> ```
> 
> ```
> function orig_uri(r) {
>     return r.uri.substr(2);
> }
> 
> function replaceText(r) {
>   r.headersOut['Content-Type'] = "text/html; charset=utf-8";
> 
>   r.subrequest(`/p${r.uri}`, r.variables.args)
>     .then(function(reply){
>       var body = reply.responseBody;
>       body = body.replace(/\<div\>/g, "<span>")
>       r.return(reply.status, body)
>     })
> }
> ```
> 
> We have plans to implement native body filters with njs (similar to sub_filter).

Thanks a lot! It works!
I have some logic in js so sub_filter don't quite meet requirements..

**Comment by benone** [comment]
> @benone
> 
> Did you consider [sub_filter](https://nginx.org/ru/docs/http/ngx_http_sub_module.html) module?
> I suggest to start from that place.
> 
> It supports multiple replacement strings as well as nginx variable.
> 
> The njs variant requires intermediate location and therefore less efficient.
> Something like this (did not verify, do not recommend):
> 
> ```
> js_set $orig_uri  orig_uri;
> 
> location / {
>     js_content replace;
> }
> 
> location /p/ {
>     internal;
>     try_files $orig_uri 
>       /cache/$host/$orig_uri/index.html
>       /cache/$host/$orig_uri.html
>       /cache/$host/$orig_uri
>       @puma_special_equipment_production;  
> }
> ```
> 
> ```
> function orig_uri(r) {
>     return r.uri.substr(2);
> }
> 
> function replaceText(r) {
>   r.headersOut['Content-Type'] = "text/html; charset=utf-8";
> 
>   r.subrequest(`/p${r.uri}`, r.variables.args)
>     .then(function(reply){
>       var body = reply.responseBody;
>       body = body.replace(/\<div\>/g, "<span>")
>       r.return(reply.status, body)
>     })
> }
> ```
> 
> We have plans to implement native body filters with njs (similar to sub_filter).

@xeioex One more question:

Can I send original headers ($uri) to my stream server @ puma_special_equipment_production?

Or somehow rewrite it back..

**Comment by xeioex** [comment]
@benone 

Take a look at [mirror](http://nginx.org/en/docs/http/ngx_http_mirror_module.html) module.
