### ISSUE TITLE
Subrequest result in variable

### ISSUE THREAD

**Issue by an0ma1ia** [nginx/njs#31]
Is it possible to return subrequest result as function result instead of callback?

**Comment by an0ma1ia** [comment]
That's sad. Using function result I can get much more simple and readable code.

**Comment by an0ma1ia** [comment]
Actually I can't exit from outer function if subrequest fails:
``
function F(r) {
  var exit = false;
  r.warn('F exit=' + exit + ';');
  r.subrequest('/uri/', '', function(res) {
    r.warn('res.status=' + res.status);
    if (res.status != 200) {
      exit = true;
      r.warn('subrequest exit=' + exit + ';');
      return;
    }
  });
  r.warn('F exit=' + exit + ';');
  if (exit) {
    r.warn('!!! EXIT !!!');
    return;
  }
``

warnings:
``
2018/07/04 16:43:47 [warn] 14095#14095: *185 js: F exit=false;
2018/07/04 16:43:47 [warn] 14095#14095: *185 js: F exit=false;
2018/07/04 16:43:47 [warn] 14095#14095: *185 js: res.status=403
2018/07/04 16:43:47 [warn] 14095#14095: *185 js: subrequest exit=true;
``

How can I interrupt outer function F if subrequest returs error status?

**Comment by an0ma1ia** [comment]
Oh, no... Callback spaghetti is not what I want to deal with.

**Comment by drsm** [comment]
@an0ma1ia, while waiting for the async/await functionality or native promise implementation, one can always write his own buggy support lib ).
e.g.
```javascript
var io = function(request) {
    var r = request;
        
    var chain = []; 
    var last = function(cxt) {
        return [200, cxt];
    };
    
    var then = function(handler) {
        chain.push(handler);
        return this;
    };
    
    var start = function() {};
    var end = function(handler) {
        last = handler || last;
        start();
    };
    
    var out = Object.create({
        then: then,
        end: end
    });

    var cxt = {};
    var done = function() {
        if (cxt != null) {
            var rs = last(cxt);
            cxt = null;
            r.return(rs[0], JSON.stringify(rs[1]));
        }
    }

    var id = {};
    var cb = function(res) {
        if (cxt != null) {
            var fn = chain.shift();
            if (fn) {
                if (fn.call(api, res, cxt) != id) {
                    // ignored
                }
            } else {
                done();
            }
        }
    };
    
    var fetch = function(uri, options) {
        r.subrequest(uri, options, cb);
        return id;
    };
    
    var api = Object.create({
        fetch: fetch,
        done: done
    });
    
    start = cb;
            
    return out;
};

function test(r) {
    io(r)
        .then(function(res, cxt) {
            cxt[0] = Date.now();
            return this.fetch('/rs', { args: 'i=0' });
        })
        .then(function(res, cxt) {        
            cxt[1] = Date.now() - cxt[0];
            if (Math.random() < 0.75) {
                return this.fetch('/rs', { args: 'i=1' });
            }
            this.done();
        })
        .then(function(res, cxt) {
            cxt[2] = Date.now() - cxt[0];
            if (Math.random() < 0.5) {
                return this.fetch('/rs', { args: 'i=2' });
            }
            this.done();
        })
        .then(function(res, cxt) {
            cxt[3] = Date.now() - cxt[0];
            if (Math.random() < 0.25) {
                return this.fetch('/rs', { args: 'i=3' });
            }
            this.done();
        })
        .end(function(cxt) {
            cxt['all'] = Date.now() - cxt[0];
            cxt[0] = undefined;
            return [200, cxt];
        });    
}
```

**Comment by an0ma1ia** [comment]
Looks bad.

When I make subrequest I need that's result. And want not any side effect. Current njs implementation allows to make side effects only, with no explicit result - "run and forget".

In the nginx ssi implementation we have "wait" parameter. Am I understand right that you will add the same parameter in the r.subrequest function and explicitly return result if wait == true or undefined if wait == false?

**Comment by drsm** [comment]
> When I make subrequest I need that's result. And want not any side effect. Current njs implementation allows to make side effects only, with no explicit result - "run and forget".

read this, please: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Run-to-completion

> In the nginx ssi implementation we have "wait" parameter. Am I understand right that you will add the same parameter in the r.subrequest function and explicitly return result if wait == true or undefined if wait == false?

No, there is nothing about adding another fs.readFileSync alike stuff, as you can see in the following example:
```javascript

var r = {
    subrequest: function(uri, options, callback) {
        var res = {
            uri: uri,
            options: options,
            s: Date.now(),
            e: null
        };
        setTimeout(function() {
            res.e = Date.now();
            callback(res);
        }, 10 + 10 * Math.random());
    },
    
    'return': function(status, body) {
        console.log('finished [' + status + ']: ' + body);
    }
};

var rx = {
    subrequest: function(uri, options) {
        return new Promise(function(resolve, reject) {
            r.subrequest(uri, options, resolve);
        });
    },
    
    'return': r.return
};

function raceOne() {
    var stat = function(name, time) {
        r.subrequest(
            '/stat',
            { args: 'name=' + name + ';time=' + time },
            function(res) {
                r.return('raceOne', name + ' wins in ' + time + ' ms');
            }
        );
    };
    var finished = false;
    var finish = function(res) {
        if (!finished) {
            stat(res.uri, res.e - res.s);
            finished = true;
        }        
    }
    
    r.subrequest('/one', null, finish);
    r.subrequest('/two', null, finish);
}

function raceTwo() {
    var name;
    var time;
    
    Promise.race([
        rx.subrequest('/one', null),
        rx.subrequest('/two', null)
    ]).then(function(res) {
        name = res.uri;
        time = res.e - res.s;
        return rx.subrequest('/stat', { args: 'name=' + name + ';time=' + time });
    }).then(function(res) {
        r.return('raceTwo', name + ' wins in ' + time + ' ms');
    });
}

async function raceThree() {
    var winner = await Promise.race([
        rx.subrequest('/one', null),
        rx.subrequest('/two', null)
    ]);
    
    var name = winner.uri;
    var time = winner.e - winner.s;
    
    await rx.subrequest('/stat', { args: 'name=' + name + ';time=' + time });
    
    rx.return('raceThree', name + ' wins in ' + time + ' ms');
}

raceOne();
raceTwo();
raceThree();
```

**Comment by an0ma1ia** [comment]
I can't understand what you want to say. Sorry, too much code...
Do you mean that I want something impossible?

**Comment by drsm** [comment]
I was trying to explain the difference between the javascript language runtime which is event-driven and other stuff, like php and lua, that don't have it's own event loop.
The thing you want is possible to implement, but it may (will) cause more problems than profit.

**Comment by an0ma1ia** [comment]
That's why I like lua - it simply do what I ask.
For now I removed all subrequests which can be removed (one by transform it to error_page construction and another rewrote as JS function) and the last one moved to the end of calling function. It may be too early to migrate from lua module to njs...
