### ISSUE TITLE
Syntax for returning static error.html page

### ISSUE THREAD

**Issue by Narragansett** [nginx/njs#310]
Re: https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-2-protecting-backend-services/#request-bodies
Using json_validator.js, line 9 you have -
line 9: return '127.0.0.1:10415'; // Address for error response
I don't have an error server. I'd like to return static html denoting error. I cannot figure out that syntax. Is it even possible? For example -
line 9: return '127.0.0.1/error.html'; // How to do anything like this?

**Comment by xeioex** [comment]
@Narragansett 

Take a look at [error_page](https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) directive.

**Comment by Narragansett** [comment]
So I have been reading the docs and trying things. In every instance json_validator.js doesn't return an error page for the catch block, e.g. invalid JSON request. The docs only discuss if error codes are thrown somewhere (where?). I need json_validator.js to return a static error.html in the catch block (for the doc'd example). What is the syntax for json_validator.js line 9
line 9: return '127.0.0.1/error.html'; // How to do anything like this?
Thank you,

**Comment by drsm** [comment]
@Narragansett 

Hi!

> The docs only discuss if error codes are thrown somewhere (where?).

Here:
```
server {
    listen 127.0.0.1:10415; # This is the error response of json_validator()
    return 415; # Unsupported media type
    include api_json_errors.conf;
}
```
This stub returns an empty response with 415 status.

It is catched by :
```
error_page 415 = @415;
location @415 { return 415 '{"status":415,"message":"Unsupported media type"}\n'; }
```
Because of `proxy_intercept_errors on;`

You may want to change it to:
```
error_page 415 = @415;
location @415 /error.html
```
