### ISSUE TITLE
ngx_http_js_module from C

### ISSUE THREAD

**Issue by sdouek** [nginx/njs#314]
If I want to use **ngx_http_js_module** from my C project 
(currently include: 
#include <ngx_http.h>
#include <ngx_http_config.h>)
I want to use the new implementation of **r.subrequest(uri[, options[, callback]])** 
which include may I have to add ?

**Comment by xeioex** [comment]
@sdouek 

Please, elaborate what you are trying to do.
ngx_http_js_module has no convenient API to be used for other C projects.

1) if you want to extend  r.subrequest(), just copy ngx_http_js_module and make your own changes.

2) if you need C-level equivalent of r.subrequest() read [nginx dev guide](http://nginx.org/en/docs/dev/development_guide.html#http_subrequests) for general understanding and [r.subrequest implementation](https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L2543) to see how it is used in real code.
