### ISSUE TITLE
dynamic proxy_pass + proxy_cache possible

### ISSUE THREAD

**Issue by aaronpeterson** [nginx/njs#316]
I'm doing something inspired by #193 but using an aws s3 signed url instead and I'm wondering if someone can tell me if this can ever work.  I think it really depends on what the cache table looks like -- if the cache table would alert nginx that with each cache miss we should re-run s3qs() OR if it's just storing the computed url (which would result in a failed upstream response because the link expired).

*edit: It appears that the cache miss triggers a new request which fails because it has the stale signature. Still curious if this could ever be possible.

Use case: More portability/freedom in running my own CDN edges with a simple docker deployment.

**nginx.conf**

```
load_module modules/ngx_http_js_module.so;

events {}

http {
    js_include /etc/nginx/include/signed.js;

    js_set $s3qs s3qs;

    proxy_cache_path   /var/cache/nginx levels=1:2 keys_zone=my_cache:16m max_size=70g inactive=1d use_temp_path=off;
    proxy_temp_path    /var/cache/nginx/tmp;

    server {
        listen       8085;

        location / {
            # validate
            js_content redirectFunction;
        }

        location @storage {
            proxy_cache my_cache;
            proxy_cache_revalidate on;
            proxy_cache_lock on;
            proxy_cache_key $proxy_host$request_uri;

            proxy_set_header Accept '*/*';
            proxy_pass_request_headers off;
            proxy_set_header Content-Type '';
            server_tokens off;
            types { } default_type "";
            resolver 8.8.8.8; # TODO: change this
            add_header X-Cache-Status $upstream_cache_status;
            proxy_pass https://s3-compatible-storage.com$request_uri?$s3qs;
        }
    }
}

```

**signed.js**

```js
function s3qs(r) {
  var accessId = process.env.S3_ID;
  var secret = process.env.S3_SECRET;

  var expires = parseInt(Date.now() / 1000) + 60;

  // ... signing, etc

  return `AWSAccessKeyId=${accessId}&Signature=${s3signature}&Expires=${expires}`;
}

function redirectFunction(r) {
  // Some custom validation logic will be placed here
  /*
  if (r.args.tits === 'up') {
    r.return(403, "Nah\n");
  } else {
    r.return(200, "Yah\n");
  }
  */

  // proxy pass
  r.internalRedirect("@storage");
}

```

**Comment by xeioex** [comment]
@aaronpeterson 

> I think it really depends on what the cache table looks like -- if the cache table would alert nginx that with each cache miss we should re-run s3qs() 

The nginx cache is simple:
 if proxy cache if configured, before accessing the upstream `proxy_cache_key` variable is evaluated, the resulting hash is a part of the file name for the cached content. If cached content is found and not expired it is returned to the client, otherwise `proxy_pass` request is initialised.


> OR if it's just storing the computed url (which would result in a failed upstream response because the link expired).

the computed URL is not stored. Only `proxy_cache_key` is stored as a part of a file name in the cache.
