### ISSUE TITLE
Unable to find the njs version

### ISSUE THREAD

**Issue by laith-leo** [nginx/njs#317]
I'm trying to find out the njs module version that compiled within Nginx. `nginx -v` shows the module is there but doesn't show the version. 

Is there any way to find out the version of njs module that already compiled in within Nginx?

I considered this [method](http://nginx.org/en/docs/njs/install.html) for installation. 
Thanks.

**Comment by xeioex** [comment]
Hi, @laith-leo 

Dynamically:
njs version: `njs.version`
nginx version: `r.variables.nginx_version`

Statically for ngx_http_js_module.so
```
strings ./usr/lib/nginx/modules/ngx_http_js_module.so  | grep -e '0\.'
U0.4.1
```

For pre-built packages in Ubuntu:
```
sudo apt install nginx-module-njs
dpkg -s nginx-module-njs
...
Version: 1.18.0.0.4.1-1~xenial
Depends: libc6 (>= 2.17), libpcre3, libreadline6 (>= 6.0), nginx (= 1.18.0-1~xenial)
...
```

Here 1.18.0 is nginx version the second part 0.4.1 is njs version.

**Comment by laith-leo** [comment]
Thanks @xeioex,
 
These options are not really helping me, I have compiled the njs module with Nginx source code, so I don't have an njc cli neither the ngx_http_js_module.so is available.

Is there a way to determine the njs version through an API call through curl command or something?  Just asking as I have hundreds of servers that I need to check which njs version is installed on each.

**Comment by drsm** [comment]
@laith-leo 

Hi!

https://github.com/xeioex/njs-examples#hello-world-hello

**Comment by laith-leo** [comment]
Hi @drsm 

I'm aware of this example, but what I'm looking for is an API call (or something similar) to check the preconfigured Nginx servers with njs, this is not ideal when it comes to checking the njs version in a fleet of hundreds Nginx servers.

**Comment by xeioex** [comment]
@laith-leo 

>Is there a way to determine the njs version through an API call through curl command or something?

The only option  to declare a location and return `njs.version` from it.  There is no builtin locations in nginx.

**Comment by xeioex** [comment]
@laith-leo 

We recommend using  [pre-built packages](http://nginx.org/en/linux_packages.html), because they are tested against the nginx version they are compiled with.
