### ISSUE TITLE
using njs in multithreaded servers

### ISSUE THREAD

**Issue by rock59** [nginx/njs#319]
Is njs suitable for using in multithreaded servers where each thread have its own context and njs vms not shared between threads?

**Comment by xeioex** [comment]
Hi @rock59,

Yes, it is suitable. We prefer to use reenterable API calls whenever possible.
The only exception I recall is `fs.readdir()` where readdir() is used and not readdir_r() because the later[ is deprecated](https://man7.org/linux/man-pages/man3/readdir_r.3.html).

**Comment by rock59** [comment]
@xeioex  Thanks for your response.I don't need fs related APIs and I will open a new issue if needed
