### ISSUE TITLE
Object.getOwnPropertyDescriptor() should not query an object's prototype chain

### ISSUE THREAD

**Issue by drsm** [nginx/njs#32]
```javascript
>> var p = Object.create(null);
undefined
>> p.one = 1;
1
>> 'one' in p
true
>> var o = Object.create(p);
undefined
>> 'one' in o
true
>> JSON.stringify(Object.getOwnPropertyDescriptor(p, 'one'));
{"value":1,"configurable":true,"enumerable":true,"writable":true}
>> JSON.stringify(Object.getOwnPropertyDescriptor(o, 'one'));
{"value":1,"configurable":true,"enumerable":true,"writable":true}
```

**Comment by xeioex** [comment]
Hi @drsm,

Please, take a look at the following patch. Here, I did some refactor of internal primitives to make them more in line with methods from the spec like [[Get]], [[GetProperty]], [[GetOwnProperty]] etc.
It is expected to fix #32 and #34.

https://gist.github.com/xeioex/4d3526c4128560559fb3d1c73e08356f

**Comment by xeioex** [comment]
Hi @drsm, 

Thank you for testing. 
I will deal with the prototype chain lookup issue.

**Comment by xeioex** [comment]
@drsm  By the way, the njs CLI is now available in the official docker container

`docker run -i -t nginx:latest /usr/bin/njs`

https://github.com/xeioex/njs-examples
