### ISSUE TITLE
How to implement a EventSource ? (I tried but failed due to buffering of some kind)

### ISSUE THREAD

**Issue by terrywh** [nginx/njs#328]
How to implement a EventSource?
I tried with the below:
``` Javascript
/// <reference path="/data/source/njs-0.4.2/build/ts/ngx_http_js_module.d.ts" />
/**
 * @param {NginxHTTPRequest} r
 * */
function hello(r) {
    r.status = 200;
    r.headersOut['Cache-Control'] = 'no-cache';
    r.headersOut['Content-Type'] = 'text/event-stream; charset=utf-8';
    function sendSimple() {
        var data = ("data: hello: " + (++i) + "\n\n").toUTF8();
        r.send(data);
        if (i>10) {
            r.finish();
        }else{
            to = setTimeout(sendSimple, 1000);
        }
    }
    // r.headersOut['Transfer-Encoding'] = 'chunked';
    r.sendHeader();
    sendSimple();
}

export default { hello };
```

```
...
location /hello {
   js_content hello.hello;
}
...
```
 I tried to send the request both by Chrome and Curl, the results are the same. It seems that all responses are buffered until `r.finish()` is called (including headers) before sending to client.

``` bash
curl -vv http://127.0.0.1/hello
# after 10s
< HTTP/1.1 200 OK
...
data: hello: 1
...
```

**Comment by xeioex** [comment]
@terrywh 
Take a look at [https://nginx.org/en/docs/http/ngx_http_core_module.html#postpone_output](postpone_output) directive.

**Comment by terrywh** [comment]
I see. But when i use a backend server to achieve the same thing, it seems i do not need to set `postpone_output` (only need to disable proxy buffer); maybe some doc to point out the difference?

**Comment by xeioex** [comment]
@terrywh 

postpone_output is always active (see the [code](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_write_filter_module.c#L219)).

Probably when proxy_buffer is disabled 'flush' flag is set for the outgoing chunks (this can be verified with the following [debug log](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_write_filter_module.c#L208)).

**Comment by xeioex** [comment]
@terrywh 

postpone_output can be overridden with special `flush` flag (see the [code](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_write_filter_module.c#L219)).

When proxy_buffer is disabled `flush` flag is set for the outgoing chunks ([code](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_upstream.c#L3714)).

[proxy_buffer](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering) doc  says:
```
...
When buffering is disabled, the response is passed to a client synchronously, immediately as it is received.
```
