### ISSUE TITLE
Modify proxy_redirect using Nginx JavaScript module

### ISSUE THREAD

**Issue by xcellenceit** [nginx/njs#336]
does njs can be used to modify Location header of requests using proxy_redirect? Is there an example to refer for this?

**Comment by xeioex** [comment]
@xcellenceit 

yes, proxy_redirect supports variables. You can create your variable using `js_set` directive.

Something like this:

nginx.conf:
```
js_import main from lib.js;
js_set $my_redirect main.redirect;

location / {
...
proxy_redirect http://localhost:8000/ $my_redirect;
}
```

lib.js:
```js
function redirect(r) {
// you may use here any available variables
// including http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables
// For example:
return `https://${r.variables.upstream_http_server.toLowerCase()}`;
}

export default {redirect};
```
```

**Comment by xcellenceit** [comment]
That's awesome. Will try this. Thanks

**Comment by xcellenceit** [comment]
This works. Thanks

Does it have any performance impact when we use this?

**Comment by xeioex** [comment]
@xcellenceit 

Obviously, it depends on the js_set handler you wrote :). 

But, in general overhead is pretty low, so JS code causes zero impact until `js_set` variable is actually referenced by proxy_redirect directive in runtime for a specified location.

**Comment by xcellenceit** [comment]
Okay, get it.
