### ISSUE TITLE
r.subrequest not working for the same URI as client request URI

### ISSUE THREAD

**Issue by abhayranjan7** [nginx/njs#339]
I have a requirement where from a client request i need to first send this client request to upstream server and then on 200 response call another API to upstream. Now issue is when i am trying to create subrequest with the URI of client request i am getting this below error:
```
2020/09/07 04:21:35 [error] 13#13: *5 nested in-memory subrequest "/api/v1/foo", client: xx.xx.xx.xx, server: localhost, request: "GET /api/v1/foo HTTP/2.0", subrequest: "/api/v1/foo", host: "xx.xx.xx.xx", referrer: "https://xx.x.x.x/"
2020/09/07 04:21:35 [error] 13#13: *5 js exception: Error: subrequest creation failed
    at native (native)
    at hello (njs_common_util.js:3)
, client: xx.xx.xx.xx, server: localhost, request: "GET /api/v1/foo HTTP/2.0", subrequest: "/api/v1/foo", host: "xx.xx.xx.xx", referrer: "https://xx.x.xx.xx/"
```
Workaround for this issue can be to create a separate location block for the client request URI which is working fine with the sub-request.
My question is this behavior correct which doesn't allow creating subrequest with same URI of incoming request?

**Comment by xeioex** [comment]
@abhayranjan7 

> "nested in-memory subrequest "/api/v1/foo"

What you are getting is the message related to creating a subrequest from a subrequest ([which is forbidden by nginx](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_core_module.c#L2324)).

Instead, you always have to use the original request object to create subrequests. See [this](https://github.com/xeioex/njs-examples#subrequests-chaining-httpsubrequests_chaining) as example (note, we have a sequence of subrequests, but they always created from the main request (`r`, not `reply`))

**Comment by drsm** [comment]
@abhayranjan7 Hi!

looks like you are trying to do something like [this](https://github.com/nginx/njs/issues/58#issuecomment-436359857).
this will not work.

> Workaround for this issue can be to create a separate location block for the client request URI which is working fine with the sub-request.
> My question is this behavior correct which doesn't allow creating subrequest with same URI of incoming request?

yes.

**Comment by abhayranjan7** [comment]
Hi @xeioex @drsm thanks for your comments. Looks like it's not a issue with njs. Closing this.
