### ISSUE TITLE
question about subrequest_output_buffer_size

### ISSUE THREAD

**Issue by elixiao** [nginx/njs#350]
I use  subrequest with proxy_pass but got `curl: (52) Empty reply from server`:

```
r.subrequest('/mp3', r.variables.args)
    .then((reply) => {
      r.return(reply.status, reply.responseBody)
    })
```

```
location /mp3 {
    proxy_pass http://new_api/test.mp3; 
}
```

from this [issue](https://github.com/nginx/njs/issues/44), I figured out that `subrequest_output_buffer_size` should larger than response body. Are there some side effects If I set a very large buffer_size such as `100M`? Is there a directive equivalent to `ngx.exec` in openresty?

**Comment by drsm** [comment]
@elixiao 

Hi!

> Is there a directive equivalent to `ngx.exec` in openresty?

No.

You may want to try `r.internalRedirect()`.

```nginx
js_import conf.d/test.js;

server {
    resolver 1.1.1.1;
    listen 10000;
    subrequest_output_buffer_size 200M;

    location /test1 {
        js_content test.test1;
    }

    location /test2 {
        js_content test.test2;
    }

    location /last {
        return 200 "last: $args\n";
        #root /tmp;
    }

    location /pass {
        proxy_pass http://127.0.0.1:10000/last$is_args$args;
    }
}
```
```js
function test1(r) {
    r.internalRedirect(`/pass${r.variables.is_args + r.variables.args}`);
}

function test2(r) {
    r.subrequest('/pass', r.variables.args)
    .then((reply) => {
        r.return(reply.status, reply.responseBody);
    });
}

export default { test1, test2 };
```

```shell
$ siege 'http://localhost:10000/last?a&a&a&a&' -t5s -c 10    
Transaction rate:           16082.23 trans/sec
Throughput:                     0.23 MB/sec

$ siege 'http://localhost:10000/test1?a&a&a&a&' -t5s -c 10    
Transaction rate:           11224.36 trans/sec
Throughput:                     0.16 MB/sec
 
$ siege 'http://localhost:10000/test2?a&a&a&a&' -t5s -c 10
Transaction rate:           10786.29 trans/sec
Throughput:                     0.15 MB/sec
 
$ siege 'http://localhost:10000/pass?a&a&a&a&' -t5s -c 10
Transaction rate:           11539.47 trans/sec
Throughput:                     0.17 MB/sec
```

**Comment by elixiao** [comment]
Thanks @drsm . Is `subrequest_output_buffer_size 200M;` harmless for production?

**Comment by xeioex** [comment]
@elixiao 

> Is subrequest_output_buffer_size 200M; harmless for production?

It depends. If you control the njs location (protection, limit_req) which would make a subrequest to a location which may return very large files, than it is somewhat safe. But, I would call it a brittle configuration (It works, until someday it does not). For example, you may easily hit some system limits (memory, cpu etc) after changing the hardware/VM instance or when traffic increases to a certain point.

Please elaborate, why do you need such a large limit?

**Comment by elixiao** [comment]
Thanks @xeioex . Maybe njs is not suitable for my case: 

I have a node.js application behind nginx which redirect (301) request url (`http://xxx/resources/5f8d4e618d83310008d48493`)  to another static location `http://xxx/upload/LGJF/206/GE5wE.jpg` which also served by nginx. I want to handle redirect (301) using njs like this:

njs.js

```js
var querystring = require('querystring')

function catchRedirect(r) {
    r.subrequest(r.uri.replace(/^\//, '/_'), r.variables.args)
        .then((reply) => {
            if (![301, 302].includes(reply.status)) return r.return(reply.status, reply.responseBody)
            r.subrequest(reply.headersOut.location).then((res) => r.return(res.status, res.responseBody))
        })
        .catch((_) => r.return(500))
}

export default {catchRedirect}
```

nginx.conf

```nginx
js_import njs.js;
server {
    location  ~ ^/resources {
        js_content njs.catchRedirect;
    }
    location /_resources {
        proxy_pass http://nodejs-backend/resources;
    }
    location /upload {
        proxy_pass http://static-server;
    }
}
```

It works fine if `r.subrequest(reply.headersOut.location)` return small files, but failed on large files.

**Comment by xeioex** [comment]
@elixiao 

>I want to handle redirect (301) using njs like this

`r.subrequest()` is not designed to be used for proxying, if possible it should be avoided. `r.subrequest()` should be used when you want to process the body of the reply in njs.

if you want to change the redirect location, you may use [proxy_redirect](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect). proxy_redirect supports variables, and njs can be used to do arbitrary replacements.

**Comment by elixiao** [comment]
OK, thanks very much for your patient explanation. Writing JavaScript in nginx is really attractive to me because I'm not familiar with nginx and c. Anyway I will try to learn proxy_redirect.
