### ISSUE TITLE
Function.name is broken – doesn’s return name of the function

### ISSUE THREAD

**Issue by jirutka** [nginx/njs#360]
```js
>> function foo () {}
>> foo.name
''  // should be: 'foo'
```

```js
>> var foo = function () {}
>> foo.name
''  // should be: 'foo'
```

```js
>> var foo = () => {}
>> foo.name
''  // should be: 'foo'
```

```js
>> (function () {}).name
''  // this is correct
```

```js
>> (() => {}).name
''  // this is correct
```

**Reference:**

* [Function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)

**Environment:**

* njs 0.4.4 (cli)
* Alpine Linux

**Comment by drsm** [comment]
Also affected:
```js
> var o = { [Symbol.iterator]: () => {}, method: () => {}, ['Yeah' + '!!!']() {} }; [o[Symbol.iterator].name, o.method.name, o['Yeah!!!'].name];
[ '[Symbol.iterator]', 'method', 'Yeah!!!' ]
```
Maybe it's worth to add a third arg to `FUNCTION` vmcode, which points to a string.

**Comment by xeioex** [comment]
@drsm  fixed all the cases, including ComputedPropertyName. Also the committed patch avoids runtime overhead when "name" is not used in most cases.
