### ISSUE TITLE
can njs take javascript parameters?

### ISSUE THREAD

**Issue by aspetonline** [nginx/njs#361]
I want to be able to transfer the status and city information that I detected with geoip2 in the nginx conf file in the Javascript file.
Example:
nginxconf
geoip2 /usr/share/GeoIP/GeoIP2-City.mmdb {
                $geoip2_data_city_name default=none subdivisions 0 names en;
                $geoip2_data_country_iso_code default=none country iso_code;
}
...
js_include example.js;
js_set $decodedArgs xxx;

example.js
function xxx(r,???){

}

**Comment by drsm** [comment]
```js
function xxx(r){
    return r.variables['geoip2_data_country_iso_code'] + ' ' + r.variables['geoip2_data_city_name'] 
}
```

**Comment by aspetonline** [comment]
thank you very much.
I've been trying to do this for days. :)
