### ISSUE TITLE
Reading subject alternative from user certificate using njs

### ISSUE THREAD

**Issue by stackoverflowe** [nginx/njs#364]
I want to read Subject Alternative Name from user certificate. Unfortunately this information is not available as Embedded variable. I now want to use NJS module to read this information. Using NJS module, I want to parse $ssl_client_escaped_cert into a X509 certificate and then read the Subject Alternative Name. I am pretty new to this world and have no clue how this will work. Any help would be appreciated.

If this works, I want to understand will this function (read Subject Alternative Name) will be executed just once per user session or for every request, this function will be executed.

**Comment by xeioex** [comment]
Hi @stackoverflowe,

Feel free to use the following library https://gist.github.com/xeioex/029228eec638d1362479250f1b57252f

nginx.conf
```
   js_import main.js;
   js_set $san main.san;
   
   # use $san variable where it is needed
```

main.js
```js

import x509 from './x509_parse.js';

function san(r) {
    var json_cert, alt_names;
    json_cert = x509.parse_pem_cert(r.variables.ssl_client_escaped_cert);
    // subjectAltName oid 2.5.29.17
    alt_names = x509.get_oid_value(json_cert, "2.5.29.17");
    return JSON.stringify(alt_names));
}

export default {san};
```

**Comment by stackoverflowe** [comment]
Thank you for quick reply. I really appreciate your help. I have few questions:
1) How can we debug this code (adding breakpoints to debug and writing data on console)? 
2) In terms of performance, is this a costly operation?

**Comment by xeioex** [comment]
@stackoverflowe 

> If this works, I want to understand will this function (read Subject Alternative Name) will be executed just once per user session or for every request, this function will be executed.

It will be executed at the first reference to $san variable (the result is cached) per HTTP request.

> How can we debug this code (adding breakpoints to debug and writing data on console)?

`r.error(<msg>)`, `ngx.log(ngx.ERR, <msg>)`

>In terms of performance, is this a costly operation?

I do not have exact numbers, but I expect it to be fast enough for most use cases (<= ~1k req/sec, at least).

**Comment by fblr** [comment]
Please let us know if this module works for you. Thank you!

**Comment by stackoverflowe** [comment]
@fblr @xeioex I am getting **nginx: [emerg] unknown "a" variable** error.

**Comment by stackoverflowe** [comment]
it worked. Only change I made was to add this function `decodeURIComponent();`

` json_cert = x509.parse_pem_cert(decodeURIComponent(r.variables.ssl_client_escaped_cert));`

**Comment by stackoverflowe** [comment]
@xeioex :I am using proxy_pass to make calls to backend server. It looks like, this function san() is being called every time a request is made to backend server. Can we limit it just once per session?

**Comment by xeioex** [comment]
@stackoverflowe
