### ISSUE TITLE
Ability to declare request state variables in JS

### ISSUE THREAD

**Issue by devgs** [nginx/njs#369]
It would be hard to overestimate an ability to **declare** variables in JS. I know that it's not supported, currently, for performance reasons, but hear me out.

Currently you have to declare them first in `nginx.conf`. But where would you do that? The obvious solution is to declare them in `http` section. After all, these are the variables that going to be used in multiple locations, by different JS handlers. Even shared, if one handler passes execution to another, via `internalRedirect()`.

And the obvious solution would be totally wrong! That's because each sub-request, issued from JS handler, would immediately overwrite all declared variables with values as they were in these declarations. This is, probably, because of how sub-requests are handled? Each sub-request executes all of the commands in the server section, **including `set` commands that declare these variables**, using *variable context* of the **original** request. That's truly unfortunate, because you're losing their values in the middle of execution of a single handler, if said handler does sub-requests!

So, back to the original topic. Oh, how good would it be to have an ability to have a reliable, robust storage of per-request data, no matter how many sub-requests or internal redirects are made. Even if this object would be only accessible by JS and not from config. That would be priceless.

**Comment by xeioex** [comment]
Hi @devgs,

We are considering adding js variable declaration directive. 

in the meantime, as a workaround consider using map variables for this.

```
map _ $my_var {
    default       0;
}
```

later you may write to $my_var from njs. It will not be overridden after a redirect.

**Comment by devgs** [comment]
@xeioex Thanks a lot for the info and suggestion regarding map! Gonna check it out.

**Comment by devgs** [comment]
@xeioex 

Your suggestion is a much better option that what I had. But there's the catch. It isn't enough to simply declare the map (variable), you must also reference it, otherwise it still isn't writable: `js exception: Error: variable is not writable`. Probably that's an optimization inside nginx: elimination of variables that aren't referenced?

The final solution looks like this:

```
# Declare variables
map _ $my_var_1 { default ''; }
map _ $my_var_2 { default ''; }
map _ $my_var_3 { default ''; }

# Explicitly reference them, to make them writable from JS
map _ $declare_my_variables {
    default 0;
    1 $my_var_1;
    2 $my_var_2;
    3 $my_var_3;
}
```

**Comment by xeioex** [comment]
@devgs 

>Probably that's an optimization inside nginx: elimination of variables that aren't referenced?

Yes, you are right. Njs is able to write to so called index variables. To make a variable indexed, it has to be referenced in nginx.conf

**Comment by devgs** [comment]
@xeioex Thanks for the info and the solution.

**Comment by sah4ez** [comment]
@devgs  @xeioex very interesting discussion. Could you help, how I can write to variables from nginx.conf from njs?

**Comment by xeioex** [comment]
@devgs  [js_var directive](https://github.com/nginx/njs/commit/a01c10ff1cf02e4d60e12f7dacd99da655a3a68e) just landed to the repo. We plan to release it on March 30 with 0.5.3.

**Comment by xeioex** [comment]
@sah4ez 
The current solution for njs <= 0.5.2 is described [above](https://github.com/nginx/njs/issues/369#issuecomment-772820005). Since 0.5.3 js_var directive can be used to declare an nginx variable writable from njs.

**Comment by devgs** [comment]
@xeioex Wow, thanks a lot for this quick delivery! I was expecting it much later :)

This definitely closes this ticket.
