### ISSUE TITLE
Getting upstream variable of a subrequest ($upstream_cache_status)

### ISSUE THREAD

**Issue by devgs** [nginx/njs#370]
Consider this case: there's a subrequest location that uses `proxy` module to issue it to some other service. Response to this request has to be cached. To be able to determine caching status from JS, I decided to set custom header field using variable `$upstream_cache_status`. Unfortunately, I find myself unable to set **any** header field at all. At least, it's not visible to JS.

Here's the example:

```
        location = /_subrequest/my_subrequest {
            internal;
            proxy_cache myzone;
            proxy_cache_key "$request_body";
            proxy_cache_methods POST;
            proxy_cache_valid 200 5s;
            add_header X-Cache-Status $upstream_cache_status always;
            add_header X-Always 11111 always;

            proxy_pass_request_headers off;
            proxy_set_header Host $host;
            proxy_set_header Protocol $http_protocol;

            rewrite .* /my_subrequest break;

            proxy_pass http://my_service;
        }
```

In JS:

```js
    var self = this;

    this.request.subrequest(
        '/_subrequest/my_subrequest'
        , {
            method: 'POST',
            body: 'foo',
        }
        , function(response) {
            for (var h in response.headersOut) {
                self.request.log(`Response header field: ${h}='${response.headersOut[h]}'`);
            }
        }
    );
```

The only headers I can see are the ones that were sent in response from `my_service`. None of the headers set by `add_header` present.

Is this a bug? Is there a way to work this around?

**Comment by xeioex** [comment]
@devgs 

>Unfortunately, I find myself unable to set any header field at all. 

Yes, for some reason, header filter is[ not applied](https://github.com/nginx/nginx/blame/master/src/http/modules/ngx_http_headers_filter_module.c#L173) for a subrequest.

**Comment by xeioex** [comment]
@devgs  to reference upstream_cache_status of a subrequest use `$upstream_cache_status`.


```js

 var self = this;

 this.request.subrequest(
    '/_subrequest/my_subrequest'
    , {
        method: 'POST',
        body: 'foo',
    }
).then(
    reply=>r.return(200, reply.variables.upstream_cache_status)
)
```

**Comment by devgs** [comment]
@xeioex Thanks a lot for suggestion!
