### ISSUE TITLE
Typo in JS code leads to nginx process to silently SEGFAULT

### ISSUE THREAD

**Issue by devgs** [nginx/njs#371]
This can be pretty hard to track down. Consider example.

`foo.js`

```js
function foo() {
}

// By accident, typo. 'bar' instead of 'foo'.
bar.prototype.othe_func = function() {
}

export default foo;
```

`bar.js`

```js
function bar() {
}

export default bar;
```

`qux.js`

```js
import foo from 'foo.js';
import bar from 'bar.js';

function qux(request) {
}

export default qux;
```

Somewhere in **nginx.conf**:

```
js_import /path/to/qux.js;
```

As the result, any location that uses `qux.js` as a handler, or simply includes it will cause a silent crash.

**Comment by xeioex** [comment]
@devgs 

It looks like it is related to https://github.com/nginx/njs/issues/300.  We plan to fix it, after a refactor which adds let variables support.
