### ISSUE TITLE
use array to get r.headersIn Duplicate header?

### ISSUE THREAD

**Issue by crasyangel** [nginx/njs#377]
use array to get r.headersIn Duplicate header

**Comment by xeioex** [comment]
Hi @crasyangel,

Can you please clarify with examples what is your problem?

**Comment by crasyangel** [comment]
> Hi @crasyangel,
> 
> Can you please clarify with examples what is your problem?

Array is a better struct than string combined with comma? I think it is clearer than string

**Comment by drsm** [comment]
@crasyangel 

> Array is a better struct than string combined with comma? I think it is clearer than string

yes, but:

https://tools.ietf.org/html/rfc7230#section-3.2.2
>    A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.  The order
   in which header fields with the same field name are received is
   therefore significant to the interpretation of the combined field
   value; a proxy MUST NOT change the order of these field values when
   forwarding a message.

**Comment by xeioex** [comment]
@crasyangel 

If you want an array, consider [r.rawHeadersIn](http://nginx.org/en/docs/njs/reference.html#r_raw_headers_in).

**Comment by crasyangel** [comment]
> @crasyangel
> 
> If you want an array, consider [r.rawHeadersIn](http://nginx.org/en/docs/njs/reference.html#r_raw_headers_in).

Thanks.
