### ISSUE TITLE
Would ngx.fetch() support https?

### ISSUE THREAD

**Issue by crasyangel** [nginx/njs#379]
limitations: only the http:// scheme is supported, redirects are not handled

redirects can be handled by user, but njs should support https itself

**Comment by xeioex** [comment]
Hi @crasyangel, 

ngx.fetch() is implemented mostly for the [stream](http://nginx.org/en/docs/stream/ngx_stream_js_module.html) module where there is no its own `r.subrequest()`.  At this moment there are no plans for https in ngx.fetch().

For http module you can use r.subrequest(), with it you can configure any backend nginx supports (proxy_pass, grpc_pass, ...). Proxy module supports https.
