### ISSUE TITLE
Arrow operator with array

### ISSUE THREAD

**Issue by pbthorste** [nginx/njs#380]
Hi - I am using njs 0.5.1.

When using this code:
```
var entries = {
  'key': 'value'
}
Object.entries(entries).filter(([k, v]) => k === 'key')
```
nginx doesn't start, and gives this error:
`nginx: [emerg] SyntaxError: Unexpected token "=>" in script.js`

but this works fine:
```
var entries = {
  'key': 'value'
}
Object.entries(entries).filter(item => item[0] === 'key')
```

**Comment by xeioex** [comment]
Hi @pbthorste,

[Destructuring syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#advanced_syntax) is not supported yet.

**Comment by pbthorste** [comment]
Thanks for the prompt answer @xeioex
