### ISSUE TITLE
Is there any C API made available?

### ISSUE THREAD

**Issue by ryanford-dev** [nginx/njs#381]
Is there any C API made available?

References:

[QuickJS C API](https://bellard.org/quickjs/quickjs.html#QuickJS-C-API)
[Duktape C API](https://duktape.org/api.html)
[Lua C API](https://www.lua.org/manual/5.4/manual.html#4)

**Comment by xeioex** [comment]
Hi @ryanford-dev ,

Unfortunately there is no the C API docs at this moment, but we plan to add it.

Luckily, public API is relatively [small](https://github.com/nginx/njs/blob/master/src/njs.h).

Some examples: [unit tests](https://github.com/nginx/njs/blob/master/src/test/njs_unit_test.c#L20647), [shell](https://github.com/nginx/njs/blob/master/src/njs_shell.c#L551).

**Comment by ryanford-dev** [comment]
Ok, so at least it's there, just un(der)documented. I'll check out the source, thanks!
