### ISSUE TITLE
Subrequests callback not being executed 

### ISSUE THREAD

**Issue by mahmoud-maher-kassem** [nginx/njs#382]
version used: 0.4.4

we are trying to build proxy service which uses tokens in the requests to validate with an external service via a subrequest

here are the the method used to call token-validation-service

```
export function authenticate(r: NginxHTTPRequest): Promise<AuthResponse> {
    try{
        const validationRequest: ValidateTokenRequest = buildValidateTokenRequestFromInputRequest(r);
        return r.subrequest('/validate-token', {
            method: "POST",
            body: JSON.stringify(validationRequest)})
            .then(subRequestResponse => {
                if (subRequestResponse.status == 200) {
                    r.log(`got success status when validating token with auth service`);
                        return {isAuthenticated: true, roles: validateTokenResponse.roles}
                } else {
                    r.warn(`got status '${subRequestResponse.status}' when validating token with auth service`);
                    return {isAuthenticated: false, roles: []};
                }
            }).catch(err => {
            r.error(`caught error '${err}' during authenticating with auth service'`)
            return {isAuthenticated: false, roles: []};
            });
    } catch (err) {
        r.error(`caught error '${err}' during authenticating with auth service'`)
        return Promise.resolve({isAuthenticated: false, roles: []});
    }
}

```

the previous method is being used from our main auth method this way

```
            return authService.authenticate(r)
                .then(authResponse => {
                    if (authResponse.isAuthenticated) {
                            r.log(`Calling API '${apiInfo!.name}' redirecting `);
                            r.internalRedirect(apiInfo!.redirect);
                    } else {
                        error.invalidSecurityToken(r);
                    }
                    return Promise.resolve();
                }).catch(error => {
                    r.error(`error while auth '${error}' `);
                    Promise.reject(error);
                });
```
                

we noticed that the promise call back isn't being executed at all, are we missing something here ?

**Comment by xeioex** [comment]
Hi @mahmoud-maher-kassem,

Looks like it is similar to https://github.com/nginx/njs/issues/359 and was fixed in 0.5.0

**Comment by xeioex** [comment]
Hi @mahmoud-maher-kassem,
I wonder whether upgrading to 0.5.2 fixed the issue.

**Comment by mahmoud-maher-kassem** [comment]
Thanks for your reply, Sorry I was on vacation,

I upgraded to latest version but I am getting a new error

`exception: Error: internalRedirect cannot be called from a subrequest`

**Comment by xeioex** [comment]
Hi @mahmoud-maher-kassem,

Feel free to reopen the issue if you have JS code for me to reproduce.

**Comment by mahmoud-maher-kassem** [comment]
`     r.subrequest('/validate', {
            method: "POST",
            body: JSON.stringify(validationRequest)
        }).then(
            c => {
                if (c.status == 200) {
                        r.internalRedirect(apiInfo!.redirect);
                } else {
                                        r.internalRedirect(apiInfo!.redirect);
                           }})`

**Comment by mahmoud-maher-kassem** [comment]
Sometimes I even get 500 before it even calls the backend service

**Comment by mahmoud-maher-kassem** [comment]
The following code returns 500 without even reaching the backend


```

   return r.subrequest('/validate-sigv4-request', {
        method: "POST",
        body: JSON.stringify(validationRequest)
    }).then((c: NginxHTTPRequest) => {
        if (c.status == 200) {
                r.internalRedirect(apiInfo!.redirect);
            } else {
              r.error(`received status code '${c.status}' and message '${c.responseBody}' when calling auth service`)
              error.invalidSecurityToken(r);
            }
    }).catch(err => {
        r.error(`Error when doing subrequest '${err}'`)
        error.invalidSecurityToken(r);
    });
    
```

**Comment by xeioex** [comment]
Thanks @mahmoud-maher-kassem,

I will take a look.

**Comment by mahmoud-maher-kassem** [comment]
@xeioex 

I found the issue,

The issue was basically that the sub-request route was trying to internal-rediret which was causing the 500 "internalRedirect cannot be called from a subrequest" so the solution I added the following to nginx.conf

        location ~ /validate-sigv4-request {
            proxy_pass http://127.0.0.1:8084/validate/$1;
        }
