### ISSUE TITLE
Add global filtering directive

### ISSUE THREAD

**Issue by vallahaye** [nginx/njs#387]
Hello, I've been recently making use of NJS's body filter feature to clear out some fields of an entity returned by my API server. Here is the configuration:

```nginx
location /api/v1/users {
  limit_except GET {
    deny all;
  }
  js_header_filter api.clearContentLength;
  js_body_filter api.clearSecretUserInfos;
  proxy_pass http://apiserver/v1/users;
}
```

```js
export default { clearContentLength, clearSecretUserInfos };

function clearContentLength(r) {
  if (r.status !== 200) {
    return
  }
  delete r.headersOut['Content-Length'];
}

var res = '';
function clearSecretUserInfos(r, data, opts) {
  if (r.status !== 200) {
    r.sendBuffer(data, opts);
    r.done();
    return
  }
  res += data;
  if (opts.last) {
    var user = JSON.parse(res);
    delete user.streamKey;
    delete user.twitchUserId;
    delete user.twitchUserEmail;
    data = JSON.stringify(user);
    r.sendBuffer(data, opts);
  }
}
```

Everything is working as it should thought, having to implement two filters, one for the headers and one for the body seems a bit heavy to me. Wouldn't it be possible to add a new filtering directive `js_filter` merging the two ?
Then the same configuration could be rewritten like this:

```nginx
location /api/v1/users {
  limit_except GET {
    deny all;
  }
  js_filter api.clearSecretUserInfos;
  proxy_pass http://apiserver/v1/users;
}
```

```js
export default { clearSecretUserInfos };

var res = '';
function clearSecretUserInfos(r, data, opts) {
  if (r.status !== 200) {
    r.sendBuffer(data, opts);
    r.done();
    return
  }
  res += data;
  if (opts.last) {
    var user = JSON.parse(res);
    delete user.streamKey;
    delete user.twitchUserId;
    delete user.twitchUserEmail;
    data = JSON.stringify(res);
    // Here we can clear out the Content-Length header
    delete r.headersOut['Content-Length']
    // or update its value since we have access to the new response body size
    r.headersOut['Content-Length'] = data.length.toString();
    r.sendBuffer(data, opts);
  }
}
```

For me this new configuration is more concise and easier to comprehend but I don't know how hard it is implement within the current code base. I'd like to have your opinion on this.

**Comment by xeioex** [comment]
>but I don't know how hard it is implement within the current code base. I'd like to have your opinion on this.

It is doable, but at this point, I don't think it worth trying given the fact that sometimes only `js_header_filter` is needed.

Nginx provides a [limited API](http://nginx.org/en/docs/dev/development_guide.html#http_body_filters) for modules.

`js_header_filter` corresponds to a header filter, a module is expected to modify headers and call a next filter in chain, in the end result the complete HTTP header is sent to a client. So, at this point we have to know all our headers, and it will not be possible to postpone this decision until the the first body chunk.
