### ISSUE TITLE
Change status code or header based on body content

### ISSUE THREAD

**Issue by zahcen** [nginx/njs#389]
Hello,

I’m using NJS for the first time.
I want to change the response status code based on text criteria found in the response body but I can’t figure out.
I also want to add a header if the test is found but the r.headerOut seems to work only within the cookie filter. 
How to check the content in the cookies_filter method ? The r.responseText returns undefined 

Here is my code:
`
location = "/LB_CHECK_MAF.txt" {
proxy_pass  http://backendMAF;
      js_body_filter http.filter;
          js_header_filter http.cookies_filter; 
}

function filter(r, data, flags) {
          var n = data.indexOf(‘ERROR’);
          if (n != -1) {
                    r.error('Found ERROR');
           }
    // Does not work
    r.status = 500;
    r.headersOut.ERROR = YES;

    r.sendBuffer(data, flags);
}

function cookies_filter(r) {
r.error('cookies_filter ' + 'responseBuffer='+  r.responseBuffer + ' requestText='+r.requestText);       
r.headersOut.ERROR = YES;
}

`
Logs:

2021/05/20 11:11:58 [error] 13389#13389: *10618 js: cookies_filter responseBuffer=undefined requestText=undefined

Regards,

**Comment by xeioex** [comment]
Hi @zahcen 

>I want to change the response status code based on text criteria found in the response body but I can’t figure out.

nginx works in stages, for responses it [calls](http://nginx.org/en/docs/dev/development_guide.html#http_response) all of the headers filters, send the response header, and *only* after it reads the response body and calls the body filters. Therefore, in nginx, it is not possible to change the status code depending on the response body content using filters.

It is possible though to use [subrequests](http://nginx.org/en/docs/njs/reference.html#r_subrequest) to do that.
But still, before doing that think twice whether it is really the only way (usually it is not).

**Comment by s3rj1k** [comment]
@xeioex 
> It is possible though to use [subrequests](http://nginx.org/en/docs/njs/reference.html#r_subrequest) to do that.

But documentation states that for `js_body_filter` and `js_header_filter` there is no possibility to use `r_subrequest` due to it being asynchronous and `js_*_filter` being synchronous, please clarify.

**Comment by Nikoolayy1** [comment]
> [@xeioex](https://github.com/xeioex)
> 
> > It is possible though to use [subrequests](http://nginx.org/en/docs/njs/reference.html#r_subrequest) to do that.
> 
> But documentation states that for `js_body_filter` and `js_header_filter` there is no possibility to use `r_subrequest` due to it being asynchronous and `js_*_filter` being synchronous, please clarify.

If you are using subrequests you will use js_content to trigger the subrequest and then use the filter but why use filters when you can give different response with specific headers and body not only response code.
