### ISSUE TITLE
add native Promise objects

### ISSUE THREAD

**Issue by drsm** [nginx/njs#39]
spec: https://www.ecma-international.org/ecma-262/6.0/#sec-promise-objects
reference implementation: https://github.com/domenic/promises-unwrapping/blob/master/reference-implementation/lib/testable-implementation.js

**Comment by lexborisov** [comment]
Hi @drsm 

Please, try [the patch](https://gist.github.com/7ea0b5f21001d721c2e1536c4ee2b19f) (without all, allSettled, race).

**Comment by drsm** [comment]
@lexborisov 

Hi!

Wow, `async/await` is near :) !

Will do.

**Comment by drsm** [comment]
@lexborisov 
@xeioex 

So, looks like the main functionality is OK!

But I found some issues:
1. `ReferenceError` problem.
2. Subclassing a `Promise` doesn't work as expected.

[reference source](https://gist.github.com/drsm/56f9ddd7b9728ee21493697f2c14ef07)

I think that subclassing a `Promise` is a same weirdness as defining an integer indexes on `Array.prototype`.
So, all this dances around constructors should be put on slow path.

**Comment by xeioex** [comment]
@drsm 

> ReferenceError problem.

BTW, can you find in the spec the way to handle ReferenceError exceptions?

**Comment by lexborisov** [comment]
@drsm 

[Final version](https://gist.github.com/76ce1e6722323efd1cbc574efab6faaf).

For `ReferenceError` we need to create a separate issue. This is not a problem of promises, but events in general.

**Comment by drsm** [comment]
@lexborisov 

`Zango.resolve('test')`, `Zango.reject('test')` are failing [here](https://gist.github.com/lexborisov/76ce1e6722323efd1cbc574efab6faaf#file-great_promise-patch-L2050) because of wrong `this` which equals to `Zango` instead of a new `Zango` instance.

And all that instances will be discarded by the constructor function which returns a modified `Promise` overriding default result.

[[[Call]]](https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist) and [[[Construct]]](https://tc39.es/ecma262/#sec-ecmascript-function-objects-construct-argumentslist-newtarget) are different, and the latter allocates a new object for `this`.

**Comment by drsm** [comment]
I didn't get what is [`obj`?](https://gist.github.com/lexborisov/76ce1e6722323efd1cbc574efab6faaf#file-great_promise-patch-L441)

Below is generic version of `NewPromiseCapability`.
I didn't dig further, but it seems that the fast path case `C == Promise` can be optimized.
Anyway, it should `Construct` at step 7. 

```js
function IsConstuctor(C) {
    // Simplified version
    return typeof C == 'function';
}

function IsCallable(C) {
    return typeof C == 'function';
}


function New_Promise_Capability_Generic(C) {
    // 25.6.1.5 NewPromiseCapability ( C )
    // 1.
    if (!IsConstructor(C)) {
        throw new TypeError('IsConstructor(C) is false')
    }

    // 3.
    var promiseCapability = { 
        Promise: undefined,  
        Resolve: undefined,
        Reject: undefined  
    };  
    // 4. - 6. promiseCapability -> [[Capability]]
    var GetCapabilitiesExecutor = function(resolve, reject) {
        // 25.6.1.5.1 GetCapabilitiesExecutor
        // 1. - 3.
        // ..
        // 4. - 5.
        if (promiseCapability.Resolve !== undefined && promiseCapability.Reject !== undefiend) {
            throw new TypeError('throw a TypeError exception');
        }  
        promiseCapability.Resolve = resolve;
        promiseCapability.Reject = reject;
    };
    // 7. Construct(C, « executor »).  
    var promise = new C(GetCapabilitiesExecutor);
    // 8. - 9.
    if (!IsCallable(promiseCapability.Resolve) || promiseCapability.Reject) {
        throw new TypeError('IsCallable(C) is false')
    }
    // 10.
    promiseCapability.promise = promise;
    // 11.
    return promiseCapability;
```

**Comment by drsm** [comment]
IMO, in addition to `njs_function_call2` we need `njs_function_construct` which covers this cases:
```js
var instances = [],
    results = [];

function One() {
    // this = OrdinaryCreateFromConstructor(One)
    // https://tc39.es/ecma262/#sec-ordinarycreatefromconstructor
    this.x = 1;
    instances.push(this);
}
 
results.push(new One());

function Two() {
    this.x = 1; 
    instances.push(this);
    return { x: 2 };
}
 
results.push(new Two());

function Three() {
    this.x = 1;
    instances.push(this);

    // All our native constructors are in this form:
    return Object.setPrototypeOf({ x: 3 }, Three.prototype);
    // So, there is no need to allocate an object for `this`
}
 
results.push(new Three());

console.log(instances, results);
```

**Comment by lexborisov** [comment]
@drsm 

Thanks for the examples! The problem has become more clear.

**Comment by lexborisov** [comment]
@drsm 

[Updated patch](https://gist.github.com/087962d930332750f2fe66bf152f87fa).

**Comment by drsm** [comment]
@lexborisov 

Looks fine, thanks!

updated [subclass test](https://gist.github.com/drsm/56f9ddd7b9728ee21493697f2c14ef07)
