### ISSUE TITLE
Support request headers filter? 

### ISSUE THREAD

**Issue by fishioon** [nginx/njs#391]
Njs js_headers_filter only response headers filter.
We can use proxy_set_header for change request headers. But sometimes not work friendly.
Any ideas support js_request_headers_filter for change r.headersIn?

**Comment by xeioex** [comment]
@fishioon 

>We can use proxy_set_header for change request headers. But sometimes not work friendly.

please, clarify what is your problem with `proxy_set_header`?

**Comment by xeioex** [comment]
@fishioon 

> Any ideas support js_request_headers_filter for change r.headersIn?

In nginx, we consider changing the r.headersIn as a bad practice (may cause hard to debug issues). Instead, `proxy_set_header` is expected to be used, which creates completely new set of headers.

**Comment by fishioon** [comment]
In my case，if headers contain A， will set x header；if headers contain B，will set y header.

**Comment by lcrilly** [comment]
In this case:

```
proxy_set_header x-header $value_when_a;
proxy_set_header y-header $value_when_b;
```

From the docs: nginx.org/r/proxy_set_header

> If the value of a header field is an empty string then this field will not be passed to a proxied server:

Therefore, you can specify multiple proxy_set_header directives and use variables to control what gets sent to the backend. `js_set` or `map` are both good approaches for this.

**Comment by fishioon** [comment]
> @fishioon
> 
> > Any ideas support js_request_headers_filter for change r.headersIn?
> 
> In nginx, we consider changing the r.headersIn as a bad practice (may cause hard to debug issues). Instead, `proxy_set_header` is expected to be used, which creates completely new set of headers.

Understand your concerns. if filter can change r.headersIn, more power.

Like this case, set headers A(timestamp=Date.now),B(nonce),C(userid), D(username) and set header E =  sha256(A+B+C+D+A)
I need export 5 vars in js file and 5 js_set in conf file.
