### ISSUE TITLE
Is there a way to add global  incremental variable to log file?

### ISSUE THREAD

**Issue by calvin2021y** [nginx/njs#398]
I want to add a global incremental variable for each item, is this already exists in nginx or I can do it with njs?

**Comment by xeioex** [comment]
@calvin2021y 

>I want to add a global incremental variable for each item, is this already exists in nginx or I can do it with njs?

It depends on what do you mean by global. 

Global per a request runtime, global per process, global per nginx instance?

What do you mean by "item"?

It is also better to describe the problem you are trying to solve with njs.

**Comment by calvin2021y** [comment]
> Global per a request runtime, global per nginx worker, global per nginx instance?

Global for all nginx instance, if this is not able to done then each nginx instance with pid .

> What do you mean by "item"?

a log entry for a request

**Comment by lcrilly** [comment]
Logging the value of `$server_addr-$connection-$connection_requests` may be what you are looking for

See:
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_connection
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_connection_requests
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_addr
