### ISSUE TITLE
proxying request after executing subrequest

### ISSUE THREAD

**Issue by sly-roar** [nginx/njs#403]
Hello,
At first I would like to say thank you for the module. It is really full of opportunities and extends functional of Nginx.
Despite on reach features of the module I have faced with several issues implementing the idea of using Nginx as an API Gateway. 

Here is the workflow that I try to implement:
1. Nginx accepts a request and checks presence of a certain header or specific key in JSON body.
2. If the requirements above are met, headers `X-ORIGIN-URI` and `X-ORIGIN-METHOD` are added to the request.
3. Next the request with added headers and original JSON body should be sent to 3rd party service with the help of `r.subrequest`.
4. The response from the service should be processed and, based on keys and values in JSON body of the response, there should be added yet another two headers and be done a selection of final endpoint for proxying the original request with headers added during the previous stages.

All stages work separately, but when I attempt to combine them into a final solution I face with the following restrictions:
1. `js_set` does not allow execution of `r.subrequests`
2. `js_content` cannot be used together with `proxy_pass`
3. `auth_request` does not allow to process `request_body` because discards it

Could you please advise me what I should pay attention to for getting a working solution?
Thank you in advance.

**Comment by lcrilly** [comment]
This blog describes how you can use `auth_request` with a `js_content` location that uses `r.subrequest` to parse a JSON body. You should be able to adapt it for your use case.

https://www.nginx.com/blog/validating-oauth-2-0-access-tokens-nginx/

**Comment by xeioex** [comment]
Hi @sly-roar,

Take a look at the following [example](https://github.com/xeioex/njs-examples#authorizing-requests-based-on-request-body-content-http-authorization-request-body).

1) in js_content request_body and r.subrequest (or even [ngx.fetch()](http://nginx.org/en/docs/njs/reference.html#ngx_fetch))
are available

2) `r.internalRedirect()` is used to get to another (protected) location where you can put ordrinary `proxy_pass`.

**Comment by sly-roar** [comment]
> This blog describes how you can use `auth_request` with a `js_content` location that uses `r.subrequest` to parse a JSON body. You should be able to adapt it for your use case.
> 
> https://www.nginx.com/blog/validating-oauth-2-0-access-tokens-nginx/

@lcrilly Thank you! This article will be very helpful when I start processing response from 3rd party service.

**Comment by sly-roar** [comment]
> Hi @sly-roar,
> 
> Take a look at the following [example](https://github.com/xeioex/njs-examples#authorizing-requests-based-on-request-body-content-http-authorization-request-body).
> 
>     1. in js_content request_body and r.subrequest (or even [ngx.fetch()](http://nginx.org/en/docs/njs/reference.html#ngx_fetch))
>        are available
> 
>     2. `r.internalRedirect()` is used to get to another (protected) location where you can put ordrinary `proxy_pass`.

@xeioex I appreciate for your response and pointing to the example!

Could you please clarify also yet another question?
In the description of `r.subrequest` is said that we must pass URI to the object. Should the URI be a string referencing to some location Nginx configuration, for instance `/3rd-party` or a named one like `@3rd-party`, or it could be an entire URI for the 3rd party service containing scheme, domain, path and etc?

**Comment by xeioex** [comment]
@sly-roar 

`uri` in r.subrequest() is an nginx location URI. (`@named_location` are not supported here).
`r.subrequest()` makes internal request to an nginx location (so scheme, domain etc. are not suppoted here).
This scheme is very flexible, because in the the subrequest location any nginx directives are supported (proxy_pass, grpc_pass, caching).

There is also `ngx.fetch()` which is generic basic HTTP client. But because it is self-contained it is very limited (no HTTPS/TLS support, no caching etc). ngx.fetch() in the first place is for [stream](https://nginx.org/en/docs/stream/ngx_stream_js_module.html) module, which does not have its own r.subrequest() counterpart.

**Comment by sly-roar** [comment]
@xeioex 
Got it! Thank you for the explanation!

If I understand properly, in my case I should define a location with proxying an incoming request to 3rd party API and use it in `r.subrequest`. 

Something like this:
```
js_var $origin_uri main.origin_uri;
js_var $origin_method main.origin_method;

location = /3rd-party {
    internal;
    resolver 8.8.8.8;
    proxy_set_header X-ORIGIN-URI $origin_uri;
    proxy_set_header X-ORIGIN-METHOD $origin_method;
    proxy_pass_request_body on;
    proxy_pass_request_headers on;
    proxy_set_header content-type "application/json";
    proxy_pass $customer_separator$is_args$args;
  }
```
and invoke `r.subrequest`:
```
function origin_uri(r) {
  return r.uri;
}

function origin_method(r) {
  return r.method;
}

function done(res) {
  return res.responseText;
}
r.subrequest('/3rd-party', r.variables.args, done);
```

However, in the case above the header `X-ORIGIN-URI` will contain the URI `/3rd-party` instead of original URI because of invoking location during the generation of subrequest. May I put original URI somehow as a value of variable $origin_uri? Is there some object that is persistent between parent and child requests?

**Comment by drsm** [comment]
@sly-roar
Hi!
Take a look: https://github.com/nginx/njs/issues/394#issuecomment-854703984

**Comment by sly-roar** [comment]
@xeioex @drsm 

Sorry for the late reply.

I would like to say you all a big thank for your answers and links to examples! 
They are really useful and have helped me a lot in implementing the desired.

The module is definitely great and I can't help but notice that you are doing an awesome job!
