### ISSUE TITLE
How to get ssl_preread_server_name in js_preread?

### ISSUE THREAD

**Issue by sungy2014** [nginx/njs#404]
I encountered a problem when use ssl_preread on and js_preread together,
they can not both be there, so how can i get   
ssl preread server name in js_preread scripts?

**Comment by xeioex** [comment]
@sungy2014 

It seems, you are right.

[ngx_stream_core_preread_phase](https://github.com/nginx/nginx/blob/master/src/stream/ngx_stream_core_module.c#L203) ignores next preread handler if the first one returns NGX_OK.

It seems, the only way is to parse ClientHello in JS. It should be relatively straightforward, [given](https://stackoverflow.com/questions/17832592/extract-server-name-indication-sni-from-tls-client-hello) its format.

**Comment by sungy2014** [comment]
@xeioex thanks,
Actually i have a scenario,

One application calls another application by https,
Flow is app1 -> proxy1 -> proxy2 -app2,
these two proxy are all layer4 stream proxy.

Now,  i want the proxy1 listen on port 10000,
proxy2 listen on 443, app2 listen on 10000.

app2's domain dns is hijacked to proxy1 ip,

so the flow becomes
app1(call 10000) > proxy1(call 443)> proxy2(call 10000) > app2( port 1000).

My question is how can proxy2 get the 10000 port variable from the app1?

I don't want to put the hardcode port number(10000) in proxy2 conf.

**Comment by xeioex** [comment]
Hi @sungy2014,

What you are looking for is very similar to [proxy_protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

**Comment by sungy2014** [comment]
> Hi @sungy2014,
> 
> What you are looking for is very similar to [proxy_protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).
> 
> 

But I have another kind of load balancer (cloud lb) set at the front of these two proxy( which do not support proxy protocol)

But anyway, thanks for your info, let me dig out more.

**Comment by jo-carter** [comment]
If anyone else stumbles upon this; use s.decline() in js_preread handler function, and it will move onto the next handler (such as ssl_preread).
