### ISSUE TITLE
Report document misinformation about fs

### ISSUE THREAD

**Issue by hyeonisism** [nginx/njs#405]
If I use as+ flag to run appendFileSync, it turns out there is none.

[njs doc](https://nginx.org/en/docs/njs/reference.html#njs_api_fs_flags)

The flag is seen here.

https://github.com/nginx/njs/blob/ce158c6ab0a645e0720dba84276f9b7d8ece699c/src/njs_fs.c#L108-L128

But when I checked the code, as, as+ did not exist in the flag table.
I think either the document or the code is wrong.

I would appreciate it if you could check and let me know.

**Comment by xeioex** [comment]
Hi @hyeonisism,

Thanks for reporting the issue. It looks like a bug in the code (not documentation). will be fixed.

**Comment by hyeonisism** [comment]
@xeioex Thank you for your reply, it seems simple, can I contribute when I have time?

**Comment by xeioex** [comment]
> @xeioex Thank you for your reply, it seems simple, can I contribute when I have time?

Sure
