### ISSUE TITLE
fs.appendFileSync does not save to disk

### ISSUE THREAD

**Issue by partok** [nginx/njs#407]
I just tested https://github.com/xeioex/njs-examples#file-io-misc-file-io with nginx 1.20.1 and njs 0.6.2 compiled from http://hg.nginx.org/njs (on Fedora).

Everything works fine (I can push data and read that same data) but no file is saved to disk.
And if I restart nginx, and try to read the previously pushed data, I get nothing.

I also tried with the "as" flag, but had no success.
         
Is there any way to "fsync" the fd?

**Comment by drsm** [comment]
@partok 

> Is there any way to "fsync" the fd?

`fs.appendFileSync` closes the fd on each call:
https://github.com/nginx/njs/blob/7c1caf6b2f6c6a5870d86c9b1ec7704585b4276b/src/njs_fs.c#L429

Are you running inside docker?

**Comment by partok** [comment]
@drsm I run nginx without docker.

It's a bit too low-level for me but, in the man close notes, I can see:
`A successful close does not guarantee that the data has been successfully saved to disk, as the kernel uses the buffer cache to defer writes.  Typically, filesystems do not flush buffers  when  a  file  is  closed.  If you need to be sure that the data is physically stored on the underlying disk, use fsync(2).  (It will depend on the disk hardware at this point.)`

**Comment by drsm** [comment]
@partok 
Yes, the data you wrote may stuck in hardware buffer cache and get lost in case of, for example, power outage.
But at nginx/njs level, if there are no exceptions thrown, the data were successfully written.
Restarting nginx service may interfere if the service has a private '\tmp' configured or something similar when the temporary directory is recreated upon restart.
Try change the path first.

**Comment by partok** [comment]
> Restarting nginx service may interfere if the service has a private '\tmp' configured or something similar when the temporary directory is recreated upon restart.

Thank you so much @drsm 
Indeed, /etc/systemd/system/nginx.service is configured with PrivateTmp=true (on Fedora at least).
Everything is okay now.
