### ISSUE TITLE
Send udp packet

### ISSUE THREAD

**Issue by calvin2021y** [nginx/njs#408]
Is there a way to send udp packet from njs ?

I plan to use it send format log.

**Comment by xeioex** [comment]
@calvin2021y 

Why not use "[syslog](https://nginx.org/en/docs/http/ngx_http_log_module.html)" feature of nginx?

**Comment by calvin2021y** [comment]
because it not just log but with other function syslog will not able to provide.

**Comment by xeioex** [comment]
@calvin2021y 

> Is there a way to send udp packet from njs ?

unfortunately, there is none.
