### ISSUE TITLE
Using node packages with net and tls requirements

### ISSUE THREAD

**Issue by f100024** [nginx/njs#409]
Hi, could you please help me. 
Am I properly understand that there is no way how to use  node packages prepared for server execution?

For example I wanna to use `redis` package (https://www.npmjs.com/package/redis), but it use `net` and `tls` in depencies which are not parsed by browserify on webpack.

**Comment by f100024** [comment]
@xeioex Thank you for reply, is there any plans for supporting them?

**Comment by xeioex** [comment]
@f100024 

No, there are no plans to support node.js style networking. It is not going to work with nginx architecture well.

Instead, there is a limited support for [fetch API](http://nginx.org/en/docs/njs/reference.html#ngx).

**Comment by f100024** [comment]
Many thanks!
