### ISSUE TITLE
How can I decrypt aes256?

### ISSUE THREAD

**Issue by rightly** [nginx/njs#410]
### Encrypt code
```
function hmacEncrypt(r) {
    let str = r.uri.split("/", 2)
    return require('crypto').createHash('sha256', 'key')
                          .update(str)
                          .digest('base64url');
}
```

I want to use njs to decode aes256, base64 encoded string. 
However, the official njs document only shows the encrypt method. 
Is there a way to decode or encode aes256? Can I help you?

**Comment by xeioex** [comment]
@rightly 

Currently, encryption is not supported yet. See what is supported in the [reference](http://nginx.org/en/docs/njs/reference.html#crypto).

We are currently working on adding 'aes256' encryption. You can track the progress [here](https://github.com/nginx/njs/issues/251).
