### ISSUE TITLE
can not install nginx-module-njs on docker-compose 

### ISSUE THREAD

**Issue by johney4415** [nginx/njs#415]
When I do docker-compose build
I got error message 
My Dockerfile will call a script that I writed, when script do below command 

`apt-get install --no-install-recommends --no-install-suggests -y nginx=1.17.10-1~buster nginx-module-xslt=1.17.10-1~buster nginx-module-geoip=1.17.10-1~buster nginx-module-image-filter=1.17.10-1~buster nginx-module-njs=1.17.10.0.3.9-1~buster gettext-base
`

I will got error 
`nginx-module-njs : Depends: libreadline7 (>= 6.0) but it is not installable`

Anyone can hlep? thanks!

**Comment by thresheek** [comment]
Hi @johney4415 can you show full Dockerfile you're using?  Thanks!

**Comment by johney4415** [comment]
Hi @thresheek thanks replay
Dockerfile  is 

`FROM python:3.6

ENV PYTHONUNBUFFERED=1

# install nginx
COPY install-nginx.sh /
RUN bash /install-nginx.sh
EXPOSE 80

# copy nginx config
COPY nginx/uwsgi_params /etc/nginx/uwsgi_params
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/dhost.conf /etc/nginx/conf.d/default.conf

# create source code folder
RUN mkdir -p /var/www/code
WORKDIR /var/www/code

# install logrotate, odbc dependencies
RUN apt-get update \
    && apt-get install -y gcc logrotate \
    && apt-get install -y gettext 

# clean the install
RUN apt-get -y clean
`

I think error is because run this command 
`RUN bash /install-nginx.sh`
install-nginx.sh is 
`#! /usr/bin/env bash

# From official Nginx Docker image, as a script to re-use it, removing internal comments
# Ref: https://github.com/nginxinc/docker-nginx/blob/594ce7a8bc26c85af88495ac94d5cd0096b306f7/mainline/buster/Dockerfile

# Standard set up Nginx
export NGINX_VERSION=1.17.10
export NJS_VERSION=0.3.9
export PKG_RELEASE=1~buster

set -x \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 ca-certificates \
    && \
    NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
    found=''; \
    for server in \
        ha.pool.sks-keyservers.net \
        hkp://keyserver.ubuntu.com:80 \
        hkp://p80.pool.sks-keyservers.net:80 \
        pgp.mit.edu \
    ; do \
        echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
        apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
    done; \
    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
    apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
    && dpkgArch="$(dpkg --print-architecture)" \
    && nginxPackages=" \
        nginx=${NGINX_VERSION}-${PKG_RELEASE} \
        nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
        nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
        nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
        nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-${PKG_RELEASE} \
    " \
    && case "$dpkgArch" in \
        amd64|i386) \
            echo "deb https://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list.d/nginx.list \
            && apt-get update \
            ;; \
        *) \
            echo "deb-src https://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list.d/nginx.list \
            \
            && tempDir="$(mktemp -d)" \
            && chmod 777 "$tempDir" \
            \
            && savedAptMark="$(apt-mark showmanual)" \
            \
            && apt-get update \
            && apt-get build-dep -y $nginxPackages \
            && ( \
                cd "$tempDir" \
                && DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
                    apt-get source --compile $nginxPackages \
            ) \
            \
            && apt-mark showmanual | xargs apt-mark auto > /dev/null \
            && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
            \
            && ls -lAFh "$tempDir" \
            && ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
            && grep '^Package: ' "$tempDir/Packages" \
            && echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
            && apt-get -o Acquire::GzipIndexes=false update \
            ;; \
    esac \
    \
    && apt-get install --no-install-recommends --no-install-suggests -y \
                        $nginxPackages \
                        gettext-base \
    && apt-get remove --purge --auto-remove -y ca-certificates && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
    \
    && if [ -n "$tempDir" ]; then \
        apt-get purge -y --auto-remove \
        && rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
    fi

# forward request and error logs to docker log collector
ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
# Standard set up Nginx finished`

**Comment by thresheek** [comment]
That's because python:3.6 is now based on Debian Bullseye, and you're using scripts to install nginx from Debian buster.

You can fix the nginx versions and debian version in your install scripts to point to bullseye and the problem will be solved.

**Comment by johney4415** [comment]
Thanks replay , I change Dockerfile 
FROM python:3.6.14-buster
and problem solved
Thanks~
