### ISSUE TITLE
async operation inside header filter

### ISSUE THREAD

**Issue by speller** [nginx/njs#417]
I'm trying to send a subrequest in the header filter function but it doesn't work. The documentation doesn't say that this function must be synchronous. Is it a bug?

My function:

```
function header_filter(r) {
  r.subrequest(
    '/ecr',
    {
      method: 'POST',
      body: 'body',
      function: function (res) {
        if (res.status == 200) {
          r.headersOut['X-Test'] = res.responseBody
          return
        }
        r.return(500, 'Something was wrong')
      },
    }
  )
}

export default {header_filter}
```

My intention is to set a header depending on a subrequest.

**Comment by xeioex** [comment]
@speller 

> Is it a bug?

No, it is not a bug. The header filter is synchronous.

**Comment by xeioex** [comment]
@speller 

>My intention is to set a header depending on a subrequest.

Take a look at [this](https://github.com/nginx/njs/issues/384) and [this](https://github.com/nginx/njs/issues/362#issuecomment-742993025).

**Comment by speller** [comment]
@xeioex Can you update the documentation clarifying explicitly which functions can be async and which can not?

**Comment by speller** [comment]
Regarding the `auth_request` workaround, I was unable to make it working, it didn't take headers from the auth request response. I spent a day debugging it and gave up for now. It's too hard to debug nginx at all.

**Comment by xeioex** [comment]
@speller 
> it didn't take headers from the auth request response.

I suggest to start from reproducing the provided example which does exactly that.

The most probable reason you are getting nothing it that are are referencing the wrong variable

`$upstream_http_`
```
// $upstream_http_x_backend takes X-Backend header response from the location's upstream 
// this variable should be used when you have proxy_pass directive in your auth_request location
auth_request_set $backend $upstream_http_x_backend;
```

`$sent_http_`
```
// $sent_http_x_backend takes X-Backend header response from the current request itself
// this variable should be used when you have js_body_filter or js_content in your auth_request location
auth_request_set $backend $sent_http_x_backend;
```

**Comment by xeioex** [comment]
@speller 

>but my impression is like "if you want something advanced, pay us".

BTW, njs is 100% open source and 100% free.

**Comment by xeioex** [comment]
@speller 

>when I put the example.js in the correct location (this should be fixed in the documentation I think) the example works.

The examples are working when the docker is invoked with the following arguments, see the [introduction](https://github.com/xeioex/njs-examples#running-inside-docker).

`docker run --rm --name njs_example  -v $(pwd)/conf/$EXAMPLE.conf:/etc/nginx/nginx.conf:ro -v $(pwd)/njs/:/etc/nginx/njs/:ro -p 80:80 -p 443:443 -d nginx`

**Comment by speller** [comment]
Great, thank you!
