### ISSUE TITLE
Async/await support.

### ISSUE THREAD

**Issue by xeioex** [nginx/njs#419]

**Comment by lexborisov** [comment]
@xeioex 

I did it in 7 minutes! :)

**Comment by xeioex** [comment]
@drsm, @jirutka  
 
 Feel free to test the async/await support.
 
Current known limitations:
1) await is not supported in function arguments.
For example t.js:
```js
async function f() {
    ff(await x, await y);
}
```

```sh
$ njs t.js
Thrown:
SyntaxError: await in arguments not supported in t.js:2
```

2) `for await () {} `   is not supported yet.

**Comment by jirutka** [comment]
Wow, that’s awesome! Thanks! I’ll test it ASAP.

**Comment by xeioex** [comment]
Known problem, the fix is in progress:

```js
async function test() {
    let k1 = await Promise.resolve("PUBKEY");
    let k2 = await Promise.resolve("KEY");

    return 'SUCCESS';
};

Promise.all(['x', 'y'].map(t => test(t)))
.then(results => {
    if (results.every(r => r === 'SUCCESS')) {
        console.log(" SUCCESS");
    }
})
.catch(e => {
    console.log(`exception:${e}`)
})
```

**Comment by drsm** [comment]
@xeioex 
@lexborisov 

Looks Great! Thanks!

Some more problems:

> 1. await is not supported in function arguments.

object/array literals are also affected: `{ x: await y }, [ await z ] `,
but this works well:
```js
>> var x = async () => `aaa ${await Promise.resolve(111)} bbb`; void x().then(console.log);
undefined
aaa 111 bbb
```

object method syntax is not supported:
```js
var n = 'm1';
var x = {
    async m0() {},
    async [n]() {},
}
```

**Comment by lexborisov** [comment]
@drsm 

Thanks for testing!
Fixed.

**Comment by xeioex** [comment]
@rafi16jan 

> When will this be released? This is a very awaited feature hehe :)

The [0.7.0](https://github.com/nginx/njs/milestone/24) is planned to be released by the next Tuesday (19 Oct 2021).
