### ISSUE TITLE
Using njs to perform blocking operation for ngx.fetch and update variables 

### ISSUE THREAD

**Issue by variable** [nginx/njs#422]
Hello sorry if this has been asked before, I am trying to use njx to perform a lookup to get some data and then update the ngx variable so that I can use that variable for `proxy_pass`, it seems to me the lookup is an IO operation and the execution continued without waiting for it to return, hence `proxy_pass` get an empty variable. I understand that `js_content` specifically handles that callback but in this case I am not using `js_content`, is there a way to get around this?

**Comment by xeioex** [comment]
Hi @variable,

 >  is there a way to get around this?
 
 Yes.  Take a look at [this](https://github.com/nginx/njs/issues/384).

**Comment by variable** [comment]
Thanks @xeioex, I think I am heading the right direction but cannot get past the following problem, this is what I have

```
js_import novnc.js;
js_var $vmhhost '';
js_var $pve '';

server {
    ...
    location = /novnc-auth {
        internal;
        js_content novnc.auth;
    }

    location = /novnc/ {
        auth_request /novnc-auth;
        proxy_set_header Cookie 'PVEAuthCookie=$pve';
        proxy_pass https://$vmhhost/$is_args$args;
    }
}
```

novnc.js
```javascript
function auth(r){
        r.subrequest('/api/proxmox/novnc-connection-lookup/' + r.variables.cookie_novnc + '/').then(
                reply => {
                        var result = JSON.parse(reply.responseBody);
                        r.variables['vmhhost'] = result.host;
                         r.variables['pve'] = result.pve;
                        r.error(r.variables['pve']);
                        r.return(200);
                }
        ).catch(e => {
                r.error(e.message);
                r.return(501, e.message);
        });
}

export default {auth};
```

Somehow, some requests cannot get the `pve` and `vmhhost` variables populated.

**Comment by variable** [comment]
Another question `upstream: "http://127.0.0.1:8000` in the error log, how does that gets defined?

**Comment by drsm** [comment]
@variable 

- your upstream fails to return a valid answer: `upstream prematurely closed connection while reading response header from upstream`
- `JSON.parse` fails on empty `reply.responseBody`, it's better to check `reply.status` first.
- control goes to the `catch` block

**Comment by variable** [comment]
@drsm, yes but I don't know why the upstream in auth_request fails, they are identical.

**Comment by drsm** [comment]
@variable 

A `subrequest: "/api/proxmox/novnc-connection-lookup/eac2faed-734c-4511-b40f-276d214c730a/"`
goes to `upstream: "http://127.0.0.1:8000/api/proxmox/novnc-connection-lookup/eac2faed-734c-4511-b40f-276d214c730a/"`
via `proxy_pass`.
The upstream fails to return a valid response, so it's better to check the logs on the upstream side.
Also, check an output of `curl -v http://127.0.0.1:8000/api/proxmox/novnc-connection-lookup/eac2faed-734c-4511-b40f-276d214c730a/`, to ensure there is no [gzipping](https://github.com/nginx/njs/issues/14) involved.

**Comment by xeioex** [comment]
@variable  Please take a look at the following complete [example](https://github.com/xeioex/njs-examples#setting-nginx-var-as-a-result-of-async-operation).

**Comment by variable** [comment]
Thanks guys I sussed it out, it's because the second ajax request was a POST, I was missing some directive but once I added those directives then it's fine.

```
location = /novnc-auth {
        internal;
       ...
        # added below
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }
```
