### ISSUE TITLE
auth_request not being executed?

### ISSUE THREAD

**Issue by variable** [nginx/njs#424]
```
js_import novnc.js;
js_var $vmhhost '1';
js_var $pve '1';

server {
    ....
    location = /tttt {
        add_header Cache-Control no-cache;
        auth_request /novnc-auth;
        default_type text/plain;
        return 200 $pve;
    }
}
```

novnc.js
```
function auth(r){
        r.error(r.variables['pve']);
       r.variables['pve'] = '2';
       r.return(200);
}

export default {auth};
```

But I am not seeing the variable being logged in error.log, why is that? It's probably the reason $pve doesn't get updated as well?

**Comment by xeioex** [comment]
@variable 

```
location = /tttt {
        add_header Cache-Control no-cache;
        auth_request /novnc-auth;
        default_type text/plain;
        return 200 $pve;
    }
```

`return` directive is a very special directive, it is applied early on (NGX_HTTP_SERVER_REWRITE_PHASE), even before access [phase](http://nginx.org/en/docs/dev/development_guide.html#http_phases) (where `auth_request` are expected to work).

**Comment by variable** [comment]
@xeioex thank you!
