### ISSUE TITLE
ngx.fetch example isn't working

### ISSUE THREAD

**Issue by vldmri** [nginx/njs#426]
The example from [docs page](http://nginx.org/en/docs/njs/reference.html#ngx_fetch) isn't working - falling into `catch` handler with e.message: `no resolver defined`.

worker.js:
```
function hello(r) {
    ngx.fetch('http://nginx.org/')
        .then(reply => reply.text())
        .then(body => r.return(200, body))
        .catch(e => r.return(501, e.message));
}
export default {hello};
```

nginx.conf:
```
load_module modules/ngx_http_js_module.so;

events {}

http {
    js_import worker.js;

    server {
        listen 8080;

        location / {
            js_content worker.hello;
        }
    }
}

```

Versions:
`{"njsModuleVersion":"0.6.2","nginxVersion":"1.20.1"}`

**Comment by xeioex** [comment]
Hi @vldmri,

You need to define [resolver](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) directive.
