### ISSUE TITLE
Missing headers in Request.headersOut

### ISSUE THREAD

**Issue by vbuciuc** [nginx/njs#43]
While trying to use njs to log request/response headers I noticed that some headers added by nginx are missing in the Request.headersOut

nginx version 1.14.0
njs version 0.2.2

I format headers as a stringified json object:

````
function escapeMap(map) {
  var result = {};
  for (var key in map) {
    result[key] = map[key];
  }

  return JSON.stringify(result);
}
````
...
````
responseHeaders: escapeMap(req.headersOut)`
````

Following headers present in the response are missing in the created object:

> Server: nginx
> Date: Thu, 02 Aug 2018 13:08:30 GMT
> Content-Type: application/json; charset=utf-8
> Content-Length: 399
> Connection: keep-alive

**Comment by xeioex** [comment]
Hi, 

Some special headers, like `Content-Length`, nginx treats in a special way (http://hg.nginx.org/nginx/file/tip/src/http/ngx_http_header_filter_module.c#l501)

so, they are unavailable through generic header structure (r->headers_out.headers).

**Comment by xeioex** [comment]
Currently, they are not inaccessible. 

Making them available is required some custom C code for each such a header, which in many ways would duplicate the code in nginx.
