### ISSUE TITLE
Array.from is missing?

### ISSUE THREAD

**Issue by denouche** [nginx/njs#436]
Hello,
I'm faced to this error:
```
│ 2021/11/12 16:53:33 [error] 32#32: *10 js: error:TypeError: (intermediate value)["from"] is not a function     
```
while trying to call 
```
Array.from(iv)
```

Is the Array.from function avalaible?
Thanks in advance!
Regards

**Comment by xeioex** [comment]
Hi @denouche ,

There is no `Array.from()`. 

See the complete list of what is available [here](http://nginx.org/en/docs/njs/compatibility.html).
There is also a [CLI](https://github.com/xeioex/njs-examples#command-line-interface) to play around.

**Comment by denouche** [comment]
Hello @xeioex , thank you for your response.
Now I understand why it does not work.
For posterity, I added the polyfill I found here and it seems to do the job:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#polyfill
