### ISSUE TITLE
Will shared-memory be implemented or considered?

### ISSUE THREAD

**Issue by HermannLizard** [nginx/njs#437]
https://github.com/nginx/njs/issues/431
https://github.com/nginx/njs/issues/354#issuecomment-723712610

For instance, this can be used in web gray-release solution, totally replace the "redis+nginx+lua" solution, since web maintainers is usually more familiar with JavaScript than lua, like, me. More controllable, more flexible. Sincerely looking forward to it.

**Comment by xeioex** [comment]
Hi @HermannLizard,
 
We are planning to open source [keyval](http://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone) module for this.

**Comment by chs97** [comment]
> 
@xeioex 
Are there any updates

**Comment by raoajayy** [comment]
@xeioex Any timeline to open source [keyval](http://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone) module

**Comment by xeioex** [comment]
Hello everyone,

@HermannLizard, @osokin, @drsm, @ivanitskiy, @crasyangel, @FlorianSW, @7rulnik, @bfuvx, @cxpcyv, @jirutka  and others feel free to test and give feedback for upcoming shared dictionary feature.

https://gist.github.com/xeioex/357e64b871608cae08f8fc7fb184b151

Where `Modules: introduced js_shared_dict_zone directive.` adds a shared dictionary where keys and values are strings.

And `Modules: extended js_shared_dict_zone directive with number type.` extends the dictionary so double numbers can be stored directly. This mode allows for atomic increment of a shared counters.

**Comment by drsm** [comment]
[maybe freeSpace](https://gist.github.com/xeioex/357e64b871608cae08f8fc7fb184b151#file-shared_dict-patch-L264) ?
[typo](https://gist.github.com/xeioex/357e64b871608cae08f8fc7fb184b151#file-shared_dict-patch-L389)

**Comment by xeioex** [comment]
@hongzhidao 

Thanks for reviewing the code, it was helpful.


> What's the intention of the usage?

Yes, the original intention was to have a shortcut when there is only one shared dictionary.
But after some thinking I decided to remove it, to simplify the code and not to confuse the users.

>Handing the case of empty value.

Thanks, fixed the test case. Also reworked the deletion, so it is always explicit and empty strings are also allowed now.


> Just an idea to simplify related allocation and free.

That does not work when we want to replace the values, we want to reallocate only the value part.

**Comment by hongzhidao** [comment]
@xeioex You are welcome.
> That does not work when we want to replace the values, we want to reallocate only the value part.

You are right, but take a look again, I only combine the node structure with the key.
```
-    node = ngx_slab_alloc_locked(dict->shpool, sizeof(ngx_js_dict_node_t));
+    n = sizeof(ngx_js_dict_node_t) + key->length;
```

**Comment by hongzhidao** [comment]
My thoughts are:
1. It would be useful to log error when it happens.
2. I found, for now, the only case to return failure for `set()` is the shared memory is not enough,
    but there might more cases like "too long length for key", or "empty key".
    So I prefer to throw an exception to indicate not enough memory happened.

BTW, do we need to handle the empty key for both set and delete?

**Comment by xeioex** [comment]
@hongzhidao 

>BTW, do we need to handle the empty key for both set and delete?

No, we do not. I reworked the part with deletion, so it is done explicitly.

**Comment by xeioex** [comment]
@hongzhidao  here is the latest version

https://gist.github.com/xeioex/b61de2bba239cc84bf7c459966367ddf

**Comment by jirutka** [comment]
> ```
> # Declares a shared dictionary of strings of size 1 Mb, that
> # removes key-value after 60 seconds of inactivity.
> js_shared_dict_zone zone=foo:1M timeout=60s;
> ```

I find `timeout` a bit confusing, I think that `ttl` would be more accurate. When I see `timeout`, I think about network timeout, operation timeout, …, an interval after which something is aborted as a failure. On the other hand, `timeout` in the meaning of TTL is already used in [keyval_zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone), so it’s probably better to be consistent with that.

**Comment by drsm** [comment]
@xeioex 

I think we should throw on allocation [failure](https://gist.github.com/xeioex/b61de2bba239cc84bf7c459966367ddf#file-shared_dict_v2-patch-L1320). So one can distinguish a case of existent|nonexistent value from a low memory conditions.

 BTW,
 
```
-    items(): number;
+   readonly size: number; // like in Map, Set

-    freeSpace(): number;
+   readonly freeSpace: number;
```

**Comment by jirutka** [comment]
> ```
> items(): number;
> freeSpace(): number;
> ```

As @drm already said, `readonly size: number` and `readonly freeSpace: number` would be better.

```
> get(id: string): NgxSharedDictValue;
```

What will this do if an entry with the specified id does not exist? To be consistent with Object, Map, Set… it should return `undefined`, so the return type should be `NgxSharedDictValue | undefined`.

```
> /**
>  * Sets a value by key.
>  * @param id is a string key.
>  * @param value is a string or number value.
>  * @param flags is in optional number value with flags.
>  * 1 - the value must exist in the dictionary (the same as replace()).
>  * 2 - the value must not exist in the dictionary (the same as add()).
>  * 0 is the default value (no flags).
>  * @returns true if the value has been successfully set,
>  * and false otherwise.
>  */
> set(id: string, value:NgxSharedDictValue, flags?:number): boolean;
```

I’d prefer making `set()` consistent with [Map.prototype.set()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set):

* drop `flags` – they’re redundant, you have separate methods (`add` and `replace`) doing the same thing.
* return “this” instead of boolean to allow [chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set#using_the_set_with_chaining)

Can you also consider adding the following methods?

* `has(id: string): boolean` – returns a boolean indicating whether an element with the specified key exists or not
* `keys(): IterableIterator<string>` (or `keys(): string[]`) – returns an interator that contains the keys for each entry in the dict
* `clear(): void` – removes all entries from the dict

**Comment by xeioex** [comment]
@jirutka 

>As @drm already said, readonly size: number and readonly freeSpace: number would be better

Originally, when making `capacity` as property and `freeSpace()` and `items()`, the distinction was that the first is a constant and the latter are variables. Also the methods signify for the user that accessing it is not cost-free. As for example with `items()` we in order to count the items block the whole tree.

**Comment by jirutka** [comment]
> Originally, when making `capacity` as property and `freeSpace()` and `items()`, the distinction was that the first is a constant and the latter are variables.

This makes sense. However, I find `items()` confusing, I would expect it to return a list or iterator over the items in the dictionary. Naming it `size()` would be better.

**Comment by xeioex** [comment]
@jirutka 

>On the other hand, timeout in the meaning of TTL is already used in [keyval_zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone), so it’s probably better to be consistent with that.

yes, that was my intention to be consistent with keyval.

>>But I am working now on must_exist | should_not_exist flags.
>
>Can you please elaborate on this?

That was about flags for the set() method.

>drop flags – they’re redundant, you have separate methods (add and replace) doing the same thing.

I was thinking about allowing a user to choose programmatically the behaviour of `set()`, but I agree it is probably redundant to `add()` and `replace()`.


>> incr(id: string, delta: number, init?: number): number;
> What will this method do if called on a dictionary of type string?

It throws an exception now.

>Can you also consider adding the following methods?

Yes, I plan to add them. I am thinking about

```
readonly name: string;
readonly capacity: number;
readonly freeSpace(): number;  // method because it involves calculation
incr(id: string, delta: number, init: number): number;

size(): number;  // method because it involves counting
set(id: string, value:NgxSharedDictValue): NgxSharedDict;
delete(id: string): boolean;
get(id: string): NgxSharedDictValue | undefined;
has(id: string): boolean;
keys(max_count?:number): string[]; // optional limit for performance
clear(): void;
```

**Comment by hongzhidao** [comment]
> delete(id: string): boolean;

What does this return value represent?

**Comment by hongzhidao** [comment]
@xeioex 
>@hongzhidao here is the latest version
https://gist.github.com/xeioex/b61de2bba239cc84bf7c459966367ddf

I reworked it. But since you plan to simplify the APIs related to "set/add/replace", the patch is to show where could be reworked.
1. For the APIs `ngx_js_dict_{name}()`, `dict` is readable than `shm_zone` as its first parameter.
2. Introduced something like `ngx_js_dict_alloc/free()` as a helper to simplify related allocation and release.
3. Tiny fixes.

**Comment by xeioex** [comment]
@hongzhidao 

>What does this return value represent?

false will be returned when a value to delete was absent.

**Comment by hongzhidao** [comment]
> @hongzhidao
> 
> > What does this return value represent?
> 
> false will be returned when a value to delete was absent.

I thought this was your intention, and it seems you missed something here.
```
    ngx_js_dict_delete(shm_zone->data, &key);  /* should do something on it */

    njs_value_boolean_set(retval, 1);
```

**Comment by xeioex** [comment]
@drsm, @jirutka, @hongzhidao 

https://gist.github.com/xeioex/64e78d037bedb491bd1ebd3c48a5f78f

Here is the version the incorporates recent suggests.

1) clear(), has(), keys() were added
2) items() renamed to size()
3) add(), set(), replace() now throw exception if memory is not enough and return `this`
4) code improvements by @hongzhidao  were merges with minor changes

**Comment by hongzhidao** [comment]
@xeioex 
Take a look. I have a patch to simplify related "expire" code later, but it's based on a question I showed below.
```
diff -r 09951503ac64 nginx/ngx_js_shared_dict.c
--- a/nginx/ngx_js_shared_dict.c        Wed Jun 14 23:00:10 2023 -0700
+++ b/nginx/ngx_js_shared_dict.c        Thu Jun 15 19:14:55 2023 +0800
@@ -573,8 +573,7 @@
     rbtree = &dict->sh->rbtree;

     if (rbtree->root == rbtree->sentinel) {
-        ngx_rwlock_unlock(&dict->sh->rwlock);
-        return NJS_OK;
+        goto done;
     }

     for (rn = ngx_rbtree_min(rbtree->root, rbtree->sentinel);
@@ -589,19 +588,27 @@

         value = njs_vm_array_push(vm, retval);
         if (value == NULL) {
-            return NJS_ERROR;
+            goto fail;
         }

         rc = njs_vm_value_string_set(vm, value, node->sn.str.data,
                                      node->sn.str.len);
         if (rc != NJS_OK) {
-            return NJS_ERROR;
+            goto fail;
         }
     }

+done:
+
     ngx_rwlock_unlock(&dict->sh->rwlock);

     return NJS_OK;
+
+fail:
+
+    ngx_rwlock_unlock(&dict->sh->rwlock);
+
+    return NJS_ERROR;
 }


@@ -1166,9 +1173,11 @@

     if (node == NULL) {
         if (flags & NGX_JS_DICT_FLAG_MUST_EXIST) {
-            ngx_rwlock_unlock(&dict->sh->rwlock);
-            njs_vm_error(vm, "value to replace not found");
-            return NJS_ERROR;
+            if (!dict->timeout || now < node->expire.key) {
+                ngx_rwlock_unlock(&dict->sh->rwlock);
+                njs_vm_error(vm, "value to replace not found");
+                return NJS_ERROR;
+            }
         }

         ngx_js_dict_expire(dict);
```

Since the `has()` function is introduced, do you think we still need `add()` and `replace()`,
I'm thinking about whether we could remove the internal flags of "must_exist" and "must_not_exist".
If yes, we can simplify related code.
@xeioex @jirutka @drsm  what do you think? Does it make sense to get rid of `add()` and `replace()`?

**Comment by xeioex** [comment]
@hongzhidao 

I think it is important to have `add()` and `replace()` independently from `has()` for convenience and performance in some cases. Also lua module [has these methods](https://github.com/openresty/lua-nginx-module#ngxshareddict), and having the same primitives would help users in migration to njs if they want to.

**Comment by hongzhidao** [comment]
@xeioex
Take a look.
https://gist.github.com/hongzhidao/8c3220b1ca2e1d6bc1fe789d1674f59a

Btw, A few places about the commit log:
1. 
```
s/The directives allows to declared/The directives allows to declare/
```
2.
```
function get(r) {
            r.return(200, ngx.shared.foo.get(r.args.key));
} /* missed } */
```
3. What about adding blank lines like this:
```
        # Declares a shared dictionary of strings of size 1 Mb, that
        # removes key-value after 60 seconds of inactivity.
        js_shared_dict_zone zone=foo:1M timeout=60s;

        # Declares a shared dictionary of strings of size 512Kb, that
        # forsibly remove oldest key-value pairs when memory is not enough.
        js_shared_dict_zone zone=bar:512K timeout=30s evict;

        # Declares a permanent number shaed dictionary of size 32Kb.
        js_shared_dict_zone zone=num:32k type=number;
```

**Comment by hongzhidao** [comment]
> I prefer to leave ngx_js_dict_node_free() as is

Sure, I'm fine with it.

Btw, What about reordering the internal APIs? I have no clear idea about it, but I think it's worth doing it so that developers can understand the source code easier. And yours is a good reference.
```
readonly name: string;
readonly capacity: number;
freeSpace(): number;  // method because it involves calculation
size(): number;  // method because it involves counting

get(id: string): NgxSharedDictValue | undefined;
has(id: string): boolean;
keys(max_count?:number): string[]; // optional limit for performance

incr(id: string, delta: number, init: number): number;
set(id: string, value:NgxSharedDictValue): NgxSharedDict;

delete(id: string): boolean;
clear(): void;
```

For example, putting the `ngx_js_dict_set/add/update()` together.

**Comment by drsm** [comment]
@xeioex 

> add(), set(), replace() now throw exception if memory is not enough and return this

Do we need chaining in `add|replace` ? While lua module also does this, an [exception](https://gist.github.com/xeioex/64e78d037bedb491bd1ebd3c48a5f78f#file-shared_dict3-L1473) when an absent key has been replaced is little bit confusing. Also, as for now, one can't catch it by type. Boolean result looks better to me.

**Comment by xeioex** [comment]
@hongzhidao 
The current order is alphabetical for njs method, may be it is not ideal, but at least it is a definite order.
Also the internal routines are moved to the bottom of the file. But I can group `ngx_js_dict_set/add/update()` more tightly.

**Comment by xeioex** [comment]
@drsm 

>Do we need chaining in add|replace ? While lua module also does this, an [exception]> (https://gist.github.com/xeioex/64e78d037bedb491bd1ebd3c48a5f78f#file-shared_dict3-L1473) when an absent key has >been replaced is little bit confusing. Also, as for now, one can't catch it by type. Boolean result looks better to me.

Honestly, I have no opinion here. I did chaining for the `set()` to move the interface more closely to `Map` as you suggested.
But I still want to see the usefulness of such chaining construction for `set()` method in practice.
I do love chaining in Array methods like `map()`, `filter()` where the chaining is clearly useful.

**Comment by xeioex** [comment]
@hongzhidao 

shared_dict v4
https://gist.github.com/xeioex/6b7c18c969dfa0189e4e2d9ab6d4a4af

applied improvement from [here](https://github.com/nginx/njs/issues/437#issuecomment-1593369671).

@hongzhidao, @jirutka 

Do you have any opinion on [drsm comment](https://github.com/nginx/njs/issues/437#issuecomment-1593400445) what should be the retval of `add()` and `replace()`.

**Comment by hongzhidao** [comment]
@xeioex 
> shared_dict v4
https://gist.github.com/xeioex/6b7c18c969dfa0189e4e2d9ab6d4a4af

Great job, no issue found. And here's a small rework. Others look good.
https://gist.github.com/hongzhidao/48a5be0e82a5c1a01208d1012f83ba3c

**Comment by xeioex** [comment]
@drsm 

> But, for add() or replace() it will made error control painful.

Thanks, that was a good example. I will update the retval for `add()` and `replace()`.

**Comment by hongzhidao** [comment]
@xeioex 
> Great job, no issue found. And here's a small rework. Others look good.
https://gist.github.com/hongzhidao/48a5be0e82a5c1a01208d1012f83ba3c

Introduced a mistake here.
https://gist.github.com/hongzhidao/48a5be0e82a5c1a01208d1012f83ba3c#file-shared_dict4-patch-L60

Updated with:
```
+    njs_value_boolean_set(retval, node != NULL);
     ngx_rwlock_unlock(&dict->sh->rwlock);
-    njs_value_boolean_set(retval, has);
```

**Comment by xeioex** [comment]
@hongzhidao

>Introduced a mistake here

Yes, I already fixed it.

**Comment by jirutka** [comment]
> Do you have any opinion on drsm comment what should be the retval of add() and replace().

I agree with @drsm. Since `add` should set a value by key only if the key does not exist yet, it should return `true` when the key didn’t exist and so the value was set, `false` otherwise. `replace` is should replace a value by key only if the key exists, so it should return `true` when the key didn’t exist and so the value was replaced, `false` otherwise. In all cases, out-of-memory should be indicated by an exception.

The question is, what exception type? It’ll be better to “subclass” `Error` (or some other error type), so it can be disguised from other error cases.

**Comment by jirutka** [comment]
I also have an update of the types, but I cannot finish it now, I’ll add it later today.

**Comment by jirutka** [comment]
I rewrote the type declaration for `NgxSharedDict` to:

* use generic for the value type so users can assert a particular shared dictionary to its value type (`const mydict = shared.mydict as NgxSharedDict<number>`),
* rewrite the comments to be more informative and consistent with existing types,
* highlight method arguments in the comment texts,
* declare the suggested `OutOfSharedMemoryError` type.

```ts
/**
 * This Error object is thrown when adding an item to a shared dictionary
 * that does not have enough free space.
 * @since 0.8.0
 */
declare class OutOfSharedMemoryError extends Error {}

/**
 * Interface of a dictionary shared among the working processes.
 * It can store either `string` or `number` values which is specified when
 * declaring the zone.
 * 
 * @type {V} The type of values.
 * @since 0.8.0
 */
interface NgxSharedDict<V extends string | number = string | number> {
    /**
     * The capacity of this shared dictionary in bytes.
     */
    readonly capacity: number;
    /**
     * The name of this shared dictionary.
     */
    readonly name: string;

    /**
     * Sets the `value` for the specified `key` in the dictionary only if the
     * `key` does not exist yet.
     * 
     * @param key The key of the item to add.
     * @param value The value of the item to add.
     * @returns `true` if the value has been added successfully, `false`
     *   if the `key` already exists in this dictionary.
     * @throws {OutOfSharedMemoryError} if there's not enough free space in this
     *   dictionary.
     */
    add(key: string, value: V): boolean;
    /**
     * Removes all items from this dictionary.
     */
    clear(): void;
    /**
     * Removes the item associated with the specified `key` from the dictionary.
     * 
     * @param key The key of the item to remove.
     * @returns `true` if the item in the dictionary existed and has been
     *   removed, `false` otherwise.
     */
    delete(key: string): boolean;
    /**
     * Increments the value associated with the `key` by the given `delta`.
     * If the `key` doesn't exist, the item will be initialized to `init`.
     * 
     * **Important:** This method can be used only if the dictionary was
     * declared with `type=number`! Otherwise it will throw an Error.
     * 
     * @param key is a string key.
     * @param delta The number to increment/decrement the value by.
     * @param init The number to initialize the item with if it didn't exist
     *   (default is `0`).
     * @returns The new value.
     */
    incr: V extends number
      ? (key: string, delta: V, init?: number) => number
      : never;
    /**
     * @returns The free page size in bytes.
     *   Note that even if the free page is zero the dictionary may still accept
     *   new values if there is enough space in the occupied pages.
     */
    freeSpace(): number;
    /**
     * @param key The key of the item to retrieve.
     * @returns The value associated with the `key`, or `undefined` if there
     *   is none.
     */
    get(key: string): V | undefined;
    /**
     * @param key The key to search for.
     * @returns `true` if an item with the specified `key` exists, `false`
     *   otherwise.
     */
    has(key: string): boolean;
    /**
     * @param maxCount The maximum number of keys to retrieve (default is 1024).
     * @returns An array of the dictionary keys.
     */
    keys(maxCount?: number): string[];
    /**
     * Sets the `value` for the specified `key` in the dictionary only if the
     * `key` already exists.
     * 
     * @param key The key of the item to replace.
     * @param value The new value of the item.
     * @returns `true` if the value has been replaced successfully, `false`
     *   if the key doesn't exist in this dictionary.
     * @throws {OutOfSharedMemoryError} if there's not enough free space in this
     *   dictionary.
     */
    replace(key: string, value: V): boolean;
    /**
     * Sets the `value` for the specified `key` in the dictionary.
     *  
     * @param key The key of the item to set.
     * @param value The value of the item to set.
     * @returns This dictionary (for method chaining).
     * @throws {OutOfSharedMemoryError} if there's not enough free space in this
     *   dictionary.
     */
    set(key: string, value: V): this;
    /**
     * @returns The number of items in this shared dictionary.
     */
    size(): number;
}

interface NgxGlobalShared {
    /**
     * Shared dictionaries.
     * @since 0.8.0
     */
    readonly [name: string]: NgxSharedDict;
}
```

**Comment by jirutka** [comment]
> ```c
> if (dict->type == NGX_JS_DICT_TYPE_STRING) {
>     if (!njs_value_is_string(value)) {
>         njs_vm_error(vm, "string value is expected");
>         return NJS_ERROR;
>     }
> } else {
>     if (!njs_value_is_number(value)) {
>         njs_vm_error(vm, "number value is expected");
>         return NJS_ERROR;
>     }
> }
> ```

This throws `Error`, right? It would be better to throw `TypeError` instead.

**Comment by xeioex** [comment]
@jirutka, @hongzhidao, @drsm 

Here is the final shared dict patch: https://gist.github.com/xeioex/1429e987b0f585ef9eb599b49fcf5a5c

It includes
1) SharedMemoryError
2) pop() method
3) TypeError exceptions for unexpected values
4) TypeScript updates from @jirutka

**Comment by jirutka** [comment]
```diff
- pop(key: string): boolean;
+ pop(key: string): V | undefined;
```

**Comment by hongzhidao** [comment]
@xeioex 
> Here is the final shared dict patch: https://gist.github.com/xeioex/1429e987b0f585ef9eb599b49fcf5a5c

Looks good to me.

**Comment by jirutka** [comment]
```diff
- * @type {V} The type of stored values.
+ * @template {V} The type of stored values.
```

**Comment by xeioex** [comment]
@drsm, @jirutka, @hongzhidao 

Thanks guys, committed. I appreciate your contribution.

**Comment by xiaoxiangmoe** [comment]
Hi @xeioex, do you know when will https://github.com/nginxinc/docker-nginx update njs version?

**Comment by xeioex** [comment]
Hi @xiaoxiangmoe,

Good question, I think @thresheek, may answer this question.

**Comment by jirutka** [comment]
> do you know when will https://github.com/nginxinc/docker-nginx update njs version to 0.8.0?

Or you can just use a bare image with Alpine Linux Edge and install `nginx`, `nginx-mod-http-js` and any other modules you need. We also package dozens of third-party modules. ;)

**Comment by xeioex** [comment]
@xiaoxiangmoe  the image will be updated with new nginx release.

**Comment by rikatz** [comment]
Hey folks,

I think there's just a small mistake on docs, apparently "delete" is a reserved word and cannot be used as a function name?

When using it as 
```
function delete(r) {
        r.return(200, ngx.shared.certs.delete(r.args.key));
}
```

it gives me `Unexpected token "delete"` while if the function is called "del(r)" it works fine.

**Comment by jirutka** [comment]
> it gives me Unexpected token "delete" while if the function is called "del(r)" it works fine.

So don’t name it `delete`… Functions can be named `delete`, but you cannot declare it like this. For example, `Foo.prototype.delete = function() { }` is allowed.

**Comment by rikatz** [comment]
I just copied the example from docs, that’s why I’ve commented it :)

**Comment by jirutka** [comment]
Aha, I see now, you’re right.

@xeioex, where can I find repository for https://nginx.org/en/docs/njs/ ?

**Comment by xiaoxiangmoe** [comment]
https://nginx.org/en/docs/http/ngx_http_js_module.html#js_shared_dict_zone

> js_shared_dict_zone 
> 
> Sets the name and size of the shared memory zone that keeps the key-value dictionary shared between worker processes.

Is there anything that will define a key-value dictionary in each single worker process?
