### ISSUE TITLE
njs_internal_error(vm, (const char *) start) segfault

### ISSUE THREAD

**Issue by crasyangel** [nginx/njs#439]
http://hg.nginx.org/njs/file/tip/src/njs_regexp.c#l449

`segfault at 1 ip 000000000089332b sp 00007ffea41cfd20 error 4 in nginx`

start is not end with '\0', cannot pass it to njs_internal_error directly

`njs_internal_error(vm, "%*s", p - start, (const char *) start);`

**Comment by xeioex** [comment]
@crasyangel  Thanks, committed.
