### ISSUE TITLE
ngx.fetch with https failing: unable to get local issuer certificate

### ISSUE THREAD

**Issue by lifeofguenter** [nginx/njs#441]
When trying to `ngx.fetch` a https URL I get the following error:

> js http fetch SSL certificate verify error: (20:unable to get local issuer certificate) while SSL handshaking to fetch target

I am using the following docker-image: `nginxinc/nginx-unprivileged:1.20-alpine`. (ca-certificates is installed: https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/stable/alpine/Dockerfile#L120)

If I docker exec and curl the URL inside the container it works without any verification issues.

I also tried adding `ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;` to the nginx.conf.

For now, explicitly setting "verify: false" works.

**Comment by xeioex** [comment]
Hi @lifeofguenter,

To set trusted chain for ngx.fetch()  [js_fetch_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_fetch_trusted_certificate) is used. 

Did you enable it?

**Comment by lifeofguenter** [comment]
Apologies, yes thanks @xeioex that fixes the issue. For some reason I did not see it and tried `ssl_trusted_certificate` instead 😅

**Comment by keul** [comment]
No idea how to report this, but I'm wondering why this simple line is not activated by default on official nginx docker images.
