### ISSUE TITLE
Error: connect failed\n    at anonymous (fileName.js:195)\n    at native (native)\n

### ISSUE THREAD

**Issue by navanshu** [nginx/njs#448]
Hello, I am getting this error, when I am trying to make a fetch request through.
I could not
```js
ngx.fetch(host, {
    method: 'POST',
    headers: {
        'Content-type': 'application/json',
    },
    body,
}).catch(E => {
    throw E;
});
```

I understood that it is being thrown from here 
```c
rc = ngx_event_connect_peer(&http->peer);

    if (rc == NGX_ERROR) {
        ngx_js_http_error(http, 0, "connect failed");
        return;
    }
```

**Comment by xeioex** [comment]
Hi @navanshu 

By default, `ngx.fetch()` tries to verify a server certificate, but trusted certificates are not defined.
There are two options:
1) specify a trusted certificate using [js_fetch_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_fetch_trusted_certificate). 
2) disable verification, be adding `verify:false` to the ngx.fetch() option argument. This is not recommended.

Take a look at similar [issue](https://github.com/nginx/njs/issues/441).

If problem persists after setting `verify:false`  please provide the nginx [debug log](https://nginx.org/en/docs/debugging_log.html).

**Comment by xeioex** [comment]
@navanshu 

If you are using plain HTTP connection please check that IP:port pair is available from nginx instance.

**Comment by navanshu** [comment]
I am using HTTPS connection and I am sure the server is not sending any redirects. Still I am getting this. I have tried this with or without firewall.

**Comment by xeioex** [comment]
Hi @navanshu

By default, `ngx.fetch()` tries to verify a server certificate, but trusted certificates are not defined.
There are two options:
1) specify a trusted certificate using [js_fetch_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_fetch_trusted_certificate).
2) disable verification, be adding `verify:false` to the ngx.fetch() option argument. This is not recommended.

Take a look at similar [issue](https://github.com/nginx/njs/issues/441).

**Comment by navanshu** [comment]
Hi @xeioex 

Thanks for your support, this is quite different from standard javascript and it is pretty harcore. 

So if I use https I will have to provide the trusted certificate every time the server updates it certificate or I have to provide the certificates from various CA which I guess can be downloaded by opensll, the same thing that come pre bundled in every browser so the browser can verify the certificates as it depends on certificate chain something like that.

Aside from the certificate I did try once before with verfiy off. I didn't see any error but it is http after all. 

I really couldn't get any info on this, first I though this has to do something with resolver but that did not work, 
I read that https was a added later to `ngx.fetch` but nothing more than this. Where can I learn more about this?

I will update soon with logs, I remember seeing something like "js error while filtering hanshake".

**Comment by xeioex** [comment]
>Thanks for your support, this is quite different from standard javascript and it is pretty harcore.

Browsers and node.js bring a bundle of known trusted CA with them. For performance reasons we give user a way to optimise it by proving only needed CA certs.

>So if I use https I will have to provide the trusted certificate every time the server updates it certificate or I have to provide the certificates from various CA which I guess can be downloaded by opensll, the same thing that come pre bundled in every browser so the browser can verify the certificates as it depends on certificate chain something like that.

You have to provide only a trusted certificate for a CA which issues certs for your site. Fortunately CA certificate are rarely changing (less than once a year).

1) In Ubuntu, known CA certs can be installed using 
`apt-get install ca-certificates`

 To see the locations of the files
 `dpkg -L apt-get install ca-certificates`

You should locate the CA cert for for your site and specify a path to it in `js_fetch_trusted_certificate`.

2) the second option is to specify a bundle of trusted certificates. For example, using [mozilla bundle](https://curl.se/docs/caextract.html).  Using a bundle eliminates the necessity to find the exact CA cert for your site.
But it may impact runtime performance a bit.

**Comment by navanshu** [comment]
Hi @xeioex ,
I did specify the certerficate this time, to the correct pem file. Still I am getting this error
```log
2021/12/23 06:07:09 [error] 25357#25357: *10 js exception: Error: unhandled promise rejection: Error: cannot set done while not filtering while SSL handshaking to fetch target, client: "MY.IP", server:  "my website url", request: "POST /booking/ HTTP/2.0", host: "my website url", referrer: "my website url"
```

**Comment by navanshu** [comment]
Hi @xeioex 
Thanks for your help. I figured out the issue the new backend was sending a 30x and so wa the cause for error. Please ignore the last comment.
