### ISSUE TITLE
boringssl build error!

### ISSUE THREAD

**Issue by calvin2021y** [nginx/njs#455]
HMAC `EVP_PKEY`s not support by boringssl.
```sh
`EVP_PKEY_HMAC` is removed. Use the `HMAC_*` functions in `hmac.h` instead. This
is compatible with OpenSSL.
```

This function used from external/njs_webcrypto_module.c

**Comment by xeioex** [comment]
Hi @calvin2021y,

Please share a step-by-step way you use to build and link boringSSL.

What I did:
```
git clone https://github.com/google/boringssl
cd boringssl
mkdir build
cd build
cmake ..
make
..
# at this point I have a dir with a static library libcrypto.a

cd <njs>

./configure --ld-opt='-L/path/to/boringssl/build/crypto -Wl,-Bstatic -lcrypto -pthread -Wl,-Bdynamic'
make
...
/usr/bin/ld: build/libnjs.a(njs_webcrypto_module.o): in function `njs_set_rsa_padding':
njs/external/njs_webcrypto_module.c:1932: undefined reference to `RSA_pkey_ctx_ctrl'
njs/external/njs_webcrypto_module.c:1932: undefined reference to `RSA_pkey_ctx_ctrl'
njs/external/njs_webcrypto_module.c:1955: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/bin/ld: build/libnjs.a(njs_webcrypto_module.o): in function `njs_ext_import_key':
njs/external/njs_webcrypto_module.c:1859: undefined reference to `EVP_PKEY_new_mac_key'
njs/external/njs_webcrypto_module.c:1548: undefined reference to `EVP_PKEY_new_mac_key'
/usr/bin/ld: build/libnjs.a(njs_webcrypto_module.o): in function `njs_cipher_pkey':
njs/external/njs_webcrypto_module.c:607: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/bin/ld: njs/external/njs_webcrypto_module.c:609: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/bin/ld: njs/external/njs_webcrypto_module.c:607: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/bin/ld: njs/external/njs_webcrypto_module.c:609: undefined reference to `RSA_pkey_ctx_ctrl'

```

and I have a bit of diffrent set of problems.

**Comment by calvin2021y** [comment]
I build cloudflare quiche cmake to build boringssl.

**Comment by gornostay25** [comment]
How did you fix that? I can't build quiche with nginx 1.21.6....

**Comment by calvin2021y** [comment]
last time I check  it still not fixed.

**Comment by gornostay25** [comment]
@calvin2021y Try to use quictls, maybe it will work

> Alternatively, nginx can be configured with QuicTLS [9]

    $ ./auto/configure --with-debug --with-http_v3_module         \
                       --with-cc-opt="-I../quictls/build/include" \
                       --with-ld-opt="-L../quictls/build/lib"

**Comment by xeioex** [comment]
@calvin2021y, @gornostay25 

Alternatively, if you are building from sources anyway, you may disable WebCrypto API if you do not need it.

Just comment out the [webcrypto module](https://github.com/nginx/njs/blob/master/auto/modules#L16).

**Comment by maximkonovalov** [comment]
@calvin2021y just as a side note, we do have a robust native implementation of quic/http3 here https://hg.nginx.org/nginx-quic/ and working on a merging this code to the mainline.  It should work ok with njs.
