### ISSUE TITLE
Incorrect value of r.args with array in query string

### ISSUE THREAD

**Issue by Reginald-Yoeng-Lee** [nginx/njs#462]
When sending a request with the query string containing multi-value fields, such as
`/path/to/target?ids[]=aa&ids[]=bb`
It's expected that the value of key `ids[]` is an array containing two items - `'aa'` and `'bb'`.

However, when trying to log the `JSON.stringify(r.args)`, we could see that the actual value is 
`{"ids[]":"aa","ids[]":"aa"}`
(by the way, it seems strange why an object can contain two exactly the same keys)
And of course, when stringifying the content back to query string using `qs.stringify(r.args)`, it becomes 
`'ids%5B%5D=aa&ids%5B%5D=aa'`

This seems to be a strange behavior, especially the value of `r.variables.args` is correct (which is `'ids[]=aa&ids[]=bb'`). Or am I misusing something? Correct me if I misunderstand the purpose of this feature please.

**Comment by xeioex** [comment]
Hi @Reginald-Yoeng-Lee,

Currently `r.args` getter does not support multiple values with the same key. `r.variables.args` is just a URI part after `?` sign (so it is identical to original URI).

If you want to modify URI arguments with multiple values with identical keys consider `querystring` module.

```js
import qs from 'querystring';

function handler(r) {
     let args = qs.parse(r.variables.args);
     // modify args
    
    // stringify back using qs.stringify(args);
}
```

**Comment by Reginald-Yoeng-Lee** [comment]
@xeioex 
Great thanks for the reply and help.

Before your clarifying, I thought the `r.args` is just assigned by using `qs.parse(r.variables.args)`. I suggest this (feature?) could be indicated on the [official documents](https://nginx.org/en/docs/njs/reference.html). In fact, nothing about `r.variables.args` has been mentioned all over the official documents (if I didn't miss something). The `r.variables.args` comes up to me only after my searching from the previous issues.

Btw, the documents of njs are really quite simple. 

Last but not least, thanks again for the time.

**Comment by xeioex** [comment]
@Reginald-Yoeng-Lee 

Thanks for your feedback.

>I suggest this (feature?) could be indicated on the official documents

I think, I will be easier to improve r.args getter to support multiple values.
