### ISSUE TITLE
vm->retval always returns undefined after using promise

### ISSUE THREAD

**Issue by renhax** [nginx/njs#464]
Hi,

I'm having this simple js code use promise, but vm->retval always returns undefined after the execution.

```
function resolveImm() {
    return new Promise(resolve => {resolve("success")});
}

async function handler(event) {
    console.log("abc");
    let x = await resolveImm();
    console.log(x);
    return event.request;
}
```

The way we are calling vm is
```
njs_vm_call(vm, function, function_input, 1);
njs_vm_run(vm);
output = njs_vm_retval(vm);
```
This works fine without any promise in the js code.

Look more into njs code, the retval is set to undefined is because the promise fulfilled queue is empty, the promise task was never added to the queue indeed, maybe because it was resolved immediately?

Can I get some help to understand what's the issue here? Do we suppose to get the function output from vm->retval for async js function? Or is there anything with our js code?

Thanks in advance!

**Comment by xeioex** [comment]
Hi @renhax,

> njs_vm_call()

this method just calls a single JS function. Async functions return Promise object.
You have to call njs_vm_run() to process as many pending events as possible.

Specifically in your example, the following sequence would return a:

 njs_vm_call(vm, test, input, 1);
njs_vm_run(vm);
njs_vm_retval(vm);

In general, njs does not implement event loop by itself,
so a host environment is expected to process async events and feed them to
njs using njs_vm_post_event().

Take a look at  ngx_js_call
https://github.com/nginx/njs/blob/master/nginx/ngx_js.c#L78.

Please note that, if truly async operation (like r.subrequest())
is called, ngx_js_call() will return NGX_AGAIN meaning that you have to
call njs_vm_run() later when external operation finishes.
For example for r.subrequest() this is done in 
https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L3190
 
You are expected to call njs_vm_run() while it returns NJS_AGAIN.
The execution is finished when njs_vm_run() returns NJS_OK or NJS_ERROR.

>njs_vm_retval(vm);

also, njs_vm_retval(vm) will be a last executed statement.

nginx module, uses ngx_js_retval() and r.setReturnValue()
https://github.com/nginx/njs/blob/master/nginx/ngx_js.c#L121

if r.setReturnValue() was called ngx_js_retval() returns it, and not 
njs_vm_retval()

A more advanced unit test which emulates parallel execution of several VMs and
external event loop: https://github.com/nginx/njs/blob/master/src/test/njs_unit_test.c#L22028

**Comment by xeioex** [comment]
>How do we get the function return statement works with promise?

Take a look at the it is done in the modules:

r.setReturnValue():
https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L2158

r.variables['var_name']:
https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L1077
https://github.com/nginx/njs/blob/master/nginx/ngx_js.c#L121

So, the designated return value is stored outside of VM `r.setReturnValue()`,
the `r.variables['var_name']` looks at that return value first when returning the value for `r.variables['var_name']`

**Comment by renhax** [comment]
Thanks @xeioex,

Does that mean we have to integrate njs_vm through `ngx_http_js_module`? 

Sorry about the confusion, some background on how we integrate with njs. We only use njs_vm as a javascript engine, but not rely on any Nginx module. In our c code, we have something like,
```
while (1) {
   njs_vm_create();
   njs_vm_compile();
   njs_vm_start();
   njs_vm_call();
   njs_vm_run();
   njs_vm_retval();
}
```

We always expect the function has a return statement, so that we can process the function output. for example,
```
function handler(event) {
    return event.request;
}
```

The returned output can always be read from `vm->retval`. However after merged the latest 0.7.3 NJS runtime, if there is a promise or async syntax in js function, we found the returned output can't be read from `vm->retval`. For example,
```
function resolveImm() {
    return new Promise(resolve => {resolve("success")});
}

async function handler(event) {
    console.log("abc");
    let x = await resolveImm();
    console.log(x);
    return event.request;
}
```

For the example in `ngx_http_js_module`, seems `setReturnValue` need be called to set the correct return value. But in our use case, there are two issues,
1) Our returned object is generated within the function inside the vm, how can it be set outside the vm?
2) Our js engine is not running with nginx module, how is `setReturnValue` be used here?

Sorry about this many info here, really appreciate the help here.

**Comment by xeioex** [comment]
Hi @renhax,

Sorry for the late reply, I somehow missed your last comment.

>Our js engine is not running with nginx module, how is setReturnValue be used here?

What I was suggesting is implementing your own global object. The same way as nginx module introduces [ngx](https://github.com/nginx/njs/blob/master/nginx/ngx_js.c#L188) object.

Regarding async functions, the proper way to get the correct return value is to use promise chains or async/await.
There are many examples in `test/js`, for [example](https://github.com/nginx/njs/blob/master/test/js/async_add.t.js#L6).

**Comment by renhax** [comment]
Thanks for the suggestion here, we are working on storing asyc output into a new global object, probably a new field in vm. Hopefully it can solve the issue here. Appreciate for the help!
