### ISSUE TITLE
Can use njs implement http tunnel proxy?

### ISSUE THREAD

**Issue by fishioon** [nginx/njs#466]
Like https://github.com/chobits/ngx_http_proxy_connect_module

**Comment by fishioon** [comment]
At stream js_pread handle http connect request.
1. response http ok to client
2. set dynamic upstream with url

How implement 1 step?

**Comment by xeioex** [comment]
@fishioon 

>How implement 1 step?

Yes, at this moment, it is not possible to send anything to a client BEFORE any data is received from the upstream.
This is a limitation.

**Comment by fishioon** [comment]
Sad. Can combine http and stream in one context?
At http handle connect request set dynamic upstream. Then use stream proxy to the upstream

**Comment by xeioex** [comment]
> Can combine http and stream in one context?

you can double proxy. Take a look [at](https://github.com/lcrilly/nginx2squid/).
