### ISSUE TITLE
var kills

### ISSUE THREAD

**Issue by drsm** [nginx/njs#47]
```js
>> var x = 1;
undefined
>> var x = x * x;
undefined
>> x
NaN
>> (function() { var x = 1; var x = x * x; return x; })()
1
>>
```

**Comment by xeioex** [comment]
Fixed by patch for #46

**Comment by drsm** [comment]
No, it isn't duplicate. It is CLI related problem. Updated.

**Comment by drsm** [comment]
Hi!
the issue seems to been fixed by https://github.com/nginx/njs/commit/48e02ed8bfd06ce8e12cb0d2594d6a85a2decf50

**Comment by xeioex** [comment]
Fixed by https://github.com/nginx/njs/commit/48e02ed8bfd06ce8e12cb0d2594d6a85a2decf50
