### ISSUE TITLE
proxy_pass is taking precedence of js_content

### ISSUE THREAD

**Issue by Taymindis** [nginx/njs#487]
I am current having some logic and need to be done by validating the request_body before proxy_pass

E.g.

```nginx

        js_content main.verifyBody;
         proxy_pass http://backend;
             
```
###### main.js
```js

   function verifyBody(r) {

    if( r.requestBody ...... ) {
           r.warn("forbidden"); 
           r.return(403);
    }


    ....
    ....
  }
```

But somehow proxy_pass taking precedence and the js function not actually triggered.

**Comment by xeioex** [comment]
Hi @Taymindis,

proxy_pass and js_content set a [content phase handler](http://nginx.org/en/docs/dev/development_guide.html#http_phases). Only one content phase handler is available.
The last directive overwrites the handler.

The [standard way](https://github.com/nginx/njs-examples#authorizing-requests-based-on-request-body-content-http-authorization-request-body) is to use an internal redirect and two locations.

**Comment by Taymindis** [comment]
You’re right and I almost forgot the term. Just wondering if njs could add on one more directive on `precontent` handler will be great.
