### ISSUE TITLE
timeout for ngx.fetch()?

### ISSUE THREAD

**Issue by lifeofguenter** [nginx/njs#489]
How can one set the timeout for a ngx.fetch() call?

**Comment by xeioex** [comment]
@lifeofguenter,

Right now, [the timeout value for ngx.fetch is 10 seconds, at it is non-configurable.](https://github.com/nginx/njs/blob/master/nginx/ngx_js_fetch.c#L622)

We may consider making it changeable.

**Comment by xeioex** [comment]
@lifeofguenter 

Feel from to test the [patch](https://gist.github.com/xeioex/269c9eebd0cea8878397cbbaba90fb33) with the following directives

    * js_fetch_timeout (for example `js_fetch_timeout 5s;`)
    * js_fetch_verify
    * js_fetch_buffer_size
    * js_fetch_max_response_buffer_size

**Comment by ppathard** [comment]
This would really help if we have capability to increase timeout.
