### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [nginx/njs#491]
Hey there!

I belong to an open source security research community, and a member (@salmonx) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by lcrilly** [comment]
Please report any security-related issues concerning njs to security-alert@nginx.org. For our mutual convenience, specifically mention njs in the subject and follow the [CVSS v3.1](https://www.first.org/cvss/v3.1/specification-document) specification.

See https://nginx.org/en/security_advisories.html for confirmation of the contact method.

**Comment by JamieSlome** [comment]
Thanks for your response @lcrilly 👍 

We have just sent an e-mail to the elected address. We do follow the CVSS specification which can be found in the report.

Let me know if you have any questions and I will be happy to help!
