### ISSUE TITLE
Buffer.concat() ignores start index of buffer created with Buffer.subarray()

### ISSUE THREAD

**Issue by gallarda** [nginx/njs#494]
If I create a new buffer with Buffer.subarray() of a parent buffer using a "start" index and then try to join that buffer with another using Buffer.concat(), data is copied from the beginning of the parent instead of honoring the "start" index.

If I copy the subarray buffer to a new buffer using Buffer.from() first, Buffer.concat() behaves as expected.

Example code:
```
var buff1=Buffer.from([1,2,3,4,5,6,7,8,9]);
var slicedBuff = buff1.subarray(4,8);

var buff2=Buffer.from([0,0,0,0]);

var buff3 = Buffer.concat([slicedBuff, buff2]);
console.log(buff3)
```

In node.js, the correct output is:
`<Buffer 05 06 07 08 00 00 00 00>`

In njs, the erroneous output is:
`Buffer [1,2,3,4,0,0,0,0]`

**Comment by gallarda** [comment]
This issue was identified in njs 0.5.3.  After upgrading to njs 0.7.2, the issue no longer exists.

**Comment by xeioex** [comment]
Duplicate of #458.
