### ISSUE TITLE
Is it possible to make gRPC call?

### ISSUE THREAD

**Issue by ivanmakarychev** [nginx/njs#496]
There is an [example](http://nginx.org/en/docs/njs/node_modules.html#protobuf) of making gRPC messages, but is it possible to make gRPC calls from njs? Our use case is to send some information about a request to a gRPC service for validation.

**Comment by xeioex** [comment]
Hi @ivanmakarychev,

You may try to experiment with making njs subrequest to a location with [grpc_pass](http://nginx.org/en/docs/http/ngx_http_grpc_module.html).

**Comment by ivanmakarychev** [comment]
Thanks, @xeioex. I'll try that.
