### ISSUE TITLE
[Question] Njs is not allowed to be used in rtmp/application blocks?

### ISSUE THREAD

**Issue by Fenny** [nginx/njs#498]
According to the documentation the context which njs is allowed to be used is http/server, but I assume it doesn't work for RTMP?
```nginx
rtmp {
    server {
        listen 1935;

        # not allowed?
        #js_path "/etc/nginx/njs/";
        #js_import main from test.js;

        application live {

        }
    }
}

**Comment by xeioex** [comment]
Hi @Fenny, 

Yes, it does not work for rtmp blocks, but in addition to http it also works for [stream](http://nginx.org/en/docs/stream/ngx_stream_js_module.html) blocks.
