### ISSUE TITLE
Error thrown from async function can not be caught

### ISSUE THREAD

**Issue by Reginald-Yoeng-Lee** [nginx/njs#500]
Let's say we have an async function
`fn = async () => throw new Error('something wrong');`
And somewhere else we call this function with the try-catch
```
try {
  await fn();
} catch (err) {
  // log the error or whatever
}
// do the rest stuff
```

However, the `catch` clause does NOT work. The `Error` could not be caught and the lines behind `catch` could never be reached. Meanwhile an "unhandled promise rejection" error message is printed on the log.

Currently, we have to use a (clumsy?) workaround like _wrap the async function with another function_
```
const callFn = () => fn().catch(err => {
  // log the error and **return anything logical except an Error**
});
await callFn();
// do the rest stuff
```

`async` `await` is the great syntactic sugar and we're excited about introducing it to njs. Just we hope it can work more like the normal js.

njs version: v0.7.1

**Comment by xeioex** [comment]
Hi @Reginald-Yoeng-Lee,

Thanks for the report. Feel free to test it before the next release.
