### ISSUE TITLE
How to access js_var variable in js script

### ISSUE THREAD

**Issue by Holy-Shine** [nginx/njs#505]
Hi,
If I defined a variable with `js_var` directive, then how to access it in other js script?
`nginx.conf` just as follows:
```nginx
....
http {
  js_import test.js;
  js_var $foo "bar";
  ...
  location /whatever {
         js_body_filter test.func;
 }
}
```
how to access variable `foo` in `test.js`

**Comment by xeioex** [comment]
Hi @Holy-Shine,

you may access all the nginx variables using the [r.variables](https://nginx.org/en/docs/njs/reference.html#r_variables) object. For example, `r.variables.foo` to access "foo" variable.

**Comment by Holy-Shine** [comment]
Got it!, thanks!
