### ISSUE TITLE
Function.prototype.apply() should support array-like objects

### ISSUE THREAD

**Issue by drsm** [nginx/njs#51]
```js
>> (function(){ return Math.max.apply(null, arguments) })(1,2,3)
TypeError: second argument is not an array
    at native (native)
    at anonymous (:1)
    at main (native)
```

**Comment by lexborisov** [comment]
Hi Artem (@drsm ),

Please, try [this patch](https://gist.github.com/e9f6ed57579ce773b86dedb325679c0f) for solve the issue.

**Comment by xeioex** [comment]
@drsm BTW,

non-primitive `length` properties, are not supported yet, as for example in:
```js
> String.prototype.concat.apply('a', {length:{valueOf:function() {return 2}},  0:'b', 1:'c'})
'abc'
```
Some internal mechanisms need to be refactored.

**Comment by drsm** [comment]
@lexborisov 
Hi Alexander!

```js
>> String.prototype.concat.apply('', { length: Object(3), 0: 'a', 1: 'b', 2: 'c' })
''
```
maybe add some generic ```njs_arraylike_get_length``` implementation, if this possible?
It will be also needed in #72 

also, if we're moving to ES6, this should be [fixed](https://tc39.github.io/ecma262/#sec-tolength) too:
```js
>> String.prototype.concat.apply('', { length: -1, 0: 'a', 1: 'b', 2: 'c' })
MemoryError
```

**Comment by drsm** [comment]
@xeioex 
I didn't see your answer.

so, everything OK then, except ```ToLength```, Array.prototype.slice is also affected, maybe fix this in a separate patch.

**Comment by lexborisov** [comment]
@drsm 
I committed this patch to the `master` branch.
With the next patch, we will refactoring the code and add the implementation of `toLength` function.

Thank you for the report!
