### ISSUE TITLE
adding new request header?

### ISSUE THREAD

**Issue by prof-alazhary** [nginx/njs#544]
Hi everyone, 

I'm using the `js_content` directive to intercept and manipulate the request and apply my own logic, and I'm using `r.subrequest`,
Now I want to inject/append a new request header to the request itself before calling `r.subrequest` , but as per the documentation: `r.headersIn` is a read-only object. So what's the proper way to apply this??

ex:
```js
function myFun(r){
//here I want to append a new header?
r.subrequest(...)
}
```

Thanks

**Comment by xeioex** [comment]
Hi @prof-alazhary,

In nginx, you add new headers using [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) is a subrequest location.

**Comment by prof-alazhary** [comment]
@xeioex 
Thanks for your response, I think It's an alternative way to achieve this.
but It would make things hard to me :smile: , because I was intend to add the header with a dinamyc value that cames from the cookies by njs code: 
```js
 const cookies = r.headersIn["Cookie"]; //r.requestBody
 const cookiesObj = parseCookiesToJSON(cookies);
 const agent_token = cookiesObj.agent_token;
 // then doing something like: r.headers["Authorization"] = `Bearer ${agent_token}`;
```

**Comment by prof-alazhary** [comment]
Thanks a lot It's very inspiring!
