### ISSUE TITLE
[Question] How to exit "safe" mode? Function constructor is not working by default.

### ISSUE THREAD

**Issue by fuweichin** [nginx/njs#558]
How to exit "safe" mode? or simply how do I construct a function instance? I got TypeError: function constructor is disabled in "safe" mode.

njs 0.7.5
nginx 1.22.0

**Steps to Reproduce:**
1. preload.js
```js
function construct(Function, args) {
  switch (args.length) {
    case 0:
      return new Function();
    case 1:
      return new Function(args[0]);
    case 2:
      return new Function(args[0], args[1]);
    case 3:
      return new Function(args[0], args[1], args[2]);
    case 4:
      return new Function(args[0], args[1], args[2], args[3]);
    default:
      throw new Error('Too many arguments for ' + Function.name);
  }
}
let functions = {};
function init(){
  // ...
  functions['add'] = contruct(Function, ['a', 'b', 'return a + b;']);
  // ...
}
init();
function setHeaders(r){
  
}
export default {setHeaders};
```
2. nginx.conf
```nginx
js_import preload from "preload.js";
server {
  location / {
    # ...
    location ~* \.html$ {
      js_header_filter preload.setHeaders;
    }
  }
}
```

**Expected Result**
Function constructor is supported since ([0.3.6](http://nginx.org/en/docs/njs/changes.html#njs0.3.6)), right?

**Actual Result:**

> TypeError: function constructor is disabled in "safe" mode
>   at Function (native)

**Additional Information:**

I'm working on a HTTP Preload project across Node.js, Java (GraalVM) and Nginx (njs),

Since `eval` is not implemented, and `Function` constructor also is disabled by default, I cannot pass user-defined functions, like "conditions" in JSON below.

```json
{
  "$schema": "../../../preload-manifest/preload-v1.schema.json",
  "manifestVersion": 1,
  "conditions": {
    "supportsModulepreload": "function(userAgentData, headers){return userAgentData.brands.some(function(e){return e.brand==='Chromium'&&parseInt(e.version)>=66);})}"
  },
  "resources": {
    "/index.html": [
      {"rel": "preload", "href": "/assets/index.css", "as": "style"}
    ],
    "/index.html supportsModulepreload": [
      {"rel": "modulepreload", "href": "/src/foobar.js"},
      {"rel": "modulepreload", "href": "/lib/foo.js"},
      {"rel": "modulepreload", "href": "/lib/bar.js"},
      {"rel": "modulepreload", "href": "/src/qux.js"}
    ]
  }
}
```

**Comment by xeioex** [comment]
Hi @fuweichin,

`eval()` and `Function()` ctor are intentionally disabled (they only available in CLI mode (standalone njs shell)).
So, at this moment there is no way to enable them for nginx without modifying the source code.
To enable it, add `options.unsafe = 1;` [here](https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L4257) and recompile the module.

**Comment by fuweichin** [comment]
Thanks, it works anyhow. The project has been published.

![feature-comparison](https://user-images.githubusercontent.com/1687235/178155530-6f5d5fdd-1da9-48c1-aa34-ca7601dd3583.png)
