### ISSUE TITLE
How to write from njs to console in a custom format?

### ISSUE THREAD

**Issue by nettnikl** [nginx/njs#563]
## Situation
I'm trying to setup logging for a set of nginx instances in my company. These are heavily relying on njs scripts for the functionality, and produce information that is critical to collect in the given environment.

However the responsibles would like to receive json formatted logs.

## Question
Is it possible to log the output of njs in json?

## Possible Solutions
Similar to the access_log with log_format specifying a json-like format - seems not possible (similar to how it is impossible to specify it for error messages in general).

Access to console.write, which is not possible during non-cli sessions (scripted, as in this cases, only the HTTP client with its ngx.log is available). The ngx.log however prints with a big format, not easily parseable for services down the line, as it's not json.

## Related

https://github.com/nginx/njs/issues/76

https://stackoverflow.com/questions/4246756/is-it-possible-to-specify-custom-error-log-format-on-nginx
https://stackoverflow.com/questions/16711573/nginx-error-log-format-documentation
https://serverfault.com/questions/805855/how-to-change-the-timestamp-format-in-error-logs?rq=1

**Comment by nettnikl** [comment]
Hi @drsm , thanks for your reply and the smart solution!

Sadly, this is not applicable for my use case, so let me explain. We are actually using this approach for access logs.
However, during one request, there are multiple log entries to be written. So, if i don't want to do a subrequest to a dedicated log-endpoint for each log entry to write, i will have to find a way to print multiple lines. Preferably while the request is being handled, not collected in the end.

**Comment by drsm** [comment]
@nettnikl 
> However, during one request, there are multiple log entries to be written. 

So, why not to aggregate 'em into array?

```js
var logdata = [];
function logsome(data) {
  logdata.push(data);
}
function logflush(r) {
  r.variables['whatever'] = JSON.stringify(logdata);
}
```
> i will have to find a way to print multiple lines

Maybe `fs.writeFileSync` as a last resort.

**Comment by nettnikl** [comment]
Thank you again for your suggestions!
I will look into both the following day(s).
