### ISSUE TITLE
first argument undefined is not a string or Buffer-like object

### ISSUE THREAD

**Issue by Fantros** [nginx/njs#564]
Error: unhandled promise rejection: TypeError: first argument undefined is not a string or Buffer-like object
I'm getting this error and I can't solve it, can you help me?

**Comment by xeioex** [comment]
Hi @Fantros,

First of all, please provide your code.
Most probably you are providing unexpected arguments for a Buffer method.

**Comment by Fantros** [comment]
Hello, problem solved. POST Attack has arrived.
