### ISSUE TITLE
json string truncated

### ISSUE THREAD

**Issue by jameschu** [nginx/njs#565]
Hi,

I am working on a drm function using njs. However it seems like njs truncate our X509Certificate string. But njs works fine in console mode (very strange). 

I don't know if it is a bug (string too long?).

njs

0.7.5

nginx

nginx version: nginx/1.23.0
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)
built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'

code 
-------------
const fs = require('fs');

function request(r) {
    let root = {
        'cpix:CPIX': {
            $: {
                'name': 'test',
                'xsi:schemaLocation': 'urn:dashif:org:cpix cpix.xsd',
                'xmlns:xenc': 'http://www.w3.org/2001/04/xmlenc#',
                'xmlns:pskc': 'urn:ietf:params:xml:ns:keyprov:pskc',
                'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
                'xmlns:cpix': 'urn:dashif:org:cpix',
                'xmlns:ds': 'http://www.w3.org/2000/09/xmldsig#'
            }
        }
    };
 
    // Delivery data list
    let deliveryDataList = {
        'cpix:DeliveryData': {
            'cpix:DeliveryKey': {
                'ds:X509Data': {
                    'ds:X509Certificate': 'XXXXhzCCA2+gAwIBAgIULYj8wTdDT4n6ntwT+DA27HMzm18wDQYJKoZIhvcNAQELBQAwUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMB4XDTIwMDIyNTE1MTk1N1oXDTI0MDIyNDE1MTk1N1owUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtJ9ctGvoBbRq1mKQJeKTbZUO7VBU6HJhBwcTnwJSLiI/kBxvUZNJ5ANCW52aTVojFEsXfV3mAlEG9VHcBH8w+7OC8DW5qWHVAwpLX5Ek150k7b3vWgkJepe+RIGY3jjuH1X+uHVERgojw+9pmw3ubNBxP102IkU/LYytb5AD+Yo0uSpl9ybh4M8vRnnjNqPHkISsm3NRmh3G41VNLJ5NHlHe3uUn7AY2ZwnGxsaK4ZC5VVZ7ehh5vWZePTicWxV/WJVT3a/2btaaAzlIWHVquRW6JmBg+kEieUGMfxJULsWBKEhMQhCP44djX8ATJ7HCqwL7x29MhYlU27g6Jn6GdU2Gf+VgPevBZ9NB8MSYz1q1IuVecnzZ9nQfENGH9591Zkzzhb+YkWzQ+0pFghq6XXAyY7GTDIyuEKxheCS+/bpb7zg0W8/TN1SH4d2w2XmeeM4qJAyJuTpyXdEnS5A8C49+sARg8wPXnodnb65zYWqbxydmzjxEW7FWJOLBjY8kNj4pdnGs+4D1tzGztGePfgK+c6aPYmj+237fAhz68c9hQWpAx+VtX8eswwJb1jRgX9DFWL+chBIWRClrLNmJq9/lZgAVZ1eQf6E14E/Q2cRo4Jt3C/8zoYhVXhnDjf0CmJMabvgBl/aoysm4HztVxmscy4rapncgkH7PJ3yTYwkCAwEAAaNTMFEwHQYDVR0OBBYEFJateGZum2Ox5fZr+FruVIrQczojMB8GA1UdIwQYMBaAFJateGZum2Ox5fZr+FruVIrQczojMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGFBDDWs7PL0Utl+B6q0FC1Eve1X7ecyRHHqb6rqDUrHM63IWHM0OYSIx9TZtsZ/+JOffLeUENL3oocrysB8ngvif0xckBomyEr44egpLZQXfZhwqqf4etWrXXWB4b1OrhtTqTxIx8aZxwLR9vnHy9HMZ0Z5MolcxRVtE29BIZz5lZRBj1wTXS3Kn7P2dJNrENqXIhkBteSLnb7+CknA+nit6rAPiwKQTo2D7yCLAGtODpokNjGfj0LgNVx2VNAYKf5seCC7PuKqqKUAj1I2Td0RT8KrdiIcIisFITkE6e1x9f4nb5R5k4LJtzofI8QewcunWJFcXOgbp6KA2RnQmZRy75Mqqt4W7M9XjAUXilkbMqqYIC1qolWouJhYNN+DmSEkeoZMOOPMUmTC1/TZO97FZCizVBF7Nog02T2bZZdKWSUIfU3W6gfcs05z7tY70BliqMNcFDeSXCw66rhwmUtNOkFm0lJoE0+64ju9LRSp7teANP20g9fdYWHX/kaUzVyyv+7Nu1LOampu8l6k7XGI4xCi4jqhXGOLhgZrdwlmx2COM4dyqhIR1mPw8gtWTUwPjARpluU4vFOFJ36hEqNdahDUvSRfXO+lhjoYqW/rvyhk3818wxS7KJZBZNnseYSKc252NP1nqZBZJ0PoeH/Dy5xzZkF6EvXyjIA5YOzZ'
                    // 'ds:X509Certificate': 'short string test' -- short string is fine
                }
            }
        }
    };

    ngx.log(ngx.INFO, JSON.stringify(deliveryDataList));
 
    root['cpix:CPIX']['cpix:DeliveryDataList'] = deliveryDataList;

    ngx.log(ngx.INFO, JSON.stringify(root));

}

export default {request};
----------

log
--------
2022/07/22 12:01:51 [info] 332832#332832: *1 js: {"cpix:DeliveryData":{"cpix:DeliveryKey":{"ds:X509Data":{"ds:X509Certificate":"XXXXhzCCA2+gAwIBAgIULYj8wTdDT4n6ntwT+DA27HMzm18wDQYJKoZIhvcNAQELBQAwUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMB4XDTIwMDIyNTE1MTk1N1oXDTI0MDIyNDE1MTk1N1owUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtJ9ctGvoBbRq1mKQJeKTbZUO7VBU6HJhBwcTnwJSLiI/kBxvUZNJ5ANCW52aTVojFEsXfV3mAlEG9VHcBH8w+7OC8DW5qWHVAwpLX5Ek150k7b3vWgkJepe+RIGY3jjuH1X+uHVERgojw+9pmw3ubNBxP102IkU/LYytb5AD+Yo0uSpl9ybh4M8vRnnjNqPHkISsm3NRmh3G41VNLJ5NHlHe3uUn7AY2ZwnGxsaK4ZC5VVZ7ehh5vWZePTicWxV/WJVT3a/2btaaAzlIWHVquRW6JmBg+kEieUGMfxJULsWBKEhMQhCP44djX8ATJ7HCqwL7x29MhYlU27g6Jn6GdU2Gf+VgPevBZ9NB8MSYz1q1IuVecnzZ9nQfENGH9591Zkzzhb+YkWzQ+0pFghq6XXAyY7GTDIyuEKxheCS+/bpb7zg0W8/TN1SH4d2w2XmeeM4qJAyJuTpyXdEnS5A8C49+sARg8wPXnodnb65zYWqbxydmzjxEW7FWJOLBjY8kNj4pdnGs+4D1tzGztGePfgK+c6aPYmj+237fAhz68c9hQWpAx+VtX8eswwJb1jRgX9DFWL+chBIWRClrLNmJq9/lZgAVZ1eQf6E14E/Q2cRo4Jt3C/8zoYhVXhnDjf0CmJMabvgBl/aoysm4HztVxmscy4rapncgkH7PJ3yTYwkCAwEAAaNTMFEwHQYDVR0OBBYEFJateGZum2Ox5fZr+FruVIrQczojMB8GA1UdIwQYMBaAFJateGZum2Ox5fZr+FruVIrQczojMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGFBDDWs7PL0Utl+B6q0FC1Eve1X7ecyRHHqb6rqDUrHM63IWHM0OYSIx9TZtsZ/+JOffLeUENL3oocrysB8ngvif0xckBomyEr44egpLZQXfZhwqqf4etWrXXWB4b1OrhtTqTxIx8aZxwLR9vnHy9HMZ0Z5MolcxRVtE29BIZz5lZRBj1wTXS3Kn7P2dJNrENqXIhkBteSLnb7+CknA+nit6rAPiwKQTo2D7yCLAGtODpokNjGfj0LgNVx2VNAYKf5seCC7PuKqqKUAj1I2Td0RT8KrdiIcIisFITkE6e1x9f4nb5R5k4LJtzofI8QewcunWJFcXOgbp6KA2RnQmZRy75Mqqt4W7M9XjAUXilkbMqqYIC1qolWouJhYNN+DmSEkeoZMOOPMUmTC1/TZO97FZCizVBF7Nog02T2bZZdKWSUIfU3W6gfcs05z7tY70BliqMNcFDeSXCw66rhwmUtNOkFm0lJoE0+64ju9LRSp7teANP20g9fdYWHX/kaUzVyyv+7Nu1LOampu8l6k7XGI4xCi4jqhXGOLhgZrdwlmx2COM4dyqhIR1mPw8gtWTUwPjARpluU4vFOFJ36hEqNdahDUvSRfXO+lhjoYqW/rvyhk3818wxS7KJZBZNnseYSKc252NP1nqZBZJ0PoeH/Dy5xzZkF6EvXyjIA5YOzZ"}}}}

2022/07/22 12:01:51 [info] 332832#332832: *1 js: {"cpix:CPIX":{"$":{"name":"test","xsi:schemaLocation":"urn:dashif:org:cpix cpix.xsd","xmlns:xenc":"http://www.w3.org/2001/04/xmlenc#","xmlns:pskc":"urn:ietf:params:xml:ns:keyprov:pskc","xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance","xmlns:cpix":"urn:dashif:org:cpix","xmlns:ds":"http://www.w3.org/2000/09/xmldsig#"},"cpix:DeliveryDataList":{"cpix:DeliveryData":{"cpix:DeliveryKey":{"ds:X509Data":{"ds:X509Certificate":"XXXXhzCCA2+gAwIBAgIULYj8wTdDT4n6ntwT+DA27HMzm18wDQYJKoZIhvcNAQELBQAwUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMB4XDTIwMDIyNTE1MTk1N1oXDTI0MDIyNDE1MTk1N1owUzELMAkGA1UEBhMCVVMxFTATBgNVBAoMDEJ1eURSTSwgSW5jLjEtMCsGA1UEAwwkS2V5T1MgQ1BJWCBBUEkgKFNlbGZFbmNvZGVyIFNhbXBsZSkKMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtJ9ctGvoBbRq1mKQJeKTbZUO7VBU6HJhBwcTnwJSLiI/kBxvUZNJ5ANCW52aTVojFEsXfV3mAlEG9VHcBH8w+7OC8DW5qWHVAwpLX5Ek150k7b3vWgkJepe+RIGY3jjuH1X+uHVERgojw+9pmw3ubNBxP102IkU/LYytb5AD+Yo0uSpl9ybh4M8vRnnjNqPHkISsm3NRmh3G41VNLJ5NHlHe3uUn7AY2ZwnGxsaK4ZC5VVZ7ehh5vWZePTicWxV/WJVT3a/2btaaAzlIWHVquRW6JmBg+kEieUGMfxJULsWBKEhMQhCP44djX8ATJ7HCqwL7x29MhYlU27g6Jn6GdU2Gf+VgPevBZ9NB8MSYz1q1IuVecnzZ9nQfENGH9591Zkzzhb+YkWzQ+0pFghq6XXAyY7GTDIyuEKxheCS+/bpb7zg0W8/TN1SH4d2w2XmeeM4qJAyJuTpyXdEnS5A8C49+sARg8wPXnodnb65zYWqbxydmzjxEW7FWJOLBjY8kNj4pdnGs+4D1tzGztGePfgK+c6aPYmj+237fAhz68c9hQWpAx+VtX8eswwJb1jRgX9DFWL+chBIWRClrLNmJq9/lZgAVZ1eQf6E14E/Q2cRo4Jt3C/8zoYhVXhnDjf0CmJMabvgBl/aoysm4HztVxmscy4rapncgkH7PJ3yTYwkCAwEAAaNTMFEwHQYDVR0OBBYEFJateGZum2Ox5fZr+FruVIrQczojMB8GA1UdIwQYMBaAFJateGZum2Ox5fZr+FruVIrQczojMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGFBDDWs7PL0Utl+B6q0FC1Eve1X7ecyRHHqb6rqDUrHM63IWHM0OYSIx9TZtsZ/+JOffLeUENL3oocrysB8ngvif0xckBomyEr44egpLZQXfZhwqqf4etWrXXWB4b1OrhtTqTxIx8aZxwLR9vnHy9HMZ0Z5MolcxRVtE29BIZz5lZRBj1wTXS3Kn7P2dJNrENqXIhkBteSLnb7+CknA+nit6rAPiwKQTo2D7yCLAGtODpokNjGfj0LgNVx2VNAYKf5seCC7PuKqqKUAj1I2Td0RT8KrdiIcIisFITkE6e1x9f4nb5R5k4LJtzofI8QewcunWJFcXOgbp6KA2RnQmZRy75Mqqt4W7M9XjAUXil
-------

**Comment by xeioex** [comment]
Hi @jameschu,

You are hitting the nginx's limitation of 2048 bytes for a single log string.
Here, `r.log()` and `ngx.log()` use `ngx_log_error` which ends up [here](https://github.com/nginx/nginx/blob/master/src/core/ngx_log.c#L113). Nginx log is designed for arbitrary size strings.

I will update the docs, to make this clear.

**Comment by jameschu** [comment]
thanks for quick response
