### ISSUE TITLE
ngx_stream_js_module: ngx.fetch in js_filter function

### ISSUE THREAD

**Issue by hcmf-wice** [nginx/njs#567]
Hi!

I'm working on an MQTT reverse proxy.

In the js_preread handler function I can do this:
```js
function preread(s) { 
    s.on("upload", function(data, flags) { 
        ngx.fetch("http://...", {…}).then(reply => reply.text().then(result => { 
            if (isResultCool(result)) { 
                s.allow(); 
            } else { 
                s.deny(); 
            } 
        })); 
    } 
} 
```
and it works (so the connection gets allowed or denied based on the async result of my fetch call).

But in the js_filter handler function, this doesn't work:
```js
const DISCONNECT = Uint8Array.of(224, 0); 
function filter(s) { 
    s.on("upload", function (data, flags) { 
        ngx.fetch("http://...", {…}).then(reply => reply.text().then(result => { 
            if (isResultCool(result)) { 
                s.send(data); 
            } else { 
                s.send(DISCONNECT); 
            } 
        })); 
    }); 
} 

```
So basically s.send(...) doesn't seem to work if I call it in the callback of an asynchronous function.

My questions are:
1. Is this intentional, or a bug?
2. If it's intentional, is there any way to make a synchronous HTTP call in the js_filter handler method, so that I can call s.send(…) synchronously based on the info from the HTTP result?

This is very frustrating because there is some information I only have in the MQTT SUBSCRIBE and PUBLISH messages (which are only passed to the filter function), so I cannot use the info in the CONNECT message to make this call to the HTTP endpoint.

Also, some information only becomes available on the HTTP server (to which I try to make a call) after the connection was already established, so it’s not an option to get and cache all the info in the preread phase.

Thanks in advance.

**Comment by xeioex** [comment]
Hi @hcmf-wice,

>Is this intentional, or a bug?

Originally, the stream callback code was not designed for async methods like `ngx.fetch()`.

As of now, there is a problem with `s.send()` and async calls, because `s.send()` is context dependant.
The direction it sends to, depends on in which context it is called. For e.g., when is called from `upload` callback the direction to a server.

If you prepare a minimal standalone example, it will be easier for me to look into it in details. 
I am thinking about adding a new method, where it will be possible to specify a direction for data to be sent to.

**Comment by hcmf-wice** [comment]
Hi @xeioex , thanks for your answer.

Here is a standalone example, please let me know if you have any problem running it:
[https://github.com/hcmf-wice/NginxExample](https://github.com/hcmf-wice/NginxExample)

**Comment by xeioex** [comment]
Hi @hcmf-wice,

Thanks, I will look into it next week.

**Comment by xeioex** [comment]
Hi @hcmf-wice,

Feel from to test the following [patch](https://gist.github.com/xeioex/b6d5855779d55fe39407929ce488c5f2).

The patch fixes the problem I described above, so s.send() should send data in a proper direction, even if it was called asynchronously.

**Comment by hcmf-wice** [comment]
Hi @xeioex !
Sorry for the late response, I was on a vacation last week. Anyway, thanks for the patch, I have tried it today and it seems to solve my problem: with it, the subscribe and publish messages go through even when s.send(...) is called asynchronously. Thank you very much!

Will this patch be part of a later release?

**Comment by xeioex** [comment]
Hi @hcmf-wice,

Yes, I am planning to add the patch for the next release.

**Comment by xeioex** [comment]
Was fixed in https://github.com/nginx/njs/commit/569292e0a74f2b1ec09566f3329f82bdd0d58e87.
