### ISSUE TITLE
RegExp exec doesn't work 

### ISSUE THREAD

**Issue by chartera** [nginx/njs#568]
```
const regex1 = RegExp('foo*', 'g');
const str1 = 'table football, foosball';
let array1 = regex1.exec(str1) // should be Array ["foo"] but is null

'nginx'.match( /ng/i )  // also null
``` 

v. [0.7.6](https://github.com/nginx/njs/releases/tag/0.7.6)

**Comment by xeioex** [comment]
Hi @chartera,

Thank you for the report.
Please, clarify how do you get njs binary? If you build njs by yourself, please share the configure log output.

Here is the njs in official docker container.
```
$ docker run -i -t nginx:latest /usr/bin/njs
interactive njs 0.7.6

v.<Tab> -> the properties and prototype methods of v.

>> 'nginx'.match( /ng/i )
[
 'ng'
]
>> const regex1 = RegExp('foo*', 'g'); regex1.exec('table football, foosball')
[
 'foo'
]
>> 
```

I am also getting the same result when njs is used as an nginx module.
