### ISSUE TITLE
nginx: [emerg] failed to create JS VM in /home/nginx/conf/nginx.conf +23

### ISSUE THREAD

**Issue by bdhidoc** [nginx/njs#57]
nginx.conf
....

js_include hello.js; +23
 server{
.....
}
}

# /home/nginx/bin/nginx -t 
nginx: [emerg] failed to create JS VM in /home/nginx/conf/nginx.conf +23

**Comment by xeioex** [comment]
Hi @bdhidoc,

Thank you for the report.

Please, report the way you compile njs and nginx.
Most probably there is the issue with pcre library path.

**Comment by bdhidoc** [comment]
nginx-1.14.0
./configure 
....
--add-module=../path-to-njs/nginx \ 

----------------
path-to-njs
./configure
configuring for Linux 3.10.0-862.el7.x86_64 x86_64
checking for C compiler: cc
 + using GNU C compiler
 + gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
checking for GCC __builtin_expect() ... found
checking for GCC __builtin_unreachable() ... found
checking for GCC __builtin_prefetch() ... found
checking for GCC __builtin_clz() ... found
checking for GCC __attribute__ visibility ... found
checking for GCC __attribute__ malloc ... found
checking for GCC __attribute__ aligned ... found
checking for struct tm.tm_gmtoff ... found
checking for altzone ... not found
checking for posix_memalign() ... found
checking for getrandom() ... found
checking for PCRE library ... found
 + PCRE version: 8.38
checking for editline library ... found

**Comment by bdhidoc** [comment]
pcre
--------------
libpcre.a  libpcrecpp.a  libpcrecpp.la  libpcre.la  libpcreposix.a  libpcreposix.la  pkgconfig


system:
#name -an 
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 
#free -m
              total        used        free      shared  buff/cache   available
Mem:           3888         417        2818           8         652        3210
Swap:          6143           0        6143

**Comment by xeioex** [comment]
you can install a prebuilt packet for redhat linux
http://nginx.org/en/docs/njs/install.html

**Comment by whitekyo** [comment]
hi, I have the same question

$ ./configure
configuring for CYGWIN_NT-6.1 2.11.1(0.329/5/3) unknown
checking for C compiler: cc
 + using GNU C compiler
 + gcc version 7.3.0 (GCC)
checking for GCC unsigned __int128 ... not found
checking for GCC __builtin_expect() ... found
checking for GCC __builtin_unreachable() ... found
checking for GCC __builtin_prefetch() ... found
checking for GCC __builtin_clz() ... found
checking for GCC __builtin_clzll() ... found
checking for GCC __attribute__ visibility ... found
checking for GCC __attribute__ malloc ... found
checking for GCC __attribute__ aligned ... found
checking for struct tm.tm_gmtoff ... found
checking for altzone ... not found
checking for posix_memalign() ... found
checking for getrandom() ... found
checking for explicit_bzero() ... found
checking for PCRE library ... found
 + PCRE version: 8.40
checking for editline library ... not found
checking for editline in /usr/include/edit ... not found
checking for editline in /usr/include ... not found
 - building interactive shell is not possible
checking for expect ... not found
 - expect tests are disabled

**Comment by xeioex** [comment]
hi @whitekyo, 

You need libedit here https://thrysoee.dk/editline/
Please, note that this library is not essential for nginx modules, it is needed only for njs CLI (http://nginx.org/en/docs/njs/cli.html)

If you simply want to play with njs, it is better to run it inside a docker container
here are the examples: https://github.com/xeioex/njs-examples

**Comment by whitekyo** [comment]
thanks but when I compile libedit  

$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking build system type... i686-pc-cygwin
checking host system type... i686-pc-cygwin
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 8192
checking how to convert i686-pc-cygwin file names to i686-pc-cygwin format... fu
nc_convert_file_noop
checking how to convert i686-pc-cygwin file names to toolchain format... func_co
nvert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|
^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_imp
lib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking whether ln -s works... yes
checking for gawk... (cached) gawk
checking for nroff... /usr/bin/nroff
checking for tgetent in -lncurses... no
checking for tgetent in -lcurses... no
checking for tgetent in -ltermcap... no
configure: error: libncurses, libcurses, or libtermcap is required!

I dont know what's the libncurses, libcurses, or libtermcap

**Comment by Muten-007** [comment]
hello，I met the same error today using the latest njs module. What is the final reason？I did not use the docker .I
 used the source code , got the nginx exe file , and then used the commond in nginx javascript module , and got the error. How should I do now to solve the problem?

**Comment by xeioex** [comment]
Hi @Muten-007,

Try to disable "xml" module using environment variable NJS_LIBXSLT=NO while configuring nginx (or other external modules) https://hg.nginx.org/njs/rev/1f84f3c34bb0

Make sure that "xml" is disabled. Look at the configure output of njs configure.
