### ISSUE TITLE
proxy_cache_background_update on ignored using subrequest

### ISSUE THREAD

**Issue by dfex55** [nginx/njs#573]
Requesting a location through njs subrequest that has caching enabled with `proxy_cache_background_update on` and `proxy_cache_use_stale updating` will never get stale data.

That seems to be a bug, because requesting the same location directly, the cache returns stale data.

In the provided example there are three locations:

`/longRunningRequest/`:
Has a js handler delaying the result for two seconds

`/longRunningRequestCached/`:
Has a cache that is valid for one second, allowing stale data while updating and proxy passes to /longRunningRequest/

`/longRunningRequestThroughNjs/`:
Has a js handler making a subrequest to /longRunningRequestCached/

Expected behavior:
`/longRunningRequestCached/` and `/longRunningRequestThroughNjs/` will always return immediately (except for the first request) and serving stale data if needed.

What actually happens:
`/longRunningRequestCached/` works as described above
`/longRunningRequestThroughNjs/` is blocking every time the cache entry has to be renewed.

nginx config:
```nginx
    js_import myjs.js;

    server {

        location = /longRunningRequestThroughNjs/ {
                js_content myjs.requestToCachedLongRunningRequest;
        }

        location = /longRunningRequest/ {
                js_content myjs.simulateLongRunningRequest;
        }

        location = /longRunningRequestCached/ {
                proxy_connect_timeout 1s;
                proxy_read_timeout 12s;
                proxy_set_header Content-Length "";
                proxy_pass http://127.0.0.1/longRunningRequest/;
                proxy_ignore_headers X-Accel-Expires Expires Cache-Control Set-Cookie;
                proxy_hide_header Set-Cookie;
                proxy_buffering on;

                proxy_cache_use_stale http_404 error timeout invalid_header updating
                                        http_500 http_502 http_503 http_504;

                proxy_cache_background_update on;
                proxy_cache_lock on;
                proxy_cache_lock_age 50s;
                proxy_cache_lock_timeout 60s;
                proxy_cache_revalidate on;
                proxy_cache MYCACHE;
                proxy_cache_valid 200 1s;
                proxy_cache_key $http_accept_encoding$uri;

                add_header x-cache-status $upstream_cache_status;
        }
    }
```
myjs.js:
```javascript

function delayed(r) {
  r.return(200);
}

function simulateLongRunningRequest(r) {
  setTimeout(delayed, 2000, r);
}

function requestToCachedLongRunningRequest(r) {
  r.subrequest('/longRunningRequestCached/')
    .then(reply => {
      r.return(200);
    })
    .catch(_ => r.return(401));
}

export default { simulateLongRunningRequest, requestToCachedLongRunningRequest };


```

**Comment by xeioex** [comment]
Hi @dfex55,

Thank you for the reproduction steps, will take a look.

**Comment by xeioex** [comment]
Hi @dfex55,

What you see, is the limitation of an nginx subrequest mechanism. `r.subrequest()` creates an internal nginx [subrequest](http://nginx.org/en/docs/dev/development_guide.html#http_subrequests) with `NGX_HTTP_SUBREQUEST_BACKGROUND` and `NGX_HTTP_SUBREQUEST_IN_MEMORY` flags.

`proxy_cache_background_update` directive is also relies on subrequests. The main problem is: nginx does not support nested subrequest at this point.

Spefically the code of the cache update below checks the `r->background` flag, which is 1 for `r.subrequest()` and does not try to make a background update:
https://github.com/nginx/nginx/blob/fb0890aee646ec4bb2b5c57f113f5bed433be7cc/src/http/ngx_http_upstream.c#L903-L906

Feel free to ask the same question on https://trac.nginx.org/.

**Comment by dfex55** [comment]
Hi @xeioex,

thank you for investigating and clarifying.

I created a trac ticket for that:
https://trac.nginx.org/nginx/ticket/2389

Please close this issue.
