### ISSUE TITLE
Help to add browserslist support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [nginx/njs#582]
see https://github.com/browserslist/browserslist/issues/733#issuecomment-1263422707

browserslist need your help to add njs runtime [js compliance information](https://nginx.org/en/docs/njs/compatibility.html) to some database like browserslist-db.

**Comment by ai** [comment]
[Browserslist](https://browsersl.ist/) is a config with target browsers for the project. You can use this config to find what polyfills you have to add. For instance, you can avoid adding polyfills if target browsers don’t need it.

Browserslist is a very popular config. It already used by Autoprefixer, Babel, webpack, postcss-preset-env. CRA adds it by default.

**Comment by xeioex** [comment]
Hi @ai,

>You can open an issue and mention me, I will add extra details.

Please, provide me with the list of information required to create a `.browserslistrc`. A link to a `.browserslistrc` for project like njs would help.

**Comment by ai** [comment]
Browserslist is a library with Can I Use data, which automatically look and parse config to get target browsers from end-users queries like `last 2 versions`.

We have a [JS library](https://github.com/browserslist/browserslist) and [Rust](https://github.com/browserslist/browserslist-rs).

**Comment by xiaoxiangmoe** [comment]
@ai Is there any tutorial and spec for providing Can I Use data?

**Comment by ai** [comment]
There is a spec for queries:

1. https://github.com/browserslist/browserslist#queries
2. https://github.com/browserslist/browserslist/blob/main/grammar.w3c-ebnf

**Comment by xiaoxiangmoe** [comment]
@ai Is there any tutorial for providing Can I Use data?

Should we provide data by creating a PR to  https://github.com/Fyrd/caniuse repo?

**Comment by ai** [comment]
It depends on your programming language and environment.

I am using Can I Use data from `caniuse-lite` npm package.

**Comment by jirutka** [comment]
FYI, If you need browserslist just to configure the Babel transpiler, you can use [babel-preset-njs](https://github.com/jirutka/babel-preset-njs) instead. This doesn’t deal with polyfills though.

**Comment by xiaoxiangmoe** [comment]
@jirutka But some other tool like swc need using . browserslistrc
