### ISSUE TITLE
Does classes support?

### ISSUE THREAD

**Issue by Fantros** [nginx/njs#597]
For example code like this:
`
class Test {
  constructor() {}
} 
`

`js_content Test; `
Can it be used?

**Comment by Fantros** [comment]
Is there a function like ngx.exit() in Nginx + Lua in NJS?

**Comment by xeioex** [comment]
Hi @Fantros,

There is [njs.on('exit')](http://nginx.org/en/docs/njs/reference.html#njs) callback.
