### ISSUE TITLE
Can njs call nginx c function

### ISSUE THREAD

**Issue by ggcking** [nginx/njs#602]
how njs call the nginx internal funciton, such as ngx_delete_file.

**Comment by xeioex** [comment]
hi @ggcking,

There are no access to C-level function from NGINX/NJS, but there is [node.js compatible FS API](http://nginx.org/en/docs/njs/reference.html#njs_api_fs).

**Comment by ggcking** [comment]
I want to delete some files by njs, how to do that?

**Comment by xeioex** [comment]
```js
var fs = require('fs');

function my_handler(r) {
    fs.unlink(<file_path>);
}
```

you may also, since [0.7.8](https://nginx.org/en/docs/njs/changes.html#njs0.7.8) use `ngx.conf_prefix` to get  the directory where nginx is currently looking for configuration.

**Comment by ggcking** [comment]
it's work, thks.
