### ISSUE TITLE
how to close file after call openSync() ?

### ISSUE THREAD

**Issue by ggcking** [nginx/njs#603]
hi, I use openSync(filepath) to open one file, and read. how to close it?

**Comment by Swanty** [comment]
Have you tried `closeSync`?

**Comment by ggcking** [comment]
yes，I found closeSync(),  It is recommended to write more detailed documents。

**Comment by xeioex** [comment]
Hi @ggcking,

if you use async API, like

```js
const fs = require('fs').promises;

async function() {
let fh = await fs.open('file/path');

// do fh.read(), fh.write()

// fh.close()
```

Also, fd is closed automatically  when current request finishes, but it is not recommended to rely on it.
