### ISSUE TITLE
JWK key support 

### ISSUE THREAD

**Issue by ram-vet** [nginx/njs#604]
Any immediate plans to add [JWK key support](https://github.com/nginx/njs/blob/85ce59830cd54186c0125982614ff9a61efdc5b0/external/njs_webcrypto_module.c#L1748) to Webcrypto module?

**Comment by xeioex** [comment]
Hi @ram-vet,

We plan to add JWK support approximately in 3 month time frame.

**Comment by xeioex** [comment]
Committed in https://github.com/nginx/njs/commit/50e7c9b291188962cf21348eeb3659dcbc930721.

**Comment by ram-vet** [comment]
@xeioex when can we expect the next release with this commit ?

**Comment by xeioex** [comment]
Hi @ram-vet,

We plan to release JWK as a part of 0.7.10 on Feb 7th 2023.
