### ISSUE TITLE
ngx_stream_js_module: ngx.fetch

### ISSUE THREAD

**Issue by moricatzo** [nginx/njs#608]
Hi, 

I was checking improved async callback support for s.send() in stream module. 

There was another [ticket](https://github.com/nginx/njs/issues/567) about it that I tried out.
@hcmf-wice provided a standalone example where ngx.fetch was used and caused some issue that did not allow the client1 to subscribe.

The above bug was fixed (it can subscribe now) however the other client2 cannot publish messages.

That I can see in logs:
`2023-01-18 14:16:39 rp         | 2023/01/18 13:16:39 [error] 43#43: *44 pending events while proxying connection, client: 172.18.0.1, server: 0.0.0.0:1883, upstream: "172.18.0.2:18831", bytes from/to client:36/4, bytes from/to upstream:4/0`

I also created an example, [NginxExample](https://github.com/moricatzo/NginxExample).
Please find details in README file.
Can you please look into it?

Thank you in advance

**Comment by moricatzo** [comment]
> [return?](https://github.com/moricatzo/NginxExample/blob/main/nginx/stream_mqtt.js#L46)

Updated.

**Comment by moricatzo** [comment]
> Hi @moricatzo,
> 
> Please also share the njs version (`njs.version`). I will look into the issue, thanks for the detailed reproduction steps, it helps a lot.
> 
> My initial guess, there is a problem in detecting appropriate direction for the `s.send()` method. BTW, by any change didn't you try [s.sendDownstream()](https://nginx.org/en/docs/njs/reference.html#s_send_downstream) or [s.sendUpstream()](https://nginx.org/en/docs/njs/reference.html#s_send_downstream) ?

Hi @xeioex,

I have tried but experiencing the same error as for `s.send()` method.

njs version is 0.7.9.

**Comment by moricatzo** [comment]
@xeioex
Is there anything else that I can help with?

**Comment by xeioex** [comment]
Hi @moricatzo,

I am looking at it now. 

this is the debug log after I hit `./client/pub.sh 1883 client2 topic3 qwe`
https://gist.github.com/xeioex/eee3513c7a8f4ab3f694f0739f324be8

njs works as expected, until the stream proxy module [finalizes](https://github.com/nginx/nginx/blob/master/src/stream/ngx_stream_proxy_module.c#L1759) the stream connection because the remote side closed the connection:

```
2023/01/30 20:23:51 [info] 1995752#1995752: *1 client disconnected, bytes from/to client:36/4, bytes from/to upstream:4/21
2023/01/30 20:23:51 [debug] 1995752#1995752: *1 finalize stream proxy: 200
```

At this point the session is closed unconditionally before the fetch finishes.

It is not clear what stream/njs should do in such a case (njs has pending events, but the session connection is closed)  in general. Any idea?

**Comment by xeioex** [comment]
hi @moricatzo,

Here is the funny workaround that I found while looking into ngx_stream_proxy_module source code.

[proxy_half_close](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_half_close) directive may help here.

1) enable in, `proxy_half_close on;`
2) unfortunately this is not enough, as a PUB client should not close the connection by itself right away.

In my case the following shell command works
`bash -c "echo qwe; sleep 2"  | mosquitto_pub -V 311 -d -h localhost -p 1883 -i client2 -t topic3 -l`

by forcing mosquitto_pub to expect its input from stdin we delay the connection closing.

as a result, nginx/njs has time to make a fetch request.

**Comment by xeioex** [comment]
Hi @moricatzo,

I wonder did any advice helped you?

**Comment by moricatzo** [comment]
Hi @xeioex,

Sorry for the late response.

I have tried your workaround and it is working altough it is not that lucky to have delay on publisher side.
Unfortunately, this solution does not fit into my usecase.
