### ISSUE TITLE
Reload Interval for js_preload_object

### ISSUE THREAD

**Issue by mwcng** [nginx/njs#609]
Hi, 

I was wondering if there any plans to introduce a reload interval option to the js_preload_object directive?

Right now the only way I can load data from a file that I update every couple of minutes is to read it on every single request and then JSON.parse it, which is not optimal, so it would be really nice to have the option of data automatically refreshing in the background every X minutes/seconds for js_preload_object without having to reload or restart nginx.

**Comment by xeioex** [comment]
Hi @mwcng,

This will not be easy. js_preload_object is preloaded once as a JS object during configure phase at master process, to be shared by forked worker later.

js_preload_object was designed mostly for the static data, or the dynamic data that do not change too often. In this case you can just reload your nginx process from time to time.

**Comment by mwcng** [comment]
Hi @xeioex , thanks for answering. 

Sad to hear that, but I hope this gets considered in the future regardless, maybe not for js_preload_object specifically but for something else that's more designed to handle dynamic data. Would be a very welcome addition, at least from my point of view.

As far as reloading nginx on every update goes, I have considered it, but haven't checked yet if it would be truly worth it or even efficient to reload that often because it would mean reloading every minute at the moment.
