### ISSUE TITLE
Idiomatic way for caching in njs

### ISSUE THREAD

**Issue by thekip** [nginx/njs#622]
I need to get an application config (from REST endpoint) to determine the route to redirect to. 
I want to cache this config for some time for 5 minutes for example. I'm wondering what is the idiomatic way to cache this config and fetching this endpoint in each request? 

Is a filesystem a good place for that? Or maybe I can use some global variable for cache? Or may be this task is in general not for njs and should be implemented in application server?

**Comment by xeioex** [comment]
hi @thekip 
The Idiomatic for caching is using [nginx own cache](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path) and use [r.subrequest()](https://nginx.org/en/docs/njs/reference.html#r_subrequest) to get the data from the upstream or from the cache.

With nginx cache you will have automatic cleanup, expiration, etc. Unfortunately, the is no cache for ngx.fetch() so far.

**Comment by thekip** [comment]
Thanks, will try this.
