### ISSUE TITLE
njs cli util throws SyntaxError: Illegal export statement

### ISSUE THREAD

**Issue by thekip** [nginx/njs#623]
I'm trying to check a very basic example from the docs:

```js
function hello(r) {
    r.return(200, "Hello world!");
}

export default {hello};
```

then:

```bash
njs /etc/nginx/test.js
```

It returns  `Illegal export statement in ...`

So i don't understand what i'm doing wrong. It seems `njs` binary could not understand export statements. 

I wanted to use it for unit tests, or at least just testing. But looks like it completely useless and i should tests everything through the nginx configuration. 

```bash
root@6b0569c59618:/# njs -V
0.7.9
```

**Comment by drsm** [comment]
Hi! @thekip 
As for now, the `export` statement works only for files that are `import`ed.

**Comment by thekip** [comment]
Does this mean I can use imports in files used in configurations? Or its some specific syntax supported only in njs binary?

**Comment by xeioex** [comment]
@thekip 

>Does this mean I can use imports in files used in configurations?

Yes, you can. You just cannot load a module as a main script file.

**Comment by thekip** [comment]
What you mean by `module` ? If it's from regular js terminology (file with import or export statements) so how  than I can use imports if a module couldn't be loaded as main script? 

Could you show this on the example?

**Comment by xeioex** [comment]
@thekip 

I mean, [ES6 module](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/).


```
Module basics
An ES6 module is a file containing JS code. There’s no special module keyword; a module mostly reads just like a script. There are two differences.

ES6 modules are automatically strict-mode code, even if you don’t write "use strict"; in them.

You can use import and export in modules.
```

**Comment by thekip** [comment]
Ok, what is main script file?

**Comment by drsm** [comment]
@thekip 

> Could you show this on the example?

Just don't use `export` in the entry point script when using CLI.
BTW, circular dependencies are not supported also.
