### ISSUE TITLE
How to send a header defined in an NJS function to the receiver.

### ISSUE THREAD

**Issue by alex-oliveira** [nginx/njs#635]
I need to know how to make a recipient receive a header that was defined within a function that validates authentication.

My .conf file is like this:

```
js_import authorizer from /usr/share/nginx/lambda/authorizer.js;

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        auth_request /authorizer;

        proxy_pass http://172.20.160.1:8787;

        proxy_set_header X-Custom-Header "$http_x_custom_header ";
    }

    location /authorizer {
        internal;
        js_content authorizer;
    }
}
```

My NJS function looks like this:

```
export default function handler(r) {

    r.headersOut['X-Custom-Header'] = 'MY VALUE';

    return r.return(200);

 }
```

My recipient does not receive desired header.

Although I've already searched a lot, I don't know where I'm going wrong.

**Comment by xeioex** [comment]
Hi @alex-oliveira,

after `auth_request` subrequest is executed, there is special way to get the variables of a subrequest using [auth_request_set](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request_set).

For your example:
```
auth_request_set $my_header $sent_http_x_custom_header;
...
proxy_set_header X-Custom-Header $my_header;
```

**Comment by alex-oliveira** [comment]
> Hi @alex-oliveira,
> 
> after `auth_request` subrequest is executed, there is special way to get the variables of a subrequest using [auth_request_set](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request_set).
> 
> For your example:
> 
> ```
> auth_request_set $my_header $sent_http_x_custom_header;
> ...
> proxy_set_header X-Custom-Header $my_header;
> ```

Hi @xeioex !

Wow!
Thanks for the tip!
Worked perfectly!
