### ISSUE TITLE
Host headers no longer allowed in fetch

### ISSUE THREAD

**Issue by jgriffith** [nginx/njs#638]
In njs 0.7.10 a breaking change was introduced.

When I use the fetch function in njs 0.7.9 I can set the Host header to a different value than the host in the url.

https://github.com/nginx/njs/blob/9645655a22d588cebb27bda9c455c8fac7b74ceb/nginx/ngx_js_fetch.c#L527

example nginx js code:

```js
async function dynamoQuery(r){
  let res = await ngx.fetch("http://localhost:8081", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-amz-target": "DynamoDB_20120810.Query",
      Host: "dynamodb.us-east-1.amazonaws.com", // SET HOST HEADER for aws-proxy
    },
    body: `{...}`,
  });
  let body = await res.text();
  r.return(200, body);
}
```

In the new njs 0.7.10 this is not possible anymore. The Host header is always set to the host in the url.

This is because the `host` header is now a forbidden header name.

https://github.com/nginx/njs/blob/ead31a59fafb281a8c6604198f34efd518e1ac99/nginx/ngx_js_fetch.c#L2200

This is a problem for me because I use the fetch function to proxy requests to the aws-proxy docker sidecars. I need to be able to set the Host header to a different value than the host in the url.

This change is also rolling out all the latest nginx docker images causing our services to fail.

https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile#L8

**Comment by xeioex** [comment]
Hi @jgriffith,

The changes were implemented in accordance with [fetch API requirements regarding forbidden methods](https://fetch.spec.whatwg.org/#fetch-method).

**Comment by xeioex** [comment]
@jgriffith 

Did you tried to use [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)

**Comment by jgriffith** [comment]
I checked, and the aws-sigv4-proxy only respects the `Host` header

https://github.com/awslabs/aws-sigv4-proxy/blob/26b15d857b7e09f6a921c8ca0410e4a2d97c76bd/handler/proxy_client.go#L138

I think I'll be able to rewrite the nginx logic like this to bypass the `host` header issue.

```
function dynamoQuery(r){
  r.subrequest("/_aws_query_dynamo", 
                "key=my-dynamo-key",
                function(res){
                    r.return(200, res.responseText);
                }
              );
}
```

```
    location = /_aws_query_dynamo {
      internal;
      set $upstream         "http://aws-proxy:8081/";
      proxy_method          POST;
      proxy_set_header      "Content-Type"  "application/x-amz-json-1.1";
      proxy_set_header      "x-amz-target" "DynamoDB_20120810.Query";
      proxy_set_header      "Host" "dynamo.us-east-1.amazonaws.com";
      proxy_pass            $upstream;
      proxy_set_body        "....$arg_key....";
    }
```

You can close this issue if you'd like.

**Comment by xeioex** [comment]
@jgriffith,

According to [configuration options](https://github.com/awslabs/aws-sigv4-proxy#configuration) you can fix the 
host to proxy to using `aws-sigv4-proxy ...  --host dynamo.us-east-1.amazonaws.com` if anyway it is fixed in nginx/njs code.




host | String | Host to proxy to
-- | -- | --

**Comment by jgriffith** [comment]
@xeioex 

Yes, the `--host` option is another possible workaround.  The downside of the `--host` option is that it locks the proxy to only use a single AWS service.  For example, I can't use secretsmanager, dynamo, and lambda, all with the same proxy.  I'll need to run 3 proxies, one for each service.

Thank you for your help on this.

**Comment by jgriffith** [comment]
I was also able to confirm this isn't an issue with nodejs

This nodejs (v19.3.0) test file

```js
  let response = await fetch("http://localhost:8080", {
    headers: {
      Host: "foobar.com",
    },
  });
  let text = await response.text();
  console.info(text);
```

returns "foobar.com" with this njs config

```
js_import debug.js;
location = / {
   js_content debug.test;
}
```

```
async function test(r) {
  r.return(200, r.headersIn["host"]);
}
```

**Comment by xeioex** [comment]
@jgriffith,

> I was also able to confirm this isn't an issue with nodejs

thanks for the information, I will look into the details in nodejs. Probably we need to relax the requirement if address in URL is ip address or localhost.

**Comment by xeioex** [comment]
@jgriffith,

Thanks for your feedback, I am going to remove special treatment for "forbidden headers" in the next release.
