### ISSUE TITLE
eIDAS and ecstatement

### ISSUE THREAD

**Issue by mrsingh88** [nginx/njs#641]
Hi 
we want to parse an incoming eIDAS certificate and fetch the qcstatement from it in nginx.
I have installed ngx module for it and would like to know is it possible to shell scripting so as to include openssl to do the job?
or is it possible to do it in njs itself ?

**Comment by xeioex** [comment]
Hi @mrsingh88,

Shell scripting is not supported in njs.

**Comment by mrsingh88** [comment]
Hi @xeioex 
Thank you for your reply. Is there any other method available which could be used to parse qcstatement from an eidas certificate for every request on nginx ?

thanks
Charandeep

**Comment by lcrilly** [comment]
> or is it possible to do it in njs itself ?

It should be possible with njs. There is an example about reading the SAN from a X.509 certificate. I expect this solution can be adapted to read the QCstatement from a X.509v3 extension.

https://github.com/nginx/njs-examples#certificates
https://github.com/nginx/njs-examples/blob/master/njs/http/certs/js/x509.js

**Comment by mrsingh88** [comment]
> > or is it possible to do it in njs itself ?
> 
> It should be possible with njs. There is an example about reading the SAN from a X.509 certificate. I expect this solution can be adapted to read the QCstatement from a X.509v3 extension.
> 
> https://github.com/nginx/njs-examples#certificates https://github.com/nginx/njs-examples/blob/master/njs/http/certs/js/x509.js

This comment helped me to achieve my goal. Thank you.!
