### ISSUE TITLE
Internal Redirect does NOT work within `js_body_filter`

### ISSUE THREAD

**Issue by AyodeAwe** [nginx/njs#645]
I have a use case where I need to perform an internal redirection after parsing data returned in the `js_body_filter` handler, so I have tried to use `r.internalRedirect` within the `js_body_filter` handler but no response is received; the browser just hangs indefinitely.

`default.conf`
```
server {
    ...

    location named_location {
        ...

        js_body_filter gateway.filterListResponse;
    }
}
```

`gateway.js`
```
function filterListResponse(r, data, flags) {
​
  if (r.uri !== '/files/') {
      r.log('redirect!');
      r.internalRedirect('/files/');
      return;
  }
​
  r.sendBuffer(data, flags);
  return;
}
```

In the above snippets I simply try to redirect the user to the `/files/` path with the `if` condition. If execution falls outside of the `if` condition, everything works as expected, but otherwise (when I actually want to redirect to the `/files/` path with `r.internalRedirect('/files')`), no response is returned, and the browser only keeps loading indefinitely. I have also tested redirecting to a named location configured in `default.conf` but I get the same behavior.

**Comment by ajschmidt8** [comment]
@xeioex, any thoughts on this?

I'm experiencing the same issue.

**Comment by drsm** [comment]
`r.internalRedirect` should fail with an exception inside a filter.

**Comment by xeioex** [comment]
Hi @AyodeAwe, @ajschmidt8 

Calling r.internalRedirect() in `js_body_filter` is too late. At this moment a response header was already sent to a client.
r.internalRedirect() can be callled in `js_content` handler BEFORE anything was sent to a client. See the proper example of r.internalRedirect() usage [here](https://github.com/nginx/njs-examples#authorizing-requests-based-on-request-body-content-http-authorization-request-body).

To make things clearer, I am going to add an exception throwing when r.r.internalRedirect() is called inappropritely, as @drsm  suggested.
