### ISSUE TITLE
SEGV in njs_scope_value

### ISSUE THREAD

**Issue by Jminis** [nginx/njs#647]
<html>
<body>
<p>Hello. I would like to inform you about an error related to SEGV that I encountered while performing fuzzing.</p>
<h1>📌 Main Information</h1>

Project | njs
-- | --
Fuzzer | libfuzzer
Fuzz binary | LLVMFuzzerTestOneInput in /src/njs/external/njs_shell.c:775
Sanitizer | ASAN
Crash Type | SEGV
Crash State | njs_scope_value in /src/njs/src/njs_scope.h:82:12

<pre><code class="language-c">INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 4107131323
INFO: Loaded 1 modules   (29349 inline 8-bit counters): 29349 [0x930fd0, 0x938275), 
INFO: Loaded 1 PC tables (29349 PCs): 29349 [0x938278,0x9aacc8), 
./njs_process_script_fuzzer: Running 1 inputs 1 time(s) each.
Running: ./njs_process_script_fuzzer_poc/njs--njs_process_script_fuzzer--crash-923f4ff7f4e78210eebcf0db9c86b37c-2023-05-23-23:21:25
AddressSanitizer:DEADLYSIGNAL
=================================================================
==29==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x000000594df1 bp 0x7ffd41114b90 sp 0x7ffd41113ec0 T0)
==29==The signal is caused by a READ memory access.
==29==Hint: address points to the zero page.
    #0 0x594df1 in njs_scope_value /src/njs/src/njs_scope.h:82:12
    #1 0x594df1 in njs_scope_valid_value /src/njs/src/njs_scope.h:92:13
    #2 0x594df1 in njs_vmcode_interpreter /src/njs/src/njs_vmcode.c:398:9
    #3 0x587c07 in njs_vm_start /src/njs/src/njs_vm.c:561:11
    #4 0x56f4d3 in njs_process_script /src/njs/external/njs_shell.c:999:19
    #5 0x56f4d3 in LLVMFuzzerTestOneInput /src/njs/external/njs_shell.c:775:16
    #6 0x440703 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #7 0x42be62 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #8 0x43170c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #9 0x45ac42 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #10 0x7f02b4090082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #11 0x42202d in _start (/out/njs_process_script_fuzzer+0x42202d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /src/njs/src/njs_scope.h:82:12 in njs_scope_value
==29==ABORTING
</code></pre>
<h1>🎯 Fuzz target Information</h1>

<ul>
<li>LLVMFuzzerTestOneInput in <code>njs_shell.c</code></li>
</ul>
<pre><code class="language-c">int
LLVMFuzzerTestOneInput(const uint8_t* data, size_t size)
{
    njs_vm_t      *vm;
    njs_opts_t    opts;
    njs_str_t     script;
    njs_vm_opt_t  vm_options;

    static uintptr_t uptr[] = {
        (uintptr_t) NULL,
    };

    static njs_vm_meta_t metas = {
        .size = njs_nitems(uptr),
        .values = uptr
    };

    if (size == 0) {
        return 0;
    }

    njs_memzero(&amp;opts, sizeof(njs_opts_t));

    njs_vm_opt_init(&amp;vm_options);

    vm_options.init = 1;
    vm_options.backtrace = 0;
    vm_options.metas = &amp;metas;
    vm_options.ops = &amp;njs_console_ops;

    vm = njs_create_vm(&amp;opts, &amp;vm_options);

    if (njs_fast_path(vm != NULL)) {
        script.length = size;
        script.start = (u_char *) data;

        (void) njs_process_script(vm, NULL, &amp;script);
        njs_vm_destroy(vm);
    }

    return 0;
}
</code></pre>
<ul>
<li>input data</li>
</ul>
<pre><code>66 6F 72 28 0A 0A 74 28 72 72 3D 3E 72 76 3D 7C 72 77 3B 3B 72 72 3D 3E 72 76 3D 3E 72 3D 3E 72 3D 76 3D 3E 72 3D 3E 72 3D 72 76 3D 76 3D 3E 72 3D 3E 72 3D 73 3D 3E 72 3D 76 3D 72 3E 3E 3D 72 3D 76 3D 72 72 74 42 42 24 41 29 42
</code></pre>
<h1>🧐 Detailed Analysis</h1>

<ul>
<li>The following is a debugging screen at the point where a Null Deref occurs in a 2-dimensional array</li>
</ul>

![njs_debug](https://github.com/nginx/njs/assets/68144858/233d7bbc-7502-4a8b-b87f-250f925d8ace)

<ul>
<li>Ultimately, it attempts to READ the data of a NULL pointer structure</li>
</ul>
<pre><code class="language-c">Thread 1 &quot;njs_process_scr&quot; received signal SIGSEGV, Segmentation fault.
0x0000000000594df1 in njs_vmcode_interpreter ()
─── Assembly ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0x0000000000594df1  ? mov    (%rax),%r12
 0x0000000000594df4  ? mov    %r12,%rax
 0x0000000000594df7  ? shr    $0x3,%rax
 0x0000000000594dfb  ? mov    0x7fff8000(%rax),%al
 0x0000000000594e01  ? test   %al,%al
 0x0000000000594e03  ? jne    0x5a4218 &lt;njs_vmcode_interpreter+96728&gt;
 0x0000000000594e09  ? movzbl (%r12),%r13d
 0x0000000000594e0e  ? mov    $0x7,%edi
 0x0000000000594e13  ? mov    %r13d,%esi
 0x0000000000594e16  ? callq  0x458240 &lt;__sanitizer_cov_trace_const_cmp1&gt;
─── Breakpoints ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[1] break at 0x000000000058c844 for njs_vmcode_interpreter hit 1 time
─── Expressions ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── History ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Memory ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       rax 0x0000000000000018           rbx 0x00007fffffffd5e0        rcx 0x0000000000000003        rdx 0x00000000000000a6
       rsi 0x000000002c9a2980           rdi 0x0000623000000128        rbp 0x00007fffffffd9f0        rsp 0x00007fffffffd5e0
        r8 0x00000000009ab200            r9 0x0000000000000001        r10 0x000000000000000f        r11 0x00000c4a00003caa
       r12 0x0000000000000010           r13 0x0000623000000100        r14 0x0000623000001960        r15 0x0000000000000303
       rip 0x0000000000594df1        eflags [ PF ZF IF RF ]            cs 0x00000033                 ss 0x0000002b        
        ds 0x00000000                    es 0x00000000                 fs 0x00000000                 gs 0x00000000        
─── Source ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Stack ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x0000000000594df1 in njs_vmcode_interpreter
[1] from 0x0000000000587c08 in njs_vm_start
[2] from 0x000000000056f4d4 in LLVMFuzzerTestOneInput
[3] from 0x0000000000440704 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)
[4] from 0x000000000042be63 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long)
[5] from 0x000000000043170d in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))
[6] from 0x000000000045ac43 in main
─── Threads ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[2] id 92 name njs_process_scr from 0x00007ffff7a3823f in __GI___clock_nanosleep+223 at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
[1] id 91 name njs_process_scr from 0x0000000000594df1 in njs_vmcode_interpreter
─── Variables ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
&gt;&gt;&gt;
</code></pre>

</body>
</html>

**Comment by xeioex** [comment]
Hi @Jminis,

Thank you for the report. 

The bug was fixed in https://github.com/nginx/njs/commit/b9c1533fa97c3088c082239744b23de5029f28cd as a fix for another fuzzer report.
And more additional fixes was committed in https://github.com/nginx/njs/commit/893c94e1a9ed0fc241722c831964ebb8bcb67ca3.
