### ISSUE TITLE
When copying "location" header of a subrequest, response body of the subrequest is copied into it as well

### ISSUE THREAD

**Issue by tokumeo** [nginx/njs#648]
I'm getting unexpected behaviour when copying "location" header of a subrequest's response into "location" header of response - it seems that subrequest's response body is copied as well. Here's what curl looks like:
```
# curl -v "http://localhost:45000/_test_copy_location"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 45000 (#0)
> GET /_test_copy_location HTTP/1.1
> Host: localhost:45000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Server: nginx/1.24.0
< Date: Thu, 01 Jun 2023 10:45:47 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< location: /_test_copy_location
< Location: <html>
< <head><title>307 Temporary Redirect</title></head>
< <body>
< <center><h1>307 Temporary Redirect</h1></center>
< <hr><center>nginx/1.24.0</center>
< </body>
< </html>
< 
* Excess found in a non pipelined read: excess = 2, size = 171, maxdownload = 171, bytecount = 0

<html>
<head><title>307 Temporary Redirect</title></head>
<body>
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
* Connection #0 to host localhost left intact
```
Notice two "location" headers and response body data in the second one.

Versions used:
```
ii  nginx                                                   1.24.0-1~bionic                  amd64 
ii  nginx-module-njs                                        1.24.0+0.7.12-1~bionic           amd64 
```

Minimal configuration:
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

load_module modules/ngx_http_js_module.so;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    js_import test_copy_location from njs/test_copy_location.njs;

    server {
        listen       45000;
        server_name  localhost;

        location = /_test_copy_location {
            js_content test_copy_location.test;
        }

        location = /_redirect {
            return 307 "$request_uri";
        }
    }
}
```
njs/test_copy_location.njs
```js
function test(request) {
    function response_callback(response) {
        request.headersOut["location"] = response.headersOut["location"]
        return request.return(response.status, response.responseBody);
    }

    request.subrequest(
        "/_redirect",
        request.variables.args,
        response_callback
    );
}

export default {test};
```
This is also reproducible in nginx 1.21.6 with njs 0.3.6

**Comment by xeioex** [comment]
Hi @tokumeo,

nginx treats the 3xx codes specially, the njs doc also [says](https://nginx.org/en/docs/njs/reference.html#r_return):

```
It is possible to specify either a redirect URL (for codes 301, 302, 303, 307, and 308) 
or the response body text (for other codes) as the second argument
```

So for 3xx codes the second argument set as a Location header.

Still there is a bug that you stepped into. When setting 'location' header, the previous header was not cleared properly, because nginx has a [separate field for location header](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.h#L269) which njs did not clear. As a result you have two Location headers in the output. This will be fixed.

**Comment by tokumeo** [comment]
Hi @xeioex,

```
        location = /_redirect {
            return 307 "$request_uri";
        }
```

is used for creating a minimal config to reproduce the issue. I'm hitting this bug when getting a 3xx response from an upstream server in a subrequest

**Comment by xeioex** [comment]
Hi @tokumeo,

>Subrequest's response body ends up in response headers

That is the way it is done by nginx for 3xx code - it [treats the body argument as a Location header value](https://github.com/nginx/nginx/blob/cb70d5954c65b5683bc1c104bbf2466b73f4aa2b/src/http/ngx_http_core_module.c#L1773), as I already said [above](https://github.com/nginx/njs/issues/648#issuecomment-1574533195) for `r.return()`.

If you want no special treatment of 3xx code consider using other methods as in:
```js
function test(r) {    
    function response_callback(response) {    
        r.headersOut.Location = response.headersOut.Location;
        r.status = response.status;
        r.sendHeader(); 
        // r.send(); to send body.                                                                                                                                   
        r.finish();
    }

    r.subrequest(
        "/_redirect",
        r.variables.args,
        response_callback
    );
}

```

**Comment by tokumeo** [comment]
@xeioex 

Thanks for the clarification. I did not realise that nginx' `return` [directive](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return) and njs' `return` [method](http://nginx.org/en/docs/njs/reference.html#r_return) are essentially the same

**Comment by tokumeo** [comment]
@xeioex 

Thanks a lot for patiently explaining what was wrong with my code :) It took three messages for me to understand that I was using `r.return()` incorrectly. I've fixed my code using the example you provided and can no longer reproduce the issue
