### ISSUE TITLE
NJS Fetch() always adds text/plain;charset=utf-8 to any Content-Type header

### ISSUE THREAD

**Issue by YawningCobra8** [nginx/njs#654]
**The Problem**
Using the ngx.fetch() function results in the Content-Type header having `text/plain;charset=utf-8` appended to anything already present. This results in request failures when the backend system being called only accepts a specific content type (in our case, a third party system accepting only x-www-form-urlencoded).

**Expected Behaviour**
When explicitly setting the Content-Type header in ngx.fetch(), njs should pass _only_ the contents of this explicit header, rather than appending the default text/plain configuration. This will allow for developer controlled overrides to default values for cases where a backend server will reject text/plain.

**How to reproduce**
Have a server that requires Content-Type to be application/x-www-form-urlencoded, and attempt to call the service using a simple ngx.fetch() function, like this
```
const formData = {
        grant_type: 'refresh_token',
        refresh_token: 'dummy'
      };
const requestParams = {
        method: 'POST',
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: formData,
        verify: false
      };
const response = await ngx.fetch('https://some_site.com/api/path', requestParams);
```

Alternatively, this config also produces the error (as do several others, I have personally tried several variations to attempt to workaround this limitation to no avail, such as manually encoding the body, passing the body directly rather than through a variable, explicitly using url encoding for the string rather than relying on a function to encode, etc):
```
const formData = 'grant_type=refresh_token&refresh_token=dummy';
const requestParams = {
        method: 'POST',
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: formData,
        verify: false
      };
const response = await ngx.fetch('https://some_site.com/api/path', requestParams);
```

**Comment by YawningCobra8** [comment]
I believe the portion of code that requires an additional condition to be checked is https://github.com/nginx/njs/blob/master/nginx/ngx_js_fetch.c#L1061

Would adding a check for if the Content-Type header is already set, and if so, don't append the text/plain portion to it, be possible?

**Comment by xeioex** [comment]
Hi @YawningCobra8,

Thanks for pointing out to the problem. I plan to modify the code by setting Content-Type only if it is not set by user.

**Comment by YawningCobra8** [comment]
Thanks @xeioex, really appreciate the speedy response too!

**Comment by xeioex** [comment]
@YawningCobra8 

Feel free to test the following patch: https://gist.github.com/xeioex/4dfe27055be6804b58fa22d2c223f5d6

I plan to commit it after a review.

**Comment by YawningCobra8** [comment]
Thanks @xeioex, I'm using this as part of the nginx-unprivileged docker container so I'll get a custom build of that with this patched into the njs module and test it out.

**Comment by xeioex** [comment]
Hi @YawningCobra8,

I committed the patch, feel free to report issues if any.
