### ISSUE TITLE
Where is the x509.js file located?

### ISSUE THREAD

**Issue by ag0r** [nginx/njs#656]
Looking at [this example](https://github.com/nginx/njs-examples/tree/master#reading-subject-alternative-from-client-certificate-http-certs-subject-alternative), I'm confused where the `import x509 from x509.js;` exists. Is there an external package I need to install to get that file? The example as presented in the repository does not work for me.

Other issues here ([this](https://github.com/nginx/njs/issues/364) and [this](https://github.com/nginx/njs/issues/641)) have appeared to succeed in using that example code, so I'm not sure what I'm missing. Any help would be greatly appreciated.

**Comment by chc-work** [comment]
was there an answer for this?

**Comment by xeioex** [comment]
@chc-work 

[x509](https://github.com/nginx/njs-examples/blob/master/njs/http/certs/js/x509.js) is here.

**Comment by chc-work** [comment]
Thanks. I just found it earlier. They are many examples and code in the https://github.com/nginx/njs-examples/tree/master/njs
