### ISSUE TITLE
Is it possible to process whole request body in 'js_filter -> upload' event handler?

### ISSUE THREAD

**Issue by amelentjev** [nginx/njs#657]
I'm trying to do some processing of whole request body sent from client to server, but without success. 
basic prototype :

nginx.config 

```
stream {
    js_import scripts/my.js;

   server {
        listen       82;
        js_filter my.fixform;
       proxy_pass localhost:80;
   }
}

```
my.js: 

```
function fixform(s) {
    var req = '';
    s.on('upload', function (data, flags) {
        req += data;
        if (flags.last) {
            s.error(data); //logging
            s.send(req,flags);
        } 
    });
}
```

Browser just hangs. Seems to me that on any data chunk received I must send it to backend, but how to deal with situation when some string (which must be processed as whole) is splitted for two data chunks...

**Comment by xeioex** [comment]
hi @amelentjev,

Stream is working on tcp stream level which is quite low level for http traffic. If you want to process http requests, what is the reason to using stream module?
If you want to work with the whole response there are `js_body_filter`, `r.subrequest()` or `ngx.fetch()`.

**Comment by amelentjev** [comment]
I'm using stream module because in http module there is no possibility to work with data going from client (browser) to server, it is working only with responses from server. Or I'm wrong?

**Comment by xeioex** [comment]
Hi @amelentjev,

In HTTP, nginx avoids modifying original request. Instead, [proxy_set_body](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_body) or [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) is recommended if you wants to modify the client's request.
