### ISSUE TITLE
`fetch content length is too large` error w/ `ngx.fetch` using `HEAD`

### ISSUE THREAD

**Issue by ajschmidt8** [nginx/njs#658]
I'm trying to use the `HEAD` method with `ngx.fetch` to verify the existence of a large (`2.2MB`) file, but I'm getting an error.

This is a minimal reproducer of the JS code that I'm trying to run:

```js
async function hello(r) {
  let reply = await ngx.fetch(
    "http://rapidsai-data.s3-website.us-east-2.amazonaws.com/tmp/index.html",
    {
      method: "HEAD",
    }
  );

  r.headersOut["Content-Type"] = "text/plain";
  r.return(200, "Hello world!");
}
```

When I run the code, I get the following error:

```
2023/07/25 02:16:48 [error] 584#584: *177 js exception: Error: unhandled promise rejection: Error: fetch content length is too large, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
172.17.0.1 - - [25/Jul/2023:02:16:48 +0000] "GET / HTTP/1.1" 000 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
```

It looks like this error is being triggered: https://github.com/nginx/njs/blob/b263f0cb0b6cab1605db3dbf44a10cc42348fc63/nginx/ngx_js_fetch.c#L2432-L2434

I would expect that the content length shouldn't matter when using the `HEAD` method as opposed to the `GET` method.

Is this a bug? Or am I misunderstanding things?

**Comment by xeioex** [comment]
Hi @ajschmidt8,

Thanks for reporting the issue, I will fix it. As a workaround consider configuring [js_fetch_max_response_buffer_size](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_fetch_max_response_buffer_size) directive.

**Comment by ajschmidt8** [comment]
@xeioex, just checking in. any updates here?

**Comment by xeioex** [comment]
@ajschmidt8 
I am on it, thanks for prodding.
