### ISSUE TITLE
js_set read requestText is empty

### ISSUE THREAD

**Issue by ourfor** [nginx/njs#659]
I want to use js_set check request body, but request body is empty.
```js
function verify(r: NginxHTTPRequest) {
  const message = r.requestText
  const hash = crypto.createHash('sha256');
  hash.update(message?.toString() ?? "");
  const digest = hash.digest('hex');
  const sign = r.headersIn["X-Sign-Hex"]

  ngx.log(ngx.INFO, `${message?.toString() ?? ""}`)
  ngx.log(ngx.INFO, `${sign} == ${digest} ? ${sign === digest}`)
  if (sign === digest) {
    return 200
  } else {
    return 403
  }
}
```
and `Nginx` config
```nginx
events {}

http {
  js_import main from ../dist/main.js;
  js_fetch_verify off;
  server {
    listen __ADDRESS__:__PORT__;

    location = /health {
      return 200;
    }

    location = /hello {
      js_set $verify main.verify;
      resolver 8.8.8.8 ipv6=off;
      if ($verify = 403) {
        return 403;
      }
      js_content main.hello;
    }

    location = /echo {
      resolver 8.8.8.8 ipv6=off;
      js_content main.test;
    }
  }
}
```

**Comment by lcrilly** [comment]
In your configuration, nginx has no reason to read the request body. `r.requestText` is not populated until nginx will proxy or store the request body.

If your ultimate aim is to sign the entire request before proxying to a backend system then you can *trick* nginx into reading the request body early with the `mirror` directive.

A short explanation in this [blog post](https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-2-protecting-backend-services/#request-body-variable).

**Comment by ourfor** [comment]
> In your configuration, nginx has no reason to read the request body. `r.requestText` is not populated until nginx will proxy or store the request body.
> 
> If your ultimate aim is to sign the entire request before proxying to a backend system then you can _trick_ nginx into reading the request body early with the `mirror` directive.
> 
> A short explanation in this [blog post](https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-2-protecting-backend-services/#request-body-variable).

OK, great, thank you!
