### ISSUE TITLE
Degrades the performance to get the values of all the keys using key() function

### ISSUE THREAD

**Issue by coolkingh** [nginx/njs#666]
Using keys() function we can get all the keys and then to fetch the value of all the keys we have to call get() function in a loop and it will lead to  read locks which degrades the performance in case there is huge number of keys.

Use case :   Multiple users are connected to the persistent connection ( proxying to RDP ) and we want to update the activity of the user in the shared dict and periodic daemon will fetch the activity from the shared dict and update that details in the database. 

If we could have got the value along with key then it would be great.

**Comment by coolkingh** [comment]
@xeioex  I will look into it. Thanks

**Comment by coolkingh** [comment]
There is no items() function currently. I got the below error. I also checked the code but didn't find anything related to items()

`2023/09/06 08:51:35 [error] 17547#17547: js exception: TypeError: (intermediate value)["items"] is not a function`

Below is teh code snippet :-

```
ngx.shared.foo.set("ajay", 1);
ngx.shared.foo.set("amarjeet", 2);
ngx.log(ngx.INFO,ngx.shared.foo.items());

```

**Comment by xeioex** [comment]
Hi @coolkingh,

Yes, there is no items() right now. The question is, will `items()` which returns key-value pairs help with your task?

**Comment by coolkingh** [comment]
Yes, if it return all the key value pairs which are not expired ?

**Comment by xeioex** [comment]
Hi @coolkingh,

Feel free to test the following patch: https://gist.github.com/xeioex/663613ccbc374fdb61893292b7a97c72

The patch adds items() method which returns all non-expired key-value pairs.

**Comment by xeioex** [comment]
Implemented in https://github.com/nginx/njs/commit/fa2c9857d90f827b8d524b85b1e95b4ef1416d5e.
