### ISSUE TITLE
Support for Unicode Aware Mode in Regex

### ISSUE THREAD

**Issue by lancedockins** [nginx/njs#678]
Are there any plans to support unicode-aware mode in Regex?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#unicode-aware_mode

It doesn't appear that the /u modifier is currently supported so unicode character escapes don't appear to work
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

**Comment by xeioex** [comment]
Duplicate of #442.
