### ISSUE TITLE
ngx.shared.SharedDict.clear() fails!

### ISSUE THREAD

**Issue by jaysee** [nginx/njs#690]
Hello,

I'm using `ngx.shared` to save some datas, but when I call `ngx.shared.SharedDict.clear()` the bucket is not cleared, I can still show datas, sample code :  

nginx conf:
`js_shared_dict_zone     zone=test:5m;`

njs code:
```javascript
const test = ngx.shared.test;
console.error( "____1 SIZE=" + test.size() + " NB ITEMS=" + test.items().length );
test.set( "test", "test value" );
console.error( "____2 SIZE=" + test.size() + " NB ITEMS=" + test.items().length );
test.clear();
console.error( "____3 SIZE=" + test.size() + " NB ITEMS=" + test.items().length );
```

results : 
```
____1 SIZE=0 NB ITEMS=0
____2 SIZE=1 NB ITEMS=1
____3 SIZE=1 NB ITEMS=1
```

I thought `____3` to be like `____1` ?

**Comment by VadimZhestikov** [comment]
Hi jaysee,

Yes, you are right, clear() don't work for js_shared_dict_zone without timeout parameter. The fix is drafted and will be available soon.  I guess, for a while as workaround you can configure zone with big enough timeout to be actual infinity.

Thank you for the report!
Vadim

**Comment by jaysee** [comment]
Ok, using a timeout makes it, no problem for my usage so can wait the final fix.

thanks, 
jC
