### ISSUE TITLE
NJS call wrong function.

### ISSUE THREAD

**Issue by mingkyme** [nginx/njs#700]
When use same variable name, it called wrong function.

Here is an example.
```config
server {
  server_name a;
  listen 80;
  js_set $value main.A;
  add_header X-A-Value $value;
  location / {
    return 200;
  }
}

server {
  server_name b;
  listen 80;
  js_set $value main.B;
  add_header X-B-Value $value;
  location / {
    return 200;
  }
}
```

```js
function A(r){
  return 1;
}

function B(r){
  return 2;
}
export default { A,B }
```

```bash
curl -I 0 -H "Host: a"
HTTP/1.1 200 OK
Server: nginx/1.24.0
Date: Wed, 03 Apr 2024 04:14:50 GMT
Content-Type: application/octet-stream
Content-Length: 0
Connection: keep-alive
X-A-Value: 2
```

**Comment by xeioex** [comment]
Hi @mingkyme,

`js_set` variables (as all nginx variables) are global, so basically `$value` is declared twice and the second declaration shadows the first one. `js_set` is different from ordinary `set` because `js_set` does not init the variable.

I am going to add some checks though to detect situations like this.

**Comment by zsteinkamp** [comment]
Would be nice to have at least server{} block scoped vars. It's surprising that they're global. If this is impossible, then I guess the next best thing is to write a warning into the error log.

**Comment by xeioex** [comment]
@arut Roman, do you have an opinion about server{} scope nginx variables?

**Comment by arut** [comment]
The variables are global by design. It's hardly possible to change it without significant refactoring of nginx. To avoid such misconfigurations, it should be advised to place `js_set` at `http{]` level. These variables hold different values, then why do they have the same name?

**Comment by NetForce1** [comment]
@arut I don't know about @mingkyme , but for me the reason for wanting server-scoped variables is to have generic NJS functions that need different configuration per server. Like in njs-acme: https://github.com/nginx/njs-acme/issues/57.

Without server-scoped variable, the only proper way to do that would be to create a separate function per server that calls the generic function with the server-specific config?
