### ISSUE TITLE
Test failure with zlib-ng

### ISSUE THREAD

**Issue by remicollet** [nginx/njs#704]
Since Fedora 40, zlib-ng is used instead of zlib

Compressed output may differs, so test suite is failing
```
...
xml tests: PASSED [46/46]
njs("const zlib = require('zlib');['WAKA', 'αβγ'].map(v => zlib.deflateRawSync(v, {dictionary: Buffer.from('WAKA')}).toString('base64'))")
expected: "CwdiAA==,O7fx3KZzmwE="
     got: "C3f0dgQA,O7fx3KZzmwE="
zlib tests: FAILED [10/11]
module tests: PASSED [6/6]
...
```

**Comment by remicollet** [comment]
I don't see any simple way to ignore 1 test  :s

**Comment by remicollet** [comment]
It is not about build (which is OK), but about test suite, as compressed result is different.

**Comment by xeioex** [comment]
Hi @remicollet,

Thanks for the report. I will rewrite the tests so they will work with any zlib library.

**Comment by xeioex** [comment]
Hi @remicollet,

Please let me know whether the [patch](https://gist.github.com/xeioex/a862529a255ae88e9f50653ccd100a65) works for you.

**Comment by remicollet** [comment]
I confirm the patch fixes the test suite

Pass with both **zlib** (1.2.13) and **zlib-ng** (2.1.6)

Thanks
