### ISSUE TITLE
False Positive Duplicate Checker Warning

### ISSUE THREAD

**Issue by lancedockins** [nginx/njs#705]
In NJS 0.8.4, the new duplicate declaration checking feature seems like it may need some adjustment.  In the current version,  if you use js_set inside of a location block in an include file that needs to be shared amongst multiple vhosts, it issues a warning and fails to start Nginx

Example test case:

```
# PHP-FPM
location ~ \.php$ {
	js_set $some_variable some.variable;

	# whatever other config
}
```

Use that location in an include file in more than one vhost.  With NJS 0.8.4, this fails and Nginx refuses to start.   It works fine with previous NJS versions.

Since these are used at the location level, they're definitely not duplicate.  If the duplicate logic was correct, then it would remove the js_set feature's support for use in location entirely which would be a backward breaking change.  I haven't tested this in a similar situation where the same variable name applies at a server block level.

Given the way that NJS works, technically, I imagine that the declaration could be made at the HTTP level and then use an if() or something to invoke the variable where it's needed in the location block in the include.  But that is both a workaround and still a backward breaking compatibility problem.

Can this be fixed?

**Comment by xeioex** [comment]
Hi @lancedockins,

See [this](https://github.com/nginx/njs/issues/700) github issue. `js_set` variables are global even if they are declared in a location block. We allow to declare them in a location block for the case where the variable is only needed in that location and nowhere else.

I agree we can improve the duplicate check logic when the the `js_set` declaration are 100% identical, it should fix your issue.
Will do it.

**Comment by xeioex** [comment]
Hi @lancedockins,

Feel free to test the [patch](https://gist.github.com/xeioex/ee3f4bd39dfc123c31f4805bbffc7f77) that should fix the problem.

**Comment by lancedockins** [comment]
@xeioex Thank you. The patch seems to work just fine.
