### ISSUE TITLE
njs source code  compile error 

### ISSUE THREAD

**Issue by spacexnasa** [nginx/njs#706]
OS:AlmaLinux 9.3  x86_64
QuickJS has been installed
njs version: njs-0.8.4

ls /usr/lib/quickjs/
libquickjs.a  libquickjs.lto.a

###### njs compile error message ##########
./configure --with-quickjs

configuring for Linux 5.14.0-362.13.1.el9_3.x86_64 x86_64
checking for C compiler: cc
 + using GNU C compiler
 + gcc version 11.4.1 20230605 (Red Hat 11.4.1-2) (GCC) 
checking for sizeof(int) ... 4
checking for sizeof(u_int) ... 4
checking for sizeof(void *) ... 8
checking for sizeof(uintptr_t) ... 8
checking for sizeof(size_t) ... 8
checking for sizeof(off_t) ... 8
checking for sizeof(time_t) ... 8
checking for system byte ordering ... little
checking for GCC unsigned __int128 ... found
checking for GCC __builtin_expect() ... found
checking for GCC __builtin_unreachable() ... found
checking for GCC __builtin_prefetch() ... found
checking for GCC __builtin_clz() ... found
checking for GCC __builtin_clzll() ... found
checking for GCC __attribute__ visibility ... found
checking for GCC __attribute__ malloc ... found
checking for GCC __attribute__ aligned ... found
checking for GCC __attribute__ packed ... found
checking for GCC __attribute__ fallthrough ... found
checking for GCC __attribute__ no_sanitize ... found
checking for Address sanitizer ... not found
checking for Memory sanitizer ... not found
checking for _mm_setcsr() ... found
checking for clock_gettime(CLOCK_MONOTONIC) ... found
checking for struct tm.tm_gmtoff ... found
checking for altzone ... not found
checking for posix_memalign() ... found
checking for getrandom() ... found
checking for stat.st_atimespec ... not found
checking for stat.st_birthtim ... not found
checking for stat.__st_birthtim ... not found
checking for stat.st_atim ... found
checking for Computed goto ... found
checking for explicit_bzero() ... found
checking for PCRE2 library ... not found
checking for PCRE2 library in /usr ... found
checking for PCRE2 version ... 10.40
checking for editline library in editline/readline.h ... found
checking for QuickJS library -lquickjs.lto ... not found
checking for QuickJS library -lquickjs ... not found
checking for QuickJS library -I/usr/include/quickjs/ -L/usr/lib/quickjs/ -lquickjs.lto ... not found
checking for QuickJS library -I/usr/include/quickjs/ -L/usr/lib/quickjs/ -lquickjs ... not found

./configure: error: no QuickJS library found.

**Comment by xeioex** [comment]
Hi @spacexnasa,

Please share a build file `build/autoconf.err`.

**Comment by spacexnasa** [comment]
> `build/autoconf.err`

maybe this file autoconf.err?
