### ISSUE TITLE
fs.writeFileSync does not work

### ISSUE THREAD

**Issue by reyou** [nginx/njs#75]
I have following JS code as `js_content`:

```
var fs = require('fs');
var filename = "logs/fileexport.txt";
fs.writeFileSync(filename, "qqq",{ encoding: 'utf8' });
```

but writeFileSync does not write anything nor logs any error.

How can I trace this?

**Comment by xeioex** [comment]
>but writeFileSync does not write anything nor logs any error.

how do you check it? 

 1.To ensure correct directory, please use the absolute path.
 2. make sure that you are hitting the correct location with js_content.

**Comment by reyou** [comment]
Hi @xeioex ,

here is new setup with absolute path:

```
var fs = require('fs');
var filename = "/etc/nginx/logs/fileexport.txt";
fs.writeFileSync(filename, "File Executed.",{ encoding: 'utf8' });
```

still no luck :( 

Yes, `js_content `is getting called, I know it because it makes `req.subrequest("/routingApi", "", done);` and it gets hit.

**Comment by xeioex** [comment]
@reyou please take a look at the following example of working with file IO in njs https://github.com/xeioex/njs-examples#file-io

Also, please verify that the example works as expected in docker, after you can run the same script from the example and compare the results.

**Comment by reyou** [comment]
Will do and and validate, thanks!

**Comment by xeioex** [comment]
Hi @reyou, can you confirm the problem still persists, or I can close the issue?

**Comment by reyou** [comment]
Yes we can close, thanks!

**Comment by furiedev** [comment]
The problem is that njs can create directory. Same error here!
If file doesn't exists, njs create it. But if directory doesn't exists, the request crash. I don't know if this is a bug or a feature request, but it will be nice to have directory creation method.
