### ISSUE TITLE
It'd be great if we could js_set an async function, not just sync

### ISSUE THREAD

**Issue by dstromberg** [nginx/njs#758]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is.
Yes.  If I try to crypto.subtle.digest("SHA-512", msgUint8), that means async is required. But if I try to call it from js_set, then sync is required.  TTBOMK, that's an inherent conflict that keeps js_set from being used with with crypto.subtle.digest.

### Describe the solution you'd like
js_set'ing an async function should "do the right thing", instead of returning a string that vaguely describes the Promise.

### Describe alternatives you've considered
I tried a few ways of turning the async crypto.subtle.digest into something synchronous, but none of them worked.  The general Javascript community seems hostile to the idea.
I also tried to find a synchronous SHA-512 module, but found that none of the ones I tried were "compatible enough" with njs.

**Comment by xeioex** [comment]
Hi @dstromberg,

See the [r.setReturnValue()](https://nginx.org/en/docs/njs/reference.html#r_set_return_value) for this.

For example:

```
http {
    js_import http.js;

    js_set $hash    http.hash;

    server {
        listen 8000;

        location = /crypto {
            add_header Hash $hash;
            return     200;
        }
    }
}
```

```js
async function hash(r) {
    let hash = await crypto.subtle.digest('SHA-512', r.headersIn.host);
    r.setReturnValue(Buffer.from(hash).toString('hex'));
}

export default {hash};
```

**Comment by dstromberg** [comment]
r.setReturnValue() helped in one case, and didn't in another.  I'm going to open a new ticket about the one that doesn't work.
