### ISSUE TITLE
It'd be good to be able to const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');

### ISSUE THREAD

**Issue by dstromberg** [nginx/njs#759]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is.
Yes, I desire to be able to use a synchronous SHA-512 module, to work around a problem described in another ticket.
To do this, I want to:
const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');
...where js-sha512 is from https://github.com/emn178/js-sha512

### Describe the solution you'd like
It'd be nice if const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');
...would import sha512 and others into the global namespace.

### Describe alternatives you've considered
I also tried: crypto.subtle.digest("SHA-512", msgUint8), but it has a synchronicity conflict with js_set.

### Additional context
Add any other context or screenshots about the feature request here.\
Here's sample code:
root@tact_manager_nginx:/tmp# NODE_PATH=$(pwd) nodejs ./t
ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
root@tact_manager_nginx:/tmp# ./t
Thrown:
SyntaxError: Token "sha512" not supported in this version in ./t:2
root@tact_manager_nginx:/tmp# cat t
#!/usr/bin/env njs

const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');

console.log(sha512("abc"));
root@tact_manager_nginx:/tmp#

BTW, I confess I'm a Javascript newb.

**Comment by dstromberg** [comment]
I just tried the following, all without success:
// const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');
// const { sha512 } = require('js-sha512');
import sha512 from 'js-sha512';

**Comment by dstromberg** [comment]
Maybe it just disliked the curly braces:
root@tact_manager_nginx:/tmp# ./t
Thrown:
Error: Cannot find module "js-sha512"
    at require (native)
    at main (./t:4)

root@tact_manager_nginx:/tmp# cat t
#!/usr/bin/env njs

// const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');
// const { sha512 } = require('js-sha512');
const sha512 = require('js-sha512');
// import sha512 from 'js-sha512';

console.log(sha512("abc"));
root@tact_manager_nginx:/tmp#

**Comment by dstromberg** [comment]
Seems to work without curly braces.

**Comment by xeioex** [comment]
Hi @dstromberg,

See [compatibility](https://nginx.org/en/docs/njs/compatibility.html) page for njs. Destructuring introduced in ES6 is not supported. We are working on adding a [QuickJS](https://bellard.org/quickjs/) engine which support modern JS syntax though.

**Comment by Sayedbila** [comment]
> ### Is your feature request related to a problem? Please describe
> A clear and concise description of what the problem is. Yes, I desire to be able to use a synchronous SHA-512 module, to work around a problem described in another ticket. To do this, I want to: const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512'); ...where js-sha512 is from https://github.com/emn178/js-sha512
> 
> ### Describe the solution you'd like
> A clear and concise description of what you want to happen. It'd be nice if const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512'); ...would import sha512 and others into the global namespace.
> 
> ### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered. I also tried: crypto.subtle.digest("SHA-512", msgUint8), but it has a synchronicity conflict with js_set.
> 
> ### Additional context
> Add any other context or screenshots about the feature request here. Here's sample code: root@tact_manager_nginx:/tmp# NODE_PATH=$(pwd) nodejs ./t ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f root@tact_manager_nginx:/tmp# ./t Thrown: SyntaxError: Token "sha512" not supported in this version in ./t:2 root@tact_manager_nginx:/tmp# cat t #!/usr/bin/env njs
> 
> const { sha512, sha384, sha512_256, sha512_224 } = require('js-sha512');
> 
> console.log(sha512("abc")); root@tact_manager_nginx:/tmp#
> 
> BTW, I confess I'm a Javascript newb.

**Comment by Sayedbila** [comment]
My money is successfully transfer but not add in my game ID
