### ISSUE TITLE
How to log in js_content?

### ISSUE THREAD

**Issue by reyou** [nginx/njs#76]
I have following setup:

```
server {    
    listen 8081;   
     location / {
     error_log  /etc/nginx/logs/info.txt;
     access_log  /etc/nginx/logs/info.txt;
     js_content routingApi;        
      }
```

And in `routingApi` method, I could not figure out how to log into file. `console.log` does not work, and as I reported [here ](https://github.com/nginx/njs/issues/75) fs.writeFileSync does not work.

Is there any way to do this?

**Comment by xeioex** [comment]
Documentation about `r` is [here](http://nginx.org/en/docs/njs/reference.html#http)

```
r.error(string)
writes a string to the error log on the error level of logging

r.log(string)
writes a string to the error log on the info level of logging

r.warn(string)
writes a string to the error log on the warning level of logging
```

**Comment by reyou** [comment]
Hello @xeioex ,

I have following setup:
```
server {    
    listen 8081;   
     location / {
     error_log  /etc/nginx/logs/info.txt;
     access_log  /etc/nginx/logs/info.txt;
     js_content routingApi;        
      }
```
```
function executeRoutingApi(req, res) {    
    // ngx_http_js_ext_get_reply_body    
    function done(reply) {
     // res.contentType = "text/html; charset=utf-8";
      res.contentType = reply.contentType;      
      res.return(reply.status, reply.body);       
    }
    req.log("ReqUrl: " + req.url);
    req.subrequest("/routingApi", "", done);
}
```

Here I cannot see `ReqUrl` is logged under `info.txt`.

Am I missing something?

**Comment by xeioex** [comment]
I would suggest to start from req.error().

**Comment by reyou** [comment]
`req.error` worked, thanks!

Should I be using it for all logging for now?
I am not sure why `req.info` would not work.

**Comment by xeioex** [comment]
to see req.log() you have to configure error_log directive with info log level (https://nginx.org/en/docs/ngx_core_module.html#error_log).

**Comment by reyou** [comment]
This makes sense, thanks!
