### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH while sending a long text

### ISSUE THREAD

**Issue by imzlh** [nginx/njs#760]
### Describe the bug

When I try to send a long string(JSON.stringify), the browser reports an error
![image](https://github.com/user-attachments/assets/7eeed4ec-eeda-468f-8822-1652fe7f5ae3)

### To reproduce

NJS:
Here: https://github.com/imzlh/vlist-njs/blob/master/main.ts#L429

CURL:

```
*   Trying 192.168.1.1:81...
* Connected to 192.168.1.1 (192.168.1.1) port 81
> POST /@api/?action=slist HTTP/1.1
> Host: 192.168.1.1:81
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Length: 26
> Content-Type: application/x-www-form-urlencoded
>
} [26 bytes data]
< HTTP/1.1 200 OK
< Server: nginx
< Date: Sat, 13 Jul 2024 11:16:55 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 33829
< Connection: keep-alive
< Alt-Svc: h3=":444"; h2=":8443"; ma=86400
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Type, Authorization
<
{ [3798 bytes data]
* transfer closed with 6387 bytes remaining to read
 81 33855   81 27442  100    26   337k    327 --:--:-- --:--:-- --:--:--  339k
* Closing connection
curl: (18) transfer closed with 6387 bytes remaining to read
```

### Expected behavior

Complete JSON string

### Your environment

- Version of njs or specific commit: 0.8.5
- Version of NGINX if applicable: nginx/1.27.0
- List of other enabled nginx modules if applicable
   configure arguments: -`-prefix=/usr/local/osgi/ --sbin-path=bin/ --modules-path=lib/nginx/ --conf-path=etc/nginx/nginx.conf --error-log-path=/tmp/nginx/error.log --pid-path=/tmp/nginx/.pid --lock-path=/tmp/nginx/.lock --user=daemon --group=daemon --build='for ARMRounger' --without-poll_module --without-http_ssi_module --without-http_userid_module --without-http_mirror_module --without-http_geo_module --without-http_map_module --without-http_split_clients_module --without-http_uwsgi_module --without-http_grpc_module --without-http_memcached_module --without-http_empty_gif_module --without-http_browser_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_least_conn_module --without-http_upstream_random_module --without-http_upstream_keepalive_module --without-http_upstream_zone_module --http-log-path=/tmp/nginx/log.log --http-client-body-temp-path=/tmp/nginx/body --http-proxy-temp-path=/tmp/nginx/proxy --http-fastcgi-temp-path=/tmp/nginx/fcgi --http-scgi-temp-path=/tmp/nginx/scgi --with-cc=armv7m-linux-musleabi-gcc --with-cpp=armv7m-linux-musleabi-gcc-g++ --add-module=../njs/nginx/ --add-module=dav --with-http_dav_module --with-zlib=../zlib-1.3.1 --with-http_v2_module --with-http_v3_module --add-module=fancyindex --with-ld-opt='-static -s -w'`
- OS: `Linux 4.1.25 #3 SMP PREEMPT Fri Apr 7 01:40:44 UTC 2023 armv7l GNU/Linux`

**Comment by xeioex** [comment]
Hi @imzlh,

Can you please minimize the code so I can reproduce the issue? Also please share the minimal nginx.conf.

**Comment by imzlh** [comment]
minal version:
 - nginx.conf
   ```
    js_import                               /usr/local/osgi/lib/nginx/vlist.js;
                location = /@api/{
                        js_var                  $authkey "....";
                        js_content              vlist.main;
                }
   ````
 - vlist.js
  ```
    return h.return(200, JSON.stringify(res));
  ```
 - nginx extension
   fancyindex
  dav
  njs
  [built-in: http2 http3 ssl]
 - question
   ERR_CONTENT_LENGTH_MISMATCH

**Comment by xeioex** [comment]
Hi @imzlh,

Were you able to identify the source of the issue?

I am trying to reproduced it, unsuccessfully so far.

It seems the outcome depends on the content of the directory in question. (You also omitted this information from your issue description).

For me the following setup works as expected

```sh
$ mkdir /mnt/bar; touch /mnt/bar/a && touch /mnt/bar/b && /mnt/bar/c
```

```sh
$ curl -X POST -d '{"path": "bar"}' http://127.0.0.1:8000/long?action=slist
[{"type":"file","name":"c","ctime":1726791684307.4236,"access":33204,"size":0},{"type":"file","name":"a","ctime":1726791682571.3972,"access":33204,"size":0},{"type":"file","name":"b","ctime":1726791683563.4124,"access":33204,"size":0}] 
```

Please share the dir content or what is the content of `res` from

` return h.return(200, JSON.stringify(res));`

**Comment by imzlh** [comment]
oh, I forgot the issue here. I recompiled NGINX/1.27.1 and found that the problem has disappeared.
I dont know why.It's really strange
