### ISSUE TITLE
js_preload_object and reload

### ISSUE THREAD

**Issue by jaysee** [nginx/njs#761]
Hello,

I know the limitations of `js_preload_object` imutable, not writable, but will it be possible to "reload" the object when reloading nginx? Actually it requiers a full restart, not my favourite way of upgrading configurations.

Regards

**Comment by xeioex** [comment]
Hi @jaysee,

`js_preload_object` is reloaded during nginx reload, are you seeing something different?

**Comment by jaysee** [comment]
oh! doing some simple testing, yes it is reloaded, something should be wrong in my app...

thanks, sorry for the false alarm!
