### ISSUE TITLE
Fetch information from an API before sending the request 

### ISSUE THREAD

**Issue by reyou** [nginx/njs#77]
I would like to do something below;
https://stackoverflow.com/questions/48348647/fetch-information-from-an-api-before-sending-the-request-upstream

Is it possible to do with this module?

Here is my SO question:
https://stackoverflow.com/questions/53799389/calling-external-api-in-nginx-location-section/53804483#53804483
 
I need something like below:

```
location /proxy-pass-uri {
   # block request here, and somehow set  $urlToProxy variable
    js_content executeRoutingApi;
   # make proxy_pass dynamic. result ($urlToProxy) should come from js_content 
    proxy_pass $urlToProxy;         
}
```

Thanks!

**Comment by xeioex** [comment]
hi @reyou,

Take a look at [this njs example](https://github.com/xeioex/njs-examples#complex-redirects-using-njs-file-map)

**Comment by reyou** [comment]
Looks great, thanks a ton!
