### ISSUE TITLE
The proxy_connect configuration of nginx is 300s, but within 20 minutes there are still websocket requests to send routing requests to the failed machine.

### ISSUE THREAD

**Issue by karsapeng** [nginx/njs#780]
hello 
nginx.conf:
user root;
worker_processes  4;

error_log  logs/error.log error;
#access_log logs/access-$year&month&day.log main;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    proxy_connect_timeout 300s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    client_max_body_size 3000m;
    client_header_buffer_size 100M;
    client_body_buffer_size 16M;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$upstream_addr" "$upstream_http_host" "$upstream_response_time" ';

    access_log /usr/local/nginx/logs/access.log main;

    upstream rpa {
        server 192.168.10.97:8080;
        server 192.168.10.98:8080;

        # 配置健康检查
        check interval=1000 rise=2 fall=2 timeout=1000 type=http port=8288;
        check_http_send "HEAD /health HTTP/1.0\r\n\r\n";
        check_http_expect_alive http_2xx;
    }
    server {
    listen 80;
   listen 80;
    server_name 192.168.10.92;

    location / {
        return 301 https://$host$request_uri;
    }
}
    server {
        listen 443 ssl;
        server_name 192.168.10.92;
        ssl_certificate /usr/local/nginx/conf/cert/server.crt;
        ssl_certificate_key /usr/local/nginx/conf/cert/server.key;

        location / {
           # proxy_connect_timeout 300s;
           # proxy_read_timeout 300s;
           # proxy_send_timeout 300s;
           # client_max_body_size 3000m;
           # client_header_buffer_size 100M;
           # client_body_buffer_size 16M;
            proxy_pass http://rpa;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
When I shut down the 10.97 machine, there were still requests going to 97 within 20 minutes.
report error route to host while proxing upgraded connection.client:192.168.10.209.server:192.168.10.92.
request:"GET /connector/worker/hub HTTP/1.1",upstream:"http//192.168.10.97:8080/connector/worker/hub",host: "192.168.10.92". 
 what should i do ?

**Comment by xeioex** [comment]
Hi @karsapeng,

Is your question related to [njs](https://nginx.org/en/docs/njs/) project?
