### ISSUE TITLE
Calling another service to query routing information for a TCP proxy

### ISSUE THREAD

**Issue by z0Kng** [nginx/njs#790]
My use case is to use nginx as a TCP proxy (with TLS being broken up). The IP to be forwarded to is to be determined with the help of a rest call to another service, which returns an IP and port using the subdomain of the connection to the nginx. The problem now is that js_set does not allow asynchronous calls, and therefore it is not possible to execute a web request to set the variable for proxy_pass.

I have seen the workaround using auth_request, but am I right in assuming that this only works with HTTP?

**Comment by jo-carter** [comment]
@z0Kng  Use js_preread or js_access's associated callback functions as a conduit to populate the values of a js_var from the result of a fetch request. That js_var should be the target of proxy_pass. 

There is a close-ish example of this (using preread) in the njs-examples repo [here](https://github.com/nginx/njs-examples?tab=readme-ov-file#id52).

**Comment by z0Kng** [comment]
Thank you very much, got it working with js_access.
