### ISSUE TITLE
NJS 0.8.6 Buffer.indexOf reads out of bounds instead of returning -1.

### ISSUE THREAD

**Issue by ap-wtioit** [nginx/njs#794]
### Describe the bug

NJS since version 0.8.6 Buffer.indexOf reads out of bounds instead of returning -1.

Before submitting a bug report, please check the following:

- [x] The bug is reproducible with the latest version of njs.
- [x] I minimized the code and NGINX configuration to the smallest
possible to reproduce the issue.

### To reproduce

Use the following script in a js_body_filter to replace contents in the data
- JS script
```js
function bufferReplace(data, search, replacement) {
    for (var i = data.indexOf(search, 0); i !== -1; i = data.indexOf(search, i + search.length)) {
        // replace search with replacement in buffer
        replacement.copy(data, i, 0);
    }
}

function fix_response_body(r, data, flags) {
    var data_buffer = typeof data === "string" ? Buffer.from(data) : data;
    bufferReplace(data_buffer, "Text", Buffer.from("Test"));
    r.sendBuffer(data_buffer, flags);
}

export default { fix_response_body }
```

- NGINX configuration
```
js_body_filter somefile.fix_response_body  buffer_type=buffer;
```

- NGINX logs
in case out of bounds read crashes the worker (it does not find "Text" in any of the following memory)
```
nginx-1          | 2024/10/09 05:25:41 [notice] 76#76: signal 17 (SIGCHLD) received from 77
nginx-1          | 2024/10/09 05:25:41 [alert] 76#76: worker process 77 exited on signal 11 (core dumped)
nginx-1          | 2024/10/09 05:25:41 [notice] 76#76: start worker process 332
```
in case out of bounds read finds "Text" in the following memory before it crashes the worker it reports an out of bounds write at `replacement.copy`

### Expected behavior

Buffer.indexOf should read -1 when reaching the end of the buffer. It should not read out of bounds.

### Your environment

- Version of njs: `ii  nginx-module-njs 1.26.2+0.8.6-1~bookworm amd64        nginx njs dynamic modules`
- Version of NGINX:  `ii  nginx          1.26.2-1~bookworm amd64        high performance web server`
- OS: Debian Bookworm

### Additional context

This is especially dangerous because 0.8.5 did not read out of bounds in this case and if somebody just updates their packages and doesn't test their njs scripts this can lead to workers crashing or worse if the script does handle user input (ours does not).

Initially reported as a security vulnerability but was told that this is not a security vulnerability by the F5 expert.

**Comment by xeioex** [comment]
Hi @ap-wtioit,

Thank you for the report. I was able to reproduce the issue, and I am working on it.
