### ISSUE TITLE
Unable to build njs with QuickJS support as a module

### ISSUE THREAD

**Issue by woxxo** [nginx/njs#801]
When building Nginx with njs as a static module according to this [instruction](https://github.com/nginx/njs?tab=readme-ov-file#building-nginx-javascript-as-a-module-of-nginx), everything works like a charm:
```code
./configure --add-module=<NJS_SRC_ROOT_DIR>/nginx
```

I would like to use QuickJS engine, but can't configure the compilation properly, always getting these logs:
```code
configuring additional modules
adding module in /home/opt/src/njs-master/nginx
checking for QuickJS library -lquickjs.lto ... not found
checking for QuickJS library -lquickjs ... not found
checking for QuickJS library -I/usr/include/quickjs/ -L/usr/lib/quickjs/ -lquickjs.lto ... not found
checking for QuickJS library -I/usr/include/quickjs/ -L/usr/lib/quickjs/ -lquickjs ... not found
 enabled webcrypto module
 enabled xml module
 enabled zlib module
 + ngx_js_module was configured
```
Using these options with precompiled QuickJS libs in the mentioned folders don't give any positive result:
```code
--with-cc-opt="-I/usr/include/quickjs/" --with-ld-opt="-L/usr/lib/quickjs/"
```

Please provide an instruction how to successfully compile njs supporting QuickJS as a static nginx module!

**Comment by xeioex** [comment]
Hi @woxxo,

`checking for` tries to compile a [certain C file](https://github.com/nginx/njs/blob/master/auto/quickjs#L17), please, make sure you are using the [recent](https://github.com/bellard/quickjs) QuickJS library. The last released version is not enough. For details check `<NJS_SRC_ROOT_DIR>/build/autoconf.err` for details.

I am going to improve the reporting to make this process more transparent.

**Comment by xeioex** [comment]
Hmm, it is [controlled](https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L404) by the same define, which is defined [here](https://github.com/nginx/njs/blob/master/nginx/config#L29). Adding `-DNJS_HAVE_QUICKJS=1` to `--with-cc-opt=` should fix this. But we need to find why it does not propagate.

**Comment by woxxo** [comment]
Ok, it is working now, ```js_engine``` can be changed as expected! Thank you!
