### ISSUE TITLE
Remove fs.promises.readSync.

### ISSUE THREAD

**Issue by jo-carter** [nginx/njs#810]
https://github.com/nginx/njs/blob/606ceb243c49ce336be8d34085ee158f3723e271/external/njs_fs_module.c#L400

All other promise fs functions have their "Sync" postfix removed. Is leaving it in for readSync intentional?

https://github.com/nginx/njs/blob/606ceb243c49ce336be8d34085ee158f3723e271/external/njs_fs_module.c#L1334
I see there is also a fs.promises.read function that appears to be identical.

**Comment by xeioex** [comment]
Hi @jo-carter,

>All other promise fs functions have their "Sync" postfix removed. Is leaving it in for readSync intentional?
There is no `fs.promises.read()` in [nodejs](https://nodejs.org/api/fs.html#fspromisesread).
`"readSync"` should be removed from `fs.promises`though, thanks.

>I see there is also a fs.promises.read function that appears to be identical.

Actually it is not `fs.promises.read` but [filehandle.read](https://nodejs.org/api/fs.html#filehandlereadbuffer-offset-length-position).
We have [filehandle](https://nginx.org/en/docs/njs/reference.html#fs_filehandle) partially implemented.

While they share the same C function, their behaviour is different depending on the `magic8` constant.

**Comment by jo-carter** [comment]
> There is no fs.promises.read() in [nodejs](https://nodejs.org/api/fs.html#fspromisesread). So, read() is unlike other methods.
readSync() should be removed from fs.promisesthough, thanks.

Ah yes you're right, I forgot about that quirk in NodeJS's non-promise API.

> Actually it is not fs.promises.read but [filehandle.read](https://nodejs.org/api/fs.html#filehandlereadbuffer-offset-length-position).
We have [filehandle](https://nginx.org/en/docs/njs/reference.html#fs_filehandle) partially implemented.

 Yes, I also missed that this was for filehandles while scrolling through :)
