### ISSUE TITLE
Fixed vmcode function call.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#82]
Hi, @xeioex 

1. Fixed vmcode function call.
2. Refactored the return type of njs_function_frame_free.

https://gist.github.com/hongzhidao/fe76ced2296d03b9a9e4a51476119492

**Comment by hongzhidao** [comment]
BTW, please keep the condition though the function is alway not null.
```
        if (function != NULL) {
            args += function->args_offset;
        }
```
And I'll refactor the codes related to function call.

**Comment by xeioex** [comment]
hi @hongzhidao,

Changes look good. Will be committed. This ticket will be closed.
