### ISSUE TITLE
r.return has a max size ?

### ISSUE THREAD

**Issue by puppetninja** [nginx/njs#825]
i am seeing a issue that r.return seems only sending 2M at most, this is the code I am using, I see the ngx.fetch response size is `3047402`, meanwhile on client I only see 2047k bytes returned. 

```
            try {
                let reply = await ngx.fetch('http://127.0.0.1:8000/forward/', {
                    method: r.method,
                    headers: {'Content-Type': content_type(r.headersIn), 'X-Forwarded-For': r.headersIn['X-Forwarded-For'] },
                    body: JSON.stringify(requests),
                });
                let body = await reply.text(); // Read the raw response as text
                r.log(`Response: ${body.length}`); // Log the response length
                response = JSON.parse(body); // Parse the text into JSON
                response.id = requests.id;
            } catch (e) {
                r.error(`Error in fetch and json parse: ${e.message}`);
                response = error( -32099, "Endpoint error", request.id);
            }

            r.return(200, JSON.stringify(response));

```
Other nginx config issue could be ruled out as it works perfectly fine with proxy_pass without njs

**Comment by xeioex** [comment]
Hi @puppetninja,

Could you, please, check the behaviour after https://github.com/nginx/njs/commit/b300a93311a4ffeb37ca137eecda5f4cd92b4caf.

**Comment by puppetninja** [comment]
Hi, okay I will try this out and get back to you

**Comment by xeioex** [comment]
Hi @puppetninja,

I checked it, https://github.com/nginx/njs/commit/b300a93311a4ffeb37ca137eecda5f4cd92b4caf indeed fixes the issue.

**Comment by puppetninja** [comment]
Hi, sorry for the late reply, it was not easy for me to test njs built with src, I tried to increase the sendfile_max_chunk, then it works. I would say https://github.com/nginx/njs/commit/b300a93311a4ffeb37ca137eecda5f4cd92b4caf should fix the issue.  I would be happy to test it with latest release of njs.

**Comment by puppetninja** [comment]
https://github.com/nginx/njs/commit/b300a93311a4ffeb37ca137eecda5f4cd92b4caf
