### ISSUE TITLE
Add ability to use Environment Variables as it's possible with Lua and Perl

### ISSUE THREAD

**Issue by pavelsevcik** [nginx/njs#84]
As of [Using Environment Variables In Nginx.conf
](https://web.archive.org/web/20170712003702/https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html)

Lua supports `os.getenv("API_KEY")`

Perl supports `$ENV{"API_KEY"};`

would be very usefull and appreciated to have such an ability in njs too, especially for cases like handling secrets for [Creating HS JWT
](http://nginx.org/en/docs/njs/examples.html#jwt)

thank you

**Comment by appelgriebsch** [comment]
Just looked into that same scenario myself and a potential workaround would be to put the JWT key into a local file first and have it read out from Nginx via the filesystem API. But to be honest I would also prefer to have os.getenv or something similar in the JS core module. 

Is there some roadmap on the upcoming changes / extensions and when they are ready?

**Comment by xeioex** [comment]
Hi @appelgriebsch 

There is no official roadmap as of now. But you can find most of the planned features to add by 'feature' tag on the issues page. Upcoming changes can be found by the activity (available patches) in the specific feature tasks.
Release notes are available [here](http://nginx.org/en/docs/njs/changes.html), they are published through [nginx-announce](http://mailman.nginx.org/pipermail/nginx-announce/2019/thread.html).

Access to environment variables will be added in 0.3.3 or 0.3.4.

**Comment by xeioex** [comment]
@appelgriebsch

You may try the following patch: https://gist.github.com/xeioex/2cca33f09e099d21118e3f7406ddc116

**Comment by drsm** [comment]
@xeioex 

why not?

```diff
diff -r 2fb43ddbce84 njs/njs_builtin.c
--- a/njs/njs_builtin.c Mon Jun 10 22:23:56 2019 -0400
+++ b/njs/njs_builtin.c Tue Jun 18 22:40:48 2019 +0300
@@ -1335,24 +1335,28 @@
         .type = NJS_PROPERTY_HANDLER,
         .name = njs_string("argv"),
         .value = njs_prop_handler(njs_process_object_argv),
+        .enumerable = 1,
     },
 
     {
         .type = NJS_PROPERTY_HANDLER,
         .name = njs_string("env"),
         .value = njs_prop_handler(njs_process_object_env),
+        .enumerable = 1,
     },
 
     {
         .type = NJS_PROPERTY_HANDLER,
         .name = njs_string("pid"),
         .value = njs_prop_handler(njs_process_object_pid),
+        .enumerable = 1,
     },
 
     {
         .type = NJS_PROPERTY_HANDLER,
         .name = njs_string("ppid"),
         .value = njs_prop_handler(njs_process_object_ppid),
+        .enumerable = 1,
     },
 
 };
```
but `njs.dump` and `JSON.stringify` should be fixed also to invoke property handlers.
