### ISSUE TITLE
WIP: Refactor njs_continuation_t.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#85]
Hi @xeioex 

Take a look at these patches, please.

1. Refactored njs_function_lambda_call() and style.
https://gist.github.com/hongzhidao/0a87adeb26e8b0eb71c7203d7a9d82b8

2. Refactor njs continuaction. (Optional)
https://gist.github.com/hongzhidao/36b74142d3eb08b8d24509da6b543f91
https://gist.github.com/hongzhidao/4e818cd152da82e1fc77f2f23b10dc59
https://gist.github.com/hongzhidao/c23d90c783cafd6c16b6b2f270391495

Finally, we refactored out three important APIs. 
`njs_function_frame, njs_function_activate, njs_function_call`

**Comment by xeioex** [comment]
Hi @hongzhidao,

For the future, please, add 
```[diff]                                                                                                                           
showfunc = 1 
```
to your ~/.hgrc.

The hg patches, will additionally contain, the name of the changed functions.

**Comment by xeioex** [comment]
Hi @hongzhidao,
> **Refactor njs continuaction. (Optional)
> https://gist.github.com/hongzhidao/36b74142d3eb08b8d24509da6b543f91**

`continuation = nxt_mem_cache_alloc(vm->mem_cache_pool, continuation_size);`

why do you think that it is a better idea to allocate memory for continuation from heap rather than from stack (as it is now)? 

Having it on stack allows us to automatically free the memory for it as a stack unwinds. In you patch I see no nxt_mem_cache_free() invocation. I would leave it as is, on stack, if there is no compelling reasons to do otherwise.

**Comment by hongzhidao** [comment]
No problem.
Sorry for not been carefully thought out the patch of 'Refactor njs continuaction'.
The purpose is to make continuation more generic, but it's still an experiment.
I notice you if there's any change.

**Comment by xeioex** [comment]
>Fixed njs_vm_value_dump().

Thank! 

I am not sure about alloc -> zalloc change.

**Comment by xeioex** [comment]
@hongzhidao 

> it causes many coredumps.

Thank you for the report. Will look into it.

**Comment by xeioex** [comment]
>Is it ok to add mallopt() for debuging?

"This function is not specified by POSIX or the C standards."
I would rather not, because it is not a POSIX function, and there are other ways (non-invasive) to look for memory issues.

**Comment by xeioex** [comment]
@hongzhidao 

I can confirm, that `-fsanitize=address` catches a bug.

**Comment by hongzhidao** [comment]
It's introduced in the patch.
http://hg.nginx.org/njs/rev/045ba10db769

**Comment by hongzhidao** [comment]
Hi @xeioex 

Reason: the variables `frame->skip`, `cont` is still be used after frame is freed.

```
diff -r 4427aede6e95 njs/njs_function.c
--- a/njs/njs_function.c	Mon Jan 14 12:20:08 2019 +0800
+++ b/njs/njs_function.c	Tue Jan 15 06:02:19 2019 +0800
@@ -528,7 +528,6 @@ njs_function_native_call(njs_vm_t *vm, n
         frame = vm->top_frame;

         vm->top_frame = njs_function_previous_frame(frame);
-        njs_function_frame_free(vm, frame);

         /*
          * If a retval is in a callee arguments scope it
@@ -552,6 +551,8 @@ njs_function_native_call(njs_vm_t *vm, n
             *value = vm->retval;
         }

+        njs_function_frame_free(vm, frame);
+
         return NXT_OK;
     }

diff -r 4427aede6e95 njs/njs_vm.c
--- a/njs/njs_vm.c	Mon Jan 14 12:20:08 2019 +0800
+++ b/njs/njs_vm.c	Tue Jan 15 06:02:19 2019 +0800
@@ -2287,12 +2287,14 @@ const njs_vmcode_generic_t  njs_continua
 static njs_ret_t
 njs_vmcode_continuation(njs_vm_t *vm, njs_value_t *invld1, njs_value_t *invld2)
 {
+    u_char              *return_address;
     njs_ret_t           ret;
     njs_native_frame_t  *frame;
     njs_continuation_t  *cont;

     frame = vm->top_frame;
     cont = njs_vm_continuation(vm);
+    return_address = cont->return_address;

     ret = njs_function_native_call(vm, cont->function, frame->arguments,
                                    cont->args_types, frame->nargs,
@@ -2300,7 +2302,7 @@ njs_vmcode_continuation(njs_vm_t *vm, nj

     switch (ret) {
     case NXT_OK:
-        vm->current = cont->return_address;
+        vm->current = return_address;
         /* Fall through. */

     case NJS_APPLIED:
```

Sorry for my negligence :)

**Comment by xeioex** [comment]
> I can't get useful information from fsanitize, can you share your experience in debugging these similar problems?

What do you mean?

After you patch, `make test` passes with `CFLAGS='-O0 -DNXT_DEBUG_MEMORY=1 -fsanitize=address'`

fsanitize=address enables [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer). It is available with recent gcc and clang compilers.

**Comment by hongzhidao** [comment]
BTW, I use NJS recently, and I found we need a better way to organize js codes.
Such as:
```
var m = require('some-module.js');
m.foo();
```
You can raise the priority of this feature.

**Comment by xeioex** [comment]
@hongzhidao 
>Reason: the variables frame->skip, cont are still be used though frame is freed.

Committed, thanks.

**Comment by xeioex** [comment]
>var m = require('some-module.js');

Yes. modules are on the roadmap too.

**Comment by hongzhidao** [comment]
Is it used like this?

```
js_module  foo foo.js ;
js_include  http.js;
```

foo.js
```
var _m = {};
_m.some = {}
return _m;
```

I prefer to define by directive, not by js code. Such as:
```
var foo = require('foo.js');
```
I guess njs will not plan to implement inline parse like `eval` function?

**Comment by xeioex** [comment]
The plan is to support :

```var foo = require('foo.js');```

We do not need `eval` function here, because the module body has to be executed only once (during compilation phase). Otherwise, it will be too heavy to load a module for each request again and again.

**Comment by hongzhidao** [comment]
1. Is variable of require argument also supported?
```
var m = 'foo.js';
var foo = require(m);
```
2. I don't which phase happened that `parse, compile and execute` the module body?
3. Is there any patch implement the feature?

**Comment by hongzhidao** [comment]
Get it.
The key point is that execute the module once at the compilation phase.
So in the following case, it's still be executed.
```
if (false) require('foo.js')
```

**Comment by xeioex** [comment]
> So in the following case, it's still be executed.

Yes.
The idea is, during parsing/compilation phase, when require('file.js') is encountered, load and execute the body of 'file.js'.
Resulting object is stored, and returned as is at runtime.

**Comment by hongzhidao** [comment]
It's similar to variable.
Have you already started the feature? 
Maybe I can try to implement it.

**Comment by xeioex** [comment]
>Have you already started the feature?

no. At that moment I am dealing with labels support. After it, I am going to do nginx related stuff.

>Maybe I can try to implement it.

that would be awesome!

**Comment by hongzhidao** [comment]
Hi @xeioex 

> Otherwise, it will be too heavy to load a module for each request again and again.

I totally agree it. 

There are questions related to it, I think they are similar.
1. In ngx_http_js_module.
Is it better to run njs_vm_start on config phase?
At the runtime we find the func and call njs_vm_call.

2. require module.
```
var a = {}
function foo() {}
```
2.1 The variable 'a' can't not be shared with http requests?
This happens in lua, it's kind of useful that we can use it to cache data in process, but I don't think it's a good idea. The vm (not cloned) should be kept immutable even though the required module is invoked  many times by different requests.

2.2 I think the required body of module is an anonymous function, do you agree it?
```
js code
```
vs
```
(function() {
js code
})()  -- It runs on compliation phase.
```

3 njs codes
3.1 In what case the vm->global_scope has value?
```
In njs_vm_init()
420     vm->scopes[NJS_SCOPE_GLOBAL] = (njs_value_t *) values;
421     memcpy(values + NJS_INDEX_GLOBAL_OFFSET, vm->global_scope,
422            vm->scope_size);
```
Actually, I want to copy global values from initial vm to cloned vm. (As an experiment)
```
In njs_vm_clone()
366         nvm->external = external;
367
368         memcpy(vm->global_scope, (u_char *) vm->scopes[NJS_SCOPE_GLOBAL] + NJS_INDEX_GLOBAL_OFFSET,
369                vm->scope_size);
370
371         nvm->global_scope = vm->global_scope;
```

3.2 runtime in generator.
```
struct njs_generator_s {
    /* Parsing Function() or eval(). */
    uint8_t                         runtime;           /* 1 bit */
};
```
Can you talk more about the field runtime?

3.3 Useless field?
```
struct njs_vm_s {
    /* njs_vm_t must be aligned to njs_value_t due to scratch value. */
    njs_value_t              retval;

    /*
     * The scratch value is used for lvalue operations on nonexistent
     * properties of non-object values: "a = 1; a.b++".
     */
    njs_value_t              scratch;  /* Is it useful? */
```

Thanks.

**Comment by xeioex** [comment]
> In ngx_http_js_module. Is it better to run njs_vm_start on config phase?

In ngx_http_js_module we call njs_vm_compile(), I think njs_vm_compile() should  run the body of loaded modules, it would populate the global scope (so ngx_http_js_module should not call njs_vm_start() directly). At njs_vm_clone() we have to copy global scope values to cloned vm (as you suggested).

> 2.1 The variable 'a' can't not be shared with http requests?

yes. For paradigm with cloned VMs to work, module bodies have to be immutable somehow (for example, we can enforce it, by setting all extensible, configurable, writable properties to false).

> 2.2 I think the required body of module is an anonymous function, do you agree it?

Almost. Ideally, it have to be completely isolated from the global code.
For example something like this, should not work:
```js
var a = 1;
var m = require("file.js"); // where file.js contains: a = 2;
```
To me, It looks like more as an anonymous function with empty global scope.

>3.2 runtime in generator.

I am not sure what it is for, will ask @igorsysoev.

> 3.3 Useless field?

Seems so. Will be deleted. Thanks.

**Comment by hongzhidao** [comment]
> 3.2 runtime in generator.
I am not sure what it is for, will ask @igorsysoev.

And this.

> 3.1In what case the vm->global_scope has value?
In njs_vm_init()
420     vm->scopes[NJS_SCOPE_GLOBAL] = (njs_value_t *) values;
421     memcpy(values + NJS_INDEX_GLOBAL_OFFSET, vm->global_scope,
422            vm->scope_size);

**Comment by hongzhidao** [comment]
> yes. For paradigm with cloned VMs to work, module bodies have to be immutable somehow (for example, we can enforce it, by setting all extensible, configurable, writable properties to false).

I have also thought about it, but it seems too may details need to be processed, and we also should avoid the arguments and return from function break immutable.

**Comment by xeioex** [comment]
BTW, It is a good idea, to read https://nodejs.org/api/modules.html first. Ideally, in the limit, we want to load node.js modules with minimal or even without any modifications at all.

**Comment by xeioex** [comment]
@hongzhidao 

>I have also thought about it, but it seems too may details need to be processed, and we also should  avoid the arguments and return value from function break immutable.

I talked to @igorsysoev. To avoid this issue with mutable object, njs has different strategy. For example, object literals `{a:1, b:2}` are created at runtime, so each VM has its own copy. This is done because object literals are not always constants (think for example of: `{a:new Date()}`).

```
./build/njs -d
interactive njs 0.2.8

v.<Tab> -> the properties and prototype methods of v.
type console.help() for more information

>> var o = {a:1, b:2}
00000 OBJECT            60300000CDC0
00024 PROPERTY SET      60300000CD60 60300000CDC0 60300000CD90
00064 PROPERTY SET      60300000CD00 60300000CDC0 60300000CD30
00104 MOVE              60300000CDF0 60300000CDC0
00136 STOP              60300000CCD0

undefined
```

Igor suggests, at least to begin with, not to run modules code during compilation phase, only compile it. It automatically solves problems with shared objects. It has some performance impact though, for example it is quite heavy now to define large object and array literals (they are evaluated again and again for each request). But we can improve it in the future, by identifying truly constant literals like, `const o = {a:1, b:2}`, and replacing them with shared global objects.

> runtime in generator.

this is a stub for, not implemented yet, `new Function()` constructions.

> Actually, I want to copy global values from initial vm to cloned vm. (As an experiment)

with the compile only strategy, it seems to me, we do not need it.

**Comment by drsm** [comment]
Hi!
How about this:
```
js_preload  lib.js;
js_include  codes.js;
```
And
```js
// lib.js is executed only once
require('one');
require('two');
// the required modules are cached inside initial vm
```
then
```js
// codes.js is executed on every request
// the require() there does only a cache lookup...
var one = require('one');
var x = 'two';
var two = require(x);
var xxx = require('xxx'); // bail!
```
