### ISSUE TITLE
incorrect parsing of string literals

### ISSUE THREAD

**Issue by drsm** [nginx/njs#93]
```shell
$ cat nl.js 
var c1 = null;
console.log('c1:
', c1);
$ build/njs nl.js 
'c1:\n' null
$ node nl.js 
/home/drsm/work/njs/nl.js:2
console.log('c1:
            ^^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
...
```

**Comment by xeioex** [comment]
@drsm 

Thank you for the report.

Please, try the patch below:
https://gist.github.com/xeioex/f0aa2031f7897eec774b278777fc7b09

I included the following grammar ([according to](https://www.ecma-international.org/ecma-262/6.0/#sec-primary-expression-literals))
```
LineTerminator ::
<LF>
<CR>

LineTerminatorSequence ::
<LF>
<CR> [lookahead ∉ <LF> ]
<CR> <LF>
```

`<LS> <PS>` characters are omitted for simplicity.

**Comment by drsm** [comment]
@xeioex the patch works fine for me.
thank you.
