### ISSUE TITLE
Fixed error line number.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/njs#94]
@xeioex 

Fixed variable.
https://gist.github.com/hongzhidao/7c628db04af7ac403677a2b39e1c426d

**Comment by xeioex** [comment]
@hongzhidao 
Take a look, reworked a bit:

https://gist.github.com/xeioex/dc12347c583e1bb3bd4e9be2483c8566

**Comment by hongzhidao** [comment]
@xeioex 
Looks better, no problem.
